# 20231106_02

---
課程：1121所得稅法一
日期：2023/11/06
周次：10
節次：2
---

## 【孳息，區分資本類型】

這節課，我們談一下關於孳息的這一類型。因為不同的資本類型，在標準上面可能會有不太完全一樣的地方。

### 【股利】

我們來看一下股利所得，股利盈餘。我在8條的第一款規定跟第二款規定裡面有跟各位提到過，你是依中華民國公司法設立的公司所發放的股利盈餘，原則上這個就中華民國來源所得，第二款規定亦如是。沒有寫，依合作社法，或者是依商業登記法所設立登記的合作社，或者是合夥組織或獨資商號。雖然沒有這樣寫，但從我們的認定原則裡面，基本上也是看，你是依據哪一國法來設立而發放的股利盈餘。我們在這個之前跟各位提到過，這個其實就是一個準據法，但轉過頭來，他其實就是在講債務人。債務人是誰，那他就是那個地方的來源所得。換言之，付錢給股東的那個人，付出去的那個人，他是哪一國的稅籍事業，那個地方就會是所得來源地。第一款跟第二款，其實就是債務人法，也就是以債務人的稅籍國來作為判斷標準。

這個稅籍居民，我們是用準據法判斷。但有沒有取得中華民國來源所得，則是用債務人法，也就是給錢的那個人，他是哪一國的稅籍居民，來作為判斷標準。

股本的股利所得，原則上是以債務人法，那債務人的稅籍的判斷標準，不是以實質的經營管理地點，而是以他的準據法來作為判斷標準。

勞務的旅行，第8條的第三款，境內提供勞務，其實在我們這裡沒有直接講他是獨立勞務或是非獨立勞務，按照我們的來源所得認定原則，第4點，也就是所得稅法第8條第三款規定，把營利事業他把執行勞務的部分，包括獨立和非獨立，全部都放在第8條的第三款規定裡面。實在這裡面應該要分兩個部分，應該是提供勞務，分成獨立跟非獨立勞務這兩種類型，那麼非獨立勞務，原則上第8條第三款的規定，應該是以勞務的履行，實行的地點來作為判斷標準。可是只要你是獨立勞務，則應該以第九款規定，也就是在中華民國境內經營工商農林漁牧礦冶等業之盈餘。

執行業務也是一種勞務的經營的行為，因為他是一個獨立勞務的付出，只是我們的法律上規定，我們並沒有第九款規定是適用在執行業務者。第九款規定適用在營利事業的經營上面。執行業務者，我們適用第8條的第三款規定來做判斷，因此在第8條第三款規定裡面，其實綜合包含了兩種，獨立勞務跟非獨立勞務的類型。從理論上來講，應該是區分經營地點跟勞務履行地點啊，當然這個地方也是在判斷你的中華民國境內提供勞務這個標準上面。


### 【利息】


第四款規定好，就涉及到了自中華民國各級政府、中華民國境內之法人及中華民國境內居住之個人所取得之利息。這個是由我國付出去的利息。我國付出去的利息，也因此利息的所得是按債務人法，也就是誰付錢的，原則上那個就是中華民國來源所得，只要是中華民國的政府、法人或個人付出去的，就是中華民國來源所得。這個就是債務人法。

這樣各位前兩種的資本的孳息的類型就出來，一個是股利盈餘，一個是利息的類型。

### 【財產之孳息，租金】

第8條第五款規定，在中華民國境內之財產因租賃而取得的。什麼叫境內之財產，就是你的財產為在中華民國境內，所在地點在中華民國境內。特別是因不動產租賃而產生出來的租金。當然第8條的第五款規定，不一定是不動產租賃，動產，只要在中華民國境內，其租金所得原則上就是中華民國來源所得。當然我們的困擾會是在，如果這個動產會移動的話，例如船舶或航空器，則應該是依照他的船籍國或航空器的登記國，作為他的所在地國。這個是第五款規定，我們有法律上沒有規定清楚的地方，因為是像我國籍的航空器跟船舶，他雖然是動產啊，但是在判斷標準上面來講，原則上是以船籍國或者是他的登記國來作為他的判斷標準。

還有其他的動產，也可能會移動。其他的動產的話，我們看一下在營業稅法的關於動產的部分。營業稅法第4條，貨物會有這一種不斷在移動的可能性，在營業稅關於貨物銷售地點的判斷，是以貨物的交付，如果需要移運的話，起運地在中華民國境內。另外第二個就是銷售貨物之交付地，如果無須移運的話，則以所在地點在中華民國境內。營業稅法的第4條，對於貨物這一類的動產的判斷標準，第一個，貨物在哪裡，那這個就是在哪裡的貨物銷售行為，這個是以貨物所在地作為判斷標準。這個標準原則上跟我們的動產，物在哪裡，一樣的判斷標準。可是當動產會動的時候會移運的時候，營業稅法的第4條是以起運地，而不在於到達地點，甚至在概念上，也可能會有經過第三地轉運至地點的可能，那么營業稅法裡面，在判斷貨物銷售行為的銷售地的時候，是以貨物在哪裡起運，作為判斷標準。


這一類的所得，在所得稅裡面要不要採取同樣標準，也就是當租賃之財產持續在移動，屬於船舶跟航空器，原則上是以登記國為基準，這個是我們剛剛所提到的。

其他的財產有移動的問題的話，那么原則上就有可能以移運之地，也就是起運之地點來做為跟所得來源地一樣的判斷標準。這個是當是一個動產會持續運動狀態底下所產生出來的所得，跟營業的這種銷售行為的判斷標準。

### 【權利金】

最後一個叫權利金，回到我們所得稅法第8條的規定，所得稅法的第8條裡面的第六款規定：「專利權、商標權、著作權、秘密方法及各種特許權利，因在中華民國境內供他人使用所取得之權利金。」

看起來是以權利使用的地點為標準，沒有直接去聯繫那個「他人」，是否是我國的稅籍居民，如果那個「他人」是我國稅籍居民，當然你可以理解，一般而言會在我們境內使用，那個「他人」可能是我們的稅籍居民。以我們的第8條的第六款規定，是以權利的使用地點作為判斷標準，這個地方權利的註冊地、使用地，跟債務人國，這個都可以是這一類的無形資產的課稅管轄權的主權國家或地區。因為他本身的特性是一個無形資產，他必須要透過註冊跟使用，以及給付對價，才能夠產生經濟上的成果，所以這三方都有可能依據各自所得稅法之規定，而採取他們的課稅管轄權的規範。以我們的第8條第六款規定，看起來是使用地，但國際租稅法裡面往往這一類passive income，是一個消極所得，原則上坐著躺著就會自動進來。那這一類的所得，往往都是以債務人的稅籍國來作為判斷標準。因為我從那個地方去取得所得，這個人不管他在哪裡使用，付錢那個人，付錢的那個國家，就會被認為是所得來源國。第六款規定，我們採取的是「使用地」，沒有對那個「他人」做特定的描述。

## 【財產交易】

第8條第七款，你只要是在中華民國境內的不動產跟動產，特別是不動產，這個是採所在地課稅原則。如果是動產的話，我們剛剛跟各位講過屬於動產的話，原則上船舶跟航空器，屬於我國籍的船舶航空器的轉讓，他基本上還是中華民國來源所得。如果你是一個不斷移動當中的財產，那理論上這個地方的境內財產也包含了權利的交易。權利，包括專利跟商標這些無體財產的交易。

第六款跟第七款規定，差別差異在第六款是使用權的授權給予，是權利金所得。如果你是所有權的讓與，則各國原則上會以註冊的地點來作為判斷標準。因為他是哪裡來的，那他就會是哪裡的專利跟商標權。

對那個境內財產交易這件事情的話，我們的法條，第8條的第七款規定本身並不是很清楚。如果不動產，那不動產所在地，沒問題。那如果你是動產的話，原則上船舶航空器當然各自會依照那個船籍國國或是航空器的登記國，來作為所得來源地的判斷標準，但如果他是一個持續移動的動產或者是不動產的話，會依照他的登記國，或者是動產的起運的地點，來作為判斷上的標準。

## 【政府派駐】

那麼，第八款的規定：「中華民國政府派駐國外工作人員，及一般雇用人員在國外提供勞務之報酬。」

這個要注意，這邊必須是視為境內的地方。不然我們的課稅管轄權限，無權去管轄，物理上境外的地區，我們卻對他們去做國外勞務提供的報酬的課稅。所以第八款的規定是指中華民國政府派駐國外之工作人員及一般雇用人員，在國外的相當於我們的使領館範圍內所提供的勞務，因此所產生出來的報酬。他如果不是在使領館範圍內提供的報酬，我們對他根本也沒有管轄權限。我們政府派出去的國外工作的員工，不履行公法上任務的這些人員、一般雇用人員在國外提供勞務，他已經是境外，根本不在我們的課稅管轄權限範圍內。

這個條文規定，不管是在主體跟適用的客體範圍上面都不盡清楚，都不是一個很完整的法條規定，一般僱傭人員要特別注意到，我國政府派出去國外的人，有一些是實行公法上勞務的，也就是他在境外是行使我們的外交管轄，外交的權限的這些人員，他才會是前半段那個部分的適用人員。因為還有一部分的事務性勞務，有可能是派遣我國人員去那個地方，比如說派人去那邊做清潔打掃，可是因為各國為什麼會有這種派駐這種國外的情況，最主要是避免萬一所在地國你跟所在地國基本上是處在一個比較緊張的關係底下的話，你可能在當地雖然找一個清潔工或是找一個來做打掃的人，可是可能是對方的間諜。所以我們有可能派出去的，有一部分是屬於履行公法上勞務的，這一些外派的公務員，不管你是文官和武官，另外一方面，我們也有可能是派遣出去國外的事務性工作的這些人員包括負責影印機，包括打掃清潔，甚至包括住宿服務，我們可能都會有派駐國外非履行公法勞務的這些，一般的派駐人員。這個部分，只有前半段，是維也納外交公約裡面所明白認為，只有這部分的公務人員的所得，所在地國不能對他課稅，至於後半段這個部分，這個是要依雙方國家的交涉跟談判去做認定的，並沒有必然要免稅。即使他工作的地點可能是在境外使領館，可是由於他非執行公法上的勞務，這個部分是容許由雙方就是派駐國跟駐在國，兩方面去做協調，來達成相互一致的協議。如果你給我免，我也免你的，那這個雙方是互惠的，但沒有必然免的道理。只有執行公務的人人員，他才會有必然免除的適用，這個是在維也納外交公約裡面所規定的。

目前我們的外交處境的特殊，往往沒有國對國之間的外交關係，因此透過授權給公權力私人行使的這一些被授權的人員，只要是實行公法上勞務的這一部分的人員……我們當然不是直接是維也納外交公約裡面簽署適用的對象，可是在這裡面，由於我們在外交上面採取的是受委託公權力授權給私人行使的方式，因此我們派出去的跟相對方派過來的人員，基本上都是透過我們跟對方之間雙方的互談以後，才因此會有適用我們第8條的第八款的規定。

比如說美國啊，美國派駐到臺灣的，跟我們派駐到美國的臺灣駐美國的代表處、辦事處裡面的相關人員，基本上也是適用這樣一個條文的規定。雖然我們不直接適用維也納公約裡面的相關的條文規定。維也納公約，是要我們跟A國跟B國，有一個正式的外交關係，彼此之間是執行公法上任務的這些外交人員，原則上一方是不能夠去對他方課稅。這個人員都是在履行各該國家的公法上的權限。未經允許而進入他們的外國使領館的範圍內，這個是被認為是戰爭行為。這個1978年的伊朗德黑蘭的那個學生，爲了抗議美國，衝進去那個美國的外交使領館去綁架相關的人員，這個在國際法上，就是視為戰爭行為。這個叫沒有宣告，就發生發動戰爭的行為。所以美國他的反擊就會是依照國際法裡面的，你既然對我宣戰，那我也對你去做這樣子的一個宣戰的行為。

所以，外國使領館並不是一個國家的課稅主權所及，即使在物理上是屬於該外國境內範圍，但並未經過允許，他基本上就是不能去進入，在這裡面去行使，包括課稅管轄權限在內的各國的主權。這個是維也納外交公約裡面。所對各國之間的相互往來所適用的基準的行為上的規範。非履行公法任務的這一部分，並不在當然適用範圍內，而是從許由雙方各國來互相來去談判而去做個別的決定。你可能互不免除，也可能互相免除，或者是單方免除，這個都有可能，但原則上要不是互不免除，要不就互相免除。


## 【境內經營】

第8條第九款的規定是指境內經營，也就是經營地，原則上應該是屬於獨立勞務，不管你是貨物跟勞務的銷售，第8條第九款規定，應該是以經營地點來作為判斷標準。這個就是獨立勞務，或者是營利事業經營的判斷標準的原則。那當然我們這個地方關於境內經營這一類的事件，由於在我們的法條規定裡面本身並不是很清楚地去呈現出來。這個地方因此實務上透過來源所得認定原則。

原則上如果一個passive income，變成是一個activity的一個經營的內容，變成是積極的所得來源，這個時候會被認爲，你的事業經營就在該當地該當一個常設機構，從而會適用第九款的規定，也就是以經營地來做判斷。

這也是雙邊租稅協定裡面會涉及到的，也就是說，營利事業，當你的消極性的行為反覆為之，會讓他變成是積極性的行為，而轉變則是一個營利事業所得的態樣，適用經營地的判斷標準，也就是以常設機構所在地作為一個課稅的所得來源地。

## 【競技、競賽、機會中獎】

最後一個是關於第十款的規定，也就是競技競賽，沒有很清楚地說明，境內參加是什么樣的意思。其實在這裡面，應該是以舉行地點作爲依據。因為競技競賽及機會中獎，一般而言，會有一個競技競賽舉辦的地點，而以這個地點成為所得來源地的來源地的判斷標準。

## 【其他收益】

最後一個是十一款的規定，在中華民國境內取得之其他收益。我們在這裡面屬於一時性的，我們跟各位列出幾種類型，一時貿易盈餘，競技競賽及機會中獎，還有一個就是具有射悻性的非法行為的判斷標準。

我們第十一款規定，在中華民國境內取得。什麼叫中華民國境內取得？這是在實務上不容易判斷的地方。你的貿易，如果是一時貿易，這種經營行為本身是在中華民國境內，理論上來講，用第九款規定就可以，而不需要去適用第十一款規定。那麼第十一款規定往往是對於非法經濟活動，你在非法的經濟活動的活動地點在這個境內所取得的，那因此就會是屬於該地的來源的所得。


我們實務上有來源所得認定原則，但長達5頁的認定原則，往往甚難給予司法機關一個客觀上比較明確的判斷標準，我們透過解釋上的說明，原則上四個原則：經營地、勞務實現地、所在地，還有就是債務人地。就是債務人，給付的這個人的稅籍。這四大標準是所得來源地的判斷標準，所連結的是我們的稅捐客體，所得來源。我想我們就到這裡跟各位做一個客體方面的結束。

## 【稅捐客體小結】

稅捐客體，涉及到總共四個層次不同問題：是所得、非所得的問題，是應稅所得跟非稅所得的問題，是屬於何種所得類型的問題，跟所得的實現時間跟所得實現地點的問題。每一個區分都有區別的實益。這個是我們跟各位談到稅捐客體的部分。

## 【稅基】


14條結束了，之後就進入到第17條的規定。稅基\index{構成要件!稅基}的概念是客體的數量化，也就是每一個都要把前面講的客體帶上一個額度，所得額。比如說你是第14條第一類的營利所得，稅基就是營利所得額。

稅捐客體的數量化被稱之為叫稅基。為什麼被稱之為稅基？他是稅捐計算基礎的簡稱。稅額就是你的稅捐負擔，稅捐負擔的計算基礎是透過稅基乘稅率，得到稅額。

因此在稅捐法總論裡面，我們提到所謂的總額主義，在講稅額。形成稅額的基礎有兩個，一個是稅基，一個是稅率。稅基怎麼來？是看稅捐客體，也就是稅捐主體獲得的稅捐客體，透過計算方式把他換成稅基，乘上稅率，得到稅額，這個就是你的稅負，就是課稅處分裡面所載的那個稅額。


納稅義務人不服的，往往是，我知道我要繳稅，我有營業行為，我有所得，但我所得額沒那麼多。所以一般而言，納稅義務人不服，會展現在他對稅基的計算基礎上的不服。正因為稅基是所有的課稅構成要件裡面，我把他稱之為他是最重要的構成要件，因為他承接了前面的稅捐客體，之後就是稅額，所以他是關鍵要素。稅基，因此要由立法者自己決定。基於重要性理論，立法者要自己決定應稅所得額，到底怎麼算出來，應稅銷售額到底怎麼出來的。這個要由立法者自己做決定，這個是重要的，重中之重的構成要件要素。

那么另一方面，所有的稅制改革裡面的最重要的基礎，是稅基，而不是稅率。

非法律學者往往把他們的稅改重點放在稅率。稅率，就是去調整那個比例，但任何明白稅額是透過稅基乘稅率的人，再怎麼樣的一個簡單的道理，這個只是稅捐負擔比例的高低的調整而已，稅基才是決定稅額的最重要的基礎，所以稅改重點是稅基，不是稅率。但很可惜的是，以往操縱臺灣，包括產官學界裡面，所謂認為的稅法的專家，幾乎都是以財稅為背景的，他們把重點都一直放在稅率。所以我們2009年的遺產贈與稅法的改革，一直都是在講稅率。我們的房地合一稅，所謂的對短期持有，要加強他的稅捐負擔，我們也是把重點都放在稅率。

但法律背景的我們認為，應該重點是在正確的稅基，才有正確的稅額，才有正確的量能課稅。如果沒有正確的稅基，稅率，尤其是累計稅率，只會扭曲稅捐負擔分配的結果。例如，沒有被適當扣掉的稅基，就會加重納稅人的稅負，會扭曲稅捐負擔分配的效果。從而，未來如果哪一天，各位同學有人有機會成為立法院裡面的立法委員。你可以講，整個稅制改革的重點是在所謂的寬稅基、低稅率，廣稅基、低稅率。稅改的重點，一般稱之為叫廣稅基、輕稅率。稅率輕不輕，要看前面稅基，稅基廣，那當然稅率就輕，稅基窄，國家還是要錢啊，那當然稅率就會高，可是越高的稅率會說引起人們不斷地逃漏稅基，因為這是相對應的。越廣的稅基，會讓人們會覺得，他的稅捐負擔能夠在公平的計算方式底下算出來，這個才是符合稅捐負擔分配正義的稅法。

也因此我們進入所得稅的稅率之前，稅基是最重要的構成要件。理論上應該要由當事人在稅捐申報的時候提供正確的數額，來讓稅捐稽徵機關一方面依職權調查，你提供的這些數額對不對，另外一方面，他當然也要依職權調查，查核有沒有未申報的所得。這個正是協力義務。協力義務，透過納稅人告知正確的所得額。我們的所得額，進入營利事業所得稅裡面通常會有收入額，成本費用額，甚至有虧損額度，所以在這個地方，我個人建議，任何稅基的計算都應該要加入「額」，而不要單純只講「收入」，收入是客體概念，算成數額應該要加一個額度的「額」。在這裡面，收入額、成本額或費用額、盈餘額跟虧損額，都一樣，我個人是認為都要加「額」這個字眼，才能彰顯出客體數量化的稅基名詞。

不過很可惜的是，我們現在目前實務上基本上都喜歡用收入、成本、費用、虧損，都是用這些比較有可以指稅捐客體，又可以指稅基的名詞來做描述。

這個是首先我們跟各位去談到稅基跟稅捐客體之間的關係。稅基作為稅捐計算稅額負擔計算基礎，是一個非常重要的概念。


## 【客觀與主觀凈所得】

所得稅法14條，主要是客體的類型，14條裡面也是要去計算出他的客觀凈額的範圍，客觀凈所得的範圍。簡單來講就是個類型的所得，是透過14條的規定，以收入減成本減費用，甚至必要的時候減除掉法律所允許的虧損。14條的規定，因此是屬於我們在稅基計算上的前階段，也就是第一個階段叫，各類所得的淨額。

那么14條算完之後，會有一個各類所得的綜合總額。我們請各位同學來看到第17條的規定：「按第十四條及前二條規定計得之個人綜合所得總額，減除下列免稅額及扣除額後之餘額，為個人之綜合所得淨額」

這邊的「個人綜合所得總額」，我個人認為啊，「總額」會讓人家以為是沒有扣掉成本費用的。

那個地方其實是兩階段的計算方法。14條15條跟16條，這幾個條文算起來是為了要算客觀凈額。從第17條開始，是要進入主觀淨額、主觀淨值的範圍。也就是市場經濟活動算出來的淨額，之後就進入到我們稅法裡面，維繫個人生存，維繫個人跟個人一起生活的配偶及受扶養親屬的生存需求。

因此，前面14、15、16條在立法的結構上，是客觀凈所得的計算範圍，接下來進入17條的是主觀凈所得。稅基，是分兩階段計算。第一階段，客觀淨所得。第二階段，主觀凈所得。

第一階段，法律學、經濟學都承認，客觀淨值才是稅捐負擔能力的計算基準。

第二階段，只有法律學者認為很重要，甚至重要性高過客觀凈所得。因為我們認為賺錢不是為了繳稅給國家。賺錢是為了要養活我自己，跟我自己親愛的配偶跟家人。從而主觀凈所得的減除，負有憲法上維繫生存權保障的這樣一個任務，比客觀淨所得，在規範的位階上，雖然排列在後面，但憲法上的意義則更為強烈。

前階段這一部分的客觀凈所得，如果不準許解除，侵害的毋寧只是工作財產權。後半段的這個部分沒有核實的反應，則侵害到憲法上的生存權保障。

也因此，我們在稅法總論裡面區分了主觀淨值跟客觀淨值原則，最主要的表現就在這裡面。這一個表現在個人綜所稅裡面，透過14、15、16條，客觀淨所得的計算，第17條開始，這個是主觀凈所得。

第17條的主觀凈所得，在法人沒有這個問題。因為法人沒有維繫生存的概念，法人是一個人的組織體，是一個人的集合體，就算採用法人實在說，法人仍然沒有像個人自然人一樣的維繫生存的必要或需要。法人沒有吃飽穿暖的問題，沒有維繫人性尊嚴的問題。儘管你可以講，法人在基本權的保障，依其性質，有同樣適用的可能性，但維繫生存的需求這一件事情並不存在。

從而在這裡面，我們進入第17條之前的時候，有幾項基本的觀念要讓各位清楚。

第一個，經濟學者普遍並不認同主觀凈所得。他們認為，稅捐只有客觀淨值，沒有主觀淨值，主觀淨值已經影響到正確的稅捐負擔能力的計算。以他們來講，賺錢凈所得就是指客觀淨值，之後就是稅捐負擔能力的起點。對法律學而言，我們賺錢不是為了國家繳稅給國家，我們賺錢要先養活自己。從稅法的角度，稅捐負擔能力是主觀淨值。這個主觀淨值也表現出來稅法跟社會法的一體兩面。因為，我賺錢是養活我自己，然後我還要養活我這一些受我扶養的人，這些人包括配偶跟受扶養親屬。在社會法裡面有一個補充性原則，國家是補充性的介入，當一個人自己沒辦法養活自己，也要先由其他負法律的扶養義務人先養他，如果連這個負法律扶養義務人也養不起他，我國家才來介入，用社會救助法把你撈起來，建構社會安全網，把你扶助起來。

從而在法秩序的一體性地下，社會法跟稅法，共同建構起的共同的法律價值，就是我養我自己的，我當然可以扣除，我養我負有法律扶養義務的這些人，因為國家也只有在我養不起他的時候，事後性地、補充性地，才去承接這些人，從而這一部分的生存權保障，在我可以照顧他的時候，都是屬於不可自由支配的所得，應該要準許減除。

這反映的是憲法位階的生存權保障，從而在我們的釋憲實務上，一般涉及生存權保障的財產權問題，會提高其違憲審查的位階到中度的審查基準，背後的理論基礎就是在這樣一個前提基礎上。第17條的規定，因此是生存權保障的稅法上的實踐。


在進入所得稅法的規定之前，我們不可避免，還要再談一個概念，在納稅者權利保護法裡面，有一個基本生活費用不課稅原則，在納保法的第4條。根據地納保法第4條第一項，「納稅者為維持自己及受扶養親屬享有符合人性尊嚴之基本生活所需之費用，不得加以課稅。」

第4條的基本生活費用不課稅原則，這個條文規定現在在目前的實務上，幾乎取代了所得稅法裡面的關於免稅額跟扣除額的規定，是因為如果基本生活費用不課稅原則，他直接用一個額度就涵蓋了所有的這一些維持生存的費用所需的額度的話，那麼納稅人必然不需要去適用所得稅法裡面的免稅額跟扣除額規定。

簡單來講，就是，除了免稅額以外的所有的生活費用，全部都會被納保法第4條基本生活費用規定所涵蓋。

基本生活費用不課稅原則，理論上應該是立法者據以調整所得稅法的免稅額跟扣除額的一個誡命義務，也就是他應該要時時調整所得稅法裡的免稅額跟扣除額，俾便反應納保法第4條的基本當代基本生活費用。簡單而言，就是的納保法第4條的規定應該是作為所得稅法的免稅額及扣除額，立法作為義務的一種誡命。立法者應該要與時俱進檢討，我們現在的免稅額跟扣除額規定，俾便能夠實質反映當代生活的最低生活費用，而不是另外取代他，把他取代掉。那這樣會造成了我們所得稅法裡面的這些相關規定在現實上的適用就不太具有意義。納保法增訂這個條文理論上來講，應該是促使立法者，負一個作為的誡命義務，調整所得稅法裡面的免稅額扣除額的規定。

那這個是我們對納保法還有對所得稅法兩者規範之間的體系性的瞭解，彼此之間的關係，所產生出來的這樣子的一個法律適用上的關係。


進入到第17條的規定，他的法條規範結構上總共有三項的規定。所得稅法的第17條的規定非常的長。第一項裡面總共就有3個或4個不同的名詞。

第17條的第一項第一款有「免稅額」規定。
17條的第一項第二款的第一目，有「標準扣除額」。
17條的第一項第二款的第二目，有「列舉扣除額」。
17條的第一項第二款的第三目，有「特別扣除額」。

各位很抱歉，立法者不是我，我也沒辦法，就長這樣啊。所以17條第一項，我們總共有4個專有名詞，這4個專有名詞，免稅額之外，標準跟列舉二擇一，之後再有一個特別扣除額。

所以規範結構是這樣，免稅額先，然後接下來標扣跟列舉扣除二擇一，然後再加特別扣除額。

請各位務必把這個法條適用結構在這麼複雜的規範邏輯當中，外在體系很不好，但至少這一個適用的順序，原則上各位一定弄清楚。

免稅額，標扣跟列扣是二擇一相互替代，然後再加特別扣除額。


那我現在跟各位說一下，我們在禮拜六的時候補課的時候，我們再跟各位進一步去說明。免稅額是維繫物理生存需求，基本上就反映出當代生活的維持溫飽，就是吃飽傳染好，還有第二個這個部分叫標扣跟列舉扣除額，他的概念上是維繫物理生存需求之外，因為人不只是一個動物的人，除了吃飽穿暖以外，人也是一個群居的動物，需要跟別人有所往來連結，所以他有一個維持社會生存的需求。這個維持社會生存需求的這個額度，則由中間這個標口跟列舉扣除額，用二擇一的方式去反映。第三個叫特別扣除額，因為個人的特殊因素給予特別考量而加進來的扣除額。

各位一個一個去對照，免稅額是物理生存，基本上反映出維繫物理生存，你可以講馬斯洛需求的層級，人有一個至少要吃飽穿暖的需求。然後接下來是要有一個大家可以跟人往來的需求，至少我是個人，我不是只有吃飽穿暖，我不是一個動物的人，我還是一個我需要有住的地方，讓我知道我朋友來找我的時候，他可以找得到我，而且我要活得健康。所以在這裡面，我們把這一切把他稱之為叫維繫社會生存的需求。這兩個合起來就是基本生活費用。基本生活費用就是剛剛我們提到了納保法第4條所講的基本生活費用。接下來還有一個叫特別扣除，這個特別扣除額講什麼？因為你個人的年紀身心狀態而產生出來的特殊的個別的需求而給予扣除。這裡面有包括量能課稅跟稅捐優惠，理論上來講就是你個人做了一些好事，那我就給你特別的額度。

那基本上這個概念在這裡面，我們反映出來的就是，一個納稅義務人，除了獲得市場經濟活動的客觀凈所得以外，繳稅的稅捐負擔能力也要扣掉維繫個人及家庭成員的維繫生存需求，及個人特殊因素所產生出來的這些需求。最典型的就是身心障礙者。因為我們前面的算法基本上是以一般人的平均來做為比較的標準，那你如果有身心障礙的特殊因素的話，再給你加上去。所以身心障礙特別扣除額是一個很典型的因為個人的特殊因素產生出來的扣除額。

那我們在禮拜六的時候會跟各位把這整套的稅基主觀凈所得的計算方式來跟各位做一個說明。對各位而言，這個部分是屬於考試上比較重要的地方。說實在話，客體的部分有時候是去做區辨，當然也很重要，我也不否認他是很重要，但考試比較不太好考試。稅基比較好考，特別是淨所得的這個部分。

我們今天先講到這裡。