# 20231023_01

---
課程：1121所得稅法一
日期：2023/10/23
周次：08
節次：1
---

## 【繼續談所得類型】

在上個禮拜，我們講到所得的類型裡面，我們區分勞務的投入或是資本的投入，二者原則上應該都具備一個特徵：繼續一段期間內才能獲得財產上的增益。

（圖示，勞務所得、資本孳息、財產交易之類型）

特殊技藝獨立執業的這一個類型，在工商的部分，其實毋寧比較是偏向於獨資跟合夥。因為如果他是屬於公司組織的公司、合作社、依有限合夥法成立的組織型態，這一個區塊，原則上就會進入營利事業所得稅的稅捐主體的範圍，課徵營利事業所得稅。當然在這裡面有交界的領域啦，因為這裡面是一個獨資跟合夥。我們在民國86年以前，全部都是營利事業所得稅，因為獨資合夥跟公司、合作社，那時候還沒有出現有限合夥，基本上是營利事業的不同組織的形態。86年以前的所得稅對獨資跟合夥是最不利的。因為他們原則上被課了兩次稅捐，當時候是25%課一次，75塊，再來乘以40%，所以等於是25+30，是55塊錢的稅負，等於稅後净所得只有剩下45塊。86年以前是這樣。87年開始到民國107年之間，我們兩稅合一的制度，這個時候他是消弭了，特別是獨資跟合夥的重複課稅，因為只剩下對個人的營利所得的課稅。但造成了非獨資合夥，特別是一般組織型態利用公司合作社，在課徵稅負上的極大的依從跟稽徵成本上的負擔，也就是那個兩稅合一的設算所得稅額扣抵制度。設算扣抵稅額的公司帳戶，對特別是公開發行股份的公司來講，因為他們的股東本來就是一直不斷在變化，在所謂的基準日之前，基本上還是一直可能在變化的過程當中裡面。從而造成了上市櫃公司一個極大的，我們稱之為叫依從成本上的負擔，因為公司為了要設兩稅合一的可扣抵稅額帳戶，一方面很大很大的成本，為了要避免超額分配盈餘，又做了一個可扣抵稅額帳戶的可扣抵稅額比例的分配，也就是當年度你原則上可以被扣抵的稅額，只有在那個限度，也就是要分配給自然人股東的那個盈餘限度範圍內，你們去做課稅，但你如果是做過度的盈餘分配的話，這個地方他有限制的規定。

也因為這個限制的規定，造成了一方面是國家稅收短收，因為本來86年以前，我們是兩稅分立的。對公司營利事業所得稅來講，等於是前階段的稅收，國家收不到，後面到個人營利事業的時候啊，登記個人股東的時候，才會課到所得稅。然後為了防堵大家不分配盈餘，在這種情況之下，我們又加徵一個在其他國家稅制裡面沒有的，變成只課徵未分配盈餘所得稅，但實際上我們既損失大量稅收，又增加高度的依從成本，以及，關於可扣抵稅額的比例而造成徵納雙方極大的爭議。

從而我們終於才在107年的時候把他廢掉，廢掉以後，現在留下一個尾巴，就是這個地方改變成，公司課徵一次的營利事業所得稅，現在是20%，公司如果發放盈餘，給同樣是公司的，我們再也不課稅，因為第42條的規定，我們就不課稅。只有在公司繼續分配盈餘給自然人的時候，我們才對自然人再去課徵那一次的個人的所得稅，但原則上透過用分離課稅28%，或者是做稅額扣抵，8萬元額度內。複雜的稅制，這就是我們現在的兩稅合一的這個制度的本身的演進的過程。那留下來獨資跟合夥呢，則是用一套，在德國稱之為叫做兩重計算的方式，在臺灣沒有一個正式的稱呼。所謂的兩重計算，就是營利事業這個層次的時候，先算一次營利事業所得額，但不課稅。然後第二重的計算則是按照他的股份就直接分配盈餘給獨資資本主跟合夥事業合夥人。所以第一重這個營利事業所得稅這個層次裡面，只有做帳務上的計算營利事業所得，然後按個別的合夥股東的股份，在第二重計算裡面，就直接認為他已經把盈餘分配給合夥人，然後計入他個人的營利所得。所得的類型是屬於我們的講的營利所得的類型，就是股利盈餘的分配。

但留下一個尾巴，在我們所得稅法第71條第二項裡面說，在這裡面獨資商號跟合夥事業還是要做營利事業所得稅的申報，只是不用繳而已。繳稅是到了他們的股利盈餘分配給自然人的股東時，因為他就做了第二道的計算，股利盈餘的計算，從而把那個營利所得就直接算入獨資資本主或合夥人的個人的營利所得，來繳納綜合所得稅就好。

他是兩道計算，但是申報這個階段仍然不可免，就是營利事業所得稅還是要做申報。71條第二項有做了一個很偉大的怪異的規定是，但書，如果你是小規模營利事業，則不用申報，我幫你算。一個德國制度裡面簡單的穿透稅制，在臺灣是分兩個階段，然後做申報稅的不同處理，也就是說原則上你還是要報，但小規模營業的營利事業不用報，我幫你算。

所以這個地方，在稽徵程序的協力義務上面來講，有申報跟有不申報的，但都不需要繳。什麼時候繳？直接就算入個人的營利所得，以個人綜合所得稅的方式去繳納。這就是關於我們的這一種穿透性的稅制裡面的這個獨資跟合夥商號，這就是我們偉大而難以説明的規定，因為到目前為止，目前為止也沒有一個正式的名稱的稱呼去說明這件事情。


## 【一時性】

我們今天跟各位從這個地方再開啟另外一個可能性，叫一時性。一時性，意味著他是一種偶然，機會。遺產稅也被認為是因為你爸爸死掉，被繼承人死亡所留下來給你，我們不能預測誰死亡，但是他死掉的時候突然留給我的。

我在這個地方，我先跟各位去描述一時性。在我們的所得稅裡面有三種類型的一時性的所得。

第一個是一時貿易盈餘。
第二個是第八類的機會中獎，競技競賽及機會中獎。
第三個，是第十類的其他所得。

這三類都是偶然機會發生的。一時貿易盈餘，本身就告訴你，一時性。老師的職業本業是教授，但我也有一個一時貿易盈餘，因為我在我家的上面裝一個太陽能光電板。你如果去德國，可以看到現在目前很多家庭，房屋上面本來以前不管是鋪什麼東西，現在很多都是改鋪成太陽能電板。

其實我們臺大如果有興趣的話，搞不好可以在我們頂樓上面鋪一個。很多公寓大廈，現在都是用這個租給人家，然後就可以收錢，是一個創造收益的一個收入來源。所以要透過規模經濟的方式的話，飛機這樣過去的時候，看到整個臺大一片全部都是那個太陽能光電板。

我在我家裡面上面裝了一個太陽能光電板，我賣電給臺電，這個叫我的一時貿易盈餘。我不是以之為業，但我兼差賣電。但我們這樣講，我如果經常性賣電，我賣的規模不是只有我家頂樓，我去你家，去學校，去農場，我去到處去房屋上面蓋這個太陽能光電板，我就會從「一時性」變「繼續性」。然後如果我自己去做這個生意，這個是獨立勞務裡面的哪一個？

營業所得。

類型化的功能，就是幫助各位整體掌握區分彼此你我。

這個圖請各位帶在腦海裡面，你就永遠不會忘記。所得的類型其實有包含「繼續性」、「一時性」，這也是我現在跟各位講，為什麼所得，我們不是用市場經濟活動的那個所謂的源泉理論，因為源泉基本上是掌握孳息跟勞務，資本利得就沒有掌握，所以我們的所得稅法絕對不是用源泉理論。相反的，我們是包括繼續性一時性，我們的勞務裡面不管你是在是在私的事業，或者是在公領域裡面服務，只要你付出勞務的，基本上都是所謂我們薪資所得所掌握的公私事業職工裡面的薪資所得的範圍，所以我們也不是全然採取所謂的市場所得理論。我們是把公私領域裡面的，包括你的各式各樣的勞務提供或者是非勞務提供，有可能是來自於其他所得。因為我們的薪資所得的類型，只限於現在合法雇主提供的，如果你是一時之機會利用職務工作之機會看到顧客的錢包，突然就想起來，哦，原來我可以把他偷走。竊盜。不法的哦。不法的行為，利用職務之機會收取的回扣，公務員利用職務之機會所收取的賄賂，就會是其他所得。要不要課稅？答案是要，只是不是原來的薪資所得，就這樣而已。


做不同類型的歸類，會幫助我們去比較同跟不同。也許這個地方，獨立性勞務不需要分那麼細。農林、執業跟營業，其實是營業的特殊變化特殊類型而已。是大自然界的第一次產出或是延伸的加工性商品，乃至於特定的職業類型的一種特定的形態，基本上差別在成本費用，差別在勞務的提供規制管理上又會有不同規定。但是對稅來講，我們看的是錢，我們不是在看工作管制規定。從而對稅來講，錢才重要。這裡面因此重要的區別標準叫「獨立性」。何謂「獨立性」。


這個差別，我在上個禮拜跟各位講過。陳清秀老師，平常在執業做律師，他那時候在東吳兼差的時候，還是一個執業律師。今天上法庭賺到的報酬，這個叫執行業務所得，可是今天到了東吳大學去授課，是受東吳大學的指示，告訴你幾點幾分到哪上什麼課。上課的內容，儘管是你的專業，可以去自由發揮決定你要告訴學生的內容，但你仍然是受東吳大學的指示。換言之，收不到學費，不會減少你的報酬，也就是不管盈虧都不會影響其報酬給付之本質。從而，陳清秀老師，從東吳大學取得的叫非獨立性勞務的薪資所得，但同時間可以執行律師業務。所以一個律師到學校演講，他會有兩種所得，一個是他執業的執行業務所得，一個是薪資所得。

我們任何兩種類型都可以比。我在考試的時候就可以考這個，我讓各位去比較不同類型，因為這就是區分差異你我。

一時性裡面包括一時貿易盈餘。老師有一位學生寫的碩士論文就是一時貿易盈餘跟營業所得跟財交所得這三個的區別。

我舉例而言，我賣襪子。你不會今天我賣襪子三雙，你就認為我賣襪子，我有取得所得，有一時貿易盈餘了。不會吧，因為賣襪子以這樣薄利的本質特性，一般來講，連稱之為一時貿易，都很難認為是。所以賣三雙襪子叫財產交易所得。
但是，我自己去跟人家進貨，一直賣一直賣，在某程度上就會開始進入一時貿易。然後之後越賣，生意越大，就會變成是營業所得。各位清楚嗎？ 賣東西看客體。

在德國賣房子，你一年賣一棟，算不算營利事業？ 要看客體，不是只看頻繁度。這裡面講的繼續性跟一時性，基本上是看客體、價格跟交易的性質上的頻繁性的可能。賣三雙襪子不會讓你變成營利事業，但一年賣三棟就會讓你變營利事業。因為房子高單價。

德國有一個「五年三個客體」界線，是跨年度去觀察一個人從事該項行為的頻繁跟密集性，判斷是否繼續性的勞務。你一年賣一棟房子不立刻就構成所謂的這個營利事業賣房子的營利事業，五年內賣三棟以內，還是財產交易所得。任何一個5年的期間，只要超過三棟以上，第四棟開始，就會量變變質變，讓你變成是一個營利事業的所得，從而變成是德國法制裡面被稱之為叫人合性的營利事業。一樣還是透過兩重計算，但就會變成是一個營利所得的類型，而不再是單純的財產交易所得。

這個叫類型特徵，每一個概念都叫類型概念。因為他是有邊際界線的差別。實務的有趣就在這裡，實務的複雜就在這裡。沒有一個全然絕對的標準，而是綜合整體觀察。
任何兩類三類，我都可以把他湊起來去比對。那就看各位期中考試嘍。

對於一時貿易盈餘，老師到目前為止沒辦法給各位明確界限，因為他不能以之為主業，但又不是單一的一次性的財產交易轉售價差。到什麼程度叫一時貿易盈餘？我跟各位舉個例子是我賣電，你可以想像我賣電不是以之為主業。

那我現在舉一個例子，我是一個醫生，然後我非常喜歡日本，去日本旅遊的經驗非常多，所以我就在我的部落格裡面開始去寫日本旅遊經驗的這一些分享。分享分享到最後面，有些人說啊，柯醫生，可不可以會帶我們去日本做一個日本團旅遊啊。不錯哦。好，那我們就來做日本團吧。但這日本團是這樣，就是買機票十張有送一張啦。就簡單來講就是，大家一起出團啊，大家都買一張機票啊，航空公司會有一個折價，這一張折價就送我了。這樣可以嗎？沒問題吧？所以在這種情況底下，那個折價，你獲得一張免費的機票，算不算你有所得？有所得的話，哪種類型？有趣吧！這是實務案例哦。

因為不同所得類型，有成本費用認列的問題。哪一種類型，會有對應的成本費用認列的限制、證明方法、影響所得額的計算。
所以即使我們是綜合所得，我們仍然很大程度上會需要分類。


機會中獎、還有其他所得裡面最典型的叫賭博的收入，他們都是一時性的。機會中獎，不會「以之為業」。但如果基本上還真的有人以參加各地舉行的競技競賽為他的目標，藉此賺取獎金跟報酬的，還真的有可能轉成「以之為業」。

在德國，一次玩撲克牌，這個叫一時性的所得，在德國是完全排除在課稅所的範圍內，因為他們認為十賭九輸，原則上你應該輸，所以我乾脆就不算入所得的範圍。所以用這種方式把他切出去課稅所的範圍，所以你去拉斯維加斯去拉霸，在德國，你賺到錢都不算所得，虧損也不給你認列。德國人的做法就是把他從一時性繼續性切開來，只有繼續性的活動才是課稅所得。這種好聽一點叫一時性，難聽一點，叫射悻性很高的這種中獎的，不管是合法或非法，原則上在德國被稱之為嗜好，不列入課稅所得範圍，嚴格地切割開來。因為德國人認為有所得就要課稅，但有虧損要準予減除，不可以做半套。
美國法，做半套的話也可以，只有賺到錢的才算所得，虧損不準你盈虧互抵。
我們的稅法就受美國影響，就是說，OK，如果你是有賭博行為，有所得，併計綜合所得課稅，但有虧損，不準予減除。我們的做法是這樣。因此一時性所得也是所得稅的所得，從而我國不採源泉理論。我們是採純資產增加說。不管是繼續性或一時性，或者是採跨越市場所得理論的營利所得，我們原則上只要賺到錢，都會被認為是所得。不管你的行為來自繼續性、一時性、合法性或非法性都是一樣，都是所得，只是歸類為哪一種類型的差別而已。

儘管是這樣，我還是要把一些排除在現行的課稅所得範圍的部分跟各位作說明。第一個部分，財交所得。首先，我們排除掉土地的財產交易所得，105年以後排除掉房屋跟土地的財產交易所得，改課房地合一稅。財產排斥土地，因為土地改課土增稅，105年以後排除掉房屋加土地的房地合一稅。第二個是，財交所得排掉證交期交的財產交易所得，4-1條4-2條，這個地方我們不課證交期交的交易所得稅，所以透過這個立法的圖形，立法者告訴你，要炒地皮要炒股，賺的錢都不用課所得稅，好棒棒。這個就是我們立法者鼓勵大家做的事情。

你這個地方，不管你投入多少的勞務薪資，所得者永遠是最上面這一個，收入跟成本費用被認列的最嚴苛的，也是最沒有機會去做核實課稅的所得類型。越往下的包括利得裡面的證交期交跟房地產的部分，臺灣向來就沒有做實質核實的課稅。所以，不要以為立法者多公平。他在鼓勵各位炒地皮跟炒股，就這樣而已。因為他在稅制上是被有利對待，大家理所當然推想他應該是受國家鼓勵的行為。你可能第一次聽到，但我跟各位講，現實就是如此，也沒有。

好第二個部分，我們把一時性的所得裡面的因為爸爸死掉偶然留下來的遺產跟贈與拉出去分離課稅，所以遺產跟贈與，爸爸生前給的是贈與，爸爸死後給的叫遺產。爸爸不管生前給贈與死後給，都是一時性機會性的所得，沒有違法的問題，他是合法性的，那這種所得為什麼要分開來？簡單來講，就是怕一時性加進來，累進稅率級距升高，就這樣而已。

我們對繼續性所得，也把其中某些類型以變動所得的名義把他拉出去做部分免稅部分課稅，也就是變動所得的一半課稅，一半免稅，所以也是從繼續性裡面只是因為他是累積多年所的一次大量實現，從而，像農林所得，像漁業的一次出海打漁，累積多年所得會透過變動所得的態樣，把他做部分的課稅部分的免稅。這個是我們現行的法律規定所架構出來的分類所得的類型，我們以這個方式來跟各位做一個基本的說明。

這個所得類型的結構我們待會留著，因為我們接下來要跟各位去講所得的實現時間跟所得的實現地點，這個部分有具有要按照所得的類型去做實現的時間跟地點的一對一的判斷的需要。我們待會兒再進一步做說明。

先休息一下。