# 20231211_02

---
課程：1121所得稅法一
日期：2023/12/11
周次：15
節次：2
---

## 【續談就源扣繳】

補充一下，我們的納稅者權利保護法施行細則，第2條第二項：「本法所定納稅者\index{納稅者}，包含各稅法規定之納稅義務人、扣繳義務人、代徵人、代繳人及其他依法負繳納稅捐義務之人。」

所以，我們現行法制裡面，私人被納入稅法規範裡面的地位，其實有各種不同的類型，直接因為公法上的權利義務關係，公法上的稅捐債權債務關係而發生的繳納稅款的行為義務，這個叫繳納義務人。我在稅總的課程裡面，我通常會區別成說，因為你是依稅法規定而產生的稅捐債務，所以其實是先是稅捐債務人，然後因此自己的稅捐債務自己去申報繳納，所以他是納稅義務人。依照法律規定而產生的稅捐債權債務關係，其實是首先是稅捐債務人。

稅捐債權人是誰，稅捐債權人就是依照財政收支劃分法裡面劃分的成國稅，或是直轄市及縣市稅裡面的稅捐債權人。


我們在稅法總論裡面，大致上跟各位提到過，稅捐債權人跟債務人的概念。債務人是實體法，納稅義務人則是程序法，但我們的現行法是直接跳過實體法規定，直接就用程序法的這個概念，涵蓋涵攝了稅捐債務人，同時成為納稅義務人。

但稅捐債權債務關係在我們的現行法裡面還有一些，並不是自己申報繳納的，像是扣繳義務人。扣繳義務人，其實是程序法概念。

納稅義務人，是實體法概念，在實體法依法課稅原則底下，稅捐債權債務關係在構成要件該當的時候，就因此該當了。取得所得者，同時是納稅義務人，也是納保法施行細則第2條第二項所講納稅者。

接下來，還有代徵人。代徵人\index{納稅者!代徵人}，這個制度是臺灣有的，德國沒有。但正是這個制度，我可以跟很明確跟各位講，代徵人就真的是公權力委託私人行使，因為那個名詞就告訴你，代為徵收啊，徵收權限給代徵人代而為之啊。證交稅、期交稅、娛樂稅，就是這種代徵人概念，所以這就是很典型的公權力委託私人行使。代徵人，有代徵的獎金


代徵人，是公權力委託私人行使。那扣繳義務人是什麼人？怎麼會一樣呢？這個地方你只要明白臺灣跟德國的差異，你很快就可以分辨，這個人，這個代徵人，真的就叫做公權力委託私人行使。扣繳義務人，叫做，服公法勞務的私人，而且，他服公法勞務是不用錢的。代徵人還可以拿錢你。你這樣一比較下去，回到前面的第一個命題，我就可以跟各位講，扣繳制度的不義或者是不正當性更明顯。

代徵人，有代徵的獎金，名詞不太一樣，有些會講代徵獎金。就是國家公權力委託私人行使，國家給你一筆錢。

扣繳義務人呢？是這樣，沒錢。做不好，要賠。而且罰也罰到你身上，罰到你身上的時候，跟納稅義務人是同樣的處罰。你真的好倒楣喔。扣繳義務人的這樣一個制度，你認為合憲，我也是輸了。真的完全不能理解釋字673號。

也許各位聽我的課的時候，或者是有時候，像在不同的領域裡面，大法官解釋往往被認為是圭臬，被認為是準則。在稅法領域，往往這個要稍微打一點折扣。我倒不是否定大法官的貢獻，因為他確實是在我們國家法制裡面，唯一能夠現行現行法律規範違憲的一個機制。可是大法官在行使相關權限的時候，我個人還是強烈的建議，好好地審視，在先進國家已經發展出來的理論。我也不是首先提出的，我沒那麼偉大。你只要好好的去參考，比較法制。比較法制最大的功能作用，就是告訴你自己哪裡不足，就這麼簡單。就看各位願不願意去把你的眼光看到比較法。

我為什麼會知道扣繳的「通報」？因為很簡單，荷、比、盧，這幾個國家都是通報而已，不需要就源扣繳。德國有就源扣繳，但他的就源扣繳是比較有限的。我上一次有跟各位講過，薪資所得、利息所得，就這兩種，結束。一個綜合所得稅是國家原則上是不需要就源扣繳制度的。我們不僅有結算申報，我們還要有廣泛的就源扣繳制度。光這個制度一比較以後，你立刻就會產生很大的懷疑，爲什麽爲什麽，為什麼我們國家要找這麼多人來當扣繳義務人。還不給錢哦。做不好，要賠，那就算了，還要罰。罰的程度，以前是一點，限度都沒有。彷彿國家在這個地方把你規定進去就具有正當性。

在我來看，公法勞務的私人，在某種程度上被拉進來，他是一個犧牲。我們的特別犧牲理論從來都不會去講到這一種服公法勞務的私人。如果不過度，那就算了。

就源扣繳制度，確實在德國也引起爭議，德國也在討論，究竟扣繳的義務是否要有償。但目前的主流意見還是認為這個是無償的。正是因為無償，所以他會盡量減輕對扣繳義務人的非難，因為基本上我們只是讓他賠而已。德國的所得稅法，雖然也規定扣繳義務人要負連帶責任，但基本上也大致上就是連帶而已。就是國家，如果有可能的話，還是要優先去向納稅義務人去做，請他補繳稅款的主張，因為本來就是納稅義務人的責任，不是扣繳義務人的責任。

扣繳義務人是用他自己的錢，用他自己的時間跟精力來幫國家做這件事情，犧牲沒拿到對價，那就算了，還要負擔這麼高的行為義務。

沒辦法，現在就長這個樣子。所以如果可以，要趕快換工作。沒辦法，就法律就長這個樣子。

上一堂提到的，那幾號解釋，317、327、673號跟713號，裡面都有一些責罰非難的規定，那些規定你大致上可以歸納出，就是說單純，如果是應扣未扣，因為這個時候有產生國家短收稅款的風險，這一種短收稅款的風險，原則上他會用漏稅罰，這種處罰，比較沒有所謂的上限額度的問題。可是單純的未填發扣繳憑單，其實主要是風險，是在國家無法對帳，沒辦法確切地清楚知道說，這個錢到底是誰的。那原則上是行爲罰。也就是說，這一種情形應該是一個行爲罰的概念。而這種行爲罰，我們從一路317、327，基本上當時都是警告一下，說，這個要注意到有比例原則的問題。到673號，才比較清楚地在第二段跟第三段，特別是在第三段裡面去講這個責罰的過當的問題。釋字713號亦如是。


好，這個是就源扣繳。就跟各位談到這裡。



## 【結算申報制度】



我們最後面來談到所得稅的結算申報制度。

所得稅的結算申報在所得稅法第71條的第一項規定。當然，這個條文規定本身是綜所稅營所稅都適用喔。

根據我們的報繳合一的制度的規定，結算申報繳納是同時間在這裡完成，所以我們的綜所跟營所，申報跟繳納是報繳合一制度。我們在上稅總的時候，有提到報繳制度的合一，這個主要是考慮到避免稅捐稽徵機關核定時間差異太大，導致納稅義務人繳納稅款時間不公平而做的一個考量。那麼在你申報繳納之後，稅捐稽徵機關理論上會做調查，之後會做核定。核定的話，可能在實務上面不一定是用具體的行政處分來送達給相對人，而是用公告的方式去代替核定。相關的規定，調查，第80條的規定，公告代核定是81條第一項跟81條第三項。



這個是整個綜所稅裡面最主要的協力義務。你自己的所得結算申報的時候，你自己來做結算申報。綜所稅最重要的，往往也是許多所得類型裡面，唯一的協力義務，通常就是你有所得，你自己來報。

往前推進啊，其實在綜所稅裡面，也不乏有其他的協力義務之可能。其他協力義務，譬如說記帳，跟更早之前的登記。

申報繳納是稅捐構成要件該當的時候，要求納稅義務人在申報期限內，依法而為的一定作為。

在此之前，登記跟繳納。在綜合所得稅裡面，由於課稅的稅捐主體就是自然人。對於自然人課予登記跟記帳的義務，這一個性質類別主要是在如果你是獨立付出勞務，國家才會課予你一個登記或記帳的義務。如果不是獨立付出勞務，一般而言，不管你是資本投入或是勞動力投入，尤其是非獨立的勞務，要求薪資所得者去記帳，那是沒有太大道理。

薪資所得者，一般而言沒有記帳的能力。你要記帳只是讓自己清楚自己收入多少支出多少。

各位同學可以自己記帳看看。老師自己在學生時代的時候也想過記帳，但記不到一天就立刻做不下去，因為太瑣碎啊，做不來。當然，後來我在研究生的時候，我有信用卡，開始嘗試著想說，哦，我透過信用卡來記帳，就是刷什麼東西，原則上都用那一張卡刷。但你也知道，有些地方以前電子支付沒那麼發達，所以還是要用現金。所以當然我有想過說，那我可不可以用提領一個固定定額現金的方式，來了解一下，除了刷卡以外，我現金支付要多少。但我每次都會忘記。所以我就告訴各位一件事情。記帳很難。就這樣，我只是爲了告訴各位，記帳有點難。對一般人而言，我們沒有辦法期待他記帳。


可是我們對一個獨立執業的人，我們是有一個記帳的義務。請各位看一下所得稅法第14條第一項的第二類，第二段。

就我我因為我們所得稅法有點羅裡吧嗦的慘吼，這第二段第一句第一句因為你看，所得稅法第14條第一項第二類第二段：「執行業務者至少應設置日記帳一種，詳細記載其業務收支項目；業務支出，應取得確實憑證。帳簿及憑證最少應保存五年；帳簿、憑證之設置、取得、保管及其他應遵行事項之辦法，由財政部定之。」


所以，執行業務者的協力義務，要記帳、保持憑證。好在這個地方，根據14條的第一項第二類，第二段的第一分句，至少要設置日記帳。第二句的規定，要設置帳簿跟憑證啊，要依財政部規定的帳目跟憑證來設置好。

這個就是協力義務。協力義務不是只有71條的申報，包括在此之前的記帳跟憑證。

如果是獨資跟合夥，基本上是拿到第一類所得。第一類所得，他的記帳跟保持憑證義務是在第三章營利事業所得稅，21條、22條的第一項規定。他的登記義務，則是18到20條，已經廢止了。

所以我們現在就用這個圖形來跟各位說一下。原則上綜所稅的納稅義務人，除非你是獨資合夥、執行業務者，我們沒有特別針對其他的所得類型，課予記帳憑證的義務。

就是這一些獨立付出勞務去取得所得的人，我們課予他一個記帳、保持憑證的義務。以前有登記，現在沒登記的義務。

這個是我們現在除了申報義務，往前，大致上有協力義務的相關規定。

執行業務者要記日記帳。日記帳，其實就是流水帳。我剛剛做的那個說明，其實就是流水帳，就是我把我個人，一天會花多少，或者一個月會花多少跟收多少，去做一個收支的單純的記錄，這個就叫日記帳。現在是12月11號，昨天是12月10號，就這樣每天記帳就好。跟業務有關的收支都記進去，這個就叫日記帳。

商業會計法裡面，記的帳是T字帳，有資產負債表，看起來就像一個T。T字裡面，有資產這一邊，跟負債這一邊。負債裡面，有自己去跟人家借來的，資本的負債，跟我自己除了資本的自有資本的負債。這就是商業會計法裡面的T字帳。這個是適用商業會計「權責發生制」的基礎。

簡單來講就是，你的記帳決定你用什麼方式去呈現你的經營成果。日記帳，原則上沒有相互用收入對成本費用的問題，因為他就是一個流水帳而已，原則上就是用現金收付。如果你是用商業會計法用T字帳去記帳，因為有資產負債表、有損益表，這個時候他就有辦法去相互勾稽對應，這個就叫做權責發生制。

所以釋字722號講，今天你是執行業務者，你如果用日記帳，基本上就是現金收付制而已。但如果你是執行業務者，假設你自己比照商業會計法的規定去做T字帳的話，那這個時候，在德國就讓你執行業務者可以選擇改用權責發生制。所以，你的所得怎麼去計算，會根據你的帳簿記載的方式去做呈現。

用商業會計法，權責發生制，讓稅跟財就合一，原則上稅遵財，再做稅的帳外調整就可以。因為這樣讓遵財的人可以不用做兩本帳。兩本帳不是指內帳外帳的意思，是指稅帳跟財務帳，不要做分離。但沒有做財務帳的人，沒有資格去用權責發生制。你沒有做財務帳，對不起來，沒有辦法這樣勾稽。記流水帳，從而就退而求其次，只能用收付實現。因為只有收付實現，他才能真正表現出你的稅捐負擔能力。

因此，回過頭來，我們談到，在綜所稅裡面，凡是採用商業會計法的規定來用T字帳，去表現出他的經營成果的，理論上要給予一個選擇的可能性，讓他可以改用權責發生制。這一個就是對獨立經營業務的執行業務者，跟獨資合夥，只要他用商業會計法方式記帳，理論上就應該給予，比照營利事業所得稅裡面的方式去記帳，去做權責發生制的適用。

相反的，對一般的綜合所得稅的自然人而言，他不太會去做記帳，或者是簡單的流水帳，這種流水帳無法去對應，因為他只是單純地去記，哎，我這個時候收多少支多少，但這個支出可能對應的他前面的收多少，這件事情無法去做勾稽。在不能做勾稽的前提下，日記帳，因此他的申報稅捐的時候，原則上就是以收付實現，也就是Cash Basis Accounting，來作為一個計算稅捐負擔能力的基礎。如此而已。

進入綜所稅的申報，原則上沒有前面的這些記帳義務的干擾的話，在所得稅裡面，他就是自己的稅捐自己申報，現金收付制。

當然，這一種現金收付，往往由於我們現在實務上的給付現金的態樣也比較複雜一點，尤其是私人的營利事業，往往他給付給他的受僱人不是當月給付。可能會隔一個月，5月份才給。甚至拖欠款項，一直沒給。我們在公立學校服務最大的好處就是月初就給，我還沒服勞務，國立臺灣大學就會先給我錢。我如果換到私立東吳大學，不知道會不會這樣，我不知道。我只是說，一般私營的事業通常不會當月就給你，他也不會在那一個月的月底給你，他是隔一個月才支付，上個月你付出的勞務的報酬。

而至於在這種情況底下，比如說啊，我領到錢，我是隔一個月啊，那你可不可以把12月的薪資所得算成1月份的薪資所得？換言之，因為你是1月份才實際領到啊，那你這個時候12月就提前課，那這樣會不會提早一個月課？對納稅義務人來講，他會有那個期限利益上的損失。

這個地方的回覆是這樣。假如僱傭關係連續，這個差別也就沒那麼大。因為你等於是隔一年，你一定會領到，一樣有薪水。確實會有時間差，也因此實現原則這一個原則，確實產生實現時間點的差。但如果這個時間點差異差太遠的話，確實就會存在著量能課稅原則過早實現所得，去計算課稅的稅捐負擔的問題。尤其是累積多年所得，如果一次大量實現的話，這個時候會對綜合所得稅的納稅義務人，產生一個稅捐負擔上急劇（集聚）的效應，就是累計稅率底下，他稅負會提高許多。

所以在我們的所得稅法第14條第二項，有一個變動所得的概念。變動所得，是累積多年所得一次大量實現。可是因為14條第二項只限於四種類型所得。我們的累積多年所得一次大量實現，當你時間差，差太遠，比如說非法解雇受僱人。雇主非法解僱受僱人，受僱人對雇主提起的勞動關係確認之訴，跟請求給付基於勞動關係的薪資報酬。這個當他打勝的時候，雇主才會給吧？他很可能會是，累積多年所得，一次大量實現。

這一種情況底下在我們現行實務裡面並沒有適切地去反映出他可能是累積多年所得，而一次大量實現在，累計稅率底下會增加稅負的問題。我們只有在變動所得這一個類型裡面，才特別去顧慮到累積多年所得一次大量實現。


正因為如此，所以這裡面確實，實現原則，是量能課稅原則上講的現金收付制，並沒有必然要用權責發生制，可是因為我們現行法律上規範的缺陷，往往即使是現金收付，也仍然會跟實際上的稅捐負擔能力有差異甚大的情形。依據個案的情況，由於立法者沒有做適度的規範，從而也會讓納稅義務人不當地增加不少的稅捐上的負擔。


申報跟繳納之後，做調查，在我們的所得稅法第80條的規定。第81條的第三項核定跟公告，那這大致上是我們整個的稅捐申報程序的規定。

我們接下來要先去談，這個申報義務有被免除的情況。我們的所得稅法第71條，請大家看71條的第三項規定：「中華民國境內居住之個人全年綜合所得總額不超過當年度規定之免稅額及標準扣除額之合計數者，得免辦理結算申報。但申請退還扣繳稅款及第十五條第四項規定之可抵減稅額，或依第十五條第五項規定課稅者，仍應辦理結算申報。」

71條的第一項，原則上所有的納稅義務人都應該做結算申報。

結算申報的義務的免除是71條的第三項第一句的規定，當你的所得額太低，低於一個門檻，就是免稅額加標準扣除額的合計數，這時候免辦理結算申報的義務。

我們處理兩種情況，第一個是納稅義務人，如果死亡的情形。有所得的，納稅義務人在年度還沒有結算申報之前，他過世了。這個是在71-1條的第一項規定：「中華民國境內居住之個人於年度中死亡，其死亡及以前年度依本法規定應申報課稅之所得，除依第七十一條規定免辦結算申報者外，應由遺囑執行人、繼承人或遺產管理人於死亡人死亡之日起三個月內，依本法之規定辦理結算申報，並就其遺產範圍內代負一切有關申報納稅之義務。但遺有配偶為中華民國境內居住之個人者，仍應由其配偶依第七十一條之規定，合併辦理結算申報納稅。」




第71-1條的第一項跟第一項的第一句的規定，納稅義務人取得所得，但他在年度中死亡，由其他的第三人來負責做結算申報程序。納稅義務人以外之第三人，包括執行人繼承人或遺產管理人。他是以一個第三人的身分，為取得所得者之納稅義務人來履行結算申報的義務。所以他不是稅捐債務人，他不是納稅義務人，因為他不是取得所得的人。也不是扣繳義務人。他是什麼人？他是第三人，就是這樣。

他是被法律賦予給他一個行為義務，這就是納保法施行細則第2條第二項所講的其他行為義務。法律沒有給他一個正式名稱，他是一個第三義務人的概念，這個第三義務人要負責來去做納稅義務人的結算申報義務的申報，而且要就該項稅款來負責繳納。

如果他有配偶的話，則根據71-1的第一項但書規定，由配偶來做結算申報。所以納稅義務人死亡有配偶，原則上有配偶做結算申報。

同樣的情形，在第二種情況叫離境。納稅義務人在年度內取得所得，但結算申報之前離境，根據71-1的第二項規定：「中華民國境內居住之個人，於年度中廢止中華民國境內之住所或居所離境者，應於離境前就該年度之所得辦理結算申報納稅。但其配偶如為中華民國境內居住之個人，仍繼續居住中華民國境內者，應由其配偶依第七十一條規定，合併辦理結算申報納稅。」


離境的時候，要由納稅義務人他自己來做結算申報。但如果配偶是中華民國境內居住個人，而且繼續居住在中華民國境內，則由配偶來做所得稅法的結算申報。

所以主要兩種情況，第一個是死亡，第二個是離境，就是境內居住者的納稅義務人在結算申報之前離境，這個時候有配偶是我國的稅籍居民繼續居住在我國境內，原則上由配偶去做結算申報。因為有兩個人嘛，就是其中一個人死掉，另外一個是境內居住者的身份，他就繼續依結算申報的規定。那如果沒有配偶，他是單身或配偶非境內居住者。這時候就會回過頭來來去適用71-1的第一項規定，由這個遺囑執行人繼承人或遺產管理人於被繼承人死亡時三個月內依本法規定來做結算申報。離境的時候則是71-1的第二項，是在離境時做結算申報做結算申報。


你離境的時候，如果你沒有去做離境時的結算申報，根據72條第二項的規定，可以在委託中華民國境內居住之個人負責代理申報。


這個條文規定有點凌亂，不過我們大致上整理。

第一個納稅義務人的自己稅捐，應該在71條第一項規定裡面讓自己去做結算申報。

納稅義務人如果在結算申報前死亡，或納稅義務人在結算申報前離境，就是去中華民國再也不回來哦，這種情況底下有配偶的話，原則上由配偶來當結算申報的行為義務人。

沒有配偶啊，或者配偶非境內居住者的身份，那這個時候死亡的情形則由遺囑執行人、遺產管理人或者是繼承人來為納稅義務人做結算申報程序。這是一個行為義務的負擔，所以他是一個第三義務人的概念。

那麼如果是離境，就是他在所得取得之後，在結算申報之前就離境，他沒有配偶或是境內居住人的配偶的話，這個時候離境的時候去做結算申報，或者他再委託本國人來為他去做結算申報程序，這個就是72條的規定。

我們的現行法規範，有點複雜，但我還是期待各位同學，整理過後，至少現況的情形你一定要熟悉。

再講一次，結算申報是自己本人申報。如果配偶是境內居住者，當他死亡或離境，則由配偶來做結算申報程序。如果這個配偶的要件不該當，那麼就是死亡的時候，由遺囑執行人、繼承人或遺產管理人，來做所得稅的結算申報。如果是離境，則由本人離境時做結算申報。沒有做結算申報，可以委託第三人來做結算申報。第三人仍然是第三義務人，他並不是一個在法律上，我們規定他作為有結算申報義務的行為義務人。


這個是我們現在的對關於這個納稅義務人的結算申報行為義務的規範。

## 【義務違反之制裁】


有結算申報的義務，才會有在應履行而不履行的情況，產生漏稅罰的問題。換言之，到這個地方為止，是申報繳納的義務。我們是報繳合一制度，所以在申報的時候，也要將相關的稅款繳納完成。當他沒有繳納國家認為該收取的稅捐債權的時候，對申報協力義務之違反，就因此產生了所得稅法第110條第一項跟第二項所規定的漏稅罰的處罰。


我們來看第110條第一項跟第二項。有申報義務之違反，如果納稅義務人申報的時候將足額的的所得，已依本法規定辦理結算決算或清算申報，而對依本法規定應申報課稅之所得額有漏報或短報的話，處以所漏稅額二倍以下之罰鍰。

應申報未申報，這個時候，除了補徵稅而以外，還要處以三倍以下的罰鍰。110條的第二項規定，他認為，應申報完全沒有去做申報，這個可責罰性非難性是比，已申報、短漏所得額申報的可責罰性非難性更高。

簡單來講，依照我國立法者的邏輯，你自己來報了，好歹我收到一部分錢。可能我沒有收足額，但你有繳一部分，但連來報都不來報，那他就認為你很過分很重大地違反義務，讓國家連錢都沒收到，也無從查核起。因為不申報，他也無法去分辨你，到底是所得額為報繳的情況，還是是未達申報門檻的情形。

我們的所得稅法第71條第三項有一個申報所得額的門檻規定，就是標準扣除額加免稅額。你只要所得沒有超過那個門檻，那就免除你稅捐申報的義務。這很明顯的是，認為既然你有所得，但你沒有超過免稅額加扣除額，計算的結果，你仍然不用報繳任何稅捐，從而就免掉稅捐申報上的義務。這是基於實用性原則，而給予納稅義務人免申報的義務。

我個人認為這個條款規定並不妥當，不妥當的原因是在，有所得理論上就應該要去做申報。因為他變成了讓納稅義務人主張，如果主張我的所得，雖然有所得，但沒有高過免稅額再加標準扣除額，因此依照法律規定，他是可以免申報的義務。那至於他的所得，他就會變成了，那我究竟我的所得是不是所得、是不是高過免稅額加扣除額，額度上面會產生法律見解跟稅捐稽徵機關的歧義。

原則上，如果依照法律規定不超過那個門檻，他確實不用申報。可是究竟他是不是所得，究竟他是不是高過免稅額跟標準扣除額的門檻，是不是因此免納稅捐，這個仍然要由稅捐稽徵機關在你申報之後，才有辦法去做判斷。

從而老師個人認為71條的第三項，免申報義務是不太適宜的規定，不太妥當，他會讓納稅義務人對這一類的所得，由於他要自行去判斷他到底是不是所得，他要自己去判斷他到底是應稅所得或是免稅所得。因為如果他應稅所得不超過免稅額加標準扣除額，理論上他是不用申報。他會構成了讓納稅義務人自己去做判斷，只要他未達門檻，所以他就不用申報。

這就會對申報義務究竟有沒有違反，可能是來自於納稅義務人跟稅捐稽徵機關對系爭所得，採取不同法律見解，而產生出來的歧義。理論上應該是請他盡量去做申報，所有只要該當於所得，不管是應稅或免稅的所得，都讓他去做申報，再由稅捐接機關來判斷是應稅或免稅所得。因為稅法本身，有非常複雜的解釋函令，對納稅義務人，他並不知道究竟這個是應稅或免稅所得，或者是所得還是非所得。讓納稅義務人自己去判斷，這個風險是非常高的。他自己如果沒有把各類所得全部都寫上去，就很可能會因為他只是存在跟稅捐稽徵機關不同的法律見解，那為什麼他會存在不同法律見解？因為他不知道解釋函令是這樣操作。

原則上應該是讓納稅義務人盡可能申報，把所有他認為可能該他所得的事實全面性的申報。當他申報以後，再由稅捐稽徵機關來為他去決定。因為稅捐稽徵機關有自己常用的解釋函令，好，這個所得，是所得還是非所得，這個是應稅或免稅所得，我幫你判斷。所以你給我事實，我就給你稅額。而不是納稅義務人自己要判斷，他到底要適用哪一條法律，到底是應稅所得還是免稅所得，或是非所得或是所得。

在這種情況底下，稅捐法制如此複雜，對非專業的納稅義務人而言，他等於是自己要去判斷。所以，有這個法條規定，我還是會建議所有的納稅義務人盡量都申報。你自己不要自以為是，說，啊，我所得沒有超過免稅額，加扣除額，所以我就不要申報。因為你不申報，很可能就會110條第二項。

你完全不申報，這個時候他查到的時候，稅捐稽徵機關會主張，可能跟你當初認知的法律見解不同。這時候他認為這是所得，而且應稅所得，你沒有報，三倍以下罰鍰？那為什麼會加重處罰？因為他認為你完全不申報。但可能納稅義務人只是認為說，這個是在我的法律概念來講，應該是非所得的概念。

所以法律條文規定，這個71條第三項的免申報義務，我個人認為是一個很不好的規定。在法律沒有變更之前，原則上納稅義務人應該是盡可能把認為有可能構成所得的事實，盡量申報。因為對這個所得的性質，他到底是所得還是非所得，你納稅義務人沒有辦法比稅捐稽徵機關做更好的判斷。

就以損害賠償為例。那一種是所得，哪一種是非所得？我們花了一段時間跟各位去講，何謂損害賠償，損害賠償為什麼是非所得，或者為什麼他是替代經濟成果的履行利益的損害賠償，就應該要報所得稅。所以有可疑，盡量揭露，盡量寫。

在現行法制裡面，雖然有告訴你一個，如果你的應稅所得不超過免稅額跟扣除額，那這個時候就不要申報。你可以免申報義務。但因為這個地方第110條第二項跟第一項的規定，他有稅負裁罰上的差異，簡單來講，就是應申報未申報這種情形底下對納稅義務人構成極大的一個風險。


也因此，回過頭來，我們講在這裡面短漏稅的裁罰分成了應申報未申報三倍以下的裁罰，如果以已申報，短報跟漏報的情形不太一樣。

短報是指所得來源申報，但對於他的數額有短少。短報所得來源是我從臺大拿到100，但我只報80，這個叫短報。

漏報則是數個所得來源，只申報了一部分的所得來源，另外一部分所得來源沒有申報。比如說，我在臺大有所得，我在成大有所得，我只報臺大的所得，不報成大所得，這個就叫漏報。

什麽是應申報不申報，就是我有臺大成大所得，但我從來不申報。

這個就叫做第110條的短報申報，應申報未申報。

那其實從理論上來講，不管是短報漏報或應申報未申報，都讓國家無法即時取得應收的稅款，從而產生短收稅款的風險。理論上這幾種情況,包括，應報未報、應報已報但短報、應報已報但漏報、應報已報但做虛偽不實的成本費用的增加，其實都是讓國家無法即時收取全部的稅捐債權債務的內容，從而存在著短收稅款的風險。這個就被認為是一個應受處罰，漏稅罰的態樣。

實務上面，漏稅罰，如果是過高的倍數，往往司法機關也會遵照立法機關的判斷，但一般而言，漏稅罰按倍數裁罰，不被認為是一個過度的責罰。行爲罰，如果有按倍數裁罰，才會有過度責罰的問題。從而這也是我們剛剛在提到扣繳義務的時候，扣繳義務為什麼會去區別，他到底是屬於哪種態樣。如果是應收未收到稅款，這個時候漏稅罰，確實會以倍數裁罰，而倍數其實是沒有數額的絕對上限的問題。可是用行爲罰概念的話，他則必須要有上限的概念，否則會有違反責罰相當性的問題。

目前為止，跟各位提到結算申報前置的協力義務，申報義務的違反，因此產生出來的處罰。雖然有申報義務的免除規定，但現行實務上面，如果納稅義務人採取跟稅捐稽徵機關不同的看法，而納稅義務人也確實沒有去做申報的話，這個時候可能會有比較高額的漏稅罰，在110條第二項的三倍以下的罰鍰。補繳稅款不是罰鍰。再講一次補繳稅款不是罰鍰，只是履行稅法規範的納稅的義務。裁罰才是適用責罰相當性的部分，而漏稅罰目前為止，大法官解釋沒有出現過，認為責罰過度，過度非難的問題。漏稅罰沒有，但行爲罰是有的，行爲罰有過度非難的可能，在我們前面講扣繳義務的漏稅跟行爲罰的時候，也有同樣的適用。


那我們就把所得稅法，大致上從所得稅法的應適用的基本原則，到主體、客體、稅基、稅率，稅基乘稅率得到稅額，進入稽徵程序裡面的結算申報、就源扣繳程序，協力義務違反的制裁，包括了行爲罰跟漏稅罰這兩種可能性，這就是一整個所得稅法裡面規範結構，大致上會討論到的相關的法律規範。

理論上來講，關於協力義務跟義務的違反，在德國是都放到稅捐通則，所以在德國的所得稅法裡面，原則上就只有稅捐債權債務的構成要件跟法律效果規定。稽徵程序則一律到稅捐通則那個地方，去做統一性的規定。那我們的稅捐稽徵法並不全然是稅捐稽徵法。我們自己的所得稅法還是有稅捐稽徵程序的規定。

所以我們所得稅法的期末考試，是全部，從實體法，到程序法跟稅捐制裁法，因為這是所得稅法的全部。我們並不是只有考稅捐債務法實體法而已。請各位好自為之。評分的方式，我們一開始就跟各位講過。


我們今天就到這裡。
