# 20231204_01

---
課程：1121所得稅法一
日期：2023/12/04
周次：14
節次：1
---

## 【就源扣繳程序】

在稅捐稽徵程序裡面，上個禮拜提到了關於婚姻跟家庭的合併申報制。那么我們今天進入另外一個在稅捐稽徵程序裡面，特別在個人綜合所得稅裡面扮演一個非常重要的角色的「就源扣繳程序」。

我們今天談完就源扣繳程序之後，我們再回過頭來來跟各位去談跟結算申報程序有關的相關的規定。

首先請各位翻開到所得稅法第88條跟第89條的規定。也是我們的就源扣繳程序的基礎規定所在的地方。


我們來看一下88條的第一項第一款的規定，納稅義務人有下列的這些所得的時候，原則上由扣繳義務人……這個是對一個基本權的主體，也就是他本質上本來就是一個基本權主體，他是一個第三人的角色，然後要求他作為一個行為義務人，在給付所得，有下列這些所得的時候，那麼原則上要依照法律所規定的扣繳率，或扣繳辦法來扣取稅款，並依照92條規定的方式去做繳納。

因此各位看到88條的第一項第一款，首先第一個，哪一類的所得呢？在第一款規定裡面是，當你公司分配給非中華民國境內居住之個人，以及總機構在中華民國境外營利事業之股利。簡單來講，就是你的股利所得的取得者，是非境內居住者或者他是非境內的營利事業，也就是總機構不在中華民國境內，在這裡面的股利所得。這個是第一款的第一分句。第二分句：「合作社、其他法人、合夥組織或獨資組織分配予非中華民國境內居住之社員、出資者、合夥人或獨資資本主之盈餘。」


簡單來講，第一款規定其實就對應只有一類所得，就是前面所得稅法第14條第一項第一類的營利所得。營利所得的股利盈餘的取得者，非境內居住者（自然人跟營利事業），你只要是非境內居住者取得股利盈餘的分配的話，原則上就是適用88條第一項第一款我們所規定的，由扣繳義務人在給付的時候，按照扣繳辦法的規定或扣繳率的規定，以92條的規定來去做繳納稅款的工作。


第一項第二款：「機關、團體、學校、事業、破產財團或執行業務者所給付之薪資、利息、租金、佣金、權利金、競技、競賽或機會中獎之獎金或給與、退休金、資遣費、退職金、離職金、終身俸、非屬保險給付之養老金、告發或檢舉獎金、結構型商品交易之所得、執行業務者之報酬，及給付在中華民國境內無固定營業場所或營業代理人之國外營利事業之所得。」


我們去對照第14條的各類所得。剛剛已經講過了第一類的股利盈餘。

我待會要去講，就源扣繳這個制度，存在的正當性跟必要性。但各位首先要先明白，我們現在法律規範的狀態是長什麼樣子？


各類所得，第一類的股利盈餘，第一款規定已經有談過了。接下來我們來看第二款的規定。

第一項第二款：「機關、團體、學校、事業、破產財團或執行業務者……」，這是給予者的主體要件的限制，簡單來講就是，薪資所得並不是全部都要去做就源扣繳，特別是私人給付的薪資所得。舉例而言，你在家裡面請家教。這個並不是要做就源扣繳。儘管取得的人是薪資所得者，因為他是受到你的指示，在特定的時間地點去給付特定的勞務的內容，原則上按時間計算報酬。這個薪資所得，並不需要去做就源扣繳。薪資所得不是必然要就源扣繳，可是因為你只要是機關團體學校事業財團或執行業務者，你受僱於以下這些主體的話，才會適用就源扣繳。

這些主體，法條文字裡面，本身沒有上位概念去描述「機關、團體、學校、事業、破產財團或執行業務者」，每次講完都非常累。

這也是我們立法技術極差勁的一個原因。就因為他常常沒有上位概念，為了要講一句，本來應該是簡單的問題，一句話就可以交代。比如說境內居住者，境內居住者這個概念，其實在我們的所得稅法裡面並沒有很常出現。那麼德國法制裡面會用一個上位概念，就是無限制納稅義務人，或限制納稅人，就涵蓋了在法條規範技術上面所想要涵蓋的對象。可是我們的稅法的立法，立法者的技術，我不知道他們哪裡來的，為什麼每一次都要用很長的一句話去交代一個本來應該很簡單的概念。比如說總機構在中華民國境內之營利事業，哇，念完就覺得，好像要花很長的時間去講一個本來透過特定名詞去指稱即可的概念，

這個讓我也大概去聯想到我們民法的立法者，因為直接從國外的法律制度把抄過來，法律概念的用意就是透過這個名詞去定義，而且彼此之間我們就不用再去討論它的意義跟内涵。這也是法律在很大程度上不太能夠用白話文去表述一些重要意義內涵的原因。也就是他需要透過一些專有名詞去告訴你說，這個地方這個名詞代表某一個意義。透過這個意義的表述，雖然是門檻沒有錯，因為，法律本身確實是用我們的文字所堆砌起來的，可是不是白話文的用語，原因是因為在這裡面，有許多的意涵，如果沒有辦法去做約定成俗的一個表述的方式，你必須要有很長的文字去描述一個，應該要結構內容清楚的一個概念。這也是文字的表述本身，可能可以蘊含的一個價值，跟蘊含著人們在討論他的時候的一個相約成俗的概念。不然的話，我們的法律文字，尤其在現代，每一個領域都需要，如果要做高密度的立法，他本身就需要以精練的文字能夠去表述你的所想要表述的概念的內容。


雇主是一個事業組織的話，那你所獲得的薪資所得的報酬，88條會課予這個給付者的一個扣繳義務。但如果給付者是私人，薪資所得的給付，是沒有這樣子的一個扣繳義務。簡單來講就是私人給付的的薪資所得，就回到我們一般原則性的結算申報制度，由取得所得者他自己來做申報。


好，那回過頭來，「機關、團體、學校、事業、破產財團或執行業務者」，我姑且稱之為「事業組織」，這個只是老師給他一個概化的上位概念的名詞。

事業組織所給付的薪資所得，第三類所得，要適用就源扣繳。

第四類，利息。事業組織給出來的第四類利息所得。

事業組織給出來的第五類租金，不動產或動產產生出來的租金。

事業組織給出來的佣金……佣金的所得到底算哪一類啊？我們在14條裡面找不到。佣金是透過勞務的付出所取得，比較接近在民法上面委任或是行紀行為所產生出來的獨立勞務的付出的對價，所以比較接近是執行業務所得的類型，但法律並沒有在這裡面直接講執行業務所得。

簡單來講就是說，如果你是事業組織所給予的第二類執行業務所得，屬於佣金的話，他還會是一樣，要做就源扣繳。


那麼接下來是權利金，再回到我們剛剛講的分類，第五類裡面，租金跟權利金的部分。

那么接下來，競技競賽及機會中獎，第八類，一樣，要有一個主體要件的限制，他必須是事業組織所給出來的競技競賽及機會中獎。私人給予的競技競賽或機會中獎，私人自己舉辦的，並沒有就源扣繳義務的問題。

第九類啊，第九類也就是包含了這裡面非常長的一句話：「退休金、資遣費、退職金、離職金、終身俸、非屬保險給付之養老金」，對應的其實就前面的第九類的退職所得。

接下來在我們所得稅法第14條的第一項裡面第十類是其他所得。

接下來有告發或檢舉獎金，其實是第十類，是一時性的所得。雖然在實務上可能有些人就常常……但這基本上不是一個執業行為，應該是一個偶發性一次性的行為。在我們許多的行政法規範裡面，有一些檢舉獎金的設置哦，這一類的檢舉獎金的設置，原則上是一次性的所得啊，除非你以之為業哈。這個很難想像，但也不是說真的很難想像，因為在臺灣的文化裡面有「檢舉達人」，這個就可能以之為業。他就到處建築工地，他就去拍，因為只要塵土飛揚啊，水很髒的話，常常就會有人去拍拍拍，然後就一直寄寄寄，寄到環保單位、道路交通、建管、勞動主管機關。這一類的東西到處都有檢舉。財稅，也有啊。財稅也有檢舉獎金。

告發或檢舉獎金，原則上是一次性的。假設，你還真的能夠以之為業，因為這個特殊的制度，以之為業，其實不妨礙變成是一個營利事業的可能啊，有可能啦。

我以前在德國念書的時候，我們老師就講過一個非常特殊的行業，是做賭博的職業玩家。在德國，原則上，這種賭博性的收入不算所得。因為這一種十賭九輸的射悻性很高的特性的關係，德國是自始把他從所得課稅的範圍排除。

有繼續性的這個特徵，才會產生出一個所得的概念。那這種射悻性很高的賭博的收入，德國自始上稱之為叫嗜好，有個概念叫Liebhaberei，意思就是這是一個人的偏好，特殊嗜好。所以你喜歡去拉霸的，德國基本上不會把你拉霸的收入當作所得課稅。當然，你有所得，不課稅，但你有虧損就不準減除。對德國人來講，有正所得就要課稅，但有虧損也要足以減除。所以他們從概念上是自始把那一種射悻性非常高的這一種賭博性的行為，就把它排除出去，完全不當作是所得的類型。這是德國人的概念。

臺灣，我們的所得稅法並不是這樣，這種一次性的所得，還是會透過一時貿易盈餘機會中獎，第八類以及第十類，包括賭博收入，是屬於這個第十類的其他所得。從而我們的法律環境確實跟德國不太一樣，我們反而比較接近美國。因為在美國，賭博的收入，還是會當作所得來課稅，可是虧損減止零而已。

這個是，跟我們的法律的規範不太一樣的地方。


德國，對於職業玩家，因為職業玩家是可以計算他的輸贏的。所以，在西方的社會裡面有一些職業的牌手，在德國，這個可以算營利所得，他可以自己計算盈餘虧損，這個還是可以賺錢的哦。如果去賽馬或賭馬的，是賭博行為，但如果是以之為業的話，在德國還是構成了所得稅的課稅的對象。

回到我們這裡，告發跟檢舉獎金是第十類的所得。只是88條這邊把這個告發跟檢舉獎金獨立出來。

結構型商品交易之所得。結構型商品交易所得從哪來？結構型商品，意思是，他本身是一個衍生性金融商品，是一個結構型的債券，本身是財產交易所得的一種類型，也就是我們前面的第14條的第七類，財產交易所得。

接下來，執行業務者之報酬。要特別注意，並不是所有的執行業務者的報酬，是機關團體學校事業組織等，這種事業組織型態所給予的執行業務者報酬，才會是屬於要做就源扣繳。所以，換言之，如果是私人聘請執行業務者，比如說私人聘請律師，是不需要做就源扣繳的。因為在法制上認為，私人比較沒有能力去適用比較複雜的就源扣繳制度。這也是第二款規定，我們只抓事業組織，做就源扣繳義務人的這個規定的正當性所在。

因此我們大概統合一下。

第一類，要。

第二類，不一定，因為要看是不是有涉及到業務報酬。

第三類，薪資所得，只要是機關團體學校事業組織給的薪資所得，要。

第四類，利息所得。

第五類的租金權利金，以及第八類跟第九類第十類裡面的告發及檢舉獎金。

第七類的結構型商品交易之所得，以及第二類，機關團體學校事業組織給予執行業務者之報酬。

農林所得那一類。在前面8條規定，有跟各位講過農林所得，本身是限於大自然界第一次產出，所以本身不會有就源扣繳的問題。因為是第一次產出，我就是從土地山川河流海洋，第一次產出取得的，這個都是我們在所得稅法第8條裡面所謂的農林漁牧礦，不會有就有扣繳問題。

因此，這個條文規定，其實換句話講，只要是機關團體事業組織給出來的所得，基本上在臺灣是全面性地適用就源扣繳程序。老師要得出的是這個結論。當然，仔細的適用，確實還是要回到88條的第一項跟第二款的規定，但這個兩款規定其實告訴你，臺灣的就源扣繳程序基本上是全面涵蓋，各類所得，都有就源扣繳問題。你只要是事業組織給出來的各類所得，原則上就會有就源扣繳程序。

我等下會講到，這個是有歷史背景的。有歷史背景，才會這樣一個非常廣泛的就源扣繳程序。

相對於德國，德國的就源扣繳程序，其實只有兩類所得，一個是利息所得，一個是薪資所得。德國的就源扣繳程序是有限的所得類型。

在臺灣，第一款規定是股利盈餘，第一類所得。第二款規定幾乎涵蓋了所有除了農林所得以外的各種類型的所得，只要你是事業組織給出來的所得，是涵蓋範圍極為廣泛的就源扣繳程序的所得。

那么我們最後面，再來談，88條第一項第二款，「及給付在中華民國境內無固定營業場所或營業代理人之國外營利事業之所得。」

這個規定，其實可以跟前面的第一款規定結合在一起看，原則上是所得者，不管你是取得股利盈餘，還是你給付給境外營利事業的所得，當然這裡面有一個構成要件是，你在中華民國境內沒有固定營業場所或營業代理人的國外營利事業。

就是，你付錢給他，這個所得的取得者，他本身是國外營利事業，但他有一個要件是，在中華民國境內沒有固定營業場所或營業代理人。

這個條文，請各位跟41條的規定，結合在一起看一下啊，因為在這個地方，我們的法條規範的技術極為繁瑣，而且那個概念，看單一這個法條不太容易清楚。

我們來看一下所得稅法第41條的規定：「營利事業之總機構在中華民國境外，其在中華民國境內之固定營業場所或營業代理人，應單獨設立帳簿，並計算其營利事業所得額課稅。」

國外營利事業在中華民國境內有一個固定營業場所或是營業代理人的時候，

第41條的規定可以告訴你，為什麼法條在88條第一項第二款裡面這樣規定。

「營利事業之總機構在中華民國境外」，這個就是88條講的「外國營利事業」。所謂的外國營利事業，在我們的稅法裡面，一下子用「總機構在中華民國境外」，一下子用「外國營利事業」，這兩個概念，立法者自己不會覺得自己有用詞不太一樣，他不會覺得哦。

這個就是外國營利事業。外國營利事業在中華民國境內有固定營業場所或營業代理人的時候，根據41條的規定，他要單獨設立帳簿，並計算營利事業所得額課稅，簡單來講，就是一個外國營利事業，只要在中華民國境內設有，第一個是固定營業場所，第二個，或者你有營業代理人，那這一個在境內的固定營業場所或營業代理人，他就變成了，根據41條的規定，要獨立設置帳簿，申報營所稅。

所以他雖然在法人格上，他不是一個獨立的法人格，可是在稅法上，他是一個獨立的稅捐申報主體。這個外國營利事業在我國境內之固定營業場所或營業代理人。在法人格上，他不是獨立的法人格，也就是說，他還沒有到子公司這個程度，他沒有獨立法人格，他只是一個分公司、固定營業場所、辦公場所，或者他在境內設有一個代理人，代理人沒有非得必然要有一個固定辦公的地方。

第10條的第一項是固定場所的規定。第10條的第二項是營業代理人的規定。那這兩個條文，我們到營利事業所得稅的時候，會再跟各位去詳細談，在稅捐法上的權利義務。這兩個是獨立的具有稅捐負擔能力的營利事業。也就是外國營利事業，設在中華民國境內的，只要你構成了固定營業場所，跟營業代理人，符合第10條第一項或第二項的這個要件的時候，他本身就是一個獨立的稅捐申報主體。

因此，稅法並沒有全然遵守民法上或者是公司法上的要件的規定。也就是說，稅法他自己本身認為，在這個地方他是一個獨立經濟主體，他已經有辦法自己去做一個稅捐申報。

所以，回過頭來，我們的再來看一下剛剛我們念的88條的第一項第二款的後段規定。當你付錢給一個外國營利事業，如果他在中華民國境內有固定營業場所或營業代理人，因為你付錢給他，拿錢的這個主體，雖然他在法人格上，不是獨立的法人格的主體，可是根據所得稅法的規定，他是一個獨立的經濟主體。他是可以有稅捐申報能力的，根據41條的規定，我們是要求他要獨立設立帳簿來做營所稅申報。

所以，為什么剛剛老師會講說，其實第二款後段規定跟第一款規定的背後的規範意旨都是相同的，就是，當你付錢給一個境外所得者，沒辦法，我只能做就源扣繳。

第一款的規定是，你付給境外所得者股利盈餘，第二款的最後那一個半段的那個規定，他是付錢給境外營利事業。只要你付錢給境外營利事業，他沒辦法去做獨立的結算申報的話，你要付錢給他，你就必須要就源扣繳，不管你是不是事業組織。

也就是說在這裡面，我們對第88條的第一項第二款的規定，特別是在你給付給境外的非境內居住者，他是一個所得者，他是取得中華民國來源之所得的時候，第一款規定股利盈餘，第二款的後段的這一個對外所做的給付，原則上必須要用就源扣繳的程序，不然我們在現實上沒有辦法再去對一個境外所得者，去要求他再回過頭來，去做所得稅的結算申報。

就源扣繳程序，特別是在對境外所得者的給付裡面，體現了 pay as you earn 的想法。賺到錢的時候，那個給錢的人就直接幫你扣繳下來，這個就源扣繳，在非境內居住者的課稅裡面，是一個在國際之間基本上被承認的一種課稅手段。因為你沒辦法回過頭來期待非境內居住者要去做結算申報制度。

這個第一款跟第二款後半段背後的法律上的規範的正當性依據在於，對境外所得者的這個課程程序，原則上你沒辦法讓所得者自己去做結算申報，必須要仰賴給錢的人站在所得的源頭，pay as you earn，PAYE。就源扣繳程序，一般來講就是所謂的PAYE制度，你在賺到錢的時候付錢。另外一個是PAYG，就是pay as you go。就是當你離開的時候，你要棄籍，要到國外去的時候，離境的時候，也會要求一個結算申報的這個制度

我們待會去講結算申報制度的71條的相關規定的時候，我們再跟各位去做說明。


回到88條的第一項第二款的後段，跟第一項第一款規定，基本上，取得所得者是非境內居住者，取得中華民國來源所得的這種情形底下，適用所謂的就源扣繳程序的規定。

88條的第一項，第三款跟第四款規定，都是對應營利事業所得稅裡面的第25條跟第26條。

第25條是，跨國際活動的海運跟空運，這種運輸事業；26條則是跨國際活動的影片事業，像好萊塢的影片業，這種國外的營利事業，在臺灣所取得的所得課稅的方式。

25跟26條的規定，我們一樣在營利事業所得稅裡面再去跟各位去講啊。本質上，這兩類的所得都不太容易去拆分他的收入跟成本費用，由於他本身是一個國外的營利事業或國外的海空運輸事業，那基本上都會比較偏向由船籍國，來去做管轄，因此原則上只有船籍國才會取得相關的財務申報的資料。那也因此大多數的非船籍國的國家，通常都是用比例的方式去做課稅。這也是25條跟26條，本身有一些營利事業所得裡面的特殊背景。這個我們留待到營利事業所得稅裡面去做進一步說明。

我們，回過頭來，在個人綜合所得的這個規範裡面，88條的第一款第一項第一款規定跟88條第一項第二款的規定，各類型所得，十種類型的所得，其實都被涵蓋在內，有適用就源扣繳程序。這是一個非常廣泛的就源扣繳程序的規定。原則上是你只要是事業組織所給出來的所得的話，不管是執行業務者所獲所得或是薪資所得，基本上都會要適用就源扣繳程序。

88條的第二項也還是涉及到獨資跟合夥組織的營利事業：「有應分配予非中華民國境內居住之獨資資本主或合夥組織合夥人之盈餘者」。

獨資合夥的營利事業在你分配，就是辦理結算申報或清算申報有應分配予非中華民國境內居住之獨資資本主或合夥事業之合夥人的盈餘的時候，「應於該年度結算申報或決算、清算申報法定截止日前，由扣繳義務人依規定之扣繳率扣取稅款，並依第九十二條規定繳納」。

第二項規定其實也是88條第一項第一款規定的延伸，只是他是在結算申報或決算或清算申報裡面，再另外獨立出來去做一個規定而已。其實他的重點仍然是在，你取得股利盈餘的所得者是非境內居住者，那取得的所得，我們在88條第一項第一款的規定裡面就有規定，這個本來就是要做就源扣繳。第二項規定，因此主要是適用在這個清算決算，因為公司你這個營利事業組織，不管是獨資或合夥，你要做清算，大家要拆夥了。第二項規定是第一項第一款規定的延伸而已。總而言之，你只要是對於境外居住者給錢，在給錢的時候就要適用就源扣繳程序的規定。


第三項的規定，仍然是針對前面的獨資跟合夥商號，而更進一步去做，營利事業所得稅申報核定增加的所得，這條規定其實是為了配合71條第二項。

我們在民國107年，兩稅合一制度開始分拆以後，特別是針對獨資跟合夥，我們設了這個營利事業組織的型態，在課稅的形態上面，實體法嘗試穿透課稅，可是申報制度裡面我們卻做了蠻複雜的規定，相當複雜的規定。這個地方為了配合第71條對獨資跟合夥組織之營利事業，做對應的規範。

獨資跟合夥，原則上他在營所稅的結算申報，他做了申報，但他是不用再報繳所得稅的，所以他沒有稅款的繳納這個程序。因此我們在第三項的規定裡面去做了一個進一步的規定。直接就是，當你分配給不是境內居住者這個人的時候，原則上就是在分配給他錢的時候，一樣還是要去做就源扣繳程序的適用。這個是我們的第88條的第三項，一樣延伸了前面的第一項的第一款跟第二項的規定，重點仍然還是在獨資跟合夥的資本主，或者是合夥事業的合夥人，只要他不是我們的境內的個人居住者或是境內的營利事業的時候，都是要做就扣繳程序的適用。


第88條第四項是關於授權規定的條文，我們這個地方就暫且打住。


第88條，不看法條，是常常會對類型不太容易去做仔細分辨的一個條文。我自己也是。基本上，我們的就源扣繳程序是各類所得都有適用，但具體哪些類型裡面的所得，我也是要看法條。我也沒辦法用背的，因為我認為這種條文不需要背，一點邏輯都沒有了，不需要背。要背的話，不如背樂透，哪個號碼常開出來，那個我覺得還比較有意思一點。像這種條文，不需要背，各位就是看法條多看幾遍就好。真的碰到實務案例，就是法條多看幾遍。

我們國家考試也是這個樣子。國家考試雖然考所得稅法，但基本上都是法條的運用，所以。對各位來講就是法條熟悉，就這樣好了，不需要背，一個條文都不需要背，這個我可以明確告訴各位。

我跟各位也說過，以前有聽我上課的同學都會聽過，我跟各位講過，我民法，我也不會背呀，有人在背民法嗎？我倒是有背過一條：因故意或過失，不法侵害他人之權利者，負損害賠償責任。我會背這一條，是因為我在當兵的時候，我要讓人家相信我是法律系的呀。因為我們資歷不夠深啦，我們只是考上預官當個預官，人家誰理你啊。

人家説，哎，那個排長，你們都是法律系畢業的，哇，那法條很會背哦。

我說，對呀，我六法全書都背下來。

我就法典丟給他（丟小六法）：你隨便考，哪一條我都背給你聼。

哇，真的還假的啊。

不然我背一條給你看，你翻翻看啊。那個，民法184條，因故意或不實不法侵害他的權利者，應負損害賠償責任。

他不會，我就翻給他看，讓他看到，哇，你真的都背下來。

不信的話，我再背另外一條，那個不當得利那個條。我為了保險，我還再把無因管理背下來，就這樣，我就只會這三條。

就這樣，不用一點方式，那個部隊裡面，因為我們都是義務役的士兵啊，那他為什麼憑什麼要服從呢。就是說，你看你不要做什麼壞事，我法條都可以背，你幹甚麼壞事我都會記得的。就是這樣。好，這個只是純粹花招而已。

法律從來不是在背，法律是在考運用、組合、排列、邏輯分析、邏輯歸納。我們法律，因此是一個歸納分析運用之學，透過你學到的這一些法條規範告訴你的邏輯，告訴你價值上的判斷，在個案裡面去做出一個最適合的一個判斷。


所以88條，背後有一個邏輯。第一個邏輯，境外居住者拿到中華民國來源所得，就源扣繳。第二個，在臺灣的所得稅裡面，原則上只要是機關團體學校事業執行業務者給出去的所得，原則上各類所得全部都要做就源扣繳。

就這個部分，待會兒我們會去跟各位去講，這個有他的歷史背景，我們大法官也做過解釋啊，對他的看法如何，他在法律上的地位，我們待會再進一步去看。因為我對各位的要求就是，不光只是知道 why，為什麼，你要先知道法律長這個樣子。

我順帶跟各位提到，以往老師在改，不管是哪一種類型的考試，我們法律系的同學們常常有一個毛病，就是法條都沒看清楚，就在那邊講這個法條規定違憲。我每次看到這個地方的時候，我心裡面都一個 OS，就是，那你知道現在法條這個樣子，到底怎麼解釋操作，能夠在不違憲的前提底下，能夠盡量讓他做合憲性的解釋的適用，你知道什么樣子叫合憲性的解釋適用嗎？

我們很多同學動不動就說，一個法條規定違憲，所以行政處分違法。老師每次看到這裡面，我都會覺得，行政處分的違法性，你要先看法條本身的解釋適用，他如果不符合法律規範，這個行政處分固然是違法。可是如果行政處分確實是根據法律的規定，你認為他違憲，沒錯，但他是根據這個法律規定作成的話，這一件事情，由於他本身符合法律的規定，而且這裡也正是立法者所做規定的問題。因此，我們接下來其實在行政救濟程序裡面，你沒有辦法去變更這個法律違憲的狀態。


在一個法治國家，你必須要透過，要不是受理事件的行政法院法官，他去提起憲法上法律規階法規範的憲法審查，不然的話，就是人民要窮盡救濟程序之後，來提起憲法審查，你怎麼那麼快就跳到違憲層次的問題？每一次在問行政處分有沒有違法，都還沒談到符合法律規定的解釋的狀態，行政處分是否違法的時候，就一下子就跳到規範的違憲。老師都覺得非常的憂心，因為這樣你去打訴訟，難怪會一直打輸。不是這樣，真的不是這樣。有些訴訟，你是必敗的，你真的會敗，因為問題不是出在行政處分，問題是出在法律。你是必敗的，因為在這種法律維持現狀的情況下，你沒有去做規範的違憲審查，那個法律就是如此的不義。

當然啦，我今天跟各位講的例子是，連大法官都說他合憲，那我還真的有點沒輒。

因此我們在接下來的這個說明裡面，各位你先了解現況長的樣子。

根據我們第88條的規定，第88條第一項第一款第二項第三項規定，跟第二款的後半段規定，基本上歸納出來的一個類型的所得就是非境內居住者取得中華民國來源所得，股利所得，股利盈餘，第一款規定；其他的所得在第二款後段規定。二項三項的規定，這個地方延伸著非境內居住的，取得我國來源所得。這個是第一個要做PAYE，也就是這個就源扣繳程序的一個類型。

然後另外第二類就是機關團體學校事業，所給予的這一種各類型的所得，我們剛剛做了一次的總覽。當然各類所得裡面並不是全部，特別是比如說第十類其他所得，裡面只有告發檢舉獎金而已，沒有其他，比如說賭博收入。賭博的收入，不會這樣叫莊家去做就源扣繳程序吧，這個不太可能啊。像職業賽鴿，你不會叫舉辦單位，辦職業賽鴿的那個人，說，欸，我付錢給你的時候，我直接做就源扣繳。都是做不法行為了，他怎麼還會去做這個就源扣繳程序呢？如果有就源扣繳一定是詐騙啊，他們自己騙自己，就是說，哎，這個根據法律規定，合法非法都是要報繳所得稅，所以我也來做就源扣繳程序啊。絕對不可能有這樣一個情況。

第二種就是只要機關團體學校事業給的各類所得，基本上都要做就源扣繳規定。

接下來我們來看第89條的規定。承接這個88條是關於客體，也就是適用PAYE這一種就源扣繳程序的稅捐客體，所得的類型。


## 【扣繳義務人】

之後，扣繳義務人\index{納稅者!扣繳義務人}，就是扣繳的主體，扣繳行為義務的主體，在第89條的規定裡面。

好，我們來看89條的第一項第一款規定，很長，每次看到這裡，我就有點昏了。

「公司分配予非中華民國境內居住之個人及總機構在中華民國境外之營利事業之股利；合作社分配予非中華民國境內居住之社員之盈餘；其他法人分配予非中華民國境內居住之出資者之盈餘；獨資、合夥組織之營利事業分配或應分配予非中華民國境內居住之獨資資本主或合夥組織合夥人之盈餘……」

我不太知道為什麼你不就直接規定，前條第一款規定之所得，其扣繳義務人是誰，這樣就好了。我不太知道為什麼當初他們不這樣規定啊。

我念了那麼多，89條第一項第一款就對應88條第一項第一款。88條是客體的規定，89條是主體的規定，也就是扣繳義務的主體，行為主體的規定。

我們來看一下扣繳主體是誰。扣繳義務人，也就是負責人。第一分句，「其扣繳義務人為公司、合作社、其他法人、獨資組織或合夥組織負責人」。

我請各位同學把「組織負責人」畫起來，他就是以這個自然人作為扣繳義務人。不管你今天分配股利，你是什麼樣一個組織型態，是公司合作社有限合夥，或者是獨資或合夥，總而言之就是組織負責人。

第二分句，「納稅義務人為非中華民國境內居住之個人股東、總機構在中華民國境外之營利事業股東、非中華民國境內居住之社員、出資者、合夥組織合夥人或獨資資本主。」

總而言之，就是你的股東非境內居住者，這個是納稅義務人。扣繳義務人，則是給錢的組織的負責人。89條是以自然人作為扣繳義務人，那麼所得的取得者當然不一定是自然人，因為也有可能是非境內的營利事業。

第二款規定一樣，直接講看：「其扣繳義務人為機關、團體、學校之責應扣繳單位主管、事業負責人、破產財團之破產管理人及執行業務者」。


機關、團體、學校之「責應扣繳單位主管」，請各位畫起來。事業一樣，就負責人。破產財團則是破產管理人。執行業務者，執行業務者給錢的時候一樣，也有可能要去適用做就源扣繳，執行業務者在這個地方也是扣繳義務人。

納稅義務人為取得所得者。


第三款跟第四款規定，當然對應的也是前面的88條的第三款跟第四款。所以原則上我們在申報稅捐的時候，納稅義務人則是外國營利事業，或者是第四款規定，講得國外影片事業，扣繳義務人則是營業代理人，或給付所得之給付人。這個是對應的關係。

因此這個89條設定了扣繳行為義務的主體，原則上並不是直接針對營利事業本身，也就是付錢的這個營利事業本身，而是事業組織私底下，我們分兩種類型，一個是機關團體學校，用一個叫「責應扣繳單位主管」的一個名字，至少在法條規範層次裡面，不太知道到底是在講誰。

但可以很明確的，你知道他並不是要找機關團體學校的負責人，他並沒有這個意思。就是說這個法條規定，其實你看的時候你不太清楚他想要找誰。因為這個地方要看法條的立法背景，有一個立法過程，才會產生這個「責應扣繳單位主管」，因為在88年之前，他叫做「會計單位主管」。

89條的第一項第二款規定，88年以前他叫這些機關團體學校的「會計單位主管」。那88年的時候發生了一個個案事件以後，就改成叫「責應扣繳單位主管」。對於事業，還是負責人。扣繳義務人是這一些自然人，納稅義務人則是取得所得者。這個就是我們的PAYE，也就是就源扣繳程序裡面，我們現在法規範的狀態。


扣繳義務人，分成兩個，一個是機關、團體、學校之「責應扣繳單位主管」，那另外如果是事業的話，是負責人。因此在這個地方，事業付錢給境外的非境內居住者的這個外國營利事業，或是境外的自然人的話，你給錢的時候，就是由事業負責人來負責做就源扣繳程序。

好，這個就是我們現況的規定。

接下來我們再來跟各位去談這樣一個條文規定，我們現行的法制的狀態，我們大法官怎樣看待，以及對這樣一個法法治的狀態，我自己個人認為到底有沒有正當性的問題，這個就真的是在講合憲性與否的問題。

因為我們法條是長這個樣子，所以我們現在實務上有大量的行政訴訟的事件，是被認為是事業負責人，也就是我開一家公司，我付錢給國外的營利事業，比如說我付錢給臉書給微軟。我付錢給國外，誰是扣繳的義務人啊，是那個付錢的營利事業的負責人。不是營利事業本身哦，是負責人，因為根據第88條的第一項第二款的規定，你付錢給境外的營利事業啊，原則上就要做就源扣繳程序。扣繳義務人呢？根據89條的第一項第二款規定，扣繳義務人是事業負責人。那你要給股利給國外的股東，假設臺積電的投資有來自於美國的這個艾斯摩爾，假設這樣，美國艾斯摩爾投資了臺灣的臺積電。當他每一年發放股利盈餘的時候，一樣，也是要做就源扣繳程序，因為根據第88條的第一項第一款規定，這個股利盈餘只要給付給境外的營利事業，那么就必須要去做就源扣繳。那扣繳義務人是誰呢？是89條的第一項裡面所講的事業負責人，也就是現在臺積電的董事長劉德音，或者是以前的張忠謀先生，不是臺積電本身。

這就是我們現在的法律規定的狀態。那當然在臺灣基本上不太會有人去挑戰這樣一個法秩序，都認為這個法律就長這個樣子，是因為我們背後曾經有過大法官解釋，認為這個是一個合憲的一個制度。

我們先休息一下，待會再來跟各位去談這樣子的一個條文規定，到底合憲與否，大法官的看法又是如何。 

