# 20231111_02

---
課程：1121所得稅法一
日期：2023/11/11
周次：10_1
節次：2
---

## 【客觀淨值】

所得稅法第14條第一項，第一類所得，營利所得，分三種類型的所得。

一種叫公司合作社，或者是其他法人類型，像有限合夥組織。股利盈餘，是因為資本投入而產生出來的所得，或稱營利所得。

第二種，獨資跟合夥，也就是人合性組織，投入勞動力加上資本而產生出來的盈餘分配，那這個我們法條也叫做盈餘分配，但我比較認為這個是營業活動，所以我把他稱之為叫營業所得，是一個獨資合夥的營利事業的營業所得。

還有第三種，叫一時貿易盈餘，我們的所得稅法裡面又再把這種，偶一為之，或兼營這個事業的型態的貿易盈餘，放在這裡。

以上總共有三類，統稱叫做營利所得，分成了股利盈餘分配、營業所得，跟一時貿易盈餘，這三類。

那請各位注意，在這裡面一時貿易盈餘，跟股利盈餘分配，跟這個營業所得的分別。特別是營業所得跟一時貿易盈餘，基本上還是會有成本費用投入的概念。

股利盈餘分配的話，基本上是，你的投入資本是你的成本，因此產生出來的股利盈餘，原則上是收入減成本。但營業所得，跟一時貿易盈餘，都會有投入，有包括成本跟費用的問題，所以在這裡面，第一類所得，透過條文規範結構，不太看得出來有客觀凈額的原則，或客觀淨所得原則的概念，但仍然他應該還是會有。

因為營業所得跟一時貿易盈餘，至少投入的成本費用，都應該在法律裡面要反映出來，這樣一個客觀凈所得的概念。

我們到第二類執行業務所得，各位就可以看著這個條文，很明顯看得出來有成本跟費用的概念。第二類：「執行業務所得：凡執行業務者之業務或演技收入，減除業務所房租或折舊、業務上使用器材設備之折舊及修理費，或收取代價提供顧客使用之藥品、材料等之成本、業務上雇用人員之薪資、執行業務之旅費及其他直接必要費用後之餘額為所得額。」

各位，收入減除成本費用，畫起來。你因為你的職業活動獲得的正所得，這個叫收入，那你的投入，你會根據你的投入的內容去做切割，一個你的投入內容裡面就是提供給事務所所需要的經營的場所，這個房租跟折舊，然後器材設備，他的折舊跟修理費，還有你的藥品跟材料，這個叫成本。費用的部分就是你業務上雇用之人員的薪資、旅費及其他直接必要費用。各位把那個「直接必要費用」畫起來哦。

收入減成本減必要費用後的餘額，這個就是客觀凈所得、客觀淨值原則的適用。這個是第二類第一大段。


接下來第二段的規定，叫做協力義務，就是你至少要備製的帳簿是什麼。這個條文規定，執行業務者至少要設日記帳。你就回去看前面的第一項，營利所得，營業所得營利事業，其實本來應該要備製的帳簿。

獨資跟合夥，是根據第21條的規定，要根據稅捐稽徵機關管理帳簿憑證辦法，設置21條所講的帳簿跟憑證。

營利事業如果你是獨資跟合夥，你是營業所得的營利事業，那原則上是適用21條的帳簿憑證管理辦法的，這些帳戶跟憑證。

相反的，執行業務者則是用第二類第二段，根據第一句的規定，就是至少要備製日記帳。執行業務者不需要備製多麼繁雜的記事本，但至少最低限度就是要日記帳。

所以我們現在從這個條款規定哦，如果你能夠按照營利事業獨資跟合夥適用的這個商業會計法，如果你用商業會計法去記帳，那麼你就應該有權利去要求要適用權責發生制。也就是說，你在第二類執行業務所得裡面，法律規定只是日記帳而已，但如果你今天自己去用比較嚴格的標準，用商業會計法的方式去記帳，那這個時候就可以有權利要求，我可以用權責發生制。

德國的所得稅法就是這樣規定。因為執行業務者跟營利事業差別，只是在業務執行內容的差異而已。他們都是獨立勞務的類型。只是記帳方式的的差別。複式簿的這一種記帳方式，有資產負債表的，這個是商業會計法裡面所做的要求。那麼如果你是執行業務者，你是比較簡便的，就是你簡單就流水帳就好。那流水帳，你記出來的話，原則上用收付實現制。但如果你今天做了一個T字帳，你做了一個資產負債表的這樣一個列帳的方式的話，那麼在德國法律上是，執行業務者可以選擇改用權責發生制。

這就是我們的釋字722號，在講的是說，哎，你的營業事業的比較複雜，會計比較複雜，其實就是根據你的記帳方式，你呈現出來的是流水帳，我用收付實現制。但如果你用商業會計法，用資產負債表，用損益表這一種方式去做你的帳戶憑證的記帳。你用會計師記帳的話，那原則上你就適用商業會計法的方式記帳。這個時候你可以選擇改用權責發生制。權責發生制，可以讓你的收入跟成本費用的對應上比較平衡。因為收付實現，基本上是看現金收入，所以有時候多有時候少。少的時候只剩下盈餘虧損至零而已啊。所以這個時候對一個執行業務者，如果他的收入也是會有常常這種起起伏伏的話，那麼原則上用權責發生制，對他來講會是比較收支比較一個平衡的狀態，繳稅的狀態也會比較平衡。這個是德國的所得稅法規制結構上，容許納稅人可以做這種稅捐上的選擇權，但是你要以記帳作為前提。


權責發生制，不是你隨便能用就能用。你只要沒有好好記帳，其實沒有人有辦法知道你這個成本費用是對應哪一些的收入。你的成本費要去對應這一個收入的話，你就必須要有一個記帳作為一個依據。

因此第二類裡面的第二段，這個是協力上的義務。那第一段則是在講收入減成本費用的淨值，客觀淨值，客觀凈所得。

所得稅法第14條第一項，第三類薪資所得。原則上是薪資所得獲得的收入，減掉，兩種可能性，一個是列舉必要費用，這個就是14條第三類第一款，第一目第二目第三目。這個是列舉必要扣除額。這個列舉必要扣除額，跟所得稅法第17條的第一項第二款第三目之二的薪資所得特別扣除，這個地方，是要二擇一的。

原則上，你可以列舉的話，你就適用列舉，你不能列舉，就適用那個薪資特別扣除額，因為那是一個概括的成本費用的概算。因為他的法律性只是概括成本費用的概算，從而，你沒辦法列舉的，那概括成本費用概算，就是用薪資特別扣除額。

那我跟各位講，這立法者很賊，你看到他每一個額度都要求要有一個上限扣除額度，而且扣除比例很低喔。他的扣除比例，14條的這個各類就是全年減除，不能超過薪資總額3%，而且每一個項目你不能併計，就是各個項目加起來3%+3%+3%。所以答案是這樣，因為我們現在目前薪資特別扣除額，假設是用20萬來算，那你20萬這樣用3%來換算下去，幾乎你的薪資所得總額要超過222萬以上，而且你各個項目都剛好就是各個項目都剛好平均分配。

就是你的薪資所得總額222萬，然後你的進修執業工作上的支出跟職業服裝的費用，這3個平均分配，這個時候你才有可能用列舉必要費用方式扣除，而達到跟特別扣除額相同的效果。或者你有列舉扣除其中一項，你要薪資所得總額666萬，扣除足額3%，才可以扣到20萬。這個幾乎是高級名模才用得到。講白一點，就因為名模，才有可能可以扣到那麽多的職業服裝費。職業專用哦，這個關鍵在那個專用哦，只要職業不是職業專用的，就是一般場合也可以用，那這樣就不算了。所以那個職業服裝就是要讓人家很印象深刻，就看得出來你只有在那個場合能穿得。比如說，比如說玉山銀行不是有那個綠色的制服。我想，平常人不會穿綠色啦，除非你是藝人。那個就真的是職業專用服裝。如果各位將來執行律師業務啊，那你穿的那個法袍也算職業專用服裝，請問那個會到20萬嗎？應該不會啦。

自己不是財政部的人員喔，其實我自己推測，實務上能真的用到進修訓練3%加職業工具3%，然後再加職業專用服裝3%，能夠平均分配到這麼高的這個不太容易。

我就跟各位講，有一個費用，沒有算在這裡面，交通。不是所有人剛好住在公司旁邊，交通費用基本上不給扣，所以你住遠是你家的事情，你最好是住在學校公司上班附近啊，不要通勤費用太高的。所以你在臺北市上班啊，你去住桃園，那是你家的事情。你每天這樣來回，看看有沒有超過20萬？那個是你家的事情。


所以我自己個人推測，大部分的人應該還是用薪資特別扣除額。這個條款規定是釋字745號，由這個名模林若亞那個案件，還有另外一位就是我們的陳清秀老師，好不容易爭取過來的，說，欸，違反客觀凈所得原則，所以我們立法者應該修正。立法者就修了一個讓你實際上用不到的條款，所以還是回到薪資特別扣除額。我們的條文規定是長這個樣子。


是14條第三類薪資所得，第四款規定。薪資收入包括一時性跟跟繼續性的。一時性的包括了那種津貼紅利獎金各種補助，這個都還是算喔，但是必須都是雇主給的，所以你利用職務受賄之行為而取得的，原則上不是薪資所得，是其他所得。

如果是退休後給付的，不是來自於雇主的話，就是退休所得，是第九類，不是第三類。

領錢的人如果變了，比如說遺孀遺屬，領取這個被繼承人生前的那個部分的所得，這個也是屬於退休金的所得，而不是薪資所得的範圍。


第五款規定，請各位注意，我們只有在勞保條例許可的範圍內，這個部分才給予免除薪資收入課稅。這個地方要請各位特別注意。其實退休金給付並沒有全額免稅，是要看是不是在勞保給付的收入範圍內。這個地方只要在每月工資6%的範圍內的話，則不計入薪資收入，給予免稅的稅捐上的優惠的規定。

第四類是利息所得。來自於金錢或者金錢的衍生性的債券，不管是國家發行公債或公司發行的公司債，或是金融機構發行的金融債券，或短票。短票是約當現金，就幾乎接近現金，所以跟現金跟存款一樣，這個都是利息的所得。利息的所得原則上在我們14-1條的規定底下，是做分離課稅。

所以我剛剛有特別跟各位講14-1條的規定，要放到第14條的第四類這邊來一併考察。這邊條文的規定，基本上都是在14-1裡面做了一個特殊的規定.

原則上，利息所得10%，分離課稅，所以各位有錢應該要賺利息所得，因為只有10%，比股利所得更低啊。當然他的缺點會是在利息所得，基本上報酬不高而已，大概是這個差別，但他的稅率基本上相對是一個比較低的稅率。所以雖然利息所得是綜合所得的範圍，但現實上來講，是分離課稅，而且是比較低比例的課稅。


所得稅法第14條第一項，第五類，租賃所得。我們先講第一款。這個地方很明顯看出來，收入減成本減費用的客觀凈額。財產租賃所得跟權利金所得以全年租賃收入或權利金收入減除必要損耗及費用。必要損耗就是你的那個租賃物的損耗折舊，這個之後減掉費用後的餘額，這個是所得額。

那接下來的第二款到第五款，是關於收入計算方式的一個防杜規避的條款。


那我們來看一下。第一個是永佃跟地上權。只要你是設定地上定期的永佃跟地上權的話，被認為都是所得的範圍。你取得類似押金的話，也是要按一年期定存利率計算租賃收入。

然後如果是租金比較低的話，這個叫一般租金標準。所以借朋友住的話，也有可能就會按一般租金標準來設算你的租賃收入喔。

這個還真的會發生實務上的爭議。就是你借朋友住，你不收錢，國稅局還是會設定，你會有一般租金所得。

當然，法律條文這樣規定，你可以去打釋憲，不過目前為止好像也沒有因此犯案的這個問題。這個條款目前還在，以一般租金所得的標準設定你對他有一個相當於是租金的收入。當然，法律上面來講，不一定是用這個方式去做規定，立法者做了價值決定，是設定認為你有一個一般租金的收入，其實你也可以當作贈與，不過贈與不一定會在免稅的範圍內。

這個是，我們現在目前的法律上的條款。


第六類，叫農林漁牧礦冶，這一種農林業所得，那原則上有收入減成本費用，但這個地方僅限於是大自然界的第一次產出的農漁牧林礦冶，這是大自然界的第一次產出，有收入減成本費用。

第七類的財產交易所得，請各位要搭配第9條的規定，關於這個財產交易所得，跟財產交易損失的概念。以及第17條的第一項第二款第三目之一，財產交易損失特別扣除額。財產交易所得僅限於扣除財產交易產生出來的虧損，跨年度，三年內的盈虧互抵。

所以第14條的第七類，一樣有收入減成本減費用。你因為出價取得以交易時的成交價額減除原始取得成本，然後減除必要費用後之餘額為所得額。

在這個裡面，客觀淨所得裡面，沒有特別去談到所謂的這個虧損的部分，則要搭配17條的規定，這樣你才會比較清楚地去適用。


第八類，競技競賽，這個條款規定的話，因為第三款規定，政府舉辦之獎金的話，原則上就不併計綜合所得總額範圍內，像財政部的統一發票的兌獎，基本上就是直接依照所得稅法第88條的規定，扣繳稅率原則上是20%，所以是用按你取得的部分直接扣20%。所以你雖然開到1000萬的獎金，你不用開心拿到1000萬，其實只有800萬而已啊，因為財政部就把20萬扣掉了，不併計所得總額。


第九類，退職所得。退職所得也是一樣喔，退職所得一定是法律明文規定的退休金給付範圍。不是法律明文規定的，就不在退休金範圍。像實務上最常看見的就是你可能跟雇主之間有紛爭。勞工跟雇主之間有紛爭，那雇主可能一次給付給你的，好了好了，趕快離開，趕快離開啦。就是給他一個和解金，或者是一個損害賠償。這一個可不可以當作是退休金給付退職所得，被認為是這個計算上面有一個比較優惠的方式？答案是，只在法律許可的退休金給付範圍內，也就是個人依照保險給付，像勞保，或者是這個軍公教人員的這種年金保險給付範圍內，只在法律所規定的年金保險給付範圍內提繳的部分，按照年資，抵繳的年資，按薪資收入狀況計算的。

所以，如果你拿的是從雇主那個地方拿到一筆的退休金，我在實務上看過非常多的類型，像從外商公司退休下來，有時候外商公司為了要給你一個不競業的獎金，意思就是，不要你又出去給我投到那個對手競爭公司，或自己去創業啊。那很多人就會主張什麼？主張說，欸我這個退休了，因為我是離開的時候一次拿的。對不起哦，你退休一次拿的是所得沒有錯，但不算退職所得，因為不是算在勞保條例裡面算的這個範圍，那個範圍的金額不會很高。那其他的不是退休所得，就變成是其他所得。


所以我們的其他所得，第十類是包山包海的，只要前面沒有了，全部都流入其他所得。只要沒辦法歸類的，全部都歸到其他所得，但這裡面其實理論上來講，應該是前面可以盡量歸類的，就要歸到他所屬的類別裡面去，比如說非法打工也算是打工，這個也是薪資所得的範圍啊。



第14條的第二項規定，這個是實現原則的規定，也是那個我們實務上面，按照那個計價課稅原則裡面的政府表訂價格的計價方式，也就是實價課稅原則。實現跟實價都是在第14條第二項規定裡面去做表現。


14條第三項的規定是得其多年所得一次大量實現的變動所得，只限於法律所規定的四種類型，其他的就不承認是變動所得。因為被認為是半數所得課稅半數也說是一種稅就優惠。作為一種稅捐優惠要例外從嚴解釋。那這裡面其實我個人也會認為累積多年所得一次大量實現，其實並不全然是一種稅捐優惠，是因為累積多年所得一次大量實現，在累進稅率底下會有稅負急劇（集聚）的效應，產生稅負增加的效果，從而理論上，變動所得這一種方式課稅並不全然是稅就優惠，而是為了避免急劇（集聚）的效應產生出來的這種稅負上可能不利的待遇。我個人比較不傾向，認為這全然是一種稅捐優惠。

當然啦，這種變動所得的這一種切割方法，是一個蠻粗暴地簡單的方式的切割方法，那確實可能在這個情況底下，帶有稅捐優惠的性質，我不排除這個可能性。


接下來我們14-4到14-8，我們就留待到所得稅法四，再來跟各位談。

15條是配偶跟納稅人的合併申報，以及納稅人跟受扶養親屬的合併申報。我們到考完試之後，我們再來跟各位講家戶所得課稅制.


15條跟16條的規定基本上是對應的，因為你既然家戶合在一起，夫妻各自經營營利事業，有營利所得，當然要併計啊。這句話不是廢話嗎？你不能夠前面那個地方有所得要併計，但是虧損就不能夠比併計減除。所以你看第16條的規定就是夫妻兩個人各自經營營利事業，那你只要併計的話，核定了盈餘虧損就可以併計。

第16條的規定，當然你可以理解為是跨主體的盈虧互抵，可是是因為我們是採家戶核定課稅制，也就是納稅人跟配偶可以合併申報，這是同一個主體的關係。


## 【主觀淨值】

我們接下來進入主觀淨值。



### 【免稅額】

主觀淨值的免稅額規定，他是一個物理生存需求的體現，他的概念是反映出當代維繫個人物理生存最低需求的額度，也就是至少吃飽穿暖所需要的額度。所以立法者有誡命，而不是立法形成空間，立法者有誡命應該要反映當代社會維繫物理生存需求的最低額度。這個額度不應該低於維繫同樣是物理生存需求的，在社會救助法裡面提供給的最低生活費。


簡單來講，有賺錢繳稅的生活水準，維繫生存需求不應該低於社會法上的標準。當然不是說沒賺錢繳稅的就怎麼樣，而是你在維繫物理生存需求這件事情上面稅法跟社會法不能背離。至少，最低限度，他們的生活水平，應該是一樣的喔。當然，如果真要不一樣，也不應該是稅法低於社會法。就是社會法裡面的最低生活費，跟納保法裡面的基本生活費，我們的概念，用不同的名詞，意義在於稅法裡面的基本生活費用不應該低於最低生活費用，不應該低於社會救助法裡面的最低生活費用，因為他反映出來的就是在當代裡面，維繫生存的最低需求。

當然，社會法也不應該低到讓人民無法生存的地步，因此誰的額度低，不足以反映出來當代的維繫生存需求，那是個別法律領域要去做調整，來反映出當代維繫生存需求的這個額度啊，這個是立法者的誡命，不在立法者的形成空間範圍內。簡單來講，立法者的形成空間受到這個誡命的限縮，立法者應該要反映出當代維繫生存的需求。


接下來的17條的第一項，各款規定，除了納稅人本人以外，也包括了配偶跟受扶養親屬。這個時候就帶進來婚姻跟家庭的制度保障。為什麼我可以減除配偶、受扶養親屬的免稅額？因為我養他。因為我們是婚姻成員，因為我們是家庭的成員，所以除了維繫個人本身的生存權以外，我養婚姻配偶，養受扶養基礎，這同時也在保障社會裡面的婚姻跟家庭制度。所以這裡面不是生存權保障而已，也包括婚姻跟家庭受憲法保障的這個概念。當然同性婚要一併進來，因為在這裡面，同性婚在法律上的待遇要等同於是異性婚姻所產生出來的待遇。簡單來講就是17條的第一項第一款體現生存權保障，在此同時也是一個婚姻跟家庭受稅法保障、憲法保障的一個體現。


好接下來跟各位簡單來講，未成年。未成年的子女受納稅人扶養沒有問題，但是成年子女跟納稅義務人的直系血親尊親屬，其實在法律上面來講，他們未必實際受納稅人扶養。納稅義務人對於直系血親尊親屬，可能有法律上扶養義務，但是他未必真的有在履行扶養義務。所以其實法律上的這個條文規定，就容許變成是納稅人可以選擇，我可以去做，把我的納稅義務人的受扶養親屬計入。其實他沒有真正受扶養，只是在法律上有扶養義務，納稅義務人把他合併申報，所以這個稅制，如果你把他合併申報，要損益同歸，也就是萬一納稅義務人的受扶養親屬，假設有隱匿所得的話，因為他隱匿所得，這時候要加計進來，將來就會提高你的所得稅的稅負。這樣各位清楚嗎？

在這裡跟強制合併申報的這一群親屬團體是不太一樣的喔。強制合併的這一些配偶跟受扶養親屬，特別是納稅人的未成年子女，因為他沒有選擇可能。從而他這裡面的損益同歸這一件事情，我們下一次上完課之後，我們再來跟各位去談。這裡面還有另外一群人是成年的親屬，其實他未必受扶養，雖然有法律上的扶養義務，但未必受扶養。也因此在這個部分，理論上來講，你如果把他申報進來，你行使的一個合併申報的選擇權，那這個時候損益要同歸，意思就是他的所得要算進來，他的虧損理論上當然也算進來。但如果他有漏報所得，這個時候補稅也會補到你納稅義務人身上。

這個地方是17條的第一項，第一款的免稅額規定，反映出維繫物理生存需求。

剛剛我有提到老年人增加50%，老年人其實這個增加50%，跟幼兒的學前扣除額每人扣除12萬，以及長照跟身心障礙者，老師個人認為他是因為身心跟年齡而產生了特別的需求。當然，老年人的需求跟幼兒的需求不太完全一致啦。老年人主要其實是更增加醫藥以外的其他的生活上的費用的支出。其實他吃的穿的反而比較少，吃穿不一定比較多啦，但一般而言，可能增加其他的營養補給品，或者房子要加裝無障礙設施啦，這些相關的費用。那就跟幼兒的情形大致上類似，是因為年齡，因為照顧幼兒，往往也是增加許多的生活費用上的支出。

所以在這個地方，就是老年人的免稅有50%，跟嬰幼兒的幼兒學前扣除額，以及身心障礙特別扣除額，以及長期照顧，老師個人認為他應該要在平等原則下做統一的平等原則的規範。原則上是放在一起去做統一的規定會比較適當。這個是建議而已喔。當然，因為目前法律是做分別不同的考量啊。


接下來我們談到關於未成年子女就學的這個部分。未成年子女，因為一般來講就是受納稅人扶養，可是如果是屬於已經成年的而有身心障礙或無謀生能力的話，那這個部分原則上必須要由納稅人提供證據資料來讓主管機關依職權調查。主管機關當然可以依職權調查，可是因為這些相關的事由，必須要由納稅人在一定程度上，對於無謀生能力這一件事情提供資料。特別是在這裡面無謀生能力的判斷的話，要有機關根據納稅人提供的證據資料來去做調查，才有辦法去做一個比較完整的判斷。


接下來我們來看那個標扣跟特別扣除，因為是二擇一。

看一下，列舉扣除額，基本上他的主體適用範圍就是那時候有配偶跟受扶養親屬，你回過頭來去看標扣。標扣，只有納稅人跟配偶，少了一個納稅人的受扶養親屬，所以適用標扣一定不利。因為法制上只允許單身跟有配偶如果你是合併申報，你有受扶養親屬適用標扣一定不利。標扣，我就不信有多少人會用。如果你是一個家裡成員，大部分的情況都是因為適用列舉扣除額。

列舉扣除額，是納稅人配偶跟受扶養親屬，三個主體都可以適用，所以實務上應該標扣可以適用的情形不多，會喪失了規範的意義，就是本來標扣是為了要避免列舉的複雜跟困難，所以就用一個概括扣除額，但實務上基本上沒有用，因為只有單身跟有配偶的才可以用。如果你有受扶養親屬的話，基本上沒有受扶養親屬的標準扣除額，所以這個額度在實務上適用的可能性比較少。

### 【列舉扣除額】

捐贈。捐贈就要請各位注意，因為這是一個稅捐優惠，所以捐贈扣除額的規定，我們後來做了一個限制17-4的規定，非現金捐贈。這個條款規定，本來就稅收優惠嘛，結果實務上就一堆賣不出去的東西就來捐贈，賣不出去的電腦就捐贈給學校，賣不出去的圖書，就捐贈給受贈的單位，反正那些受贈單位很happy啊，為什麼因為他不用花錢就可以拿到一個財產。特別是在實務上，有一段時期就是偏鄉的那些地方自治團體，你捐土地給他，他好開心啊。為什麼？某一個澎湖縣的地方團體，擁有全臺北市最多的公共設施保留地。因為大家做節稅規劃的，大家都想到這個事情。而其實，你去看了這臺面上有一些人啊，那個做節稅規劃的時候，就是在做這種事情啊。他把臺北市公共設施保留地哦，就捐給澎湖某一個鄉公所，因為他們效率很高，一天就可以開給你捐贈證明哦。所以到年底的時候要報稅之前的時候趕快捐，當天他就開給你。

開給你什麼？公共設施保留地的價格是這樣，公告現值是100塊，市價可能是只有10塊到30塊。假設是10塊，我是一個地政士，我就去買下來哦，市價10塊我去跟那個地主用20塊錢買下來，然後你要做節稅規劃的，我賣給你30塊。所以你是30塊取得對不對？然後你再把這一塊地捐給澎湖的那個地方自治團體。

以前新北市也有一個地方很有名，專門接受這個捐贈，就是一天內，行政效率都超高，就當天就開出來捐贈證明。因為他只要查那個價格就可以，公告現值。所以我用30塊買一塊公共設施保留地，我就拿到一個上面寫著100塊錢土地的價格，然後我就在報稅的時候，因為我通常都是我的所得稅額到邊際稅率的40%，所以我上面就寫著，我捐了一個100塊的土地給那個澎湖或是新北市那個鄉公所，所以我拿到多少錢的可扣抵稅額？40塊。

這樣各位知道這一個過程當中，大家都很happy。因為那個公共設施保留地，地主一般來講是政經弱勢者，他們家之所以被劃到公共設施保留地，就因為你是政經弱勢。因為人家政經强勢，剛好都是劃在緊鄰公設保留地的建地。這就是地方的邏輯。地方邏輯就這樣，你們家比較弱，你們就是公共設施保留地，就是公園預定地。剛好我們家跟你緊鄰，我就是建地。就是道路劃過去，劃到你們家，沒劃到我們家。是這樣啊，劃完以後，這塊地還是公告現值100塊，但是市價立刻跌落變成10塊。那就會有土地掮客就出來，就這樣，你那塊地哦，沒用了，真的是沒用，因為你又不能做什麼啊。那現在有人願意出20塊，我跟你講，那個農民很開心。10塊錢的市價的有人出20塊，真是開心死了，所以你很快開心地賣給他，20塊錢。

那這個20塊錢的地，你要做節稅規劃，你來找我，30塊賣給你。我就賺10塊。這個比土地仲介還好賺欸，土地仲介只能賺總價的6%，100塊錢的土地賣出去，我才只能賺6塊。我這樣一來一回之間我就可以賺10塊，而且因為他持有成本只有20塊錢，他可以去貸款嘛，這基本上都比較低的貸款，然後我就可以拿20塊換到30塊。

需要節稅規劃的那個人，他拿來這塊地，他30塊買的，他就捐給地方自治團體，拿到40塊錢的抵稅權，所以他也拿回了10塊錢，大家都happy，只有一個不happy，國家。


其實還有一個團體啊，為什麼？因為那個地方通常是他們那一個上級的地方自治團體都沒拿到錢，都是下級的地方自治團體拿到錢，所以他心裡也很恨，你們怎麼可以有這麼多錢？下級地方自治團體：啊，我們效率高啊，大家都喜歡我們啊，都捐贈給我們。

國稅局後來就去查，哎，你們所有買這些，捐這些地的，來，拿出當初購買的證明。你不拿出來，你怎麼會拿出來，你拿出來就只有拿到12塊錢的抵稅權。你捐給地方自治團體要你去買的，對不對？你買一塊地看起來是100塊，但是最後捐給地方資產，你其實也只是捐那30塊而已啊，如果真要算，你抵稅權只能30×40%，只有拿到12塊錢，那這樣你一定不會拿出來。

所以最後面，這個國稅局就是說，你不拿出來，我就用16%給你算，就是當初你這一塊地看起來是價值100塊，我就用16塊給你算，所以立刻所有人全部都，哇天啊，如果是這樣，那我不就虧了嗎？我拿30塊，我本來至少可以拿12塊錢的抵稅權，因為用40%去算啊，如果給我用16塊，我再拿一個40%，我就只有5、6塊錢的抵稅權了。所以那時候就發生很多爭議，然後就一律都去做訴訟，一律全部都輸，結果到最後面，去打一個釋憲，釋字705號，說這個違反依法課稅原則，所以不準，不準國稅局用16%。所以後來實務上就說，不準的話，那我們就訂一個17-4。就這樣。這個條文就這樣來的啦。

非現金捐贈，一律就是拿出你當初的成本。所以訴訟打了一圈以後，沒用。實務上就是這樣，現金貨真價實，大家沒有什麼好說，但是實物捐贈，原則上用成本算。你拿不出成本的話，未提出非現金的成本的話，我就用市價行情給你估算。這就是17-4條的規定。


講回過頭來，為什麼捐贈可以用這個區別現金跟非現金捐贈？很簡單，因為他就是鼓勵慈善，立法者，享有比較高度的立法形成空間。我也贊成，如果不是現金的話，嚴格去區別，這個是必要的，因為說實在話，那個東西可能是沒有流動性的的東西，像被亂葬的、亂丟垃圾的土地，捐給你市政府，我看你收不收。那個收到的市政府跟那個縣市團體大概都投大，一個頭兩個大。為什麼？要清理，光被自己的環保局一直開罰單就夠了。為什麼？因為都沒清理，亂葬崗、亂倒垃圾土地，那個高度被嚴重了。

臺南的路，我們那一帶，整個都被當時的台鹼，整個都被污染，地下水汞污染，光排除那個要幾百億的錢。臺南市這種當然說沒錢，我怎麼會有錢？ 

你看這個條款看不出來端倪，實際上就是這樣。

回來，保險費。保險費對應醫藥及生育費，這個都是屬於維繫物理生存需求、社會生存需求的最低費用。

購物借款跟房屋租金支出，這個也是一樣。

災害損失，拉到特別扣除額。災害損失應該包括他的個人受不可抗力的災害損失。如果是人為的災害損失，比如說被切到被強盜，這個就不算。

其實我是覺得這個不太有道理啦，不一定要天災地變。這個當然了，因為如果是被竊盜或者是被強盜，這個也可能要有一定的證據方法，不能說我被強盜，所以我就沒錢。有沒有報案？沒報案。損失了多少？黃金幾百兩啊。你黃金以前購買的單據沒有保留？你隨便說一個就黃金幾百兩不見了。怎麼有辦法這樣子去做一個災害損失的認定呢？這個是一個困難點。

購屋借款跟房屋租金支出，這兩個要對應啊。因為有錢買房子的30萬利息支出，沒錢買房子只能租的，只有12萬，一個月就是1萬塊錢。這個1萬塊錢的房子租金在臺北市大概租不了什麼房子，雅房應該可以，沒有廁所的雅房哦，搞不好是地下室或是頂樓陽臺，大概是可以啊。這個其實在臺北市根本就對那個這個租屋的人不太夠。


### 【特別扣除額】

特別扣除額就是交易損失跟薪資所得特別扣，都要放到第14條去。

儲蓄投資特別扣除，要放在特別扣除的項目裡面。

身心障礙跟教育學費。身心障礙，這個是身心狀態。教育學費是特殊的鼓勵的教育的費用。

最後一個就是，幼兒學前跟長期照顧。在我們的17條的第三項規定有排富條款，這個是不對的條款。

照顧幼兒是理所當然會增加支出的費用，不管是有錢人沒錢人，照顧幼兒就是要這麼多錢啊。有錢人照顧幼兒也是要錢啊，難道他就不用錢？你可以說那個錢，他不那麼care沒關係。可是這個是反映出幼兒維繫生存需求的額度的範圍。那長期照護也是一樣，有錢人照顧自己要長期照顧的受扶養親屬，也是必然會產生這一些費用。我個人認為這個排富條款根本就混淆了稅法跟社會法的界限。正確的排富是放在社會法，是放在稅捐優惠。排富不應該放在反應量能課稅原則的客觀跟主觀淨值裡面。如果你放在這裡面，那就是混淆了，量能跟稅捐優惠的差異。

## 【稅捐構成要件小結】

除了合併申報制度，跟後面的重購退稅的規定以外，我們就將課稅構成要件的規定介紹到這。

稅率，就是看第5條第二項的規定。

這也是我們大致上在期中考之前的内容，希望各位，對依法課稅原則的構成要件的部分，要重新組合。

我們的考試原則上會在構成要件裡面去做題目的設定。可能主體，可能是客體、稅基。就這樣，大概就這幾個部分，課稅的基本原則，因為稅法、所得稅法要適用的這些基本原則還是不變的。這個地方給各位做參考，預祝各位考試順利。

今天到這裡。