# 20231111_01

---
課程：1121所得稅法一
日期：2023/11/11
周次：10_1
節次：1
---

下個禮拜一，後天的考試，各位同學都很關注。老師在題目裡面是分兩個大題，下面再拆一些小題。比照國考，大家帶紙本的法條。如果各位像我一樣，我也會習慣在上面做一些劃線註記，這種都沒有關係，包括你這上面有大法官解釋，我都沒意見，因為現在社會本來這些資料就常常都是會連在一起。像我們在德國考試，稅法是兩大法典，就是紅紅的很大，就這樣，大家都帶著。法律系學生很好辨識啊，跟會計系學生都一樣，很好辨識。會計師就拿個一個計算機，法律系就拿個六法。我們就是拿這些，小六法或者是大六法都可以，隨便你，帶你自己的法典。

我至少會希望各位同學對法典稍微要熟一下，其實這個也是有助於各位如果要參加國考。其實國考不難，都是法典的運用而已，我就不太知道為什麼大家這麼畏懼財稅法。財稅法每一年考試都人數最少的。不知道什麽原因。那其實都是法條的這個運用而已。所以，我這兩個題目基本上也都是法條運用而已。就請各位就帶著法典。

當然在學習上面，我會希望各位有一個總體的概念，這也是老師在教學上面一直在強調的重點。我們其實不是注意到樹木而已，我們要有一個「林」的概念。那「林」的概念就是這樣，因為我們稅法本身，我記得我在第一節課跟各位講過，有那個內在、外在體系。就是說，稅法，其實他本來應該是依構成要件逐次展開來做相關規範，可是因為我們的稅捐法律條文的規定，他並沒有很好的外在體系做法，不像民法。民法，因為是歐陸法系最早發展的，所以體系化做最好。而且因為我們抄別人的，抄得還不錯，體系化就做得很好。凡是我們自己立法的，我們體系化都做得很爛。你不能怪他們，因為在他那個背景裡面，真的沒有這個體系。那沒關係，我們自己要來做自己的體系。

所得稅法其實就是構成要件一步一步，稅捐主體、客體、稅基、稅率，就這樣把法條的規定一個一個排列。就好像我們稅捐主體的構成要件，就是境內居住者跟非境內居住者，包括稱之為叫稅籍居民跟非稅籍居民。

稅籍、國籍、戶籍這本來就不一樣的概念，我第一次上課就跟各位講過了啦，有時候會找國籍、戶籍來做聯繫因素，但不是必然的，因為稅法本身就有自己的規定嘛。我們的兩岸人民關係條例確實是稅籍連戶籍，但戶籍不等於國籍。那國籍可不可以當作稅籍的聯繫因素要件？可以啊，我們的遺產贈與稅法就有把國籍聯繫進來，但是我們所得稅法是沒有連結國籍這個要件。

所以，不同的法律有自己的稅捐主體，這個叫權利能力的概念，就像民法有權利能力，民訴有當事人能力是一樣，這個本來就依照各法律去規定他自己的權利義務的歸屬主體。所以這個地方，稅捐主體、稅籍居民跟非稅籍居民，聯繫的構成要件，法條裡面就有規定。境內居住者的構成要件在所得稅法第7條第二項，那第7條第三項就是非稅籍居民的構成要件。

好，客體，我在這個地方花很長一段時間跟各位去講課題，包括了所得的概念所得跟非所得，然後第二個層次叫應稅所得、免稅所得，然後接下來是類型。所得本來是綜合所得，但我們就有分類所得的概念，這個不僅是因為我們的立法本身，一開始是從分類所得逐次慢慢演變，變成現在的綜合所得稅，另外一方面是我們分類所得的概念，有分類的實義，在徵收跟稅額的計算裡面，真的會有區別。那麼這個分類所得的概念之後，我們談到所得實現的時間跟地點，然後，實現的時間跟地點裡面有會有一個客體跟主體之間的這個叫歸屬的判斷，原則上所得的取得所得者，這個就歸屬給他，但那個在稅總裡面，特別在講那個經濟實質叫實質課稅原則，就是在那個歸屬主體的判斷上面，可能會有產生類型的變化，還有那個歸屬主體的變化。就是我透過一個人去取得的話，到底是他的所得還是我的所得？這個叫歸屬的判斷。在我們所得稅裡面，其實這個歸屬判斷，客體跟主體之間的聯繫關係也是非常重要的，這也是我們在稅捐實務上最常見的爭訟實務的類型。像借名行為就是最典型的。借名行為算誰的錢？出名人的還是借名的人。這個是實務上很大的爭議點所在啊。我如果狠一點，我就多考一點借名，我這次不會考，但實務上這類非常多。規避，也是屬於這裡面再考那個主體客體歸屬上面。


## 【稅基】

客體之後進入稅基，上禮拜一的時候，我們開始講稅基了，但其實稅基在某程度上還是會跟客體有連結。


在還沒有進入稅基之前，客體算出來，這個在我們的法典上面稱之為叫應稅所得總額，這個名詞出現在第14條，第一項本文規定應稅所得總額是以客體的十類所得的總額計算。

在這裡面，稅基的計算，我們的法律的規定是在第17條裡面，有幾個專有名詞是17條第一項第一款的免稅額，以及所謂的標標準的扣除額跟列舉扣除額，第2層次的17條第一項第一款跟第二款的規定，以及最後面這個叫特別扣除額。稅基的計算是經過這3道，17條的第一項第一款，17條的第一項第二款第一目標準扣除額，第二款第二目的列舉扣除額，17條第一項第二款第三目特別扣除額，這3道過濾以後，才會算出一個應稅的所得淨額。14條的應稅所得總額，經過免稅額扣除額以後，這個叫應稅所得淨額。

法條是這樣規定，但我們在釋義學的理解是這樣，就是說，我們在法律規定的層次裡面前面的第14、15、16，都是客觀凈所得、客觀淨值原則的計算，第17條則是主觀淨值主觀淨所得的計算。然後17條之後，先不用管他，比如說17條之二，那個是退給稅款，例如重購退稅的規定，這個條款規定本身是稅捐優惠，是構成要件的附加，所以在舉證責任分配上面是由主張退給稅款的納稅義務人來負責舉證責任，證明該項課稅構成要件。

在這個過程當中，法條規範結構是長這個樣子，看起來很完美，但是你看哦，我們現在的立法者，林林總總加了14-1，後來有14-2、14-3，然後後面還有14-4到14-8。你看我們的法條規範結構，這真的是修法，都不覺得他很醜。亂插進來這些法條，整體的規範結構就變調了。

本來是前面14、15、16是客觀凈所得，17條是主觀凈所得，但現在我們開始插進來一些法條。

我們現在來看一下14-1條的規定，14-1在講什麼？講公司在債券利息所得的扣繳。14-1這個條文規定，法律體系的位置，其實應該放在14條的第四類。因為那個地方，他本來就是利息所得放的位置。

「個人持有公債、公司債及金融債券之利息所得，應依第八十八條規定扣繳稅款，不併計綜合所得總額。」

14-1條，首先就破壞綜合所得課稅原則，自己做分離課稅，但法條位置也不是放在14-1，是應該放在第14條的第四類，利息所得那個地方。也就是你應該要放的話，也是放在第四類第四款去增訂一個條文規定。立法上的體系位置，要對應在對的位置，那個法條規範結構才不會被扭曲掉。然後14-2因為被刪掉了，我們就暫時不講。

14-3，你看一下法條規定，誰要適用？同學有上老師的稅捐規避課程的話，都知道這個條文本來是對應66-8，就是個人未分配盈餘的課稅，防堵利用公司來規避股利盈餘分配的規定。所以我們在66-8，隨著兩稅合一制度廢止之後，我們再增訂了14-3，目前這個條款只有14-3的第二項看得出來他是所謂的隱藏性盈餘分配的概念。14-3的第一項，你看他是個人營利事業都適用，不只適用在綜所稅也適用在營所稅。第14-3，因為這個立法條文，他本身他的位置是在綜所稅。如果你是適用綜所和營所，那你應該放到總則。可是因為他這種抽象性立法的方式，導致了他其實是稅捐規避條款，依照我們的立法體系，14-3，應該跟納保法稅稽法放在同一個位置去分辨。我們14-3的規定，是防杜個人或營利事業利用中間公司（德文是Zwischengesellschaft），來做股利盈餘分配。這個中間公司如果在境外，叫做受控制外國公司，如果在境內，叫做阻擋股利盈餘分配的公司。這個就是14-3，本來要適用的對象。14-3本身的規定本來就是對中間公司做規定。如果是個人利用中間公司，這個中間公司在境外，那個叫做個人境外受控制公司，那個是所得基本稅額條例12-1條要規範的對象。所以14-3跟所得基本稅額條例12-1是重複規定。實務上沒有人在用14-3，也是因為那個是境外公司，那就直接用個人所得基本稅額條例的規定。然後。

14-3的這個法條，因為他的適用主體包括了個人跟營利事業，所以體系上的地位來看，是一個很怪異的存在，他不應該放在所得稅法。就算放在所得，稅法應該放在通則性的規定裡面。14-3應該是放在稅捐稽徵法。稅稽法被修掉12-1條以後，他就應該放在納保法裡面做規定。

接下來是14-4到14-8，這一大段，這個叫房地合一稅。房地合一稅怎么去算稅基。房地合一稅，我們的法條規定是一個獨立稅目，但沒有稅目名稱。我們的稅法體系真的是體系亂到不可以，因為你條文明明就說所得稅是課綜所跟營所，沒有房地合一稅這個稅目，結果你法條規範結構其實還是有。亂到不行，如果真的要制定這個房地合一稅，可以啊，你應該是在第二章綜所、第三章營所，那之後就第三章之一，房地合一稅嘛，可以吧？因為你是對個人跟營利事業課徵，另外單獨拉出來去課一個稅，那這個時候他的法條規範結構才完整。

我們現在，我真的，說實在，真的是……我雖然在財政部訴願會，有時候對個別訴願，可以發揮一點點的影響，但是他整個的立法政策，說實在，有時候實在是使不上力。立法，不太會問法律學者的意見，當然問法律學者通常都反對哦。我不是反對，我有跟你講要怎麼做啊，像這種東西本來就是不應該這樣子去弄，而他還是這樣子去弄。那個條文哦，聽說他就是去直接去抄那個某一個外國的一個制定法，然後就這樣啊。人家制定法長這個樣子，他說，他們法律就這樣規定。那規定真的很粗糙哦。這是體系這個部分，14-4到14-8其實應該是另外拉出去，在所得稅裡面用一個專章規定。簡單來講，他是稅基的分離，個別課稅，就簡單這樣子去做說明。


### 【盈虧互抵】


我們就來看14、15、16。第14條本來是各類所得的淨值計算，14條裡面本來應該也要有收入減成本，減費用，甚至必要的時候，虧損的減除，也是客觀淨所得、客觀淨值的範圍。虧損減除不是主觀凈所得喔，虧損減除是客觀淨值原則的一部分。營利事業或者是個人的執業活動，這個活動產生出來的收入，這個部分是正的收入，聯繫這個營業活動或職業活動，你的投入，分成成本跟費用。所以所謂的淨所得，是收入減成本費用。你這個營業活動可能成本費用大於收入，這個時候會產生虧損嘛，對不對？你有第一個營業活動，你有第二個營業活動，你第一個營業活動有收入大於成本費用，所以你有盈餘，但你第二個營業活動是收入低於成本費用，所以你有虧損。那你要不要讓人家盈虧互抵？應該不用我特別講什麼概念，這個本來就應該要讓人家盈虧互抵啊。除非你第一個是應稅，第二個是免稅。如果是免稅，就切開來。但如果都應稅，要不要讓人家盈虧互抵？要啊。你所得稅不能講一半，有所得，就應該課稅。對啦，我承認。有虧損呢？要給人家減除啊，對不對？正確計算淨所得的概念，不能只看正的，不看負的，這樣沒有道理啦。

所以客觀淨所得或客觀淨值原則，除了釋字745號所講的成本費用概念以外，其實虧損不是稅捐優惠。我再講一次哦，虧損減除不是稅捐優惠，他是客觀淨所得的部分，你不要一天到晚用立法理由立法理由。立法者偏心你不知道嗎？立法者心是偏的。因為我的心也是偏的。

他的立法理由說，欸，因為這個所謂的凈所得這件事情，我們是按年度稅。年度稅沒那麼高尚。年度稅是一種技術性原則，因為我們所得稅不可能到你人死了，再來算所得。營利事業不能到你解散的時候，我再來算營所，因為那個時候做收不到稅。對吧？所以年度稅是一種技術性原則，作為技術性原則，不能高過於目的性原則。像我們講量能課稅，量能課稅導出來的是終生所得概念，終生雖然不可行，這個理想太高遠。終生是不可行的，但容許一定年度的跨期間盈虧互抵總可以做吧？這樣這樣各位可以聽得懂這個概念嗎？我們現在實務上，包括最高行代表的實務，一直認為跨年度盈虧互抵，就是優惠。不是啦。跨年度是客觀淨所得客觀淨值原則裡面的一環。收入要減成本費用，這個是14條裡面該有的。因為收入減成本，可能收入大於成本費用，你會有盈餘，如果收入低於成本費用，你會有虧損，所以這裡面還有第二個內容，叫做盈虧互抵。

一個營利事業只要做兩個活動。比如說我舉例而言，我是臺大的教師，然後我同時間去買賣黃金。不可以嗎？誰說不可以？我就這樣啊，不然你是要怎樣，我就真的買賣黃金那樣啊。我買賣黃金，我賺錢要繳稅對不對啊，我虧損呢？我買賣重金屬，我可能真的會虧損。信不信由你，真的會，我真的會虧損。

好，那這樣我有薪資正所得，對吧？但我有財產交易的虧損啊，你為什麼不準我盈虧互抵？我是同一個主體，你要計算我的稅捐負擔能力，我在我的薪資所得，我有100塊，但我的財產交易我有虧損，我有50塊虧損，所以我真正淨所得其實是50塊。

當然你可以講說，臺大教師怎麼可以又再去操作衍生性金融商品，或是有這種這種股票交易買賣行為？好，我這樣講啦，也許我違反公務員法，我違反教師法。我應該要倫理道德高尚，我怎麼可以去操作股票或是操作重金屬。不應該去做這些事情。這個是規制，但另外我們回過頭來，除了規制之外，基本上這些不是非法活動，賺出來的錢，要進入所得課稅範圍，沒有意見，但虧損要準予減除。

但我們現在所得稅法裡面，一個隱含著所謂的凈所得原則的概念，是各類淨所得。我們14條的各類所得，是各類凈所得，不準跨類的跨類盈虧互抵。像我剛剛講的第三類薪資所得跟第六類財產交易所得（弧虧），做盈虧互抵，不可以。

那你說為什麼不可以？答案是因為我們現行法，就把這種跨類、跨年度盈虧互抵認為是優惠規定，必須法有明文才給優惠。這個理所當然，如果他真是優惠，那當然就必須法有明文。

為什麼這一類的跨類跟跨年度盈虧互抵是不被允許的？各位來看，所得稅法第17條的第一項第二款第三目特別扣除額之一的財產交易損失。

你看哦，只有財產交易損失可以在法有明文規定情況底下同類，三年間，跨年度盈虧互抵。只有財產交易損失在法有明文規定的情況底下，可以同類，但不能跨類哦，因為只有財產交易所得可以扣除財產交易損失。可以跨期間，但是只有在三年期間內。跨期間盈虧互抵。

透過這個條文規定的反面解釋，所有其他跨類，跟所有其他所得類型的跨年度盈虧互抵，一律不準。這個就是目前實務的釋義學解釋的操作。明明法條叫綜合所得，但說實在的，根本就不準跨類，就沒有綜合這個概念。這是分類所得的時候才會出現的概念，因為分類本來就是一條路走到底。你如果盈餘虧損，原則上就是減資，就這樣而已。但我們有綜合所得之名，我們並不存在著跨類盈虧互抵的可能。

然後跨期間盈虧互抵呢？可以，只有財產交易虧損是被允許的。所以這個概念也同樣貫徹到個人所得基本稅額條例，只有法律明定的跨期間才可以，不然就都一律不可以。

這個是所得稅法第17條第一項第二款第三目之一，特別扣除額的規定，他的體系位置跟主觀淨值無關，應該移動到第14條的財產交易所得第七類，就是財產交易損失的跨期間盈虧互抵規定。法條規範位置應該是14條，第七類，你要增訂第四款規定，到那個地方才對，因為他們概念上叫客觀凈所得。

所以我現在把我們的客觀淨所得的條文規定，重組一遍喔。各位要跟上來哦。

第15條的規定，第15條是合併申報的數個主體的規定，對不對？因為他是家戶所得課稅制。15條第二項的規定，有關於薪資所得，有提到，關於減除的免稅額。我們先來看一下第四項跟第五項的規定。15條的第四項跟第五項的規定是關於可扣抵稅額計算的規定，也就是8.5%計算可抵減稅額的規定。這個第15條的第四項規定，要放到我們整個算出應稅所得額，這個地方稅率的規定是第5條第二項的規定，要放到整個稅基稅率之後算稅額的地方，去做，可抵減、可抵稅額的計算。這個稅額扣掉可抵減稅額以後，才是最後面實際上的結算稅額。

第15條的第四款規定，在規範的位置上，要在客觀凈所得、主觀凈所得、稅率，算出稅額，這個叫應納稅額，然後扣掉可抵減稅額以後才算出來結算稅額。他是應該放在稅基乘稅率得稅額之後的可抵減稅額這個位置，這個位置才會是正確的。

第五項的規定，因為他是28條的營利所得的分開計稅，第15條第五項的規定，因為他是稅基分離，所以是客體的第一類營利所得稅基分離，然後連結稅率的規定，做分離稅基固定比例計算。

分離稅基，加上28%的固定比例。15條第五項的規定，適用全戶可扣抵稅額再加分離稅基與固定比例二擇一的方式去課稅。這個叫二擇一的營利所得課稅。條文規定的位置，是在可抵減稅額，是放在稅額之後。如果是28%的第五項規定，則是第一項的稅基分離，加上稅率的個別規定，而採取28%。因為我們本來的比例是在稅率，是在第5條第二項裡面的規定，那這個時候是二擇一的方式去做課稅。

這是我們在2018年之後的兩稅分立的課稅的制度，當然實務上把他稱之為叫可抵減稅額跟固定比例的二擇一課稅的制度。


接下來16條，是承繼第15條第一項的營利事業，如果是由配偶跟納稅人一起經營或分開經營的話，第16條的規定則是盈虧互計，因為我們15條第一項配偶經營的已經算入納稅人經營的範圍啊，所以16條的規定本來就應該直接接在第15條第一項規定之後的位置。

## 【生存權保障】

我們接下來看17條的第一項的規定。第一項底下的第一款免稅額，我們在上個禮拜跟各位提到，免稅額，這個部分是關於物理生存需求。

我們的17條第一項第二款，第二個層次的標扣跟列扣，是二擇一。本文規定，納稅義務人就標準扣除額或列舉扣除額，得減除其中一個項目。這個部分反映出來的，稱之為叫社會生存需求。因為納稅義務人，不是一個動物的人，有需要跟社會上其他的人，彼此之間往來交友，這個稱之為叫物理生存需求之外的社會生存需求。

這兩個概念加起來叫基本生活費用。因為一個人，賺錢，第一個，要維持自己物理生存需求，能夠吃飽穿了，第二個，我是一個群居的人，我要跟人有所連結，所以我要活得健康，我要有居住的地方，這個時候我才是一個活得有人性尊嚴的人，而不是只是吃飽穿暖的人而已。在這一個概念底下，這個叫做社會生存需求。

在這個之外的特別扣除，則反映個人的特殊狀態，尤其是身心年齡狀態產生出來的特別需求。這一種特別需求，透過特別扣除，整個都是反映出一個當代社會維繫個人生存需求，所謂的生存權保障的不可分割的概念範圍。生存權保障在法律上面做了一個，維繫物理生存、社會生存以及按照個別需要而產生出來的考量，這個叫特別扣除額，以此反映出社會法裡面特別強調的生存權保障。這個生存權保障，在我們憲法的第15條裡面。

第17條的這一塊叫生存權保障。前面14、15、16，主要是來自於對客觀淨所得客觀淨值原則的反映。客觀淨所得的反映在經濟學界裡面，基本上也強調，收入減成本費用，盈餘減虧損，這個是客觀凈所得。後面17條這個部分是主觀凈所得。算完以後，應稅所得的淨額，才乘稅率，得到應納稅額，再扣掉可抵減稅額，得到結算稅額。這就是我們整體的稅法的規範結構。

理論上，應該是一個法條一個法條去對應。

稅捐主體中華民國的境內居住者之個人，取得，理論上應該是全球來源的所得，依照客觀凈所得計算之客觀凈額，減除掉本法所規定之維繫物理生存需求的主觀淨額之後，乘上我國所規定的稅率，得到應納稅額，減除掉事先繳納或者依照法律規定的可扣抵稅額以後得到的結算數額，這個叫結算稅額，進入稅捐申報跟繳納程序。這一段就是稅捐債務法，這樣各位可以理解嗎？

法條規範結構本來應該是一個一個去做對應，而且因為我們的外在體系看不出來，所以請各位回去自己做。因為你做起來，就會比較容易知道這個法條之間的對應關係。

## 【列舉扣除額】

根據這個對應關係，我接下來要跟各位講的，這裡有6個列舉扣除額的項目，我現在把法條本來該有的位置，他應該要放在哪裡，我們重新做一個排列組合。

各位來看一下列舉扣除額。

所得稅法第17條第一項第二款第二目之一，捐贈。捐贈跟主觀凈所得一點關聯性都沒有。因為捐贈的扣除額是來自於對慈善公益之行為的鼓勵，所以本質是稅捐優惠。其實跟主觀淨值的個人特別需求也沒有關聯性。如果要放正確位置，應該是拉出去，就像稅捐優惠的重購退稅一樣，理論上他應該是拉出去。但如果放在17條，應該放在特別扣除額，也就是我們在特別扣除額裡面，把那個概念放寬一點，就是包含個人應受獎勵的社會上的這些各項行為，被鼓勵的各種行為，也放到特別扣除額裡面，當作是一種特別的考量，特別的扣除因素。所以，捐贈，要放到特別扣除額。


第二目之保險。保險是反映醫藥及生育費的另類支出。簡單來講就是，醫藥生育是保護納稅義務人及其受扶養親屬的身體健康跟生育這一個需求所需的所謂的生存需求的概念的範圍。一個人除了養活自己以外，我也要活得健康，因此會生病的時候，我會有醫藥費的支出。涵蓋醫藥及生育的費用，是對家庭，如果要生養生育這個功能的話，會是不可或缺的一個部分。在這裡面都是屬於維繫生存需求的範圍。而保險費是cover這樣的一個醫藥及生育費。因此，這兩個，在概念上面來講，只要保險費涵蓋的醫藥及生育費的範圍，原則上不能重複減除。超過醫藥及生育費的保險費的支出，只要是具有投資性質的保險費支出，這個時候他會跟後面的儲蓄投資特別扣除額重疊，就有可能會拉出去，另外加以對待。

保險費要區分其性質，做個別的對待。

醫藥及生育費剛剛就講過，主要是維繫身心健康以及生育需求的這樣子的一個維繫生存的費用。

災害損失則是個人遭受的天災地變的事由，所以應該是特別扣除額。

購屋借款跟房屋租金支出，這兩類支出基本上是維繫納稅人住的需求，從而他是列舉扣除額的項目範圍，所以放在這裡是對的。只是購屋借款是30萬利息扣除，房屋租金支出則是一戶12萬，對應出來的就是一個月租金1萬塊可以被扣除，但房屋購屋借款利息是30萬，可以扣除。原則上就是如果是全額貸款的話，以利率1%來算的話，30萬會對應出來，你可以購買的房子，跟你可以租的房子來比較看看，哪一個是屬於在稅制上相對會比較有利。這個都被認為是滿足維繫生存需求的範圍。

接下來來看，特別扣除額的第三目之一，財產交易損失，這個要放到第14條的第七類，財產交易的凈所得的計算範圍。

接下來的薪資所得特別扣除，這個也應該放到第14條的第三類薪資所得的計算裡面。這個是概括扣除額的規定。第17條的這個薪資特別扣除，要放過去跟14條的第三類薪資所得一起，以二擇一的方式去做規定，也就是要不適用特別扣除額一個概括性扣除額度，不然就是用14條的第一項第三類的列舉必要費用，包括職業專用服裝費用，包括進修訓練費用，跟職業上工具支出的，二擇一的方式去做規定。所以，薪資特別扣除額的規定要放到14條第一項第三類裡面的列舉必要費用，去做並列適用的規定，因為這是客觀淨所得的部分。


那麼，接下來是儲蓄投資特別扣除額。儲蓄投資特別扣除額，原則上被認為是一種獎勵儲蓄投資行為的扣除額，就跟捐贈一樣。捐贈的扣除額，某種程度上是獎勵公益慈善，那獎勵你照顧好自己老後未來的生活，這一種儲蓄投資特別扣除額，因此放在特別扣除這個項目內。

身心障礙特別扣除額，是一個最典型的，因為個人身心障礙特殊狀態所導出來的一個特別扣除的因素，所以身心障礙特別扣除額，放在特別扣除額裡面，或者移動到列舉扣除額的項目裡面也很適當。

接下來我們來看教育學費特別扣除額。教育學費的教育，是指大專以上院校，不是在講義務教育的這個學費。義務教育理論上沒有學費，但我們知道實務上不一定真是如此啊。因為我們有一些學校特別是私立學校，還是會有收學費。但這個地方條文規定就是大專以上，大專以上不在義務教育的範圍，所以他是一個鼓勵你進修的，獎勵進修的教育學費特別扣除，所以放在鼓勵這個部分。

然後幼兒學前，幼兒學前是因為你的扶養對象是幼兒，從而幼兒在5歲以下，會有要照顧他的個別的需求，所以也是屬於因為年齡產生出來的個別需求。

長期照顧，則也是屬於他的身心狀態的特殊狀態的，產生個別出來的個別的照顧需求。這一個長期照顧特別扣除額，因此跟醫藥及生育費不完全相同。醫藥生育費可能會有包括的長期照顧，但長期照顧不一定會完全被醫藥生育給涵蓋。因為我們現在的長期照顧，主要是這個照顧人力的這個支出的部分，而不全然是屬於的醫藥生育費用。

基於這樣子的一個整體的觀察，我們重組一下法條規範的結構。

免稅額，有一個一定年齡以上的加計50%，就是納稅義務人跟配偶年滿70歲，就老年人加50%的免稅額。他跟幼兒的照顧特別扣除額一樣，都是因為年齡而產生出來的特別需求。因為身心障礙或特殊狀態產生出來的需求是身心障礙特別扣除跟長期照顧特別扣除，這個都是他的身心狀態產生出來的特別需求，在概念上都可以放在特別扣除額。

照顧一般平均水準下的物理生存需求，以及維持身心健康跟住的需求是社會生存需求，是前面這兩個作為反映物理生存跟社會生存需求的兩個主要費用。接下來的特別扣除額，一個脈絡，是因為身心跟年紀的特殊狀態所產生出來的特別需求，另外一個脈絡，則是受鼓勵獎勵優惠的特別扣除額。這個是我們現在所得稅法在目前稅基計算，該要分出來的規範結構。

再重申一次，前面這個部分，一直到維繫個人生存需求這個部分，我個人認為都是憲法15條生存權保障的範圍，因為他跟個人的人性尊嚴有密切的關聯性，所以在相關規範的位階審查上面，就是憲法位階，憲法的審查上面，是屬於比較嚴格一點的，也就是中度的實質關聯性的審查的基準。

但如果是屬於客觀凈所得，甚至是後面的稅捐優惠的事項。稅捐優惠，讓立法者享有比較高的立法形成空間，因為這本來就不是反應量能課稅原則的必要，而是立法者根據立法政策上所做出來的決定。因此這個獎勵的部分，即使放到特別扣除，他的法律性質，也不應該跟其他的維繫生存的需求等同對待，要做區隔，要做不同的區別。

這是我們整體理解我們的稅法規範結構。透過內在體系，我們稱之為叫主觀凈所得、客觀凈所得的區隔，稅基乘稅率得到稅額，這個是依法課稅原則的稅法的基本原則。在這樣的整體結構底下，重新解析跟建構我們的所得稅法。所得稅法的條文規定，因此需要做一定程度上的重新的排列組合。

客觀淨所得，原則上要放在14條的各類所得裡面去做規定。

接下來第15條是兩個主體的合併計算。15跟16，因為我們的所得稅法是把兩個主體合在一起去做綜合所得課稅的稅捐主體的適用範圍。也就是第15條適用的，原則上就會在16條裡面去做合併計算所得，合併計算盈餘跟虧損。因此這也是客觀淨所得的反應。第16條的規定，也是如此。

進入17條，則是主觀凈所得、主觀淨值原則的反映。當然，在法律規範結構上，稅捐優惠，應該另外拉出來，有一個17-2的相關規定，去做個別的規範。稅捐優惠的規定，其實回饋到最前面的第4條的規定。第4條裡面，我們有諸多屬於應稅跟免稅所得的規定，那個地方都是稅捐優惠的規定，要拉出去。拉出去，去做一個跟稅基有關或稅率有關的個別規定。這個才是所得稅法應然該有的一個圖像。


所得稅法，因此是依照課稅構成要件各項要素逐次展開的法條規定。稅基乘稅率得到稅額，這個是我們在這個稅捐實體法裡面最終所呈現出來的法律效果，才接著接下來的稅捐稽徵程序。

所以我們接下來談個別的問題，跟稅基計算里面有關的，做個別的調整適用，但規範結構裡面的重新調整，希望各位可以透過這堂課程，大致上有一個想像中的圖像，就是一個所得稅法規範的結構的圖像。從稅捐主體的境內居住者的這個概念，到客體的所得，到應稅所得額的計算，各類所得的淨額的計算，進入稅率乘稅基的稅額的計算，結算稅額，這個之後才是接著稅捐稽徵法，也就是所得稅法第71條的結算申報制度，跟就源扣繳制度的規定。

我們在這裡面要有一個稅額計算的規定，但我們法條規定看不太出來有稅額計算的規定，因為他是放在各個不同的稅的客體的規定裡面去做分散式的規定。

這是我們目前的規範結構。

我們先休息。