# 20231106_01

---
課程：1121所得稅法一
日期：2023/11/06
周次：10
節次：1
---


今天我們先繼續，所得稅的稅捐客體的最後一個部分，關於所得的來源地的判斷，接著在這個之後就會談到今天我們非常重要的關於稅基的部分。


所得稅的稅捐客體的最後一個部分，關於所得的來源地的判斷。在上個禮拜我們跟各位提到，所得稅法第8條本身的規定，並不是很清楚，去指明何謂所得來源地的判斷。也因此，在實務上，我們透過財政部的「所得稅法第八條規定中華民國來源所得認定原則」，作為一個判斷上的依據，這個來源所得認定原則，看起來是一個，一般性抽象性的行政規則，因為他本身並沒有法律的明文規定的授權依據，等於是以所謂的事實認定原則的方式出現。這樣子的一個條款規定，儘管實務上自認為是一個事實認定的一個規則，但，以老師個人的判斷來看，我認為他還是一個關於我國有沒有課稅權限的劃分，是屬於稅基的規定，那應該是要由立法者，透過制定法，或是授權明確的法規命令來做規範，才符合依法課稅原則。但現實上他就是沒有這樣一個授權。那司法實務上的困難是，我如果不知道這個來源所得認定原則，也不太容易有一個客觀上的一個判斷標準。

那從我們今天要跟各位去談的，就是一個應然的狀態。也就是說，實務上其實並沒有這樣一套的判斷標準，就是我們在司法的實務累積上面，他並沒有形成一個比較穩固的一個見解。

老師接下來跟各位談的，關於所得來源地的判斷的問題，涉及到國際租稅法的問題，另外一方面也是參考那個德國的立法上的規定，來做一個綜合的說明。

## 【所謂的中華民國領域】

那我們首先跟各位先談到中華民國所得來源地認定，我們現在目前的所得稅法第8條規定，本身並不是非常恰當。因為所謂的中華民國，在這個地方，不應該透過意識形態而去將所謂的臺灣地區跟大陸地區，都認定為叫中華民國所得來源地，這種判斷標準是一個意識形態，而不是法律原則的一個判斷標準。因為很簡單，中華民國，臺灣根本沒有對大陸的有效管轄權限。一個美國人在大陸地區獲得所得，你總不會認為他應該要繳我們的所得稅，只因為他是中華民國來源所得，這一個純粹基於意識形態的這樣一個標準。你完全不會認為任何人到中國大陸地區去獲得所得，因為他是中華民國來源，所以我們跟他產生屬地的連結，因此他要繳我們的所得稅。這個道理是說不過去的。

從而我們的所得稅法第8條第一項，其實應該要明白的定義，所謂的中華民國來源所得，我們只及於我們現在在國家主權有效行使範圍內的臺澎金馬地區，這一些才是我們的所謂的中華民國來源所得。要去連結所得稅法第2條第一項所講的中華民國來源所得，所謂的屬地連結是你的課稅管轄權限，能夠有效的連結的領土、領空跟領海。這個地方跟你憲法愛怎麼講，統一前的所謂中華民國主權能及的範圍，不同。你根本就沒有辦法有效去管轄大陸地區，就不要談，所謂那個地方也算中華民國來源所得。

所以第8條第一項，其實理論上應該是，本法所稱的中華民國來源所得是指中華民國現在有效管轄的臺澎金馬地區的領土、領空跟領海。

領土，待會跟各位去談到，為什麼他是所得來源地的一個判斷標準。因為領土涉及到一個國家的不管是課稅管轄區或是司法，比如說刑事法上的有效管轄，這個都是一個地域管轄的一個非常重要的一個範圍。

另外大概就是領海。依照國際法，一般而言是我們的海岸線外推再3三海浬以內，基本上會是屬於我們的領海範圍。簡單而言，就是在領海範圍內的話，那原則上還是屬於我們的課稅權限所及的中華民國的屬地的來源。200海浬的經濟海域，那個不是領海的範圍哦。200海浬的經濟海域，那個只是在，國際級的經濟行政法裡面，認為國家在那個地方有專屬的漁業上面的採摘的權利，但那並不是領海的範圍。這個要還是要請各位同學要認弄清楚，我們所謂的領海，一般而言是指你的海岸線外推。國際法之間有一些是根據大陸棚的規定，還可以繼續往外推，那個是要看看國際法的規定。

那當然還有領空，當然在這個地方的領空並不至於讓你導出，就是只要是上面飛過去的所有的可能涉及到課稅管轄的事情，比如說外國的航空器飛過去，因此就要課我們的這個所得稅。並不是以這樣一個方式。那也因此，領空這個概念必須是在國際法裡面所承認，認為在這個部分是屬於中華民國在課稅權限所管轄的範圍。


另外，第二個要解決的問題是這樣，在這裡面有許多我們並不是，跟那個領土的範圍剛好重疊一致的，有一些是物理上在境內，但被認為是境外；相反的，也有一些是物理上境外，但應該被認為是境內。這一些主要是我國駐外的使領館。

我國駐外的使領館在這個地方，物理上是境外，但在課稅權限裡面，一般是被認為是我國的境內區域。也就是在中華民國駐外的使領館裡面所發生的，屬於應受課稅適用對象的，比如說在那個地方的勞務的付出。我們駐外的使領館一定會有派駐在外的這些公務人員跟非公務人員的使用，包括大使或是領事，甚至是派駐在外的這些負有公法上任務完成的這些武官跟外交人員。那么當然也有不執行公務的，純粹是技術性事務的，比如說是清潔事務，或者是屬於這個一般事務處理的，也就是並不是在執行公務的這一類型。當然這一類，一般而言，也可能會派本地的人員去前往，但原則上並不具有執行公物公法上的這樣子的一個勞務性質。從而，在這一塊，物理上境外但在國際法上被認為是境內的這個領域裡面，所發生出來的跟課稅管轄權限，特別是在這上面行使國家公權力的公務員跟非行使國家公權力的受僱員，因此所產生出來的勞務的付出所獲得的所得，依然是屬於中華民國來源所得。

相反的，外國使領館在中華民國境內，這個在物理上是屬於我國境內，但是在法理上，是外國的課稅管轄權限所及的範圍。

一般而言，在維也納公約底下，屬於駐外使領館範圍內的這一種在物理上雖然不是中華民國的境內，或者相反的，在物理上是中華民國境內，但在課稅管轄權限行駛上面的時候，處於駐外使領館的這個部分，當然必須要在我們的法律裡面有一個明文的規定。

除了這一種，透過維也納公約所認定的一些所謂的這個物理上境內或境外，而視爲物理上境外，跟境内的這一種情形，還有是屬於我國籍的船舶及航空器。這個也同樣都必須在我們的所得稅法第8條裡面去做明文的規定。


凡掛我國旗的我國旗的這個船舶或航空器，比如說長榮海運陽明海運，或者是長榮航空公司跟中華航空公司，原則上面他在這一個航空器或是船舶內所發生的，物理上可能是在公海，或者是可能在其他國家。

從而所謂的中華民國領土、領空，跟領海第一項的規定，跟第二項，物理上境外視爲境內，或相反的是，物理上境內視為境外，以及我國籍的船舶及航空器，原則上面都是屬於我國的中華民國領域範圍內的課稅管轄權限所及的，中華民國領域來源所得，中華民國來源所得。


你看這幾個條款規定，在我們的所得稅法沒有規定，在我們的來源所得認定原則也沒有規定，那請問你怎麼認定這個算中華民國來源所得？你只有加一個第14條裡面的所得類型，加一個中華民國來源所得，等於是你有規定跟沒規定是沒兩樣的意思。這個也是我們的法制上面，我個人認為，稅法規定不僅是規範密度過低，而且是常常是該有規定沒規定。

沒有規定，這個時候會讓司法機關，往往沒有受過學校裡面養成教育，或是在司法實務上，沒有形成一個比較一致性的見解的話，他會不知道要怎麼去做判準。

這個是我們跟各位提到第一項跟第二項所談到的這些規定，也就是，所謂的中華民國領域，這個到底是指什麼地方跟範圍。


## 【所得來源地之四個判斷標準，概説】

那接下來我跟各位談第三項的規定，也就是說，何謂中華民國來源的所得，要按所得類型去做分類。也因此各位還記得我之前在講所得客體類型的時候，有跟各位提到一個非常重要的分類標準。就是按你是繼續性跟一時性分別。是勞務或者資本的投入，做兩種不同的類型。按照是勞務裡面的非獨立勞務或者是獨立勞務，分兩種不同的類型。資本類型裡面，按照是孳息或是財產的交易所得分類。

各位都還記的這個圖形嗎？還記得哦，希望各位一定要記得，我沒有暗示什麽。但你不記得的話，我一定會用某種方式讓你記得。

非獨立性的勞務跟獨立性的勞務，三種不同的類型，依照你的業務內容。農林，大自然界的第一次產出。特殊的勞務，執行業務者。以及其他的工商農林漁牧礦冶的營利事業。工商農林漁牧礦冶的營利事業，記得跟農林所得怎麼區別嗎？還記得嗎？不記得，我也一樣提醒各位，我會用某種方式讓各位記得。執行業務跟營利事業又怎麼區別呢？還記得嗎，都是獨立型勞務。

營業所得，我講的就是獨資或合夥去經營工商農林漁牧礦冶，那裡面雖然有農林漁牧礦冶，但他跟農林的所得最大的區別是在，是否是大自然界的第一次產出，或者是加工的產品的差別。執行業務所得，原則上在我們的法制環境裡面，主要是指三種不同類型的特殊勞務的所得，除了大學養成的國家考試，除了人類智慧財產權的相關的，比如說表演作曲藝術啊這一類的，以及特殊勞務的特殊技藝的這一類所得以外，原則上其他都是屬於營業。

資本裡面，我們依照資本的類型分成的股利、利息、權利金還有，還記得嗎？這四種不同的資本的形態產生出來的法定孳息。

那麼所有的資本都還會有第二種所得，叫財產交易所得，這個就叫資本利得，capital gain的概念。

我們把這個客體的類型列出來。我們接下來一個一個跟各位去說，所得來源地怎麼去判斷。

### 【所在地課稅原則】

第一個標準。涉及到領土、領海的領域的這個部分，會有一個所在地的判斷標準。你只要是中華民國境內的農林漁牧礦冶，以及財產跟孳息裡面有一個類型是租金。因為租金可以是不動產的孳息。還有財產交易所得，由於你的財產可以是不動產。不動產的話，只要你是所在地在中華民國，我剛剛講的第一項，中華民國境內的領土、領海的範圍，原則上，這個就是所在地課稅原則。在哪裡，那個地方就被認為是所得的來源地。

國稅，基本上我們不分是在哪個縣市自治團體範圍內。這個，主要是區隔我們跟外國之間的課稅管轄權限。這個是所在地的課稅原則。

只要是這裡面跟不動產有關的，原則上都是所在地。跟土地、海域有關的都是所在地課稅原則。就是，這個東西物理上在哪裡。除非你有第二項，我剛剛所講的剛好是屬於物理上的境外，但在國際法上被認為是我們境內。

這個叫所在地課稅，就是這個東西在哪裡，就有那個地方被認為是所得來源地。

### 【勞務：經營地、履行地】

第二個，我們來看一下勞務的類型，裡面分獨立跟非獨立勞務兩種類型。

屬於獨立勞務的，有以下這幾個類型：執行業務、營利事業。這一些獨立的業務的類型基本上具有一個特色，他是一種獨立經常性的經營活動所產生出來的一個所得的類型，所以他是一個active income，因此這個會適用「經營地」來作為判斷標準。經營地會聯繫在國際租稅法裡面的「常設機構課稅原則」。因為activity，你的活動，要有一個活動的主體存在。國際租稅法裡面因此稱之為叫「常設機構課稅原則」，在我們的營利事業所得稅裡面，我們到下一次談營利事業所得稅的時候，會講固定營業場所或是營業代理人。那個概念，基本上也都是在講你的經營地點，常設機構經營地點。那當然如果你是一個營利事業，你自己本身營利事業的經營地點，也就是你實質的營運地點。歐陸法系國家大部分都是以你實際經營的地點來作為判斷的標準，而不是相反的，以美國為代表的，適用準據法，依照準據法地。

很抱歉，我突然忘記，準據法的據怎麽寫。因為現在寫東西不太像以前早期我們都用手寫，大家都現在用打字，所以我自己也常常會忘記哪些字怎麼寫，如果各位同學寫錯，我基本上我也比較寬認啊，因為我自己有同樣的問題，我不能苛責各位同學。我只有對某一些字眼，我想我會比較敏感一點，比如說稅捐救濟程序裡面，原文寫這個「復查」，你如果寫成「覆查」或「複查」，這個我會比較敏感。我們稅捐救濟程序是「復查」，這個如果寫錯，我看到我會稍微跳起來一下子，要稍微注意一下。

第三個我們講非獨立勞務則是以履行的地點，也就是勞務的實行地點。因為獨立跟非獨立的差別在，獨立，是一個自己去承擔財產上經營的風險而去經營的一個行為產生出來的經濟成果，我們稱之為叫執行業務所得，或者是營業所得。非獨立勞務的薪資所得，他的勞務的付出，原則上是受僱指示，從而他產生出來的所得，我們把他稱之為叫非獨立的薪資所得。對未來做給付的，原則上是退休所得。這一類的所得原則上是以當初他勞務在哪裡付出，勞務在哪裡履行來判斷。你勞務在哪裡付出，原則上就會是那個地方的課稅管轄權限所及。

### 【債務人稅籍】

那么最後還有一個，是這一類，很大程度上排除掉不動產以外的，其他的包括股利包括利息，包括權利金，原則上他都是由債務人，給錢的人的稅籍來作為判斷標準。因為他本身的資本型態，跟「所在地」最沒有關聯的大概就是現金通貨，就是你借錢這件事情，因為現金本身不具有個別性獨特性，只是全然一個支付工具而已。在虛擬通貨興起的時代裡面，你更難以認定那個通貨到底是哪個主權國家所管轄，或者是所給予的。因此在判斷標準上面來講，以利息為代表的這一類所得，不看是用什麼通貨去給付，是誰給付才重要。也就是採用屬人上的連結，給錢的那個人來做為所謂的所得來源地，而通常一般而言，會適用債務人的稅籍國來作為判斷標準。



這裡面我們總共四個標準，第一個，不動產的所在地，第二個，獨立勞務的經營地，第三個非獨立勞務的履行地、實行地，以及第四個，所謂的資本的債務人的稅籍地。

這四個標準，理論上來講，應該要在我們的所得稅款第8條的第三項裡面，做一個明白的指示，這個就是立法者做成一個價值決定的一個判斷標準。

當然，接下來我們會進一步去延伸，因為透過這幾個基本的標準，所在地的話，會有幾個所得的類型，由於他並不一定能夠完全被涵蓋，但大致上來講，這四大標準也是國際租稅法裡面去判斷所得來源地的來源地判斷標準。

非獨立勞務類型，我們有兩種類型所得，一個是薪資所得，一個叫退休所得。退休所得是過去勞務的未來繼續性支付，對吧？因為我現在退休之後沒有付出勞務，那也因此我在概念上沒有勞務的繼續性付出。這個時候退休勞務有可能從勞務所在地轉成，債務人支付，也就是以債務人的稅籍地來作為他的判斷標準，這個是有可能的。比如說你退休之後移民到國外，移民到泰國去，那麼當投保單位繼續給你錢，你當然可以以他是一個過去勞務本來是在臺灣境內所付出的勞務，那從而臺灣對這一筆退休所得享有課稅上的管轄權限。那同時另外一個方面，就是他是臺灣的投保單位，也就是保險單位所提供的給付，從債務人的觀點來看，他也會是以債務人的稅籍國，也就是是屬於我國投保單位所支付出去的保險金給付，會是我們的來源所得，我們擁有課稅上的管轄權限。會有兩種標準的可能。

接下來我們看到農林，農林漁牧礦冶，我們剛剛跟各位講過，基本上是大自然界的第一次產出，從而跟屬地管轄，領地跟領海的管轄權有密切關聯性，這一類所得在國際租稅法裡面，基本上都是領土優先，就是誰的領土發生的，那就是他們的所得，你不能把自己的手伸到別人家的領土的範圍內裡面，去要求課稅管轄權限。就如同我剛剛一開始跟各位舉的例子，美國人到北京工作，你憑什么課他的稅呢？就算他偶爾經過臺灣的桃園的機場，你也不能說欸，你要繳完稅你才能過境啊。我們沒有那個對他的一個所謂的那個真實性的連結。他不是我們的稅籍居民，他根本沒有在中華民國境內取得所得來源，你憑什麼對他去課稅？我會特別講這個，是因為我們只對設籍在臺灣的人，他不管取得臺灣地區來源所得跟大陸地區來源所得，他全部都被認為叫中華民國來源所得，課徵綜合所得稅的所得。這是我們的兩岸人民關係條例第26條第一項的規定。一個全然是基於意識形態所做的不利本國人的一個規定，我個人認為是一個違反平等對待原則的一個規定，是很沒有道理的一個規定。

回過頭來，屬地的這個部分。跟屬地有關的不是只有農林，特別是不動產裡面的租金，還有不動產的財產交易所得，這三種所得都是適用屬地原則，所在地原則，也就是東西、土地在哪裡，該當地因此就取得了課稅上的管轄權限。

從所在地原則會衍生出來我們的第八類，我們有一個競技競賽及機會中獎。在所得稅法第14條的第八類。比賽舉行地點在中華民國境內，所發出去的競技競賽及機會中獎的獎金所得，這個就是中華民國來源所得。所以，假設在本地，舉辦一個國際菁英邀請賽，或者是舉行一個大樂透遊戲。這個都是屬於，只要是競技競賽及機會中獎的舉辦地點在中華民國境內，那這個獎金原則上就會是中華民國來源所得。這是以舉行地點來作為判斷標準，你可以理解，舉行的基本上就是所在地的延伸，他跟領土管轄主權也有比較密切的關聯性。

那么屬於獨立性勞務的，排除掉農林所得，剩下的，包括執行業務者的勞務，跟營利事業的商品跟勞務，原則上因為他具有繼續性的經營活動的性質，只是勞務內容有所區別而已，所以一般而言是以經營地聯繫著常設機構課稅原則，不管你有沒有成立成立一個法人組織的型態。常設機構，本身不一定要是法人組織，非法人組織也可以。因此獨資跟合夥，如果是一個法人組織，那當然就是你的組織的這個經營地點在哪裡，那么這就是你的所得來源地的判斷標準。獨立勞務跟繼續性的貨物跟勞務銷售行為的地點基本上是經營地。

## 【實質判斷標準】


全球化底下，經營地點，可能是遍佈在全球範圍內。數位化經濟時代來臨之後，用更容易讓那個經營地點本身是不太容易去判斷的。也因此在這裡面，所謂的經營地點，一般被理解，叫做決策做成的地點，他的經營管理階層在哪裡做成決策。那因此在實務上面以歐陸法系為代表的幾個採取實質判斷標準的這一些國家，通常會以所謂的「實質營運管理地點」來作為判斷標準。這就是我們所得稅法第43-4條的PEM的由來。

正因為我們在實務上面並不是採實質營運地的標準，我們是採準據法地。我們準據法地這個判斷標準，不是只有課稅而已，基本上營利事業所得稅跟公司法都是採用準據法地，也就是依中華民國公司法設立的，就稱之為叫中華民國的公司。那如果你是依非中華民國，外國公司法設立的，就被稱之為叫非中華民國的公司。我們是以比較形式的標準去判斷是否為中華民國的公司。同樣以比較接近這種形式的標準來判斷，這個叫總機構在中華民國境內或非在中華民國境內。那也因為這樣子的一個形式準據作為判斷標準，從而我們在理論上面為了防杜，透過設立準據法來規避我國的所得稅法的課稅，營利事業所得稅裡面基本上需要PEM的制度，叫做「實質營運地」的判斷標準。

這個立法是出來了，但是我們現在目前為止43-4條的規定，目前為止還沒有預定在甚麼時候正式施行。不像43-3，我們已經從今年開始正式實行。但43-4什麼時候正式實行，目前沒有一個比較明確的一個時間。雖然有法條的規定，但並沒有正式施行的日期。

我們在稅捐規避行為裡面，大概你只要用外國法設立的話，原則上就不叫總機構在中華民國境內，所以你去看實務上一堆用外國法設立的。本來一般而言呢，不是以我們的法律設立的，他不能夠在中華民國的資本市場去募集資金，可是在我們的相關的法律做變更之後，這一些公司用外國法設立，但他也可以在中華民國境內的資本市場裡面去募集資金，這一些就是所謂的被稱之為叫KY公司，是一些境外的公司。他理論上來講，本來應該是從境外的資本過來，但因為我們現在目前為了要擴大國內的資本市場，也容許他在境內去做募集資金的動作，但相關的財務上的考核制度，我們卻在這個部分的建構上面，沒有做得比較完整。因為這一些相關的，他只是單純依據外國法去設立，所以就認為他是一個境外公司的這樣子的一個法律上的認定，我個人認為是一個非常草率，而且是一個非常容易被規避的一個規定。以前還可以透過資本市場，你如果是境外，原則上必須要把資本匯入，你才能夠在本地進行相關的投資或營運管理的行為。可是現在目前是，你用境外公司的法律設立的，那你還是可以在本國境內去募集資本。而你的所得，凡是非從臺灣所取得的，一切境外的所得，基本上就被認為是屬於由外國的課稅管轄權限所及。但這一些往往都不是在高稅負的這些國家裡面去設立，他有可能都是屬於在租稅天堂的地區國家所設立的境外公司。

我們在實務上面，就這一塊領域來講，我們並沒有很完整的一個防杜稅捐規避行爲的相關條文的規定。

原則上，經營地是一個實質判斷標準，以判斷所得的來源地國，那麼經營地點只要在該地，一般國際租稅法裡面稱之為叫常設機構，就是，你在該地經營原則上要有一個固定營業場所在該地經營，那這個時候那個地方就被稱之為叫所得來源地。稅籍居民國，雖然也可以課稅，但稅籍居民國，對所得來源地國行使的課稅權限要予以尊重，因此他要透過稅額扣抵的方式，來避免重複課稅。

重複課稅的避免義務，是稅籍居民國家的立法上的義務，而不是所得來源地國的立法上的義務。所得來源地國主要是避免，做了過度不當的屬地的連結，像我之前跟各位講到的那個例子，那個是一個不當連結的例子。


## 【非獨立勞務與營利事業】

那非獨立性勞務，這個地方也是一個蠻有趣的一個類型。營利事業經營的內容也包括了勞務的付出。勞務的付出，在營利事業而言是經營的問題，不是勞務的履行的問題。因為營利事業的勞務的付出，本來就是透過自然人付出，但自然人的付出，這個是歸屬於營利事業本身的經營內容。換言之，營利事業透過他所僱傭的受僱人付出勞務，這是在營利事業這個層次，要判斷他的經營地點是否在中華民國境內。那個付出勞務那個人，那個是自然人，那個人，他的勞務付出叫非獨立勞務，這個時候我們才會有非獨立勞務的履行跟實現的的判斷問題。各位可以聽得懂這兩個不同層次之間的關係嗎？

我一個經營者，我一個公司，我可以派一個受僱人，柯格鐘，到美國去執行我的勞務，那這個時候是我這一家公司有沒有在美國經營的行為，這是一個層次的問題。另外，第二個，我派柯格鐘到美國紐約去執行我們這個公司的營業的內容的時候，這個人在當地，他自己本身有一個所謂的非獨立勞務，依據其履行地點是否在美國紐約，因此，美國取得課稅管轄權限的問題。這是兩個不同層次的問題。各位可以明白嗎？ 

法人的經營跟受法人雇主指示，而在當地付出勞務，這是兩個不同層次的問題。第一個層次是營利事業的經營地問題。第二個層次則是受僱人的勞務履行地的問題。所以因此，當你第一個層次，營利事業的經營地點，如果我只是偶一為之，在當地派一個人，比如說，我在當地並沒有一個固定營業場所，我只是派一個人去那邊去接洽客戶，談成了生意以後，就把這個生意轉回來，讓我們的營利事業可以把貨物跟勞務銷售在該當地區。在當地沒有常設機構，從而他不會構成營利事業的所得，要課徵美國當地所得稅的問題。各位清楚嗎？

相反的。如果是受僱主指示而到當地去付出勞務的話，他是一個非獨立勞務，因為他的勞務本質上是要歸屬給他所屬的組織，作為經營的內容去判斷。但這個受僱的人，他本身是一個自然人，他的勞務履行地點是在美國紐約，這個時候一般我們以自然人的所得判斷標準，就是以他在當地停留是否夠久作為判斷標準。原則上就是183天。也就是當你受僱主的指示派到當地去，你在當地停留超過一個歷年的一半以上，你就會因為停留夠久，這個自然人本身構成了取得當地來源所得，因為你的勞務地點是在美國紐約當地。這個時候有沒有構成營利事業的經營所得的經營地點？這個是兩個不同層次的判斷。

這個時候，原則上你付出去的所得，在當地，不管是當地雇主給付，因為我們派出去，可能也會有當地的我跟那一邊的營利事業做了接洽，所以我派出去的人可能會取得當地的雇主，當地的人所給付的所得；也可能是本地的雇主付給他外派，讓他外派到國外去的所得。這個地方屬地的連結之外，在加屬人的連結來綜合評價，就該所得是否屬於源自於該當地的所得來源。

也就是勞務的履行地點，一般而言，超過歷年的一半以上就會被認為是屬地的來源所得。但如果沒有超過6個月，只要非由當地雇主給付的，我們這邊付出去給他的，那原則上對方那個地點並不是所得來源地，而是我們付出去的錢，我們派出去的員工，那我國還是擁有課稅上的管轄權限，而不是當地的勞務履行地的課稅管轄權限。因為第一個，他停留不夠久。第二個付錢的人債務人，並不是當地的雇主。這個是依據他的停留時間，以及債務人是哪一國的稅籍居民去做綜合評價判斷。

一般而言，超過歷年的一半以上，所得來源地就會是在當地，不管你是國內或境外的雇主所做的支付。短於183天的話，則在國際法上是依照兩國之間各自所得稅法的規範，如果有可能，透過雙邊租稅協定，去維持，或者是退縮各國的課稅管轄權限，這是透過雙邊租稅協定去洽商規範。

## 【非稅籍居民在我國境內】

請各位因此來看一下我們的第8條第三款規定的但書：「但非中華民國境內居住之個人，於一課稅年度內在中華民國境內居留合計不超過九十天者，其自中華民國境外僱主所取得之勞務報酬不在此限。」

我們透過第8條第三款但書規定，假設一個美國公司派一個美國的業務代表，到臺灣來來指導我們臺灣的公司，關於他的勞務要怎么去完成。因為像技術服務常常有這種情況。那個美國公司派過來臺灣來做技術服務指導的這個美國人呢，他是非中華民國的境內居住者。他在我們境內，他停留不超過90天。而且他的所得也不是來自於我國的雇主所給予的報酬，也就是根據契約上的約定，並不是中華民國公司付給他的，而是由他的美國公司繼續付給他的。從而透過第8條的第三款但書的規定，原則上我國課稅管轄權裡面，他直接把這一塊切掉，我不課。

所以外國的稅籍居民在我國境內停留不超過90天，而且他的所得是由外國雇主付給的，那原則上非屬中華民國來源所得，我們不課。即使他的勞務在這90天以內，是在中華民國境內付出，但這還不是中華民國來源所得。理由，第一個，他在中華民國境內停留不夠久，第二個付錢的不是中華民國的雇主。不是透過契約由中華民國境內的營利事業，或者是個人付錢給他。

除了這個比較明顯的，我們把他切割出去，不在我們的課稅管轄權限範圍內，基本上幾種組合類型就比較沒有明確的標準。

如果90天內停留，但是由我們的雇主，依照契約的規定約定付給他的。請問這個要不要課中華民國來源所得？ 要課，就要開始用我們後面會講的就源扣繳程序規定喔。因為他只要是中華民國來源所得，付給他的人，要依法律的規定要去做就源扣繳，因為他是一個非境內居住者，他是一個非我國的稅籍居民。

超過90天以上的，我們沒有答案。也就是你90天以內的由我國的公司所給付給他的，因為我們請外國技術人員來，我們可能會給他一些比如說職務上的津貼，讓他住房住宿舍，或者是有所謂的加給。除了外國公司給，依照合約的規定，臺灣的公司也要給他一筆錢，那這筆錢算不算中華民國來源所得？如果是的話，那這就會要課徵所得稅的所得，要用就源扣繳，而這個問題的答案是，我之前跟各位講過，有沒有中華民國境內的個人跟營利事業的參與和協助。這樣就是要有參與的協助。

因此，在我們的所得稅法裡面，停留90天以內，外國雇主支付，我們明確切割出去，不屬中華民國來源所得，不課所得稅的所得。

除此之外的勞務付出，只要有境內之個人或營利事業的參與或協助，就很有可能依來源所得認定原則來做一定的評價，那當然來源所得認定原則裡面所講的協助或者是參與在第4點的規定裡面，有一些要件要求，尤其是第4點的第三項規定，協助或者是參與，是指說要提供設備整人力專門知識或技術等資源。只要有我們境內的個人或營利事業，提供設備人力專門知識或技術等其他資源，這個時候就可能被認為是所謂的參與跟協助。但不包含勞務買受人應配合提供勞務所需之基本背景相關資訊跟應行通知或確認之聯繫事項。

我個人當然知道，這大概想說要講的就是說我只是填表的話，這樣不算是參與跟協助。我只是填表，因為我們的營利事業跟對方營利事業簽約，原則上面我們有簽約相關的資訊去做提供，我只是告訴你我們這邊的這一些的背景知識跟應行通知或確認的聯繫事項，單純的一個資訊告知，不被認為是一個參與跟協助。可是任何只要有積極性地去提供設備人力專門知識或技術，不管是有形或無形之資產的技術上知識上的提供，只要有一個積極參與的行為，不管比例多少，原則上就會被認為是有我們的參與跟協助，因此屬於中華民國來源所得。

這個條文規定極大程度範圍地去擴張我們課稅管轄權限所及，背離了一般，如果在判斷經營地點的時候，必須要是常設機構，這樣一個國際課稅裡面的基本原則。你看起來會覺得好像我們是對外國的這個營利事業去課稅，因為他是外國到臺灣去取得中華民國來源所得的這種情形，但正因為他是一個非稅籍居民，取得中華民國來源所得，所以我們會用就源扣繳程序，基本上倒楣的會是跟外國做生意的，這一些我國的稅籍居民，包括營利事業在內。

我大致上把境內來源的所得，裡面的這獨立勞務的付出，跟非獨立勞務的付出，以及財產的所在地介紹完。休息完之後，我們再跟各位很快的講一下債務人的稅籍居民國，特別是關於他的權利金的給付的部分。因為權利金的給付，往往跟登記註冊地點相關。因為權利，專利、商標這種權利，原則上是一個無形資產，是一個無體的財產，所以會跟他登記在哪裡會有密切的關聯性。因此，根據債務人的稅籍國，未必會跟登記國是同一個國家，也因此在實務上面有可能是登記國家，也可能會行使課稅權限，認為只要是我國的專利商標，我們是所得的來源地國。但國際稅法裡面，原則上是以債務人的稅籍國來作為判斷標準，也就是是以人而不是以那個權利的這個登記地點來作為判斷標準。

這個地方我們待會休息完之後，我們很快地再跟各位講一下資本的孳息的這幾種類型，判斷的標準。

我們先休息。