# 20231120_01

---
課程：1121所得稅法一
日期：2023/11/20
周次：12
節次：1
---

## 【期中考】

期中考試的，第一題，是關於，所得稅法2條一項規定適用的稅捐主體。適用的稅捐主體，是我國的所謂的境內居住者的個人，相關的條文規定在，第2條第一項以外，那就是在第7條。適用的稅捐主體是境內居住者，或者我們也可以稱之為叫我國的稅籍居民。

關於只就境內來源所得來課稅的立法理由的說明，這個是不是符合量能平的那個的課稅原則？從這個全部所得全部課稅原則來看，並不符合，量能課稅的基本原則底下的一個子原則，也就是全部所得課稅原則。這個也是，我們在所得稅法的這個條款規定上面來講，比較不符合量能課稅原則之處。

當然，我們在民國95年，在2006年的時候，我們訂了一個所得基本稅額條例的規定，算是在一定程度上將全部所得的部分啊，就是境外來源所得，我們透過用所得基本稅額條例的方式去補充，去做課稅。因此，在這個地方，以所得稅法跟所得基本稅額條例整體來看的話，確實在這個限度範圍內，裡面也就境外來源所得去做課稅。但即使是如此，我們並沒有符合這個量能課稅原則裡面，特別是境內境外來源所得應該要同等對待的，基本精神，也就是平等課稅原則的精神，去平等地計算稅負。以所得稅法跟所得基本稅額條例這樣的一個這個課稅的模式來看，我們還是沒有符合量能課稅原則。

實務上的考量，認為有幾個理由，關於境外來源所得不易控制，關於工業化國家的稅率比我國高，所以課稅也難以增加稅收。有沒有增加稅收並不是在這裡面，立法者自己去考慮的，也就是說，簡單來講，不是稅捐增收入增加，所以就可以，也不是稅捐收入收不到就不可以。毋寧應該考慮的是稅捐負擔的公平性的問題。也就是說，作為我國的稅籍居民，理論上應該要去就境內境外來源所得，都依照法律的規定，來去做稅捐上的申報。

所以，這個制度，在全部所得課稅原則底下，法律上就應該要有相同的規定，讓納稅人去做稅捐上的申報。因此，對所得來源不易控制，以及難以增加我國稅收，這個並不是一個正確的一個考量。這個全然基於我國的稅捐稽徵程序上面是否能控制，以及稅收是否能增加作為考慮，並不是，在稅捐立法上面的完全正當的考量。在稅捐立法上面來講，仍然必須要以這個為前提，來做稅捐立法上的課稅。

順帶透過這個方式跟各位說到，對我國來源所得不易控制，這一件事情，其實在目前的實務上面，是透過稅捐資訊交換的方式去獲得，境外來源所得的相關資訊。然後對所謂的工業化國家的往來，所以我們並沒有課稅的實益，這一句話也不成立。作為國際上的往來，並不是只有工業化國家而已，那它其實也有相對稅率，相對我國來講是比較低的稅率的國家，那當然在這種情況底下，不是以所謂的稅收增加考量來作為他，這個評斷上的依據，這個是對第一題，提到全部所得課稅原則。即使是有考慮到所得基本稅額條例，我們並沒有符合稅捐負擔的平等原則。

第二題的話則是稅捐稽徵機關依照檢舉的資料查得，某甲在同一個年度內買了10筆的預售房屋，預售房屋的權利的證明，那么這位某甲在這一段時間內把這10筆的紅單轉讓獲利。

第一小題的問題，稅捐機關查得這個轉帳紅單的獲利之後，除命補繳稅款以外，又給予應繳稅款而未繳稅款的裁罰，這部分是不是構成了一行為二次處罰？ 

本題的關鍵在，補稅並不是裁罰。補稅是一個不利益。裁罰是一個制裁性的行政處分。所以補稅同時並裁罰，並不構成所謂法治國原則底下的一行為二次處罰，這個對非稅捐法律人是蠻普遍被誤解的一個道理，認為補稅就是一種裁罰。因此第二題的第一小題，稅捐稽徵機關對納稅人未申報營利所得所做的補稅跟裁罰的處分，並不構成法治國原則違反的一行為二次處罰。補稅是根據稅捐負擔能力所做出來的計算，換言之，有所得，理論上就應該要繳納申報，來負擔應負的稅捐。因此補稅是量能課稅原則的維護，是一種確實是對納稅人構成一個不利益的金錢給付的負擔義務。裁罰則是屬於對過去行為的非難，也就是你應申報未申報，應做誠實的申報而未做申報。因此第二題的第一小題不構成一行為的二次處罰。


第二題提到甲主張紅單買賣，那麼這裡面特別涉及到土地的部分，是不課徵土地所得稅。這個是非常常見的一種抗辯的方式，也就是納稅人主張，根據我國的所得稅法的規定，所得稅法第4條第一項第十六款的規定，對於土地，免納所得稅的所得，從而他是不用申報的，因此我沒有申報，本來就很正常。


本件個案，其實是預售屋的買賣。換言之，在這裡面至少就預售屋這個部分，他本身是一個權利的買賣行為，並不是一個所得稅法第4條第一項第十六款所講的土地，即使是土地，他是一個土地移轉登記請求權。所以第二小題的題目，他其實在實務上，是一種權利讓與。就算是以不動產的土地為標的，仍然是權利讓與。這個是第二小題裡面，對於實務上，當事人往往主張土地出售本身不課徵所得稅。沒有錯，所得稅法4條一項十六款，土地的出售不課徵所得稅，但性質並不是免納所得稅的稅捐優惠。其實是所得稅，跟土地增值稅，避免重複課稅，因此不是一個稅捐優惠的規定。話說回頭，這個地方並沒有土地的移轉的問題。預售屋是一個還沒有建築完成的房屋，所以它是一個權利的讓與。實務上對以往這種紅單的讓與，基本上就是以權利讓與為由來做稅捐上的核課。從而構成了，一個權利讓與的財產交易的所得。這個是對第二題的第二小題，就是關於對此沒有所得稅的申報義務，他主張的是土地的不動產的這個轉售。這裡面只有土地，才有可能有這樣一個抗辯主張成立的適用。但，不管是預售屋的部分或者是土地的部分，其實都不構成土地移轉不課徵所得稅的適用。至於土地移轉不課徵所得稅，並不是稅捐優惠，其實是分離課稅。

本題這個地方，無論如何，是一個這一個權利得讓與的概念。

因此第二題的第三小題，這個是在，房地合一稅沒出現之前，在我們實務上，對這一類的房屋，如果假設跟這個建設公司買了既成屋的買賣的話，那這個部分會不會影響到關於當事人的所得類型的判斷？第二題的第三小題裡面。特別是關於房屋的買賣這個部分，他到底是用財產交易所得，還是是營利所得？

在房屋財產交易買賣裡面，一次性的交易行為，會構成的房屋財產交易所得。但是在一段時間內的密集連續的交易行為，會讓這個行為變成是一個營利事業的營業上的行為。簡單來講，就是透過整體觀察綜合評價的方式，一個人在單一的一個年度內買賣超過10筆以上的，就算是既成房屋，不會再是財產交易所得，而是一個經常性繼續性的參與市場交易行為，從而是一個營利所得的態樣，也就是第一類的營利所得。

我們以往在紅單交易裡面基本上也是同樣的看法。買賣紅單本來就是一個權利讓與，本身是一個財產上的交易行為，但你如果在一段期間內不斷地去做買賣，那這個就會構成了所謂的營利所得，也就是從第七類的那個財產交易所得會變成的是第一類的營利所得的概念。也因此，這一類的行為以往在實務上面來講，是構成第一類，營利所得，以營利事業的方式去做課稅。

因此第二題的第三小題，一方面涉及到關於稅捐客體的類型判斷，當然也會因此連動影響到對稅捐主體的判斷，也就是這個人，會變成從個人的方式，變成是一個營利事業，這個是在實務上面，在我們房地合一稅沒有出現之前，我們在所得稅的課稅的方式。反覆不斷買賣交易行為，構成了繼續性，正因為它持續性地繼續性地參與市場交易的行為，讓它變成是一個營利所得的態樣。這是在第二題的第三小題。

在德國實務上有一個看法啊，叫做五年三個客體界線，但不寫到這個沒有什麼關係，因為老師只是借這個案例跟各位去說，對於買賣的標的物本質上是做整體觀察綜合評價，要看那個標的物本身，是不是原則上你要以之經營作為一個營利事業的營利目的。如果賣三雙襪子，不會構成一個所謂的繼續不斷的營利行為，因為本身襪子的單價並不高。但是房子的單價是比較高的，也就是說，在這個地方，德國的實務上發展出對一個人，有沒有構成營利行為的判斷，是跨年度去觀察一個行為人在任何一段5年內，只要賣三棟房子以上，第四棟開始，就會被認為他是一個營利事業。這個叫五年三個客體界線。但這個就是，整體觀察綜合評價的意思。即使在一個年度內賣三雙襪子，不會讓你變營利事業，因為襪子單價低。但賣三棟房子就會讓你變成營利事業。也就是你一年內賣一次，兩年內第二次再賣，三年內第三次賣，第四年開始，如果假設你又再賣了第四棟房子，在德國實務上就會構成了營利事業。換言之，本來是房屋財產交易所得，會變成是營利事業的營利所得，改以營利事業所得來計算課稅。因為正常來講，不會有人一天到晚都在用房屋來作為他的一個買賣交易的行為。這樣也是一個對一個社會上的一個實際經驗觀察，確實不是形諸於法律條文裡面的一個判斷標準，是由司法實務所發展出來的。

那臺灣在這個地方早期實務上一直都沒有很明確的標準，甚至，實務上流行一個叫做一年六個客體，也就是當你一年內只要不賣超過六戶就被認為不是營利事業，不課徵營業稅，因為房屋是要課營業稅的喔，所以就不課徵營業稅，你就不會課徵營利事業所得稅。那這個一年六戶的界線，即使是以本件這個地方來講，他也是一年賣超過十戶以上。所以啊，這個在我們的實務上面來講，也會認為是一個營利事業，那會同時該當了營業稅的申報繳納義務，也會有營利事業所得稅的申報繳納義務。簡單來講就是一個行為人會因為他的市場參與行為，他對一個客體的反覆繼續性的參與，讓他從個人的性質，而轉變成是一個以繼續性、經常性地參與市場的經濟活動的態樣，而變成是一個營利事業的性質。這也是我們在這裡面營利事業跟個人主體之間在稅捐主體上的差別。

從而第二題的第三小題涉及到客體的判斷，那也涉及到主體的判斷。以德國跟臺灣的實務上，基本上都認為他是一個營利所得。

不過當然很多個個案事件裡面，也有當事人會主張認為說你繼續性的判斷標準不明確。對，沒有錯。

正是因為整體觀察綜合評價，所以這個確實會存在著不確定性。就算是以五年三個客體為界線，那是不是買賣三棟房子以內就不構成營利事業，第四棟就突然變成營利事業？對沒有錯，確實在實務上會有產生這樣一個，量變變質變的道理。你不斷地這樣子去做，從客觀上他才有辦法去評價，你是一個營利事業，持續性繼續性地去參與市場上的活動。

即使構成了，個人，也會從財產交易所得第七類的所得，變成是第一類的所得的類型。這個是實務案例。老師出的這個題目，其實是從實務案例把它變換出來的，那這個是在房地合一稅沒有出來之前。房地合一稅1.0版出來，民國105年之後，預售屋的買賣就已經被列入房地合一稅課稅的範圍，所以目前的法制，房地合一稅裡面，原則上會把預售屋的買賣以他的轉售價差減掉土地增值稅的稅基，然後其餘剩餘的所得額，就改課房地合一稅。

所以本件個案發生在100年度，那時候並沒有房地合一稅。在那個年代，只要是紅單的權利讓與的行為，那以權利讓你的這個法律規範來看的話，本身是一個財產交易所得。一次讓與是財產交易所得，兩次讓與，是財產交易所得，到達一定的程度上面，一年內的十次讓與，比較清楚而明確地，會被認為是一個營利所得的態樣。


我個人也認為這個看法是正確的，雖然確實存在著不確定性，就是對於繼續性跟一次性的買賣交易行為的區分。

其實，買賣交易的行為跟一時貿易盈餘跟經常性的營利所得，本來就具有很高的不確定性，就是那個界線是不太清楚的。這也正是在訴訟實務上或稽徵實務上面，各位作為法律者常常會面臨到我體個案裡面，必須要去做綜合考量，依據客體、市場上的單價以及交易的實務的現況的一般情形來做判斷。

我剛剛舉的例子，三雙襪子不會構成一個營利事業，因為襪子單價不高，只是一年賣三雙襪子，不太可能以之為業。所以你賣三雙襪子會是一時性的財產交易所得，比較是屬於偏向財產交易的盈餘。但一年內賣三棟房子，第四棟出來的時候，就有可能就會變成了，營利所得的態樣。


以上是我們在上個禮拜舉行的期中考的部分。先檢討一下這個問題的方向跟答案，大致上給各位做參考。也歡迎各位同學，如果你自己寫題目的時候，你有不太一樣的想法，也可以。

老師改考卷，我總是要有一個特定的方向來作為一個評分評價的標準。如果各位同學在個別的答題裡面啊，你覺得你自己是很有理由跟說服力的，也可以來個別表示你的意見。沒有一定非得要照剛剛老師所說的這樣的一個做法。不過你要有具有充分的說服力。有沒有說服力，確實是以老師主觀的心證為基準。你可以來表示，你有什麼樣的看法不同的意見，老師會聽聽看你的說法，是不是可以成立。答案並沒有一定要非得照老師的。因為訴訟就是這樣。我也許我在這次的看法裡面比較偏向國稅局或是稽徵實務司法實務的看法，但你也可能採取不太一樣的看法。其實改考卷只是用一個答案去做衡量標準，那個答案未必是真的是標準答案。因為某種程度上，確實是會有開放性。因為這個開放性，所以老師並沒有一定非得要以我個人的答案作為標準。如果你不能說服我也沒有關係，那只是以老師的標準，你沒有達到這個標準而已。但歡迎各位同學未來在稅捐的訴訟實務上可以提出你的觀點。你只要能說服法官，你個案還是可能會贏。法律確實存在著有價值判斷，因此會有一些結果的開放性。

歡迎各位同學，也希望各位同學能夠，不是因為老師講的，所以你就覺得只有這種思考的方式，也希望你有不同的思考的結果和方式出來。這個是法律在價值判斷底下的結果上的開放性。

到這裡有問題嗎？沒有上課上提出問題也沒有關係，你下課再來也可以，因為我們今天有進度。假設各位沒有問題的話，我們接下來就繼續上課。


## 【所得稅法規範結構回顧】

我們在考試之前跟各位提到的，我們稍微簡單地回顧一下，我們整個法條的規範結構。

第2條的規定，區分了稅籍居民跟非稅籍居民。第2條的第一項是稅籍居民，也就是境內居住者，原則上只就中華民國來源所得課稅。在中華民國來源所得課稅底下，根據兩岸人民關係條例，戶籍設在臺灣的稅籍居民，原則上是就臺灣跟大陸地區來源，所得全部都課中華民國來源所得稅，都是所得稅的所得。第2條第二項的非稅籍居民，也就是非境內居住者，這個非境內居住者，原則上也是就中華民國來源所得課稅，但他的課稅申報的方式，或者是繳納稅款的方式，我們今天會跟各位去講。因為我們的繳納稅款方式有兩種，一種叫結算申報。2條第一項的稅籍居民原則上用結算申報程序。2條第二項的非稅籍居民，則是用「就源扣繳程序」。

因此，我們回顧一下我們前面講的稅捐主體，稅籍居民跟非稅籍居民。我們的法律規定，原則上全部都是就中華民國來源所得課稅，當然這個中華民國來源所得的中華民國的概念，根據兩岸人民關係條例啊，是指臺灣跟大陸地區，只要你是戶籍設在臺灣地區，那原則上就是臺灣大陸全部都叫中華民國來源所得。那至於港澳跟境外（真正的境外：美、日）這個是不課所得稅法上或所得，是改課所得基本稅額條例的個人所得基本稅額。

我們的所得稅法，原則上只就中華民國來源所得課稅，所以他的區分實益主要是在稽徵程序上面。因為所得稅法裡面只就中華民國來源所得課稅，稅籍居民跟非稅籍居民都是只就中華民國來源所得課稅。所以實體法上，沒有什麼差別。差別主要是差在稽徵程序上面。因為我們的所得稅法的第2條第一項啊，一樣是就中華民國來源所得課稅。但是他是按照所得稅法規定的結算申報程序，課徵綜合所得稅，這個是第2條第一項的規定。

第2條第二項，非稅籍居民除本法另有規定外，其應納稅額分別就來源扣繳。所以我們會跟各位去談關於結算申報跟就源扣繳程序。

第2條第一項的稅捐主體的區別實益，如果以德國跟日本為例，或者是以美國為例，只要是稅籍居民，原則上是全球來源所得課稅，也就是都是課同樣一種稅法上的所得。那我們的所得稅法比較特殊，我們同樣都是只就中華民國來源所得課稅，那差別是差在稽徵程序上面。第2條第一項的稅籍居民，「依本法規定」，沒有寫什麼叫依本法規定。解釋上是依本法第71條的結算申報規定來課徵綜合所得稅。那么，第2條第二項的規定則是除本法另有規定以外，分別就其應納稅額，就來源扣繳，也就是依照就源扣繳程序來做稅捐的稽徵。所以我們的稅捐主體，主要的區別實益，被認為不在稅捐的實體法上，而是在稽徵程序上面，以所得稅法的規定來看。

以稅捐主體這個脈絡，繼續看稅捐客體的規定。在我們的現行所得稅法裡面對「所得」是沒有定義的。我們是透過所得稅法的第14條的十類的所得去定義出，「應課所得稅的所得」的概念。所以我們有十種類型的所得。至於「其他所得」的類型，這個條文規定就是一個涵蓋性的綜合性的，一個網羅性的構成要件的規定，原則上你只要可以分類到前面這九類的話，就不會進入其他所得的第十類的所得。

那么，在第14條的規定裡面，除了第14條規定的應課稅所得，我們還有第4條的免納所得稅的所得的概念。第4條，4-1跟4-2，這一些概念上，是應稅所得，可是是免納所得稅的所得。換言之，是提供分離課稅的所得，不然就是屬於稅捐優惠的所得。也就是說，部分的所得確實是被免除掉的，比如說4-1、4-2的證券交易、期貨交易的所得，被認為並不構成所得稅的所得，而是另外以期交證交的交易稅來替代，就是用交易稅來替代所得稅的課稅。當然這個部分，老師個人是有很強烈的反對的意見。這個地方，依照目前實務的看法，4-1跟4-2是以其證交期交替代證所期所。老師個人看法是交易稅不能替代所得稅，雖然立法者自己這樣講。以立法者的邏輯來講，他認為這個就是一個分離課稅，因為他就是用證交期交來替代了證所跟期所，這個是4-1、4-2。


4-3條的規定。公益信託的免稅要件的規定信託課稅的部分，我們會留待到所得稅法三，關於遺產贈與稅的時候，我們再來去進一步去談。

信託課稅，原則上信託的財產移動並不是所得的概念，是一個設定信託行為的財產上移動，所以這個地方4-3條的條文規定他本質上也並不是一個市場經濟活動所獲得的所得。

4-4跟4-5條的規定，是房地合一稅，我們留待到所得稅法四的時候，再跟各位去談。他當然是所得，但問題就是我們有第4條的第一項，第十六款的免納所得稅的所得，所以他是第4條的第一項十六款之外，我們有另外4-4跟4-5，又是4條第一項十六款的例外。

從民國105年開始，2016年開始，我們又在4條一項十六款之外，另外加徵了房地合一稅。

所以我們這個地方的法條結構是，所得稅對於不動產土地的移轉，免納所得稅，改課土地增值稅的稅負，然後我們在105年開始，又再把這部分的稅負又再把它拉回來，改課房地合一稅。這個地方有立法上的價值的轉變。

根據第4條第一項第十六款規定，免納所得稅所得。但同時間我們考慮到有土地增值稅的課稅，所以它是一個分離課稅的概念，但從民國105年開始，我們把這部分的分離課稅的土地增值稅的這個部分，把不動產交易裡面的所有的剩餘所得，又再以4-4、4-5條的規定，再把它拉回來去課徵房地合一稅。所以這裡面有一個立法者的價值轉變。


第5條的第一項的規定，是免稅額的物價指數調整規定，理論上應該是放到17條，因為17條才是免稅額規定的所在。我們的立法者的立法技術，是把這個部分拉到前面來做規定。5條一項本應該要放到跟17條第一項第一款講免稅額規定的地方。他跟你講，這個地方要按照物價指數去做調整。

這個地方我跟各位簡單說明一下，免稅額不是只按照物價指數調整。根據生存權保障的憲法保障的這樣一個要求，立法者應該要與時俱進地調整免稅額，讓他可以符合當代維繫物理生存的最低需求。因為我們的免稅額立法上是6萬，雖然每一年每一年調整，基底太低。如果基底太低，每年物價指數的調整基本上就不太容易去反映出納稅人維繫物理生存需求，也就是衣食溫飽這個部分的物理生存需求。

立法者透過生存權保障以及我們在105年所增訂的納稅者權利保護法的規定，基本生活費用不課稅原則，其實也是在反映維繫物理生存需求跟社會生存需求的這個全部額度。這個額度應該回過頭來，變成是第5條第一項，在法律解釋適用上的一個重要的，立法者的義務，應該要對於數額做與時俱進的調整。這個是5條第一項的規定。


5條的第二項規定是綜所稅稅率的規定。從體系上，他應該是在應稅所得的計算之後，就是，稅基之後，是稅率規定，所以法條規範位置會是在17條之後。稅率的位置應該是在17條之後。

稅率放到前面，只是告訴你一件事情，我們的立法者基本上都是財稅背景，不是法律背景。就這麼簡單。

法條規範的位置，其實按構成要件去區別，是主體、客體、稅基、稅率，稅基乘稅率得到稅額，構成要件這樣一字排開來，這個才是法律邏輯的思考。

那因為我們的財稅背景主導了稅捐立法，所以他們認為稅率最重要。你去看我們的所有的稅法規定，稅率都放在稅基之前。充分表彰出我們的稅法，從財政部體系一直到送進立法院裡面，基本上都是財稅思考，他們認為稅率最重要。

但從法律觀點來講，稅基比稅率更重要。因為稅基不對，稅率乘稅基，只會得到更不對的稅額，尤其稅率是累進稅率，會扭曲稅捐負擔的分配。

第5條第二項的位置，這個是一個累進稅率，我們稱之為叫超額累進，我們是五個級距的超額累進稅率的設計。五個級距分別是5%、12%、20%、30%跟40%。


我們在民國97年之前，稅率級距是6%、13%、21%、30%、40%。早期的我們綜所稅的累進稅率，更體現出所得越高稅率越高的概念。各級距之間的差異，分別是7%、8%、9%、10%。

我們綜合所得稅的最高邊際稅率是40%，共是五個級距。我們這一種叫階梯式的超額累進稅率。

德國的累進稅率，邊際稅率是線性的，比如說你第一個級距是6%，那第二個級距是6.1%，第二個級距是6.2%，就一直不斷地疊上去。平均來看會形成一種弧形的平均稅率。簡單來講就是你賺100塊跟賺101塊，第101塊那一塊的稅負比前面的100塊稍微要更重一點，充分體現出累進稅率，是一種社會國底下的財富重分配思想。

如果比例稅率的稅制會是這樣？比例稅率，比如說20%，這樣也是量能課稅原則，因為你的所得越高，基本上你的稅負比例雖然一樣，但數額會比較高。即使是固定比例稅率，也是符合最佳負擔平等原則的量能課稅原則。


超額纍進稅率，我們的是階梯狀的，或是德國的線性的邊際稅率，是來自於社會國原則的財富重分配思想，實現量能課稅的平等原則。


我們採用的是超額累進稅率，因為各國，美國，在剛開始在做所得稅課稅的時候，就是以這種超額累進的方式。所以如果你調成單一比例的稅率，會對誰有利？對誰不利？對低所得的人不利，對高所得的有利。


我們現行的超額累進稅率，級距分別是5%、12%、20%、30%跟40%。假設我在稅制委員會裡面，或是在立法院，我主張，認為，我們這樣不好，我們來改平等課稅原則，我們要單一的稅率，一律都用20%或28%。

我們的股利所得，現在改28%，那個28%就是一個比例稅率。好，對誰有利？對賺高所得的有利，對吧？因為如果綜合所得稅，他本來最高是到40%呢。

對誰不利？你是低所得者，本來只需要繳納5%，你用28%，當然就不利啊。所以他告訴你，不要去投資股票，如果你沒那個能力、沒那個資格的話，你不要去投資股票。人家投資股票是節稅啊，他們繳40%人，有股利所得用28%課稅，那這樣就對他有利。但是如果你是繳5%，你用這種，變28%，那就對你比較不利。這樣清楚嗎？

我們稅制改革方向，是對有錢人有利。我們不用講太多意識形態，就光這件事情，請問有沒有去立法院質詢，為什麼是這樣啊？

我們股利所得課稅是二擇一啊，要麼28%，要麼一個家戶所得課8萬元的可扣抵稅額，所以你就一定要選擇8萬元的可扣抵稅額，你說不然的話，你本來是5%甚至20%的人，你去投資股票，你去買臺積電，臺積電發給你股利，股利所得，結果你反而被高課。

所以可以選擇，用全部的所得用可扣抵稅額一戶8萬塊錢的方式，意思是告訴你說不要賺太多股利所得。你賺太多的話扣不掉。你會被加重稅負。

這是一個我們稅制裡面的反財富分配現象。

所以回過頭來就是告訴各位一件事情，研究稅法絕對對各位腦筋清楚有很大的幫助。你才知道這個社會的財富分配的方向，究竟是從貧到富，還是富到貧。你可以大致上去看觀察這整個，我們的社會的財富分配，究竟在稅制裡面是如何地被扭曲分配。就這樣一件事。信不信由你，因為這個本來就是我們現在目前的情況。28%的股利所得稅率基本上是對高所得的人是有利的。


好，如果你今天是拿債券，10%。去投資債券的人，越高所得人投資債券去取得債券的利息所得，他更有利。但如果你只是適用5%邊際稅率，債券這個地方二選一都沒有，就是10%。對誰有利？高所得的人。

越高所得，適用40%的邊際稅率的人有利，因為他節省了邊際稅率30%。

但對越低所得，適用5%邊際稅率的人，反而不利。

這是我們在稅基稅率的關係上面的，反向的財富重分配的狀態。

其實本來累進稅率的設計，應該是，多賺錢越多的他要繳納越高比例的稅率，這是財富重分配，本來在社會國原則底下，想要的那個圖像。不過現實上並不是全然是如此。我們第5條第二項的規定，我們就跟各位談到這裡。

第5條第三項，基本上就是反映第5條第二項，課稅級距的金額，要固定調整。那這一個部分，我要跟各位說一下，立法形成空間比較大。不像第5條第一項免稅額是反映物理生存需求，所以立法者不僅沒有太大的立法形成空間，立法者有依據當代社會維繫物理生存需求的調整的行為上的誡命。他有那個誡命上的義務。

相對5條一項的生存權保障規定，5條二項跟第三項同樣都是在調整稅率的形成。對於級距跟邊際稅率，立法者享有比較高度的立法形成空間。也就是根據國家的財政上的需要，立法者享有比較高度立法形成空間。只有對免稅額跟扣除額所反映出來的那個數額，是生存權保障的範圍，立法者的立法形成空間，相對應該要比較少。

第四項的規定則是關於消費者物價指數的規定，每一年，你的級距、你的免稅額，你的扣除額，每一年都是財政部在一定時間以前公布。像這第四項規定，那個就是技術性作業性規定。什麼時間公布，財政部自己的人，內部作業規則規定公布就可以，基本上那個不需要在所得稅法裡面公布。

第5條第五項，這個是營利事業所得稅的稅率規定，我們在綜所稅裡面我們就按下不表啊。

5-1條是關於扣除額跟特別扣除額，也是按物價指數調整的規定，像這個就直接放到那個扣除額，那個地方一併去做規定。


第6條，貨幣的規定，是以新臺幣為單位。不然是要什麼？金圓券嗎？不用新臺幣你要用什麼作爲單位啊？

第6-1條的捐贈規定，這個是放到17條的那個關於捐贈那個地方去做合併的規定就可以。

所以我們大致上把前面的那個總則的幾個比較條文性的規定跟各位說到這裡。我們先休息一下，待會我們繼續回顧，把所有綜所稅的條文，實體法的部分，我們全部都拉出來，全部完整的回顧一次。

我們今天要進入到關於申報程序裡面的結算申報，跟家庭的成員的合併申報程序。所以我們再下一次才會去提到就源扣繳程序。

我們先休息一下。