# 20231120_02

---
課程：1121所得稅法一
日期：2023/11/20
周次：12
節次：2
---


## 【繼續條文梳理】

### 【第一章，第7條起】

所得稅法第7條，第一項是關於個人自然人。第7條的第一項的第二句的規定，連結的就是第7條第二項的規定。這個就是稅籍居民的規定，也就是境內居住者個人的規定，也是剛剛我講的期中考試第一題的第一小題。就是指中華民國境內有住所，並經常居住在中華民國境內；中華民國境內無住所，那在歷年當中停留在中華民國境內，居留停留超過183天。但我們實務上面其實還有一個「境內居住者的認定標準」，有設戶籍，你只要停留超過31天以上，那這個時候就是屬於境內居住者。有設戶籍，停留1到30天之間的話，經濟生活重心在中華民國境內，則也構成稅籍居民。

第7條第三項：「本法稱非中華民國境內居住之個人，係指前項規定以外之個人。」

這一句話，我個人認為是廢話，因為，他不是稅籍居民，反面就是非稅籍居民，這還要規定嗎？沒有太大的用意。

第7條第四項跟第五項的規定，我們其實在講到納稅義務人跟扣繳義務人，尤其在就源扣繳程序的時候，是有意義的。我們先暫且放下，到就源扣繳程序的時候再跟各位去談。

接下來第8條的規定，我們跟各位花了很長一段時間跟各位講。

第2條第一項跟第2條第二項都是以中華民國來源來作為區別，凡是中華民國來源所得的，稅籍居民的話，就是要課所得稅的所得。非稅籍居民，也是一樣，取得中華民國來源所得，那這個時候，就會要依就源扣繳程序去做扣繳。

相反的，非中華民國來源所得，理論上就不課我們的所得稅的所得。理論上，非稅籍居民如果取得非中華民國來源所得，從國際稅法的角度來看，我們跟這一個課稅事件是沒有任何關聯性的，所以我們也當然不可能對他去做課稅。這個是第8條的，中華民國來源所得判斷的依據。

採稅籍居民就全球來源所得課稅，最主要的意義是在判斷，這個是不是該外國的可扣抵稅額，因為非中華民國來源所得，相反的是外國的可扣抵稅額。是根據這個條款規定，去判斷是不是中華民國來源所得，再來去決定那個是不是可以適用外國的稅額扣抵。

我們的8條的十一款規定，相對於我們的第14條規定，看起來就是加了一個第九款規定，第九款規定裡面是營利事業裡面比較會用得著的，關於經營的地的，所得來源地的判斷標準的規定。也因此，這第8條的規定在實務上幾乎不太容易發揮作用，因為基本上他只有將第14條的所得的分類，然後加一個「中華民國來源所得」。

立法上有這樣的問題，因此我們實務上變成了按另外一個長達5頁以上的「所得稅法第八條規定中華民國來源所得認定原則」，來做操作。

因此實務上面僅觀看第8條的規定，其實不太容易去看得出來中華民國來源所得的判斷標準。法律上面，這個第8條的規定的功能，因此基本上全面被架空。

我們在講課的時候，跟各位去提到,第8條的規定，其實要定義什麼叫中華民國。當然不是憲法上那個定義，而是你現在課稅權限所及，屬地主義底下所及的，就是臺澎金馬，這個是我們的領土的範圍。

因此在這個地方，所謂的中華民國，基本上是指中華民國現在的臺澎金馬地區的領土，以及領海跟領空，這個才是「中華民國來源所得」中的「中華民國」。就是我國現在現行，在我們的這個統治高權有效行使範圍內的臺澎金馬這些領土領空跟領海的範圍。領海，原則上是以國際法裡面所提到的以我們的陸地往外推的三海浬。因為我們剛好臺灣周邊，沒有大陸棚的那個連結，基本上就不會再往外推。

第二項的規定是關於我國的這個境外被視為是境內領土的這個部分基本上包括了，我國船籍的船舶跟航空器以及駐外的使領館。這一些駐外使領館，這也是在第8條第二項，從國際法的角度裡面，被認為他是屬於中華民國的境內的領土。相反的，也有在中華民國境內，也就是第一項裡面所講的臺澎金馬的領土範圍內，但是是依照國際法，被認為是一個境外的領土。特別是各外國在在臺灣所設立的這些使領館。那當然因為我們存在著外交關係上的困境，我們並沒有辦法正式締結的一個所謂的維也納公約裡面，以國與國之間的身份，所締結的外交的條約。從而因此在這個地方也是在第二項裡面去做相關聯的，關於中華民國這種視為境外跟視為境內的領土的規制。

這樣才能夠去清楚地去呈現出來所謂中華民國來源，中華民國的意義。


第三項的規定，我們也有簡單談過。國際稅法裡面去分配，是不是我國來源所得，有4個原則。

第一個叫屬地的所在地原則，凡是跟不動產有關的，包括不動產的租金所得，包括不動產的財產交易所得，包括跟不動產有密切關聯性，屬於大自然界的第一次產出的農林漁牧礦，都是跟你的管轄的領域範圍有密切關聯。這些都是屬於中華民國來源所得的這個所在地原則。


這是第一個。判斷標準

第二個是經營地標準，經營地標準，特別是在獨立的勞務的付出，以及營利事業，因為都放在所得稅法。營利事業的經營的標準，這個也是。獨立勞務的勞務的付出，像執行業務者，就是屬於獨立勞務的付出的類型，他的經營地點。以及如果營利事業也放在所得稅法裡面的話，那就是營利事業的經營地。這個地方的經營地的標準，以他實際上的實際營運地點作為一個判斷標準，也就是我們在實務上面講的，所謂的經營的營運的行為，是否在前面所提到的中華民國的境內的領土領空和領海的範圍內去作為一個判斷標準，這是經營地為標準。

第三個，就除了所在地，除了經營地以外，債務的部分。尤其是債務人的所在地、債務人的稅籍地，也會是一個非常重要的判斷上的標準。特別是利息。因爲金錢的給付本身，是在任何地方都可以被給付，特別是在以通貨為標的利息給付裡面，以債務人的所在地，或者我們講債務人的稅籍國，來做為所得來源地國的一個判斷的標準。這個是在實務上面也經常被採用的判斷中華民國來源所得的標準。因此只要是利息的給付者是我國的稅籍居民，這個時候就有可能是作為中華民國來源所得。

第四個，就回到了非獨立性勞務。因為非獨立勞務的被指示而去做相關的勞務的履行，在判斷上面來講，是以現實上的履行地點來做為判斷上的標準。

這四大標準原則上是在應該在我們的所得稅法第8條裡面分別去做相關的規定，然後才會去對應第14條的各項類型的所得來去判斷，比如說是第四類的利息所得，就是根據在這裡面的關於債務人的所在地，來做判斷，這樣才叫中華民國來源所得。

第14條是客體的判斷，第8條是所得實現的的判斷，而兩個是不同的規範的意志，也不應該把它混在一起，應該要去做區別喔。

這裡面，第8條的第三款的規定，在我們的實務上面，關於境內提供勞務之報酬，這個條款規定，在我們實務上，適用的包括獨立非獨立勞務跟營利事業經營勞務，都是適用第8條的第三款規定。營利事業經營的勞務，以及獨立跟非獨立勞務，因為第8條的第三款規定，就提到中華民國境內提供勞務。

所以勞務的提供地點，適用在營利事業提供勞務，適用在獨立勞務提供跟非獨立勞務，也就是薪資所得的勞務。勞務的提供地點是在中華民國境內，那就是用第8條第三款的規定，這個也是透過來源所得認定原則裡面所判斷的標準。

那在這裡面，特別是只要有境內的個人或者是營利事業的協助，或者是輔助去做提供的話，這個會被認為是境內提供勞務的中華民國來源。

依據來源所得認定原則標準，我們在實務操作上，勞務，有境內的個人或是營利事業的協助或輔助的行為，這個報酬都被認為是中華民國來源的所得。因此我們第8條第三款規定，基本上適用的範圍是極大的。


第8條第三款，其實本來應該是只限於非獨立勞務，他本來應該是非獨立勞務，也就是受僱而提供勞務，適用第8點第三款，可是如果你是獨立勞務的話，是經營的話，原則上是第8條第九款規定，因為那個是用經營地點去做判斷，就是在中華民國境內經營工商農林漁牧礦冶，這一種基本上排除掉那個屬地的農林漁牧礦冶以外，基本上就是獨立勞務跟營利事業經營勞務的類型，其實都是第8條第九款規定適用的範圍才對。


我們司法實務的看法比較偏向於，第8條第九款，只要你是獨立跟繼續經營的勞務，特別是營利事業的勞務，是適用第8條第九款規定。老師個人看法是獨立勞務，跟營利事業的勞務基本上都是適用第8條第九款規定，只有非獨立勞務是第8條的第三款規定。但我們稽徵實務的看法是，第8條第三款是適用在獨立、非獨立，以及營利事業經營勞務，因為這是來源所得認定原則的標準所提到的。

那這裡面當然在判斷的區別實益主要就是，只要是涉及到非中華民國來源所得，那就涉及到外國可扣抵稅額的計算的問題。



屬地的所在地原則、經營地、勞務履行地，跟債務人所在地（稅籍），這四大原則，理論上應該在我們的所得來源地的規範上面來講，要清楚地呈現。


第9條的規定，其實是財產交易所得，原則上這個定義條文的規定也應該會放在第14條的第七類，財產交易所得裡面。

財產交易所得，我個人認為它定義並不是很清楚，基本上是一時性的財產交易，而排除屬於一時貿易盈餘跟經常性的營業行為所產生出來的所得。

第9條規定，從而在立法定義上是極為缺漏的，就是說他的條款規定哦，要排除沒有排除。而且要排除掉的標的是屬於第4條到第4-2條所適用的這些客題。財產交易所得，財產，應該排除掉第4條，4-1、4-2裡面所稱的各項客體，比如說土地，土地就不在這裡面。第9條的規定是排除掉繼續性的經常性的交易行為，排除掉客體，包括在4條跟4-1、4-2裡面所提到的這些客體。所以第9條的規定本身有規範上的漏洞。


第10條的規定是營利事業所得稅裡面的「常設機構」規定，這個我們留待所得稅法二的時候，再跟各位去做說明。

第11條的第一項規定，執行業務者的規定，跟第14條的第一項第二類執行業務者的所得範圍對應。

執行業務者，第11條的第一項規定，本身，沒有很清楚地呈現有哪些類型的人，不過我們在上課的時候跟各位去說明了，主要分三大類型。

一個是傳統被認為是四大師的，這一類型，是經由一定的學院的教育，跟經過國家考試及格而取得資格的，執行業務者的。

第二類我們稱之為叫，跟人類的精神創作有關的，智慧財產創作有關的這一類的執行業務者，包括了表演者作曲家、音樂家。

第三個是獨立的技藝，工匠、經紀人，有獨立的技藝。

這三類型的所得，其實本身就是獨立勞務的類型。也因此，第11條的第一項的獨立勞務類型，跟11條的第二項營利事業，會有一定程度上的重疊，因為營利事業包含了經營工商業。所以我們在11條第一項，這裡面這三大類型其實要排斥掉，屬於營利事業以外的。

也就是執行業務者是特殊的營利事業。他是這三種不同類型的營利事業。如果不是執行業務者，原則上就會進入營利事業的獨資合夥，或者是經營工商農林漁牧礦這些事業裡面。

營利事業的提供的服務的內容，是一種網羅性的構成要件。也就是，不是執行業務者，不是農林漁牧礦冶，其他這一些業者，全面進入營利事業所得稅的營利事業所得的概念範圍。

所以我在類型分類的時候，在那個地方有獨立勞務，我把執行業務者放在前面，然後接下來是農林漁牧礦冶。

「冶」，其實不太是，因為「冶」是精煉金屬的意思喔。

農林漁牧礦，這五業，基本上都是大自然界第一次產出。農，農業，播種耕作的收入，大自然的第一次產出，林，一樣。漁，其實包括遠洋養殖都是，也算自然界的產出啊。牧、礦，都是大自然界，跟屬地有關。所以我們剛剛講那個農林漁牧礦是跟屬地有關。


「冶」就不是。「冶」也應該是冶金、鍛鍊鍛造的意思，這個已經是開採之後的第二次提煉，所以他是第二次產出。他是大自然界第一次產出之後的磨練鍛造的行為，因此「冶」不是大自然界的第一次產出。「冶」其實是工商的形態的一種類型。你直接採礦出來的這個是「礦」。但把它鍛鍊鍛造這個是「冶」。

「冶」，也許是一種獨立技藝，執行業務者的獨立技藝，但如果不是執行業務者的話，那原則上它就會變成進入所謂的工商業的營利事業這個類型。

執行業務者、農林漁牧礦，這兩業拉出去，下面有一個兜底的網羅性的構成要件，這個叫做營利事業。你現在法律上面有區別啦，但如果沒有區別，他們都叫做獨立性勞務。


我突然想到，這樣去挖比特幣，這樣算不算？用電這種方式去自己去挖礦，這樣算不算大自然界第一次產出？我要好好想一想，挖比特幣的挖礦，這算不算大自然界第一次產出？不過我們現在的比特幣算虛擬資產，不是通貨，不是代替現金支付的工具。我要再好好想一下。

但無論如何，他會是屬於營利事業的一種形態，營利事業的話，我們在稅捐主體裡面都會開始進入我們所得稅法二裡面所講的，營利事業所得稅課稅的範圍。即使是穿透，基本上還是會先在所得稅法二裡面，我們再來去講營利事業的概念。


第11條的三四五項，都是營利事業所得稅的部分。

第11條的第六項規定，我們的課稅年度是用歷年。我們的財務會計不一定用歷年。像我們學校、政府會計，會計法的會計，是從每一年8月1號到隔一年的7月31號。所以財務會計當然跟稅務會計不一樣，因為稅務會計就是根據第11條第六項規定，我們是用歷年為主。

有些國家的政府會計年度是從4月份開始。像是日本的政府財務會計是從4月開始，所以他們預算他基本上編列是一直編到明年的3月底。

我們學校，我們國立臺灣大學，我們的學年度是從8月1號到隔一年的7月31號。這個都是財務會計裡面所做出來分別

但課稅的年度，期間稅原則，一律都是歷年。這個幾乎在各國都是不變的，所以財跟稅不是等號的關係。課稅一定是要根據財務報表，不管你是政府會計或是財務會計，根據那個會計再做一定的稅務上的調整。根據稅法的規定，我們是用歷年作為基準，所以我們要去對財務會計裡面所稱的盈餘跟虧損，做切割，去做帳外的調整。

帳外調整的概念，意味著原則上，營利事業要做財務帳，要再根據財務帳去做帳外調整，改製作稅務報表給國稅局查核，讓國稅局知道你究竟在這個歷年裡面賺了多少錢。這是營利事業所得稅課稅的根本。稅務會計跟財務會計去個別切割，個別去觀察。當然這兩個有很高的密切的關聯性，我們不可否認，但稅務會計真的跟財務會計不一樣。


### 【第二章條文】

第2章開始。

第13條綜合所得稅，第13條的規定，基本上是課稅的結構的規定，也就是個人之綜合所得稅是就個人綜合所得總額，也就是依第14條規定計算之個人綜合所得總額減除依17條規定之免稅額及扣除額後之綜合所得淨額。

第13條的規定，規範結構上顯現出來我們的應稅所得額的計算。這裡面有一個關鍵字沒寫出來，應稅所得額的計算是就14條規定的綜合所得總額，減除17條規定的免稅額及扣除額，之後的綜合所得淨額，為應稅的所得額，乘上所得稅法第5條第二項所規定的稅率，為應納稅額。

這個法條規範結構，呈現出不完全構成要件的這些要素的規定，就是，沒有把每個構成要件都寫清楚喔。

第14條是，從綜合所得總額，計算綜合所得淨額，裡面的第一個階段程序。我們把它稱之為叫客觀淨值原則的反映。第14條的規定，除了各類所得以外，是客觀凈所得原則的計算規定。

第17條則是客觀淨所得之後的主觀凈所得，也就是主觀淨值原則的反映。這樣各位可以對應出來那個法條規範結構的關係嗎？

第14條裡面，每一個條文規範結構，原則上應該要有一個對應的收入減成本費用，客觀凈所得的概念存在。但是他的對應的方式常常都不是很清楚。比如說第一類，營利所得看不太出來，有收入減成本費用。你看第二類就可以看得出來收入減成本費用。


第二類，執行業務所得的第一段規定：「執行業務所得：凡執行業務者之業務或演技收入，減除業務所房租或折舊、業務上使用器材設備之折舊及修理費，或收取代價提供顧客使用之藥品、材料等之成本、業務上雇用人員之薪資、執行業務之旅費及其他直接必要費用後之餘額為所得額。」


收入，減成本，減必要費用，之後的淨餘額為所得額。各位自己劃起來哦。這叫客觀淨值原則的計算。

第二類的第二段規定，這個是協力義務規定，這其實本來應該是要放到申報程序，協力義務那個地方去一併做規定，但是呢就先放在這裡。我們的所得稅法規定是，外在體系很亂。實體法沒有按構成要件的順序，然後實體法跟程序法就混在一起規定。這個是我們的立法特色，混亂的特色。

第二段的規定是在講執行業務者最低限度要設置日記帳。這是他的協力義務規定。我有跟各位提到過，執行業務者，假如他是採用跟營利事業的方式同樣記帳，要讓他有機會可以改用權責發生制。就是你有比照營利事業同樣標準的方式記帳，可以改用權責發生制。不然你本來只有日記帳，就用收付實現。因為日記帳就是流水帳的意思收多少支多少，跟業務有關的，就只要記載收支就好。不懂會計的沒關係，你就只要記載，業務收多少，業務支出多少。你不會分成本費用，沒關係，因為在這裡面，就是一個現金收付的概念。

那什麼是假的？有收，沒寫進去；不是為了業務支出，你把它寫進去，這個就是假的。這樣各位可以辨識嗎？什麼叫虛偽記載？你因為這個業務你有收入，你沒有寫進去，這個就叫虛偽記載。不是為了這個業務支出，是私人費用支出的，記上去，這個就叫虛偽記載。清楚嗎？

稅法反映出來的一個原理，就是，真的是業務目的的支出，跟真的是業務目的的收入的話，就是記載上去。這樣應該很簡單吧。這個就叫日記帳。

日記帳，不是商業會計法裡面所講的T字帳，資產負債表。在資產負債表裡面，我們同樣一個營業活動，他會同時表現在他的資產負債跟損益費損表裡面去，同時間去對應。這個對一般沒有學會計的人來講，是個困難。但所有的行業的職業的人，如果不是要去對外募集資本的話，只要求一件事情就是計日記帳。你不需要商業會計法，多麼高深的財務會計的概念，你只要一件事情就是乖乖記帳，那當然意味著要把那個真實的交易的內容記載上去，給相關國稅局查核。只是這樣一個稅捐上的稽徵協力義務。

保存憑證，5年，保存帳簿10年。憑證對帳，就這樣而已，這個就是執行業務者的協力義務。

第二類第三段的規定：「執行業務者為執行業務而使用之房屋及器材、設備之折舊，依固定資產耐用年數表之規定。執行業務費用之列支，準用本法有關營利事業所得稅之規定；其帳簿、憑證之查核、收入與費用之認列及其他應遵行事項之辦法，由財政部定之。」

關於列支憑證，由財政部來定之。在我來看，他其實應該是要讓執行業務者，如果比照營利事業來去做相關的商業會計的記帳，那就要容許納稅義務人有選擇權，可以從收付實現換成權責發生制。因為對一部分的執行業務者來講，權責發生更能反映出他真實的這個盈虧的狀態，特別是對有大量設備要求的，像醫生。醫生，有一些設備上的要求。診所，比如說牙醫診所，或者是這個外科的診所，有些特殊的機器設備。

當然啦，因為各種不同的執行業務者有會有一些差異啦，像律師跟會計師，一般來講腦力作業比較多，但也不是說他們不需要一些什麼機器設備。律師，最低限度也是要有個書狀的管理系統啊。這個本來就是看個別的業別的差異。


14條第一項，第二類，執行業務者，第一段是收入減成本費用的客觀凈所得額的規定，第二段是協力義務的規定，第三段是關於授權規定，由財政部來準用相關的營利事業的課稅的規定。



14條第一項，第三類，薪資所得的規定，也應該是客觀凈所得的規定，第一句：「薪資所得之計算，以在職務上或工作上取得之各種薪資收入，減除第十七條第一項第二款第三目之 2 薪資所得特別扣除額後之餘額為所得額，餘額為負數者，以零計算。」


17條第一項第二款第三目之二的薪資所得特別扣除額是，是一個概括扣除額的概念，是一個概括成本費用的概況扣除額的規定，因此這個薪資所得特別扣除額跟本款規定以下的一二三目，構成二擇一的狀態。第二款的規定就是告訴你，薪資所得特別扣除額跟薪資所得列舉扣除額，二擇一。


一二三目是列舉必要費用。薪資所得的特別扣除則是概括成本費用。它是二擇一的狀態。這個是我們的薪資所得特別扣除額跟薪資所得的列舉必要費用扣除額，這兩個條文規範的狀態。

這個條文的規定的狀態，是釋字745好之後，才讓薪資所得者有機會有這個列舉的必要費用啊，但我上次有跟各位講過，因為有3%的額度，所以粗估計算大概你要薪資所得總數超過600萬以上，你才用得到這一種薪資所得的列舉扣除我的額度，達到跟概括扣除額等同的效果。



第三款規定，則是要檢具相關列舉必要費用的單據。

第四款規定，各類收入。第四款規定，是對薪資所得獲得的收入做一個概括性的規定，包括了薪金、俸給、工資、津貼、歲費、獎金、紅利及各種補助費。一次性給的跟繼續性給的全部都算在內了。一次性給的獎金、津貼，或者是繼續性給的薪金、俸給、工資，這個都是屬於薪資所得的範圍。

但書規定：「但為雇主之目的，執行職務而支領之差旅費、日支費及加班費不超過規定標準者，及依第四條規定免稅之項目，不在此限。」

不超過法定標準的出差日支跟加班費，不適用薪資所得的規定。


第五款規定是勞保條例：「依勞工退休金條例規定自願提繳之退休金或年金保險費，合計在每月工資百分之六範圍內，不計入提繳年度薪資收入課稅；年金保險費部分，不適用第十七條有關保險費扣除之規定。」

也就是說，你自己自願提繳的退休金或年金保險費，不計入薪資所得的範圍。那年金保險費的部分也不適用17條有關保險費扣除的規定，依勞工保險提撥的，這個不算是員工的薪資所得。


第四類的利息所得規定，我們現在目前在實務上面幾乎都是用那個10%分離課稅的規定，因為我們的條文規定是短期票券跟各類利息所得，原則上就是用固定比例的方式，10%分離課稅。分離課稅的規定是在14-1。從民國96年，公債、公司債及金融債券之的部分利息所得，分開計算，10%。所以現在買公債就很有利喔。為什麼很有利？因為他也不課證券交易所得，就是直接就是用這個10%。就是我國現在現行，在我們的這個統治高權有效行使範圍內的臺澎金馬這些領土領空跟領海的範圍。領海，原則上是以國際法裡面所提到的以我們的陸地往外推的三海浬。因為我們剛好臺灣周邊，沒有大陸棚的那個連結，基本上就不會再往外推。


我剛剛跟各位比較過，如果你是高所得的人，你是適用邊際稅率40%的，買債券跟買公債都是10%，相對是很有利的，被認為是稅捐節稅規劃的手段。


第五類，租賃。租賃包括不動產跟動產租賃的所得，以及權利金。權利金所得是指非買斷所有權，而是只有單純的使用權的授予，所以這一類的租賃所得跟權利金的所得，各位可以去看一下，在第一款的規定就有客觀凈所得的規定，也就是用全年租賃收入減除必要的費用跟損耗後的餘額。必要費用就是折舊（因為財產會有折舊哦），必要的損耗，以及費用，之後的餘額。這是客觀凈所得。

但第五款規定，請各位特別留意。關於租金收入，如果低於一般租金行情的話，則以一般租金行情為計算租賃收入的標準。


第六類，自力耕作，有收入減成本費用的客觀淨值原則的適用，你看條文規定就可以看得到。


第七類一樣，有客觀凈所得的適用規定。你要把交易時的成交價額，這個就是收入，減除原始取得之成本，以及改良持有期間裡面的一切改良費用，之後的餘額為所得額。這個也是一樣，收入減成本費用后的凈所得，這個是客觀淨值原則的適用。

第八類，競技競賽的中獎，原則上是分離課稅啊。你看第三款的規定。政府舉辦之獎券，像運動彩券，這個都不計入綜合所得總額的範圍。不在這個範圍的是一般由民間企業團體所舉辦的競技競賽。民間企業或者是基金會所辦的活動，才會有併計所得的問題。


第九類，退職所得，是以法定的保險給付範圍內的所得為限。屬於保險給付範圍內的保險金給付養老金，或是退休金，依照工資下去去做計算。


第十類的其他所得，原則上有收入減成本費用的客觀凈所得。

因此第14條的規定就是一個客觀淨值原則的表現。

第14條第二項是實現原則。實現原則，也就是以實現時所取得的這個當地的市價。14條第二項的規定是我們實現原則的規範。


第14條的第三項規定，被稱之為叫變動所得。變動所得，四種類型，以半數所得課稅，半數免稅。

14條的第四項的規定，這個一樣是物價指數的調整，跟前面基本上是一樣的一個意思。其實這個都是只要在前面做一個總體的條文規定就可以。

14-1我們剛剛講過。

14-3是稅捐規避的條文規定。

14-4到14-8，基本上是房地合一稅的條文規定，我們就在所得稅法四再跟各位去談。


## 【條文梳理，小結】

好，我為什麼要講這麼多？因為所得稅法的國考，就是法律條文而已。你好好把法律條文看好，其實有一個規範上邏輯上的結構。

對各位同學來講，綜所說，基本上看所得稅法還可以有大致上的一個方向。

營利事業所得稅就比較不容易是這樣。營利事業所得稅，因為在整個的規範結構上面來講，他的條文規定往往在實務上，被營利事業所得稅查核準則給替代掉。所以在營利事業所得稅，我們的條文解說上面，反而在條文的解釋適用上面來講，看所得稅法的不多，大部分都是看所得稅查核準則。然後只要涉及到關係企業的，是看營利事業所得稅的不合營業常規的移轉訂價查核準則。全面性的查核準則的話，也就是變成是透過法規命令的這一條規定來去做相關的法律適用。所以反而，所得稅在營利事業所得稅裡面，看所得稅法不太容易呈現出稅捐負擔的客觀上的樣貌。

綜所稅還可以。因此也請各位務必熟悉法條的規範結構。我剛剛念到的，基本上就是綜所稅裡面的客觀淨所得。

第15條，我們上一次跟這一次來不及講的，就是合併申報，其實包括了合併所得的計算。所以放到這裡面，他也是客觀淨所得，只是現在是兩個主體。一個是納稅人，一個是配偶，合在一起。所以他有實體法規定。但這個條款規定其實應該是放到結算申報那個地方，因為他是把兩個主體合併申報，所以是一個程序法兼具實體法的規定。他本來是一個結算申報程序的規定，但是因為兩個主體合併計算所得，從而放在第15條的規定。

第16條則是第15條規定的延伸，因為他是同一個家庭申報裡面的納稅人跟配偶，他的營利事業所得的這個營利跟虧損會併計。

第17條，則是關於這個主觀凈所得的規定。所以我們的整個稅捐實體法的規定，理論上到17條規定的時候，是整個課稅構成要件的相關規定。

從17-2，這個之後是另外又出現一個稅捐優惠的規定。

因此我透過這一次的課程，也跟各位再一次去講到，我們的所得稅法的規範體系，相對其他發展比較完整完整成熟的民法跟刑法，我們確實是比較亂。但所得稅法已經是所有的稅法規範條文裡面，比較好一點得了。就是他的條文規範結構上，主體、客體、稅基、稅率的規定，基本上還可以找得出對應的那個條文的關係，而且至少在自己母法規範的層次裡面，大致上可以看得出來。雖然也有例外的，所得稅法第八條規定中華民國來源所得認定原則，或者是稅籍居民的條文規定，其實都還是要去看，財政部所公布的那些解釋函令，才能夠進一步去具體化。但這已經是算相對比較好一點了。


稅法難學的原因也是這樣，因為體系比較紊亂，常常要看解釋行政機關的行政規則，甚至是這一些沒有形諸於文字的行政規則的行政上的慣例。

綜所稅裡面算是相對比較清楚一點，請各位把那個整個規範結構稍微做一下調整，放在自己的腦海裡面。

我們先到這裡。下個禮拜，我們開始去談第71條規定跟第15條的規定，也就是家戶所得課稅制。夫妻之間的是，納稅人跟配偶的合併申報，還有其他的家庭成員，就是納稅人跟其他的受扶養親屬的合併申報。我們統稱叫家戶所得課稅制，或家庭課稅制度，那這個其實是數個主體合在一起的合併申報制。我們在下個禮拜跟各位繼續做這個部分的說明。
