# 20231030_01

---
課程：1121所得稅法一
日期：2023/10/30
周次：09
節次：1
---


## 【所得實現地】


所得的客體，最後一個段落，就是關於所得的實現地。

首先跟各位談一下，探討「所得實現地」的這個問題的實義所在。

首先，所得稅法第2條的規定，只有實現在中華民國來源的所得，才會跟我們的所得稅法產生屬地上的連結。
也就是，只有中華民國來源的所得，我們才能對該所得產生課稅上的權限。

在國際租稅法的領域裡面，對於一個國家或地區作為高權的主體，對於個別的稅捐，或者是我們稱之為叫稅捐財，對個別的經濟活動或者是經濟成果產生課稅權限的正當連結，在國際租稅法的領域裡面有一個所謂的真實連結的標準或原則。

這個真實連結的原則是指說一個國家的課稅主權，可以對系爭的經濟活動，乃至於他的經濟成果去做課稅，要不是是屬於屬人上面有所連結，例如說他是你的稅籍居民的身份，那麼這個時候，國家或者課稅主權區，原則上會對稅籍居民所產生出來的經濟活動跟他的經濟成果享有課稅上的主權。

另外，第二個就是所謂的屬地的連結，也就是這個經濟成果，經濟活動是在你的領土領域範圍內裡面去做去進行的，或者是因此去取得的經濟成果。因此真實的連結原則是一個國際租稅法裡面的一個不成文的原則，但也正因為他是一個不成文的原則，這個是一個以規則為秩序的國際之間相互約束的一個課稅上的原則。這不是一個明文規定，因為國際租稅法裡面從來沒有明文說所謂的真實的連結。但所謂的真實連結，其實也在強調各國課稅主權的行使，不能任意地無限制地行使在，對這個課稅主權國或地區而言，他是沒有屬人或沒有屬地連結的情況。

我們隨便舉一個例子來講。比如說美國總統拜登，他是在美國擔任總統的，或者是任何一個美國人，他跑到日本去工作，那麼不管是屬人或者是屬地，我們國家都跟該項經濟活動或者是該項經濟成果是沒有關聯的。你當然可以說，哦，我可以對美國總統拜登或者是任何一個美國人在美國工作，我們也享有對他的課稅主權。但這一種課稅主權的行使，並不讓你自己是一個主權國家或地區來正當化。任何國家的課稅主權的行使，他必須要有一個屬人或者屬地上的連結，這是基於這樣的一個真實連結原則。

那麼我們的所得稅法，他本身在所得稅法第2條裡面，原則上，不管你是不是我們的境內居住者，我們的第2條的第一項跟第二項都採取屬地連結。簡單而言就是，只有中華民國來源之所得，稅籍居民的人，原則上是按結算申報程序去進行綜合所得稅的報繳程序。非稅籍居民也只有在有中華民國來源所得的時候，他才會課徵我們的綜合所得稅，也許是用就源扣繳程序，而不是用結算申報程序。因為在那個地方，我們在稅捐稽徵程序裡面，對非稅籍居民，在理論上以及法規範上，無法要求非稅籍居民去做每一年結算的申報程序，從而他會用一個比較特殊的稅捐計算程序，通常就是88條，跟第89條所講的就源扣繳程序。

因此我們的所得稅法，不管是不是稅籍居民，我們都採屬地連結。

當然我們在前面的課程裡面有跟各位去講過，其實我們對於稅籍居民的連結是用一個所謂的，如果是中華民國來源所得，是課綜所稅所得，如果不是中華民國來源所得，則改課所得基本稅額條例裡面的，個人所得最低稅負制個人所得基本額。

換言之，這個地方其實我們也有某種程度上的稅籍居民的概念，只是我們並沒有把他放在同一個所得稅裡面的稅基底下適用同一組稅率，我們是把他做區別對待，一個是課綜所稅所得，一個改課所得基本稅額條例裡面的個人所得基本稅額，這樣一個制度而已。


## 【所得來源區分實益】

我們首先第一個去談，為什麼要有關於中華民國來源所得的的判斷，或者這個條文規定的區分的實益爲何。

個人產生的中華民國來源所得，只要你是我們的稅籍居民，原則上你適用的是綜所稅的結算申報程序。

雖然你是我們的稅籍居民，但非取得中華民國來源所得，那則改課所得基本稅額條例的最低稅負制。

非稅籍居民則更是只有在中華民國來源所得的時候，他才會課綜所稅的所得。

我們不會對非稅籍居民去課所得基本稅額條例，因為他本來就根本地沒有任何上的稅籍居民身份上的連結。


那么當然這一個所得來源地的判斷，在營利事業所得稅裡面就扮演更重要關鍵的角色。因為在營利事業所得稅，採取跟個人綜合所得稅不一樣的立法的方式。我們這個學期沒談到營利事業所得稅，不過各位可以去看一下所得稅法第3條的第二項的第一句的規定：「營利事業之總機構在中華民國境內者，應就其中華民國境內外全部營利事業所得，合併課徵營利事業所得稅。」


「營利事業之總機構在中華民國境內者」，我們可以簡單稱之為是「稅籍企業」，或者是「稅籍居民企業」。


當然我這個地方講「稅籍企業」或「稅籍居民企業」，這個只是一個學理上稱呼，因為我們的所得稅法本身並沒有對他做一個固定名詞的稱呼，而是用一個比較繁瑣的「總機構在中華民國境內之營利事業」。每一次你只要去講到這個概念的時候，我們沒有法條長的定義，只是一個學理上一般把他稱之為叫「稅籍企業」或「稅籍居民企業」。

德國則把他稱之為叫「無限制納稅義務人」，無限制納稅人有自然人的無限制納稅義務人，有營利事業的無限制納稅義務人。德國用一個比較統一性的稱呼去稱呼這兩者的概念。而我們的所得稅法本身沒有，我不知道為什麼他不要，我只能說法律條規定就長這個樣子，用一個比較繁瑣的「營利事業之總機構在中華民國境內者」。



所得稅法第3條的第二項的第一句的規定：「營利事業之總機構在中華民國境內者，應就其中華民國境內外全部營利事業所得，合併課徵營利事業所得稅。」

也就是總機構在境內之稅籍居民企業或稅籍企業，就其境內外全部之營利事業所得，也就是當你在營利事業所得稅的課稅裡面，你是我們的稅籍企業的時候，原則上不分境內外來源都是課徵所得稅的所得，也就是營所稅的所得。

那么對營利事業是否就沒有區別境內外的實義呢？因為第3條第二項第一句，是採全球來源所得都要課稅。那麼是否在營利事業屬於稅籍企業的時候就沒有區別「是否屬於中華民國來源所得」的區別實益呢？答案是否定的。

因為不要只看第一句，因為還有第二句。第3條第二項第二句裡面規定：「但其來自中華民國境外之所得，已依所得來源國稅法規定繳納之所得稅，得由納稅義務人提出所得來源國稅務機關發給之同一年度納稅憑證，並取得所在地中華民國使領館或其他經中華民國政府認許機構之簽證後，自其全部營利事業所得結算應納稅額中扣抵。」

很長的一句話，這個也是我們所得稅法立法上的這一種，我個人認為很差勁的一種立法上的技術。因為這一段話很長。當然了，德國所得稅法條例也許也都是很長。不過臺灣的條文通常都是把程序法跟實體法放在一起規定。這個條款是一個很典型的實體跟程序放在一起的規定。

實體是指哪些呢？你從境外取得的所得，可以依所得稅法的規定來做可扣抵稅額的扣抵的計算。這個就是實體法規定。

至於後半段：「得由納稅人提出來源地國的稅務機關所發給之同一年度的納稅憑證」，原則上這個就是程序上的規定。也就是該筆所得在所得來源地國被該國的稅捐稽徵機關做過做課稅權限的行使，那么納稅人則取得繳納稅款的納稅憑證，經由我國在當地的使領館或其他經中華民國政府認許之機構的簽證後……

當然了，這個名詞也是很不精確的。「簽證」是什麼東西？簽證是在講什麼呀？是在講國家的旅行的管理機關所發出來的一個準許旅行的一個證明文件嗎？簽證當然不是指那個意思。而是由我國駐外的使領館或者經我國政府授權許可的機構，這一些我們透過用認證的方式，認證這個確實是一個該國稅捐稽徵機關，課徵稅捐的一個繳稅的證明。這個地方其實是外國公文書的確認的程序。所以我們才說這個是一個程序法規範。

因為外國可扣抵稅額，必須要這一筆所得，確實在外國經各該國家的稅捐稽徵機關課稅，然後經過我國駐當地的使館或者是受公權力授予權限的機關去認證該納稅證明，作為一種證據方法來做可扣抵稅額的扣抵適用。


因此第3條第二項第二句的規定，是一個區辨，只有境外來源所得，在當地確實被課所得稅，而你拿到一定的程序上的認證的憑證以後，你可以來做外國可扣抵稅額的計算。

從而，辨明是否中華民國來源所得，正是第3條第二項第二句裡面，外國可扣抵稅額的一個依據。簡單來講就是只有境外來源之所得，被境外的有權機關課徵稅捐而取得一定程序上的認證的該納稅憑證，可以做外國稅額扣抵。

因此，即使是屬人主義的稅籍企業，雖然是就全球來源所得，但還是要去辨明，該所得究竟是境內或境外來源。

屬於境內，也就是認定為是屬中華民國來源之所得，沒有適用3條二項二句的餘地，因為，本質依我國的稅法規定，認定為這就是我國來源所得，并不是所謂的外國來源所得。只有外國來源所得，在各該國家經由該國的稅捐稽徵機關課稅的納稅憑證，經由我國駐在當地國家的使領館，或者是經政府認許的機構，給予這樣一個認證以後，才會有可扣抵稅額的這樣一個實體法上的效力。

辨明是否中華民國來源所得，不管是稅籍企業或者是非稅籍企業，都是有實益的。

對非稅籍企業，我們只有在真實連結原則底下，才對該非稅籍企業或者是非稅籍的居民產生對他的課稅權限。以所得稅的課稅權限而言，就是綜所或者是營利事業所得稅。

如果是稅籍居民企業，雖然是採取全球所得來源課稅的制度，但只有非我國來源所得，在各該國家被該當地的稅捐稽徵機關課徵了所得稅，然後經由一定程序去取得的這個憑證，才能夠作為可扣抵稅額的依據。

以上，是首先跟各位去談，為什麼要去談「是否中華民國來源所得」，是有區別的實益。

不管是決定我國有沒有課稅權限的行使，在真實連結原則底下，原則上只有屬地的所得，我國才可以去行使課稅權限。即使是屬於全球來源所得的，也是決定是否適用外國可扣抵稅額的依據。

簡單來講，就是劃分各國課稅權限的重要規定，所以理論上應該要由稅法本身去做規定。這個是根據重要性理論。在德國法制上面，一般而言，作為課稅劃分稅基的規定，是稅捐構成要件裡面的重要的要素，應該要由立法者自己來去做決定。那么，在間接民主底下，是由人民所選出的代表，自己的代表選出來，才能決定自己要負哪些稅捐，也就是「無代表即無稅捐」的這樣一個概念的實踐。那麼也因此，在德國認為這個是重要的，要人民自己來做決定。理論上來講，應該要由制定法來規範，連授權給法規命令都不可以，因為這個是要人民的代表自己來做決定的。

不過在臺灣我們是採一般法律保留原則，那麼只要授權明確的話，原則上還是可以把這些事項授權給法規命令，由行政機關依授權明確性原則，在目的內容範圍許可的範圍內去做，關於稅基範圍劃定的這樣子的一個法規命令的制定。這個是我們的實務現況，跟德國大致上的差距，也順帶跟各位去提到稅基範圍劃定是重要的構成要件，從而理論上，在依法課稅原則底下，應該要由立法者，適用嚴格的法律保留，國會保留原則才是比較妥當的。


## 【第8條，中華民國來源】

回過頭來，也因此，我們在第8條就設了所謂的中華民國來源的判斷，這個條文規定。

第8條的規定，「本法稱中華民國來源所得者係指左列各項所得」。總共十一款的規定，看似完全符合剛剛我們所講的法律保留啊，甚至你可以講哦，這個就是國會制定的，是立法者自己制定所謂的中華民國來源所得這個概念。


因為我們是綜所跟營所合併立法的體系。換言之，這個條款規定同時間可能適用在綜所，同時間也可能適用在營所。從而我們對於這個條款規定，要個別去判斷，這個是適用綜所的規定，這個是適用營所的規定，還是兩者皆有適用。那麼跟我們同樣採分稅立法方式的，譬如說德國或者是日本，綜所跟營所，是分開立法。從而如果有類似的條文規定，你可以很清楚而明確地知道，是只是用在綜所，或者是只是用在營所。如果要有規定同樣適用的話，一般而言，立法技術上會採用準用的方式，也就是德國法人稅會去準用德國個人稅，也就是所得稅裡面的條文規定。

臺灣則不是。自始，我們從1905年開始，因為這一部所得稅法最早是大陸時期的「所得稅條例」，一開始就是把對個人跟對營利事業放在同一部稅法裡面規定。這一部法律，我們自始就是把個人稅（個人所得稅）跟營利事業的稅負（營利事業所得稅）放在一起。所以我們雖然採用分稅立法，但我們在綜所跟營所的時候則是合併立法。

從而，第8條的規定，理論上可能適用營所也可能適用綜所，當然也有可能同時適用。這是作為一個，我們是分稅立法，但綜所跟營所卻又合併立法的立法模式，特殊產生出來的一些問題。

我們接下來看一下第8條的規定，看起來是符合立法者自己決定何謂中華民國來源所得，但實際上，你如果把第8條的規定去跟14條的規定做對照，你赫然發現第8條幾乎是第14條規定之重申，再加一句「中華民國來源」。

第8條的第一款跟第二款，還不這麼明顯，但各位可以繼續來看第8條的第三款規定。第三款的規定其實對應14條裡面的第二類跟第三類。因為第二類是執行業務所得，第三類薪資所得，都是屬於勞務付出，而取得經濟成果，差別只差在執行業務，主要是獨立勞務，薪資所得也是勞務，只是是非獨立勞務，原則上是受僱主指示而付出勞務。不管是獨立或非獨立勞務，在第三款規定第8條第三款規定裡面他就加上一句，叫"在中華民國境內提供勞務之報酬"。這一句話基本上只是把勞務這個類型的型態，透過第14條第二項第三項，把他抽象為「勞務」，加上一句「中華民國境內提供之勞務」。

簡單來講就是這個條文本身本來應該是要去判斷關於勞務類型的所得，如何決定是否是中華民國的勞務所得，也就是中華民國所取得的境內提供勞務的所得。因為勞務可以是幾種，我們可以根據他的類型態樣，可能是提供者，可能是受領者，可能是實施的地點。

我再講一次，勞務是一個無形的人力的付出，從概念上，判斷的基準，可以是提供者的所在地，勞務的提供者，假設他可以跨境提供勞務，那麼勞務的「提供者」會是一個判準。

「受領者」又是一個判決。

也有可能是以「勞務獨立實施的地點」作爲判斷。我們舉例而言，要蓋一棟特殊的建築，假設臺北的101，開放國際標國際團隊來競標。那今天會有美國日本，各國的團隊都來競標。建築勞務是一個很典型的獨立勞務的類型。如果得標的是美國團隊，提供者是美國人，受領者則是臺北市政府，受領的地點則會是在臺北市，也就是中華民國來源。實施的地點有可能因為是101，所以是在臺北市。

但假設如果我們今天把實施的地點搬到第三地。換言之，這個受領者在第三地有一個建築勞務，這個時候在概念上，他就有可能是提供受領跟實施的三個不同地點，來決定勞務究竟是否屬於境內來源所得。是哪一個？提供？受領？還是具體的實施？你看第8條第三款的規定，「中華民國境內提供勞務」，在講什麼？講提供者？還是在講受領者？還是在講勞務實施地點？哪一個？答案是，不清楚，因為他沒講。只是加上一個「境內提供勞務」，而這句話有講跟沒講沒兩樣。至少在我的觀點來看，我看不出來他講什麽。

第四款規定：「四、自中華民國各級政府、中華民國境內之法人及中華民國境內居住之個人所取得之利息。」

這個還算好，各款規定裡面有些確實是有意義的。

然後第五款。租賃，是一個有體物的租賃，所以條文是寫中華民國境內之財產，因租賃而取得之租金。這個說他有講清楚，也可以說有，說沒有，也可以沒有，因為他就是再加上一個「境內」，財產是在中華民國境內，你因為該項租賃而取得的租金，這個是中華民國來源所得。

那么第六款跟第七款，後面都是加一個「中華民國境內」，這個立法上的方式是對應著第14條總共有十類的所得，然後加上「中華民國境內」。

我們現在稍微整理一下，第一款跟第二款基本上對應第一類所得，也就是營利所得，拆分成兩款規定，一個是公司，第二款規定則是合作社跟合夥組織。公司的股利盈餘，跟合作社或合夥組織所發放的盈餘，這個是8條一款跟二款，對應第14條的第一類營利所得，因為我們14條第一類裡面，基本上就是公司合作社獨資合夥商號，有股利盈餘，有這個經濟上的成果，加上中華民國境內。這個地方條文規定的解析，我們先暫時說明完之後，我會回過頭來，再來跟各位去講他背後真正的意義在哪裡。

第三款規定對應第14條的第二類跟第三類。

第四款的規定對應利息，也就是14條的第四類。

接下來第8條的第五款規定，租賃而取得的租金，對應的是14條的第五類中的租賃所得。

第8條的第六款規定對應的是第14條的第五類裡面的權利金所得。

第8條第七款的規定對應的就是回到五類裡面的租賃所得。

第八款的規定，「中華民國政府派駐國外人員及一般雇用人員在國外提供勞務之報酬」，這個是可以認為是第三款規定的特別規定，專指中華民國公權力高權團體，派駐國外之工作人員及一般雇用人員提供勞務所獲得的報酬，這個待會我會給各位做一個整理。第八款基本上是第三款勞務的特別規定。

接下來的第九款規定，對應的是所得稅法第14條的第六類，自力耕作漁牧林礦所得，也就是農林漁牧礦冶。有一個第九款規定，是把「工商」又算進去，因為工商是營利事業的一種類型，工商只要不是執行業務者的獨立勞務的付出，原則上就是營利事業的類型。所以第8條的第九款規定，同時對應所得稅法第14條的第六類的農林漁牧礦冶的綜所稅的所得來源地的判斷標準，但同時間他也是營利事業所得稅裡面的所謂的中華民國來源所得的判斷標準。因為在這裡面，工商事業正是營利事業最主要的類型。

第十款規定，競技、競賽、機會中獎，對應的是所得稅法的第八類，競技、競賽及機會中獎的所得。

第十一款的規定，中華民國境內取得之其他收益，則對應的是14條的第十類其他所得。

從這個條文的對應關係，因為我們是綜所營所合併立法的體系，從而在一個條文裡面各款對應不同的稅目會有不同的適用範圍的劃定。在這裡面，第8條的規定，立法技術上是，把第14條的十類所得，加上一個「中華民國來源」。這一種立法導致這個條文規定的規範意旨是不明確，不清楚的。

正因為不明確不清楚，從而在實務上面才另行公布一個「所得稅法第八條規定中華民國來源所得認定原則」。

因為你的母法本身就基本上在立法技術上，只是將各類所得加上「中華民國來源」而已。從而實務上根本無從，從這一些所得稅法的母法規定裡面直接去認定究竟何謂中華民國來源所得，以決定到底外國可扣抵稅額有多少，到底要課綜所稅的所得有多少。

在這種情況底下，實務上，從而從98年9月3號財政部公布「所得稅法第八條規定中華民國來源所得認定原則」，最近修正日期是民國112年10月13日，台財稅字第11204568350號令。我們現在是10月30號，所以是17天以前。

這一個「所得稅法第八條規定中華民國來源所得認定原則」，替代了所得稅法的規定第8條的規定，成為實務上操作認定，是否中華民國來源所得的主要的判準所在。

如果我們不顧慮依法課稅原則，實務上從來基本上是不看第8條規定的，而是看這一個「所得稅法第八條規定中華民國來源所得認定原則」，簡單講，「認定原則」。就跟我們的稅籍居民的概念一樣，所得稅法上沒有清楚的劃分的標準，什麼叫你的經濟跟生活重心所在。

從而這一些屬於本來在法制上被認為是重要的構成要件，在臺灣所得稅法看不到，因為法律條文本身就模糊。至於為什麼法律條文本身模糊，立法者為什么不定清楚？我個人的看法，這只是我個人的觀察，也許我有偏見。我認為財政部送進去就是這種條文。看你立法者會不會改，你立法者如果蓋個橡皮圖章就通過的話，那條文就長這個樣子。因為立法者是立法委員，沒有比財政部更高度的專業。而財政部為什麼要這樣做？很簡單，我送一個抽象低密度的立法，我之後我只要改來源認定原則，我就可以實質變動我們的課稅權限的行使範圍。就這麼簡單。這也許我是小人之心，財政部也許認為說，沒有啦冤枉，柯老師不要常常講我們是這樣子啦，我們立法者都是這樣子，我們去他們搞不好也改了很多啊。對，沒有錯，但你送進去的草案可能就長這個樣子，你財政部希望的就是這種低密度抽象模糊規範的立法。這個認定原則，完全沒有授權依據，以一個事實認定行政規則的方式，實際上替代了所得稅法第8條的規定。

這正是在我國實務上面，當一個低密度立法的母法，連授權的法規命令都沒有講授權，然後實務操作就是用一大堆的行政規則。我們試著想想看，如果沒有這些行政規則，你怎麼去判斷所得來源地。當然待會，我會帶領各位同學我們去看一下第8條的規定，其實這裡面還是有一些蛛絲馬跡，可以去理解，究竟對應的那一類所得，我們怎麼去判斷是否為中華民國來源所得，但不是每一次都能夠對應出來。像我剛剛跟各位談的勞務所得的來源地的判斷，除非是剛好是中華民國派出去的這一些政府的去國外去行使國家公權力的外交的行為的，或者是軍事上的這些行為的人，否則原則上，你根本就看不出來第三款規定裡面他講的到底是勞務提供、受領，或者是實施地。你根本看不出來。待會我們去看來，來源所得認定原則，可能你就會知道啊，什麼叫做勞務提供地。

我會跟各位講，如果你考第8條的規定，往往只能考抽象的法條，那純粹背法條沒有意義，因為實務操作根本就是放在來源所得認定原則。也就是法條跟實務是有差距的。那麼在這個地方我們還沒有去講來源所得認定原則之前，我們還是回到本來，其實在立法上應該要很清楚地去具體指明，何謂中華民國來源所得。

因此我們先來看一下我們現在目前的所得稅法第8條的規定，是不是可以從這些文字裡面可以去瞭解立法者究竟背後所認為的中華民國來源所得，到底是在講什麼？

我們以第8條第一款規定為例。第8條第一款規定是這樣：「一、依中華民國公司法規定設立登記成立之公司，或經中華民國政府認許在中華民國境內營業之外國公司所分配之股利。」

我們先看第一款第一段，依中華民國公司法規定，設立登記成立之公司，所分配之股利。請各位同學，你跟第二款規定對照。第二款規定：「二、中華民國境內之合作社或合夥組織營利事業所分配之盈餘。」

兩相對照一下，因為他們本來都是對應的14條第一類的營利所得。看第8條第一款規定跟第8條第二款規定，差在哪裡？第8條第一款，如何判斷，股利盈餘是否來自中華民國？依中華民國公司法設立，對吧？只要你是依中華民國公司法設立的，那你發放出來的股利盈餘就是中華民國來源所得，就是第一類裡面的股利盈餘所得。所以，我們在判斷第一類的營利所得，以公司發放的股利盈餘為例，不是看經營地點，而是看你是依哪一國法設立。依我國法設立的，由你發放出來的股利盈餘，這個就叫中華民國來源所得。因此相反的，非依中華民國設立的公司，除非該當第一款裡面的後半段，那個「經中華民國政府認許在中華民國境內經營」，理論上你只要非依中華民國公司法，發放出來的股利盈餘就不會叫中華民國來源所得。所以當我今天掛一個，我是美商、新加坡商，就算在境內有所經營，他的經營成果理論上是在中華民國境內經營的經濟成果，沒關係，只要是由公司經營的成果，再把他的經營成果以股利盈餘發放的方式給你的話，他是外商公司的，就不叫中華民國來源所得。

這個就是第8條第一款，實際上這個就叫做準據法。這個也是我們在下個學期，我們講營利事業所得稅第3條第二項第一句。看起來叫總機構在中華民國境內，實際上總機構在中華民國境內判斷標準就是依中華民國公司法設立的，就叫總機構在中華民國境内。也就是你依我國公司法設立的，就是屬於我們的稅籍企業。

我們的立法跟實務上的操作，沒有很清楚地透過法條文字，去做一個連結。用第3條第二項第一句，叫「總機構在中華民國境內之營利事業」。

那麼到了第8條的第一款規定，他很清楚的告訴你，依我國公司法設立的，叫我國的來源所。但第二款就沒有很清楚，因為第二款他寫什麼，他寫「在中華民國境內之合作社或合夥組織」。理論上，如果要用同樣標準，那就是依我國的合作社法而設立之合作社，他所發放的股利盈餘則就是中華民國來源的股利所得。同樣的道理是合夥組織跟獨資商號，其實在我們的經濟法制裡面，獨資跟合夥是依商業登記法規定去做工商事業登記。所以，如果立法上體系上要一致，是依我國法設立之公司、合作社、獨資及合夥事業，所發放之股利盈餘屬於我國來源所得。

這就是透過一跟二款的規定，我們把他綜合起來，去解析第8條何謂中華民國來源所得。你只要是依我國法設立的第一類的所得，原則上就是我國來源所。條文本身並不非常清楚，但實務的操作確實是依照這個來做他的標準。獨資跟合夥由於在我們的現實實務上，很多生意，獨資跟合夥根本不辦商業登記。從而他才會用事實上你的經營地點在中華民國境內，來做為第二款的標準。為什麼他是用經營這個概念？因為在臺灣的獨資跟合夥商號，很多是不按商業登記法去辦理登記的。開店營業，本來是要先辦理登記，但他沒有去做工商登記。

稅法上的登記叫稅籍登記，他其實跟經濟法裡面的工商登記是分開來的。工商登記是指依商業登記法、合作社法或者是公司法所設立登記的組織型態的這種營利事業組織。所謂的稅籍登記，是指為了課稅之必要性。營利事業一般來講，做工商登記之後，就要做稅籍上的登記。所以才一邊歸經濟部，另外一邊歸財政部主管。所以歸經濟部管的，這個就是財務會計，國稅局財政部管的這邊就叫稅務會計。稅務跟財務是兩件事啊，不是一件事，是有兩個不同主管機關。

財稅這個是稅務的問題。工商登記，各位在學公司法的時候，你常會講到工商主管機關，經濟部才是他的主管機構。那為什麼經濟部講的財務會計，怎麼一下子會變成是稅務的計算基準啊？答案是，我們在這裡面財務會計跟稅務，為了要讓營利事業透過，記一本帳，就可以兩邊都應付，所以我們是用「稅務遵財務原則」，做帳外調整就好。財務的這一邊，原則上是做工商事業管理使用。你的財務上的報表要讓投資者，主要是股東跟債權人，能夠理解你到底賺多少，能夠理解我要借你多少錢，能夠理解我要不要投資你。誠實地讓人們知道你到底賺多少錢。這個是財務會計的主要任務，這就是商業會計法裡面相關規範的目的所在。由於這一個商業上的語言，擬募集資金對象的主體不會是只有國內的投資者，你往往都是要對外，對國外的投資人去募集資金，因為你可能會有外國的股東，可能會有外國的債權人，從而在商業領域裡面，他是國際語言，這些國際之間的商業會計語言，以一種習慣法的姿態而呈現在財務報表裡面。這個就是財務會計，為什麼會用IFRSs用所謂的國際財務報導準則。因為你只要是面對全世界的債權人跟資本主的話，也就是股東，你講的話當然是要他們聽得懂的。所以你用百分制的這種分數，到國外去看不懂。為什麼要ABCDEF這種這種評分標準，這個就叫國際語言。我們以前都是用100分的這種方式，這個叫我們本地語言。如果你募集資金，只是面對本地，你用本地語言沒問題。你拿著你在學成績99分來跟我講，那我知道哦，這個是好學生。可是99分，對美國人對歐洲人沒有意義，因為他看不懂99分是什麼意思。但你如果跟他講叫A+，這樣大家看的懂。這就是財務會計的語言，具有高度國際化。因為我要讓別人知道你的財務健康狀態，你是健康寶寶，還是是一個打腫臉充胖子的狀況？

相反的，稅務不是這樣。稅務是本地的，因為他面對的主要是國稅局，國際租稅法沒出現之前，稅務主要面對的是國內的稅捐稽的機關。從而為了不讓營利事業做兩套帳。一個是財務帳，一個是稅務帳，所以我們就是稅遵財，再做帳外調整就可以。在這樣的一個前提底下，稅法規範是内國法規範，是內國法制。沒有任何一個國家會把自己的課稅主權交給外國人去決定你有沒有課稅權限，去行使。

正是因為如此，稅法是法律，稅法是本國法。學財務會計進入稅法的領域，就一定要學法律的語言。所以各位，稅法是什麼？不是純粹的會計。財務會計不代表稅法，也不要混在一起。正因為如此，在稅法的領域，我們希望法律本身規範明確，符合依法課稅原則。當然這個還有很長的路走。

所得稅法第8條的規定，立法技術，我個人認為很糟糕，因為他什麼東西都沒講。當然你仔細分析，好像也有一些有講。但實務的操作，也正是因為他有些沒有講得很清楚，我們在實務操作往往都是看來源所得認定原則。其實來源所得認定原則，他在第2點跟第3點裡面，他就真的就寫，剛剛我跟各位講的，依我國法律設立登記的，這個就叫中華民國來源所得。這其實就是這樣一個相互的來回對照。我們今天會跟各位去講，何謂中華民國來源所得，就這樣子的一個法制不是很完整的一個狀態所產生出來的問題。


我們先休息一下。