# 20230925_02

---
課程：1121所得稅法一
日期：2023/09/25
周次：4
節次：2
---

## 【所得稅稅捐客體之判斷流程】

稅捐構成要件的第二個要素就是稅捐客體\index{構成要件!稅捐客體}，他在討論上面來講，其實是蠻重要的一個問題，也就是說，稅捐主體相對於稅捐客體而言啊，他當然是開啟了我們國家對這個稅籍居民課稅的可能性的一個構成要件，但如果沒有第二個構成要件，就是他取得所得，在這個地方，其實你整個課稅構成要件傷還是沒有辦法去滿足。

所謂的稅捐客體，就是你取得一個所得，然後他是應課稅所得，然後這個應課稅所得是中華民國來源所得。

我分三個層次去講。第一個，他必須是所得，第二個，是應課稅的所得，第三個，必須是中華民國來源所得。因為我們所得稅法第2條的第一項跟第二項都加上了一個中華民國來源，換言之，所得的實現地點在中華民國，才會被課我們的所得稅。所以其實在講稅捐客體的時候，其實分了好幾個層次上的問題。第一個，他必須是所得，非所得當然就不進來。我們待會要跟各位去舉幾個說明什麼是非所得。所得，當然可以被正面定義，我自己也寫過一篇文章去定義所得，討論何謂所得，這是我們今天上課的重點所在。

但第二個問題其實蠻重要，就是他必須是應稅所得。因為在我們的稅法裡面有許多稅捐優惠的免稅所得。只有是所得稅的所得，他才會進入第二個層次叫應稅還是免稅所得，這個是第二個層次的問題。

第三個。我們還要再談實現的地點，實現的地點必須要是中華民國來源。因為按照一般而言，稅籍居民的所得其實是不分是否跟屬地有所連結，也就是境內境外來源都要被課所得稅，一般而言是這樣。因為我們的所得稅法和比較特殊，他要求的稅籍居民也還是必須要是中華民國來源所得啊。

我們從第一節課，也了解到，所謂的中華民國來源，根據兩岸人民關係條例，就是你是我們的稅籍居民，原則上臺灣跟大陸兩個地方的所得都是中華民國來源所得，都是所得稅的所得，而不是課所得基本稅額條例裡面的最低稅負制。港澳則不是，港澳，依照港澳關係條例，則是課所謂的所得基本稅額條例裡面的最低稅負制，而不是課所得稅裡面的綜合所得。那這個地方因此產生稅捐負擔上的區別對待。

回到我們這個地方講的，所得的實現地點。這個地方我們必須要跟各位再來去談所得稅法第8條的規定，因為那個地方才是真正涉及到所得來源地的判斷。

那其實接下來還有一個很重要的問題，就是要分類型，所得是哪種類型？因為不同的類型的所得，在計算稅基的時候，他是有區別對待的，不同的類型所得。譬如說，執行業務所得，跟薪資所得，同樣是勞務的付出。獨立的執行業務的所得，他有一個計算成收入的所得的一個標準去，反映出他的稅捐法上的負擔待遇，但你如果是薪資所得，他有另外一套標準去做這個你的薪資所得的計算。


從而在這裡面，我們總共應該分4個層次的問題。


## 【所得的概念演變】

第一個問題就是所得跟非所得，要跟所得去做正面的區別，這個其實是不太容易的，因為這個要看，所得怎麼定義。但從歷史的角度來看，所得其實是有不同的定義的方法。最早的對所得定義，來自於財政學者，而這個定義的概念也形塑了最早引進所得稅的英國對所得的想法，就 income這個概念。來自於源泉而產生出來的孳息增長，增益，這個被稱之為叫所得。我們就用樹果來做描述，樹是一個所得的源泉，所得所由生的源泉，從這個上面長出來的果實掉下來以後，這個才叫所得。所得不在講那個財產本體，而在講這個源泉所產生出來的增益、孳息。這個理論就被稱之為叫源泉理論，他是最早的所得概念，從財政學界一路過來，1799年英國的所得稅法，他對於所得的定義。他的源泉來源可能是來自於勞動力投入，可能是來自於資本投入，當然有許多是勞動力加資本的投入，但無論如何是以他長出來的成果。來做為所得的 income 的概念。

那么打完拿破侖戰爭以後，英國獲勝，很快的1804年英國的所得稅法就沒有再實行，因為打完仗，財政需求就沒有了。但這個概念卻很深地影響到後面的各國的所得稅的概念。到19世紀末的德國的所得稅，在所得稅的概念裡面，也一直沿用源泉理論的看法，也就是說，要不是資本投入，要不就是勞動力投入，那至於這兩種投入長出來的果實，就變成了課所得稅的課稅的對象。這個就是所謂的源泉理論。


到了20世紀啊，德國人的講法是1921年在德國有一個財政學者叫 Georg von Schanz。

這個意思是他是一個領地的領主的後代，他們是 Schanz這個地方的地主的後代。德國的名字跟姓氏，姓氏通常是按職業或者是地名。像我有一個朋友，他叫【？】，那他是從【？】這個地方出來的地主或者是領主的後代。德國以前的那個國安部長，現在是歐盟執委會主席主席，叫馮德萊恩，Ursula von der Leyen，就是從那個地方的領地的後代啊。

我在看那個德國文獻的時候，他們就是說，這個概念其實是我們德國人先發明出來的概念，叫所謂的純資產增加說。所謂的純資產增加說是以兩個期間裡面的資產淨值做比較，全然的資產淨值的增加，包括已做的消費行為跟投資儲蓄，全部都要算回來，這個是你的所得。這個概念就叫純資產增加理論。雖然資產淨值為零，但這一段時間裡面，你所做的消費行為其實是你的凈所得的增加。這個純資產增加說的概念是用資產凈值的比較，再加上此段時間裡面所做的消費及投資儲蓄，因為你投資在外，他是用一個財產的形態產生出來的經濟成果。從而1920年代出現的純資產增加說這個概念，跟前面18世紀末19世紀的源泉理論，從一個所得源泉長出來的孳息這個概念，是全然不同的概念。

這個看法到了1930年代變成了美國的Haig跟Simons，這兩位美國財政學者的對所得的定義跟概念。你現在去看會計系的教科書，講所得都只有講Haig跟Simons，可是如果是看德國人的講法，會説，第一個提出這個所得概念的是德國的Schanz。德國的Schanz，美國的Haig跟Simons這三個人所共同認為的所得概念叫純資產淨值的增加。純資產淨值的增加，特別表現在營利事業。因為營利事業是一個數人的組合，但他沒有屬人的像你我一樣的自然人實體的存在，所以營利事業所得稅在計算所得的時候，基本上就是用純資產淨值增加說的概念。下一次上在講營利事業所得稅的時候，會跟各位在稍微簡單的去說一下他的法條規定。就是兩段時間裡面，資產淨值的做比較，然後再加上你如果有消費，你有儲蓄投資就再算回來。營利事業沒有消費，但是你拿來自用就還是要算所得，因為你的自用就構成了一個經濟成果呢的實現。


1920年代開始到1930年代，20世紀初期的所得的概念，這個叫純資產增加說。

這兩種學說看法不同，結果都表現在1789的1891年的德國的統一之後，德國統一是指普魯士3次戰爭以後統一了小德意志，排除掉奧匈帝國的奧地利以後，德國各邦連國家統一起來，

這個19世紀末的德國的所得稅法，把這兩種不同的概念，因為當時候其實對。營利事業所得要怎麼課稅，並沒有一個很統一的想法，1920年代所出現的這一個所謂的純資產增加說在19世紀末的時候，基本上還在討論的階段，但德國的立法者就把他放進去所得稅法裡面。當時的所得稅裡面的所得概念，用勞動力付出的，原則上是採取源泉理論的看法，因為他是影響最久，也是最深遠的一個對所得的概念。但當時在統一之後的德國的稅法，他所對營利事業所做的課稅所得，則採取純資產淨值說，這是當時候在財政學界裡面比較流行的看法。因此到1920年代的德國的所得稅法，就用兩種所得理論同時並存在德國的個人所得稅法裡面。

經營事業的用純資產增加說，勞動力投入的，不管你是薪資或獨立的執行業務，原則上就是採取所謂的源泉理論。

因此到了1979年的時候，到了20世紀末，1980年代開始，德國的稅法學界為了要去統一說明，這兩種不同所得理論，一個是源泉理論，一個是純資產增加說，才產生一個概念，叫做透過市場而實現的經濟成果，首次提出市場所得的概念。所以市場所得概念是1980年代提出的。而且第一個提出來的其實不是德國人，他是奧地利人，是一個奧地利的法律學者，他提到，所謂的所得是透過市場經濟活動所實現的經濟上的成果。不管你是講了源泉理論，或者是純資產增加說，其實要掌握的所得，無非就是市場經濟活動的成果。這個1980年代才出現的市場所得理論提出之後，就變成了德國稅法學界的共識，學界認為市場的概念才能適切表達出，在德國所得稅法原先立法裡面其實並存著源泉理論跟純資產增加說這兩種不同所得的概念。

相對於源泉理論是一個非常狹隘的所得理論。為什麼講到狹隘呢？因為只要果實不落下來，都沒有所得的概念，這就是源泉理論的問題。我們用樹果理論來做說明，果實，只要不落下來，你只要把樹一起賣出去，這樣就不算有所得。所以在英國的income的概念跟capital gain是有所區別的，爲income是指那個掉下來的果實，可是如果你是把果實財產本體把他賣出去，連同他上面的增值就一起賣出去，這個轉售價差，英國人的概念字眼叫做capital gain，那個是一個資本利得，不是income。如果你去問一個英國人，income，他可能理解到了，就說哦，income講的是我們相當於我們所講的孳息的概念，因為capital gain這個概念在英國是另外立法，另外課稅，不在他們的income tax裡面去做課稅。這也是不同的與法系的國家裡面對這個概念可能會產生歧義。

但各位很快就可以幫發現，如果在我們的社會裡面只對孳息課所得稅，卻不對資本的增益課所得稅的話，那麼很快就會發生，有部分的所得沒有被掌握的情況，也就是說能夠表彰出稅捐負擔能力的所得沒有被掌握。換言之，在這裡面對於源泉理論過於狹隘的這種概念，1920年代才因此產生純資產增加說。但純資產增加說最大的問題就是連維繫生存所需要的消費，以及各式各樣的投資跟儲蓄全部都要算回來。還有一個問題，就是純資產增加說，說連隱含所得，也就是你本來在家範圍內的這些消費活動，只要能夠被數量化，就應該計算所得課稅。比如說住自己的家，幫自己的小孩補習。如果我作為一個中學的老師，我在外面當補習班的老師，我可以賣錢，但我幫自己的孩子補習，我孩子因此節省費用支出，在純資產增加說裡面，也算所，也就是他要設算你節省的費用。純資產增加說無血無淚啊，為什麼？因為人就是勞務的付出，你只要賺到錢，我不管你是消費投資儲蓄，就算看到那個經濟成果，我一樣給你設算進來。所以你住自己的房子，要設算租金收入，開自己的車要設算計程車費用，然後幫自己的孩子補習，要設算你的這個節省的補習費的支出，全部都算進來。純資產增加說因此被認為對於所得的課稅範圍過廣。除了在營利事業，我們可以這樣子去計算以外，對個人綜合所得稅用這種方式去理解的話，他的範圍太過廣泛。

從而1979年，1980年代開始的市場所得理論，適切地從一個比較正面的方式去做一個比較適當的定義，也就是說，何謂所得。其實家内的經濟活動是被排除的。因為家不是市場。只有透過市場的活動，因為是一個本來是市場實現活動的經濟成果，才能被認爲是所得。

比如說你這個其實本來是市場經濟活動，你本來可以去透過你的勞務付出去賺進來你的勞務付出的所得。但是由於各種的因素，你沒有勞務上的付出，那你因此去取得替代經濟成果的那個財產上增益，這個本來是透過市場經濟活動會實現的所得，這個時候就應該要課所得稅的所得。我們舉例而言，你本來勞動付出，你會換得所得的就是你的薪資所得，可是你們現在去罷工。德國罷工，他們的工會是發起人的哦，你知道嗎？因為罷工的時候領不到薪水啊。假設雇主沒有根據法律上規定的義務，要付給你一定的薪水。那麼德國工會，因為你平常就交錢給我，所以德國工會就是在你這一段罷工期間裡面，因為我們要跟資方去做團體協商，那你領不到錢的時候，工會會發給你錢，讓你至少維繫這一段時間裡面的經濟上需求，不然罷工幹不下去的。大家要罷工，不是今天上街頭而已，他有這段時間裡面的維繫生存的經濟上的需求。德國在工會的城市裡面就是對參與罷工的人，他提供一定的經濟上的援助，讓他可以去實踐這一種團體協商裡面每一個工人都可以領得到一定罷工金。因此，罷工金在某程度上是替代經濟成果的一種另類的所得。從而在這個角度來講，替代經濟成果的所得是透過市場，也可以去計算出市場所得的範圍。


這個市場所得的概念的提出，在1980年代之後變成的是德國法學界裡面的共識，儘管同一個時間，經濟學界還是比較傾向於淨資產所得的理論。其實講市場這個概念，經濟學者一定不陌生，但市場所得這個概念又會碰到一個困難。到了2000年的時候碰到一個困難，那個困難就是非傳統上被認為是市場概念的這一些非市場，比如說，成為公務員或者是選舉市長或者議員，或是成為立法委員國會議員。那麼，這一些非傳統上被認為是市場概念的範圍，但是在這一種非市場裡面的勞動力付出，因此所取得國家不管是以賠償的名義，或者是以薪資的名義所給予的，或是給予報酬的這個部分非傳統上市場的概念。那請問，這個部分沒有進入市場，算不算所得？ 簡單來講，就是總統市長立法委員民意代表領的錢，這個算不算是市場經濟活動底下要掌握的所得範圍？在2000年以後，我自己的論文指導的老師，他就說這個地方應該要把所謂的市場擴張到所謂的以取利益、獲取利潤作為前提而參與市場跟非市場經濟活動，也就是這一些傳統上被認為不在市場活動範圍內裡面的，特別是公領域裡面的，包括這些性質上被認爲其實是參政權的行使的領域。很好玩的是，在德國的公法領域裡面，透過選舉成為民意代表跟成為公務員，他都是一種參政權行使的方式，不是市場經濟活動的範圍，但是他們所因此獲得的報酬，德國認為這個是這一段時間裡面國家提供給你的補償，非市場經濟活動的所得，但這個仍然是屬於在德國概念底下，是透過去獲取收益的方式而取得的所得。


所以為了要包括市場跟非市場，在2000年之後，德國看法，至少在科隆，是認為，所得的概念是以收入超過成本費用而投入市場，不管你是通過職業或者是營業上的活動，也包括了你在非市場領域裡面，可能傳統上被認為是高權領域裡面的參政行為，因此所取得的經濟上的這些成果都被認為是所得的概念。這個概念被稱之為叫營利所得的概念，以獲得收入大過於這個成本費用盈餘作為他的主觀上的構成要件而去透過他的經濟活動的參與行為而獲得的經濟成果。


我們透過一個簡單敘述，介紹關於所得的概念的整個的進展，從源泉理論18世紀末期到19世紀，到20世紀初期的純資產增加說，到20世紀的後半葉所提出來的市場所得理論，到21世紀，我們所提到的營利所得的概念。所得的概念依然還在持續不斷地演變，如何去做適切的掌握這一件事情並沒有改變。


## 【我國的所得概念】

那么，以我們自己的所得稅法，那我們到底是採哪一種概念？這個才是我們今天要跟各位關注的重點。理論，有各種不同的說明。當然這種不同的理論，源泉理論太狹隘了，他顯然不能掌握capital gain，可是純資產增加說，因為太過寬廣，他連隱含所得的這種自家內的消費行為也仍然被課稅，市場所得理論是一個比較適切的，能夠去掌握經濟成果的理論，但又要包含了傳統上被非稱之為叫市場裡面的，特別是在高權領域裡面的參政權行為所產生出來的勞務上的付出，因此所獲得的對價，這個依然還是所得稅要掌握的所得範圍。沒有道理市長總統民意代表所取得的報酬，就不是課所得稅的所得，公務員取得的所得不是所得稅的所得，只有民營機構，他的所得才是所得。他是市場經濟活動，他才是所得，這個沒有道理。應該公務員的薪水跟民營機構裡面的職員的薪水都是一樣的，都應該要課稅。這個概念叫營利所得的概念。


我們來看一下我們的所得稅法的規定。所得稅法的第14條並沒有正面定義所得。就像稅一樣，所得稅法的第14條，我們從頭到尾，沒有定義。所得的概念，我們也似乎是理所當然，以這十種類型來表彰出立法者認為應課稅的所得，所以總共有十類。在這個地方，看起來，我們並不限於源泉，理由在於，第七類，我們的財產交易所得是被包括在所得稅的類型當中。因為有第七類，所以你很快知道我們的所得稅不是源泉理論。那我們是採什麼呢？看起來我們有第七類的財產交易所得，第十類我們有一個其他所得：以上只要不屬於特定類型的話，則以其收入而減除成本及必要費用後之餘額為所得額。


還有另外一個，就是第八類，競技競賽及機會中獎。什麼叫機會中獎？講難聽叫賭博，就是你去買樂透這一種機會中獎機會，中獎的所得，一時性所獲得的這一個財產上的增益，在我們的第八類裡面，也是所得稅的所得類型。雖然在實務課稅上面，其實機會中獎，像剛剛講的樂透或是以前的愛國獎券，或是現在的統一發票給獎，我們都把機會中獎單獨拉出來，來做分離課稅。第八類，雖然把他放在綜合所得稅裡面，當作一種類型，但實際實務上面，我們則幾乎各類的機會中獎都有各類機會中獎自己本身的法規範，拉出去做分離課稅。從財產交易所得的七類或第八類，以及第十類的規範結構來看，我們的立法者原則上是建構在以跟營利事業所得稅一樣的前提基礎上的純資產增加說的看法。也就是說，我們對一時性跟繼續性，沒有區別。錢就是錢，就算你今天是路上撿到的，你沒有歸還，也是錢？頂多只是不算入前面的九種類型，是第十類，其他所得。包括賭博收入。賭博收入最典型的第八類的機會中獎，賭博的收入也是所得。所以，在這裡面，不管你是一時性繼續性合法性非法性都一樣，你只要是錢，表彰出來的稅捐負擔能一樣。

14條沒有做正面定義，但透過類型的適用，可以看到，接近純資產增加說。這也是老師之前在寫一篇文章，關於所得理論，在講的就是這件事情。我們的法律，在立法上面是接近純資產增加說。雖然我個人也認為市場所得理論比較合理，因為純資產增加說，他很明顯的問題就在於範圍過於廣泛，而且他其實是有些進來，有些沒進來，像我們剛剛跟各位提到的隱含所得。自家的居住跟自家的使用勞務，這個在我們的現行法制裡面都不算任何一類所得，也不是第十類的其他所得。有些國家是真的採純資產增加說，他是真的會設算利息跟設算租金，去算你的所得，加進去。像比利時就有這個規定。你今天去租別人家房子，當然有租金的支付，住自己的家的話也要再加進來，設算你本來的消費，把他計算入你的所得，來做這樣一個稅捐負擔能力的掌握。但我們並沒有，我們雖然看起來比較接近純資產增加說，可是其實在我們實務的操作上面並沒有把各種隱含所得，包括你的各式各樣的消費行為都把他包攝進去。這也是我們在實務上面來講，看似純資產增加，實際上比較偏向市場所得理論。我個人也比較認同市場所得理論，儘管他很晚才出來，到1980年代才在德國的法學文獻上面，認為這才是德國所得稅裡面所要想要掌握的所得。到了2000年，雖然有做微調的營利所得的概念的修正，但基本架構，原則上就是經濟成果，不管你是不是市場經濟活動還是非市場，你有勞動力投入或者資本投入，或這兩者相加的投入的經濟成果，才能夠被認為是所得，這個概念是不變的。我個人也比較傾向于用市場所得和營利所得的概念去解讀我們現在目前的所得稅法，儘管他是以純資產增加說的立法結構去表現出來的所得的類型。這是關於所得的概念。

## 【是否所得之判斷】

在這樣一個前提底下，以下這些都不算所得。

第一個損害賠償。損害賠償無論是從哪種所得理論來看，都不是所得。特別是填補固有利益損害之損害賠償，原則上都不是所得。因為填補固有利益損害之損害賠償是因爲固有利益之存續，固有利益的固有狀態的被破壞，於是加害人對被害人添補固有利益，因此所產生出來的賠償。在這個地方，不管是源泉、純資產增加說，都不認爲這是所得。如果以所純資產增加說，他有沒有財產禁止的增加呢？答案是沒有。所以你撞斷一條腿，人家賠100萬，小心被人家打死，賠500萬，在這裡面都沒有資產淨值增加，所以這個數額，不管怎麼給付，原則上都不是所得。不是只有人身固有利益，財產固有利益之損害賠償一樣，沒有所得的概念。財產固有利益的損害賠償，譬如說你今天車子停在路邊，被人家不小心開車撞上去，賠你10萬塊錢，儘管可能看起來哎，明明就不需要賠那麼多。原則上我們在概念上叫固有利益之損害賠償，不構成所得。

相反的，替代履行利益之損害賠償，就有可能構成了所謂經濟成果替代的損害賠償，他就有可能會是所得稅的所得。看履行利益的損害賠償。何謂履行利益？我們各位在學民法裡面的履行利益，特別是預期透過契約之履行，可以獲得的這一個經濟上的成果，譬如說轉售價差。履行利益的損害賠償是一個因為契約無法照預期履行而可歸責於債務人之事由而產生出來的損害賠償。從而履行利益之損害賠償，原則上，特別是在給予預期可以獲得的這樣一個經濟成果的替代，這個部分，基本上就是所得稅的所得。困難就出現在我們的履行利益的損害賠償裡面有包括了，所謂的關於加害給付而侵害了其原先固有利益財產狀態的，或者人身固有利益的這種損害賠償。也就是在加害給付積極侵害債權的類型裡面，因為履行利益只是一個概括的概念，包括轉售價差，但也包括了因為給付而產生對債權人的人身或者是財產固有利益的損害，這一種加害給付也算在我們的履行利益的給付範圍內。嚴格而言，當然要個別區別，做不同的區別對待。屬於固有利益添補只給付不構成所得，只有經濟成果的替代才構成所得，這是稅法上對稅捐負擔能力對所得的掌握。也因此不能夠明白固有利益跟履行利益之差別，自然就無法對所得的概念、應課稅所得的概念，有辦法做正確的瞭解。其實整個法秩序就應該在這個上面去做必要的區別對待。

我們來看一下所得稅法第4條的規定。所得稅法第4條第三款，傷害或死亡之損害賠償。法條只有規定傷害或死亡之損害賠償，為什麼他免納所得？答案是因為損害賠償。因傷害或死亡之損害賠償是固有利益之損害的填補，根本非所得，所以沒有第4條第三款的前段規定，解讀上也是一樣，不是所得稅的所得，他是非所得概念，所以免納所得稅只是表彰出非所得。但是條文並沒有完全涵攝所有的固有利益損害，譬如說財產的損害的損害賠償。這個第4條第一項第三款規定，從法條文字裡面完全不包括財產固有利益的損害賠償，所以我們沒有辦法直接透過解釋的方式，讓第4條第三款的規定去適用到財產固有利益的損害賠償。財產固有利益的損害賠償，毋寧只能透過所得的概念來把他排除在所得的適用的範圍以外，也就是他不是所得稅的所得。傷害或死亡的損害賠償，就算不是透過損害賠償的方式，以和解之方式而給的傷害跟死亡的和解金，一樣，具備非所得的性質。所以個案的情形，請各位個別去做區別判斷。傷害或死亡可以透過損害賠償法去請求損害賠償，也可以透過契約法去做和解、調解出的傷害或死亡的損害賠償金，這個是固有利益的填補，而不是資產淨值的增加，他不是所得稅的所得。法條上沒有涵蓋的財產固有利益的損害填補亦如是。

相反的，屬於經濟成果替代的履行利益的損害賠償則有個屬於所得稅的所得。傷害案件，如果在概念上被認為是因為他減少勞動能力，他本來可以從雇主去獲得的那個勞務付出的報酬，經由損害賠償法制，由加害人對被害人所做的損害賠償，理論上，他可以是經濟成果的替代，可以是課徵所得稅的所得。不過在這個地方，要不要透過第4條第三款的規定，傷害或死亡的賠償金，把他全然都免納所得稅？若如此，在經濟成果替代這個範圍內，他確實就存在著稅收優惠的意義。因為這個地方當然不是讓他有中樂透的感覺，而是說因為在法律解釋上面來講，有時候對這一個減少勞動能力，特別是從雇主那個地方，本來他可以獲得的報酬，在概念上現在是由加害人，因為我加害於你，導致你無法去上班，因此可以去請求加害人對你所做的減少勞動能力的這個的損害賠償，概念上其實是經濟成本的替代，可以去做課稅，但是不容易區別。因為這個部分仍然在實務操作上面仰賴於個案裡面的關於賠償的計算，究竟是固有利益的填補，還是是經濟成果的替代，而做個別不同的區別對待。

比較明顯，而清楚的差別是在關於侵權行為是侵害無體財產的懲罰性損害賠償。比如說對於智慧財產權，盜用他人的專利商標或者是著作，在民事法院裡面所做的懲罰性損害賠償，也就是於依照預估的方式去計算這個著作在市場上發行，因此說可以獲得的經濟上的成果，以此作為前提，而計算出來的損害賠償。損害賠償在這裡無疑是經濟成果的替代。因為無體財產本身並沒有所謂的固有利益狀態而要維護的問題。有體財產有這個問題，因為有體財產，你撞凹一個摩托車，他就是被撞凹了，他的那個固有狀態就受到損害了。但無體財產沒有這個問題啊，你盜印他人的著作，盜用他人的商標，未經許可而去使用他人的專利權。因此，法院在判決損害賠償時，對依照應該取得的市場經濟成果去乘三倍，對所謂的加害人所判處的三倍的這一種，懲罰性的損害賠償，無疑是一種經濟成果預估計算的方式，從而拿到這一筆懲罰性損害賠償的取得者，理論上應該要申報所得稅。所以你的著作被盜用，有人去印，假設預估你會有1萬本的銷售，那這個地方乘三倍所產生出來的這個損害，當然就應該是應課稅的所得。

所以我們講損害賠償，其實是要看他的損害賠償的性質，是否在填補固有狀態，不管是人身生命或者是財產的固有狀態，或者是他是一個履行利益經濟成果的替代而做不同的區別對待。法律上面的理論上是這樣建構，但實際上往往在區別上是有困難的，這一點完全可以理解。但不會因為他是損害賠償法，還是用透過契約用和解或調解的方式因此而改變其本質。

當然，接下來我們要講很多邊際案例的類型。像醫生因為醫療糾紛而給被害人的慰問金。他不承認自己的損害賠償的責任存在，而是說，欸，我這個是基於道德上我給你的一筆慰問金，10萬塊錢。像這一類的給付，到底性質上算哪一類型？這個確實在實務上並沒有辦法很清楚的。如果你有法律上義務的給付，很清楚，這個是損害賠償，原則上他是非所得。但正因為實務的操作的上面，像這一種非基於法律上的義務而做的這一種基於倫理或道德上面你所做的這一種給付，既然不具有法律上的義務，那難不成構成財產上的贈與？所以要申報財產，所以納贈與稅嗎？比如說像現在在屏東發生那個大火，假設雇主自己自認為自己並沒有任何責任，我都已經做到了該有的相關的設施，是你不小心的點燃火把，或者是不小心你人掉進去。有些不良的雇主可能會說，誒，其實這個我都規範很清楚啊，你是你自己操作不當，才掉進去熔爐。在苗栗有一個勞災的情況，就是這樣，掉進去那個1000度高溫，立刻只剩下骨骸，很可怕的勞動現場的損害啊。我們假設，雇主自己自認為自己沒有過失，所以我就給你20萬塊錢慰問金啊，不承認自己的損害賠償。像這一筆錢到底在法律上怎麼定性？這一種沒有法律上的義務，他當然自然不會落入到所得稅中替代經濟成果的這樣子的一個概念的範圍。但法律性質上不是所得，難不成是贈與嗎？這也是邊際案例類型，我們有一些在實務上不太容易去做一個比較嚴格的區別標準。


另外，第二件事情是投資。投入資本的投入，跟投資股款的取回，這不算是所得。一個自然人去投入公司營利事業的資本投入跟投資股款的取回，這都不算是所得。這個地方既然不是他的成本費用，這個地方取回來也不是他的所得，所以投資股款的取回不是所得。

第三個是信託財產的移動。在設定信託時的財產上移動取得都不構成取得者的所得，因為這是信託財產的信託設定行為。信託的設定行為，為了信託而做的財產上移動，對取得者而言不構成所得。我們先跟各位談到這裡。當然其實在這個地方對於所得的概念，只要你是非財產上的增益，非透過市場經濟活動，原則上他就不是所得。

我們第一個層次過了，才會有第二個層次的應稅所得，或者是免稅所得，或者是其他分離課稅的所得，因為在這個地方，第二則往往是比較複雜的應稅免稅或者其他分離課稅的所得，他其實不是免稅，是一個分離課稅的所得，這是我們之前跟各位講過土地增值稅的所得，以及遺產贈與稅的所得，他其實都是分離課稅，所以他不是所得稅裡面的應稅所得，而是另外分離課稅的所得。境外取得的所得也是一樣的道理，境外取得的所得不是課所得稅的所得，而是課所得基本稅額條例裡面的最低稅負制，因為在我們現行的法制裡面，是把所得做這樣一個不同的區別對待，這個是到第二個層次裡面的問題，我們再來去做判斷。

我們今天先講到這裡，下個禮拜，再從那個應稅免稅分離課稅的所得這個角度去做說明。