# 20231002_01

---
課程：1121所得稅法一
日期：2023/10/02
周次：5
節次：1
---

上周，我們談到，所得稅法4條一項三款，關於傷害或死亡之損害賠償金，及依國家賠償法規定取得之賠償金，免納所得稅。這個條文，本質上是在説明生命或身體所受之損害，而獲得的賠償金，并非所得稅法上的所得。
生命或身體所受之損害的固有利益的損害賠償，即使是通過和解去做約定賠償的數額，雖然會從法定之債轉成契約之債，也就是說，在民事法上面，金錢的給付會從侵權行為損害賠償變成的事契約之債務不履行的損害賠償，但他本質上仍然還是來自於因為生命或身體所受之損害產生出來損害賠償，他並不具有所謂的所得的適格的地位。相反的，替代履行利益之損害賠償，也就是我們稱之為叫履行利益的損害賠償。由於他是經濟成果的替代，而經濟成果作為所得，是所得稅所要掌握的稅捐客體，替代經濟成果的這樣的一個損害賠償，沒有道理排除在課稅所得的計算範圍外。從而，替代經濟成果之損害賠償，還是所得，仍然應該要有課稅所得的適用，因此沒有法律的明文規定，原則上要計入所得的範圍，他會跟4條一項三款，包括身體跟生命，但不包括財產。財產的固有利益的損害賠償不計入所得，原則上是透過解釋的方法，因為他非所得，而免納所得稅，但不會在4條一項三款內。


相反的，替代履行利益的損害賠償，會是一個非常重要的所謂的經濟成果，原則上還是要課稅所得。特別是我們在上個禮拜跟各位講過，在實務上，特別是在無體財產權這一類的專利或商標的侵權行為裡面，往往存在著所謂的懲罰性損害賠償。論其本質，是按照他的經濟成果去做估算的一種損害賠償。無體財產，並沒有因為有體財產的固有狀態被損害產生出來的填補損害的這一種損害賠償的問題。無體財產，顧名思義，他本身就是一個無體的存在，而未經他人許可而去侵害他人的無體財產所產生出來的這一種計算損害賠償，往往都是經濟成果的替代。正因如此，經濟成果替代的懲罰性損害賠償應被計算入個人或營利事業，因為經濟活動所獲得的所得，是應稅所得的適用範圍。


我們在上個禮拜大致上跟各位提到損害賠償，從這個地方我們開始展開一連串的討論。

接下來這幾個問題點，各位都可以去思考。第一個，損失補償，要不要算所得？個人因為國家的公用徵收行為，因此被國家以單方的公權力所受的損失，我們把他稱之為叫損失的補償，特別是目前在公用徵收法裡面，原則上是用市價補償，究竟這一種補償是接近損害賠償的性質，或者是契約上的價金？特別是，我們在徵收法裡面用接近市價的方式來去對被徵收者的特別犧牲給予接近市價的補償費，我們會說是損失補償，這種情況所領的補償金算不算所得？這是第一個問題。

第二個問題，我們要跟各位去講保險給付。保險金的給付保險來自於一個市場經濟的活動，也就是你去投保保險，投保保險之後，保險事故發生的時候，保險的依照保險契約對受益人所做的給付。並不是加害者對被害者所做的損害賠償給付。他是來自於一個保險契約而產生出來的約定的給付，也就是當保險事故發生的時候，我要去對你去填補，由於加害人可能沒有辦法去對被害人去做足額的賠償，為了填補這個風險產生出來的市場機制，我們把他稱之為叫保險。保險給付算不算所得？這個是我們要跟各位去討論的第二個問題。

第三個問題，是信託財產的財產上的移動。在設定信託行為的時候，原則上會有一個財產上的移動，比如說我是委託人，那麼昱如是受託人，那麼我把財產移動到她的名下，這個設定信託財產的這樣一個設定信託的行為，這個算不算是取得財產者的所得？我想各位很快就會説，不是。那變更受託人呢？也許我變更受託人，我今天從昱如變成逸帆，那么最終信託關係終止的時候，他又要再把這個財產移動回來給我受託人或者是我所指定的第三人。在這一種依據信託關係而做的財產移動，到底算不算所得？

第四個問題，投資取款。投資股款的投入跟取回，就是資本投入跟資本取回，這件事情算不算所得？因為曾經在某一個時期，某些公司溢價發行股份，比如說一張股票面額是10塊錢，由於這一家公司的夥伴非常值錢，大家都想要投資進去，所以會形成，在市場上面額是10塊錢，可是因為大家都搶著買，他可能就變成要20塊才能買到一張面額是10塊錢的股票，這個是一個股本投入的行為。相反的叫投資股本的取回，取回資本的行為，算不算所得？

這四個問題都跟他是不是所得的性質的問題有某一種程度上的關聯，都是在第一個階段的問題要去處理的。我們今天第一個小時前半段的部分跟各位很快的說明這一件問題。

## 【損失補償】

我們首先來談一下損失補償。損失補償跟損害賠償最大的區別不是在名詞，而是，不法的侵害行為所造成的損害，我們把他稱之為叫損害賠償；補償行為則是來自於一個合於法律規定對他人的財產權的干預的行為，也就是在徵收補償費的發放的情境裡面，他是一個合法的作為，國家高權公權力的作為。這種國家高權公權力的作為剝奪了相對人的財產權。在這樣一個前提底下，第一個層次，是對公用徵收的合法性跟正當性的檢驗。那么第二個層次才是進入到即使肯認了國家基於高權行政對人民所擁有的財產權，得以在合法跟具有正當性，也就是具有公用徵收之必要的前提底下去干預人民的財產權，仍然還要在第二個層次裡面，必須要國家提供給受到特別犧牲之相對人，以所謂的接近市價的補償的方式，來做市價的補償費的發放，這個就是所謂的損失補償。

兩個不同階段，各自依照各自不同的法理，基本上都在比例原則的這個思考底下，去對相對人因此所受到的特別犧牲，去做合於法治國的考量，損失補償，接近損害賠償的性質嗎？特別是我們現在在公用徵收裡面，有提供要先提供一個讓相對人可以去參與關於該公用徵收的所謂的「協議價購程序」，也就是在國家發動公權力去做多用徵收之前，在法定程序上，必須要給予當事人有思考的可能，是不是可以透過一個買賣的方式來達成所謂的用契約的價購的方式去替代原先所想要進行的國家公權力行使的第一層次的公用徵收跟第二層次的所謂的市價補償程序。

協議價購，是私法契約的性質，還是是公法契約的性質？學說上有高度的爭議，我們在這裡面一併地去說明協議價購的補償金的性質。

第二，我們再講，如果協議價購不成，國家仍然發動公用徵收程序，因此在第二道程序裡面去做損失補償費的發放。這究竟是屬於所得性質的經濟成果的替代，還是是屬於非所得性質的損害賠償，在學理上有討論跟說明的可能性。

特別是某一些認為以接近市價這樣一個性質的補償，特別在前階段有一個協議價購程序。協議價購程序，如果把他當作是一個私法契約，換言之就是視人民把他的土地賣給需地機關（需要土地的這一些國家機關，包括中央包括地方機關），因此認為這是一個私法契約，在這樣一個前提底下，這樣一個程序產生出來的履約的價金，當然是經濟成果，當然是所得稅所應掌握的課稅所得的範圍。

換言之，這種觀點認爲，在國家開啟公用徵收的必要性之下，國家仍然還是要實施單方的公權力來剝奪人民的財產權，但為了避免國家違反比例原則而過度徵用干預人民的基本權，因此在第二個層次裡面提供給予人民接近於市價的補償（現行實務上是以公告現值加四成的方式去計算的），這個損失補償費這個法律上的性質因此被認為是一個經濟成果的替代，而認為應該是課稅所得的範圍。

這個是一個看法。但我個人認為這個看法是不對的。我們先暫且不談協議價購，因為後面再過來談這個事情。損失補償在前述的說明底下，他其實是在國家發動公權力徵收的，這種情況底下對被徵收之相對人，因此所遭受到的特別犧牲的一種對價回饋。簡單而言，就是因為你特別犧牲，從而國家提供一個市價的對價的回饋。這種方式，非基於自願性的參與市場經濟活動，從而不是市場經濟成果的替代。我再一次強調，非自願性的參與市場經濟活動，縱使在結果上，客觀上，是接近市價的補償費發放，在這種情形底下，他仍然不是自由意願之下的參與經濟活動所產生經濟成果的替代。

這個問題，恐怕會跟前面那個無體財產權的損害賠償之性質相混肴。專利跟商標未經過授權者的合法授權而被使用，就是，使用該商標跟專利之人，一樣，沒有經由權利擁有者的意願，而直接就非法去或者是逾越授權的範圍而去擴張使用，產生出來的損害賠償，是不是被認為是基於自由意願產生出來的經濟成果，在學理上有進一步討論的空間。
我個人認為，市場經濟活動中，非基於自由意願而產生出來的經濟成果，跟經濟成果的替代，他依然是所得的一種類型。可是透過國家公權力的作為，由於非基於市場經濟活動而產生的對人民的干預，對人民財產權的干預而產生出來的，相對的補償費的發放，並非市場經濟活動所要掌握的對象。老師個人認為，他只是一個對因為高權行政行為產生出來的損害、損失而做的填補，即使接近於市價，仍然不構成所得，不應該成爲課稅的對象。

同樣的道理，有許多在公用徵收裡面，對，比如說土地上的農作物搬遷，在實務上會有一些搬遷補償費。比如說，你住在這裡，我這裡要做公用徵收，我請你搬離開，那往往會存在著許多搬遷的相關的費用，比如說獎勵及早搬離的獎勵拆遷補償費，或者是農作物補償費。如果你願意在一定時間以前能夠搬離開，騰空房屋的話，實務上往往也會發給獎勵的補償金。那麼，以特別犧牲作為前提的話，我自己個人比較傾向認為，在特別犧牲可以涵蓋的最大可能範圍內，盡量給予非所得的屬性，也就是認為這是一個國家公權力行使底下透過各式拆遷補償費的發放，而來完成公法上的任務，也就是爲了滿足公用地的需要，爲了達成公共目的，而對特別犧牲所做的一個單方的補助的行為，因而，這不構成經濟成果的替代。這也是我們目前在實務上基本的看法，也就是透過拆遷給予的相對的補償，或者是徵收給予的損失補償費，原則上免計所得稅的所得。


因此我們再回過頭來，來看一下第4條第三款還有一個後段的規定，各位也許就更清楚背後他的本意。在所得稅法第4條第三款還有一個後段，「依國家賠償法規定取得之賠償金」。國家的不法侵害行為固然是免所得稅的所得，理由不在給予稅捐優惠，因為國家賠償本身是國家的不法行為，從而國家的不法行為，他本質上一樣在填補被害者的不法的受害而產生固有利益的損害賠償，所以第4條的第三款的後段規定，他的本質仍然是損害賠償，作為損害賠償，跟前面的第三款的損害賠償，都是不法侵害行為產生出來的損害賠償。第4條第三款規定，本質上並沒有明文的去提到關於合法的侵害行為產生出來的補償費的發放。這個合法的侵害行為產生出來的損失補償，理論上，實務上，我們在目前的公用徵收的稽徵實務上，原則上是透過解釋函令的方式來免除掉他的稅捐負擔。就此而言，我個人認為沒有解釋函令，在理解上也應該是一致的。

只是這樣子的一個一致性的理解，

## 【變動所得】

我們來看一下在第14條的第三項。這裡面有四種類型的所得，被稱之為叫變動所得。

第一個叫自力經營林業的所得。也就是自己在山上種樹。我有認識一位老師啊，就在山上自己種樹，種一些高經濟價值的這個樹木。人稱十年樹木，他說，他種這個，三十年後可以給他兒子收成。這個叫自力經營林業的所得。

第二種叫受僱從事遠洋漁業，最近八尺門的辯護人很夯，這個議題也大概是這樣。受雇從事遠洋漁業遠洋漁船，出去一次，可能都是兩三年在海上打一次漁，再回來。受僱從事遠洋漁業於每次出海後一次分配之報酬。不管你是船長還是漁工，原則上你一次出去回來的一次的所得，這個是所謂的變動所得。

第三種類型，一次給付之撫恤金或死亡補償。

第四類型，「超過第四條第一項第四款規定之部分及因耕地出租人收回耕地，而依平均地權條例第七十七條規定，給予之補償」。給誰呢？給承租人，也就是地主依照平均地權條例收回耕地的時候，給土地的承租人的1/3的補償費，那個是平均地權條例第77條的規定。

這四種類型的所得，我們在14條第三項裡面，把他用一個名稱叫「變動所得」來加以涵蓋。

這四類型的所得，有一個共同的類型特徵，叫，累積多年所得一次大量實現。由於綜所稅是累進稅率。所以這種累積多年所得一次大量實現的所得，會在累進稅率底下產生稅負急劇增高的效應。比如說你一次自力經營林業，你可能是十年才換到一次經營林業之所得，因為是十年樹木嘛，你現在種樹不可能立刻就有經營成果，你可能十年才獲得一次收入，那你一次就賺個幾百萬，在累進稅率的前提底下，他會產生稅負急劇增高的效果。其實如果綜所稅不是採累進稅率，是像營所稅採比例稅率，這個效果是不會出現的。所以，在累進稅率底下，這種累積多年所得一次大量實現的所得，被認為在這個地方是變動所得，以一半課稅一半免稅來抵消掉這種稅負增加的現象。

那麼我們來看一下自力經營林業所得，其實就是在講自力農林所得，其中也就是他是屬於我們所得稅第14條第一項第六類裡面的自力耕作、漁、牧、林、礦之所得。遠洋漁船一次打於出來回來的一次的所得，本質其實是薪資所得，特別是對漁工而言啊。遠洋漁船的漁工，他本質上是受僱，只是他工作地點不在路上，在海上而已，那麼這個所得當然本質上也是一種薪資所得的態樣，累積多年所得一次大量實現。一次給與之撫恤金，在此之前，必然存在著僱傭關係，因此一次給與之撫恤金其實是薪資所得的後付，也就是你過世之後，再由你的遺屬來取得撫恤金。這個我們在講那個退休所得的性質的時候，會跟各位在進一步去做說明。退休是你的僱傭關係終止之後，雇主或是保險單位繼續根據先前的雇傭關係所做的給付，所以他是一段期間的僱傭關係終止之後，根據保險、根據契約而產生出來的，後面再行給付的金錢給付的法律上的關係。因此這一種撫恤金的給付性質本質上，跟薪資所得一樣。最後一個，地主依據平均地權條例，對土地承租人佃農所做的補償金的給予，我個人在法律性質上認為是一個經濟行政上的補貼，也就是在當時的法秩序底下透過對國家公權力的行使對地主的徵收，然後補貼給承租土地的佃農而產生的一個經濟上的補貼行為。那么，在這樣一個經濟上的補貼行為底下，其實在概念上面，如果是從地主徵收來，然後再發放給承租人，那其實他也是經濟上補助的一種類型，不管是剝奪或給予，理論上都不在所得的範圍。

我們今天跟各位去討論，其實損失補償費，凡涉及國家高權行政公權力之剝奪，或給予，本質上都不涉及到經濟成果或經濟成果的替代。但很明顯的，14條第三項把他列入變動所得的範圍，就會變成，他是所得，只是累積多年所得一次大量實現，所以給予一個計算上的優惠方式去抵消掉這樣的一個稅負急劇增加的效果而已。

在累計稅率底下，累積多年所得一次大量實現，仍然還是一個市場經濟活動的結果，只是他是累積多年一次實現，因為稅負急劇增加，所以我們在變動所得這一類的這個條文規定裡面，給予一個特殊計算方式，就是半數課稅半數免稅。透過這種方式來抵消掉這一種稅負急劇增加的問題跟現象。但他的前提必然是，把這一類的補償費的發放、透過國家對地主的徵收、對佃農的發給，這樣一個經濟行政上的行為，認為他是所得。在這樣一個前提底下，14條的第三項的規定，我個人認為是一個跟現行法秩序互相牴觸的作為。

簡單來講，就是高權行政裡面的作為，涉及國家公權力的行使，不管是干預剝奪或者是給付給予，不在市場經濟活動的經濟成果，或者是經濟成果替代的適用所得的範圍，不是所得。也就是，經濟上的補助補貼不是所得，是屬於高權行政的結果，他是屬於干預行政或者是給付行政，無論是哪一者，都不是市場經濟活動底下的經濟成果或者經濟成果的替代。

因此我們最後面再跟各位去講，協議價購程序確實在法律上的性質存在著公法或私法的爭議。為了讓公用徵收能夠被順利推動履行，協議價購程序先行，讓人民願意配合國家的需用計劃而願意自行以市場的方式把他賣給需地機關，就算他是一個私法上的契約，由於後面的公用徵收程序在現實上，仍然依照我們現行實務的一般的看法，這個部分的損失補償費，並不是課稅所得的計算範圍。

我們先不看14條第三項變動所得裡面的對佃農的經濟補貼，這個例外地被當作是一個所得，只是用變動所得的方式去計算他的所得的數額而已。將這種例外情形排除掉，凡是國家高權行政的作為，產生出來的經濟財產上的移動，原則上他並不構成所得的適格的地位。也因此，協議價購程序，在這個前提底下，為了促進公用徵收的適當地、適合地被履行，我個人比較傾向認為，協議價購，在法律有明文規定的前提底下，應給予免稅的優惠，否則協議價購，同意價購的相對人反而要被課稅，如果不同意架構進入公用徵收程序，以損失補償費的名義取得的補償金，就變成反而他可以免稅。在這個地方，在價值上是不衡平的。你本來是鼓勵他，希望他去做，結果他做的效果是更不利，因為他還要繳所得稅。在這種情況底下，這個反而會讓協議價購程序的目的無法達成。從而，依據特別犧牲理論，往前延伸，關於協議價購程序，老師個人還是傾向，這個協議價購的協議價購款項，不具有所得的適格的地位，應該不要課稅。但為了避免爭議，最好是有法律明文規定。因為他確實在法律性質上被認為具有私法契約的色彩，你自己願意賣的。這個時候如果從邏輯解釋上來講，價購款項會是經濟成果，既然作為經濟成果，法律沒有明文規定，那就應該要課稅，那這個反而會讓協議價購作為公用徵收的前置程序，目的無法順利達成。從而，從整體來看，關於協議價購的價購款項，老師個人認為，以法律有明文規定，而去對相關的款項給予免稅的待遇為宜。

這個是關於損失補償。現行法律在沒有明文規定的操作實務上，任何關於徵收補償費，包括拆遷、農作物補償，甚至是你提早搬離開，減少行政機關的公務人力、徵收上的費用的相關的獎勵，基本上全部都在免稅的所得適用的範圍。沒有法律明文規定，因為4條一項三款並沒有提到損失補償，只有講國家賠償的損害賠償不計入所得的範圍、不適用所得課稅的範圍。也因此在這個地方，我們以特別犧牲理論作為他的正當性的基礎，因為他是填補犧牲所做出來的補償費，性質上面非屬於經濟成果替代的所得。


我們再回到14條第三項所講的變動所得。變動所得這一種累積多年所得一次大量實現的情況，基本上也是建立在實用性原則的基礎上，而提供給予變動所得的納稅義務人一個簡便計算方式，來取得這一類所得來抵消，或者是避免所得稅因為採用累計稅率所產生出來的稅負急劇增高的不利現象的一種方法。因此他是一個在實用性原則底下提供稅捐優惠的一種方式。這一種累積多年所得，我們直接給予半數課稅，半數免稅的這樣一個做法是便利計算的做法。簡單來講，就是我不採用比較複雜的方式，譬如說立法者把你個別所得歸算個回去各年度，再回推以各年度的繳稅所得重新計算你的綜所稅的稅負，這個也許比較符合各年度依據稅捐負擔能力個別計算的課稅所得，但比較麻煩，因為你必須要各年度去做歸屬計算，而且要變更原先的所得。那么，在這樣的前提底下，變動所得是一個比較變通的便利性的計算方法。基於這樣子的一個角度而給予稅捐優惠。從而變動所得的性質，理論上可以適用到各種，如果存在有客觀上累積多年所得一次大量實現的類型特徵上面，應該可以類推適用。

但我國實務上，採取嚴謹的看法認爲稅捐優惠只是例外，從而僅限法律明定的四種類型，才稱之為叫變動所得。凡是不屬於14條第三項所稱的這種變動所得的列舉類型底下，縱使有累積多年所得一次大量實現，仍然要依據所得的取得年度來計算，義務人應該負擔的稅捐負擔。實務上最常出現的案例是，勞工被雇主非法解雇，那么他就請求確認僱傭關係存續，並且要求雇主依然還是要繼續給付薪資。對於這一段他實際上沒有上工的這一段時間裡面，他除了確認僱傭關係存在以外，還要求雇主必須要去做依照原先僱傭契約的條件所做的僱傭的薪資所得的給付。當他最終獲得勝訴的時候，可能會有累積多年所得一次大量實現的客觀上的情況。也就是假如他打了五年的訴訟，最終終於獲得勝訴，雇主也依照判決的內容對他做一次性給付，那麼他在當年度就會一次大量實現五年度的所得。累積多年所得一次大量實現，在適用綜合所得稅的前提底下，一定會產生稅負急劇增高的不利的效果。因為本來每一年的薪資會分散的在累進稅率底下，可能是用比較低的稅率，但是五年一次大量實現一次，大量給付，就必然會產生這種稅負急劇增加的效果。

實務上的看法，認為變動所得的計算方式是一種稅捐優惠，作為稅捐優惠要例外而嚴格的解釋，從而非在法律所規定的範圍內的變動所得，縱使具有累積多年所得一次大量實現的特性，也不適用第14條第三項，半數課稅半數免稅的稅捐優惠待遇。也就是目前為止我們的累積多年所得一次大量實現，特別是剛剛所提到的非法解雇而因此所取得的一次報酬的給付，往往都還是會用累積在你那一次受領的時候就一次去課徵他的所得稅的所得，而在這種情況底下，他會從薪資所得的類型變成其他所得，也就是在這裡面會用其他所得來歸類，認為他是一個綜所稅裡面的一種所得類型，然後全部去計算課稅。

那么如果你是人死了，領撫恤金，就可以認定爲變動所得。所以立法者是告訴你說不要活著啊，你最好是去跳樓自殺，你的一次領取的撫恤金，可以用變動所得的方式，來計算你的課稅所得。稅法上的立法者是這樣告訴你的。我隨便說說啦。這個，我只是讓各位看看立法者背後的荒謬的價值決定。立法者不是永遠是對的，也不在立法形成空間裡面的合法適當的一個展開的方式。


14條第三項目前被認為是稅捐優惠，那麼因此比較嚴格地去做解釋。

## 【保險給付】

基於這樣的一個說明，我們接下來進入保險給付。

保險給付正如同剛剛所講，他是一個市場經濟活動。除了法定的保險以外，商業保險的市場經濟活動的特性有更為清楚明白。你不投保保險，保險事故發生的時候，你就不會從保險公司保險人獲得保險金的給付。保險給付是接近，如果無法受加害人的完全給付時，最能填補損害的機制。也就是對於加害人對被害人無法做完全損害賠償的風險，保險是一個風險的共同體集合。簡單來講，大家都有同樣的風險，風險發生在一個人身上的時候，他是100%。沒發生，就沒發生，發生在你身上，那就是100%。那么，由於這種風險發生在個別人身上的時候，他是100%的損害，他可能因此陷於經濟上的無能力去應對，從而，即使他是一個市場上的經濟活動，在填補損害的這一個方面來講，保險金給付也是一個最接近填補損害賠償的一種風險的分散機制。也就是說，他是一個市場經濟活動，我們承認，但是他是一個替代損害賠償的一個風險分散機制，這個特別是表現在財產保險，他原則上沒有有所謂的代位求償的機制，也就是說，被保險人在保險事故發生的時候，保險人對受益人所做的給付，可以在他給付範圍內去代位被保險人去對導致保險事故發生之加害人去做求償。也就是代位權的行使在保險法裡面避免了所謂的道德上的風險，也就是人們透過過度投保的方式來將投保行為當作是一個中樂透的行為。那么同樣的道理，也就是說，在保險裡面，特別是在財產保險裡面有代位的請求，他是最接近損害賠償的市場機制。因此在這樣一個前提底下，保險金給付作為一種損害賠償的替代，老師個人傾向認爲，他是確實是具有非所得的屬性。財產保險本身作為一個損害賠償的替代，而不是經濟成果的替代。儘管保險本身確實是一個市場經濟活動。

但接下來我們要講的是沒有代位權行使的，包括人壽保險跟年金保險，這一類保險法裡面認為沒有過度投保的問題的這一類保險給付。年金保險其實是人壽保險的一種生存險的類型，就是被保險人在時間到了以後基本上還繼續存活，他可以可以繼續透過年金保險的領取來照顧他老後的生活。那麼從而人壽保險裡面特別是生存險跟年金保險的性質，在某程度上面來講，這一類的保險金給付是為了照顧自己老後的生活而產生出來的市場機制的一種為照顧自己的老後生活的風險分散行為。沒有所謂的損害，沒有所謂的損害賠償的問題，因為老不是損害，他是一個自然現象。

正因為如此，人壽保險跟年金保險，是不是要給予像財產保險這樣的非所得的市場定位？老師個人是採取比較傾向，他是一個鼓勵人們投保的稅捐優惠做法
，而不是替代損害賠償的保險金給付而非所得。

人壽保險因為分很多，有這個所謂的身體健康險，這個由於實支實付定額給付，我們原則上如果不區分其類型，沒有過度投保，仍然是屬於損害賠償的風險的承擔，從而這個部分不是所得的類型。可是屬於生存的，特別是照顧老後生活跟經濟活動所需要的這一種年金保險，他比較接近，是一種市場上的經濟活動的成果，也就是你投保多少，你將來就可以從透過年金保險而去取回多少，那也因此這一類型的保險的給付則比較具有經濟成果替代的性質，從而具有所得的適格的地位，因此需要透過法律的明定的方式給予適當的鼓勵。也就是定額免稅的方式，鼓勵人們投保保險，照顧自己老後生活，而不要等風險事故發生的時候，在你身上100%造成了其他家人的負擔，或者是造成國家社會行政上的負擔，因為沒有家人照顧的個別的國民必定會進入社會安全網，給社會安全網去照顧。這也是在稅捐優惠政策上面，鼓勵人們行有餘力的時候，照顧好自己，透過保險的方式去照顧。所以，定額給予免稅是適當的。至於定額為多少？原則上是以當代社會人民的平均餘命，以及通常的生活水準，特別是在某些職業類別上面，有一定程度上的生活水準，不是每一個人都是最低生活需求。

年金保險不是社會保險，不是社會救助。社會救助是以一個當地社會最低生活費的基準，但年金保險是一個職業上的保險，這種職業保險是有一個對應他職業老後生活的一個該有的生活基準。也就是如果他是一個某一個職業類型，他老後的生活，他之前可以領4萬，退休之後也不能差距太遠的，這種情況，在行有餘力的可能範圍內，應該要給予鼓勵人們照顧好自己老後的生活，因此會根據當地社會的平均餘命、職業收入標準，跟生活費用，去做一個合理的估算。以這個定額作為估算的基準。超過定額，就是過度優惠，會產生人們的規避動機。也就是如果所有的保險金給付一律免稅的話，就會讓人們透過用投保的方式，來享受那個優惠，這就是稅捐規避。

稅捐規避就是一種由於過度優惠措施而產生出來，人們透過私法形成來享受稅捐優惠的一種狀態。是立法者給的，不然他不會去起心動念想要獲得那個利益。

這個正是我們在保險金給付的性質裡面，我們從財產保險給付開始，其實是損害賠償的替代，特別是一個風險的承擔；那麼來到了人壽保險裡面，關於身體健康這種意外險性質，由於不管實支實付還是定額給付，原則上都是替代身體健康的這一種固有利益受損，但可能被害人無法從加害人那裡完全地求償，因此產生出來的風險的承擔，從而老師個人傾向認為這一整塊都是屬於損害賠償的替代，他是一個風險承擔的概念，他不是所得，就算法律沒有明文規定，也適當地給予免稅的待遇。但進入到保險給付裡面屬於照顧自己老後生活的這一種生存險，特別是年金保險，本質上是透過市場經濟活動裡面產生出來的一種經濟成果。那當然，年金保險，由於他都是透過法律的明定而產生出來的強制投保的態樣，因此就這個地方在法律性質上，根據我們第4條的第七款規定，你只要在法律所規定的人身保險、勞工保險及軍公教保險之保險金給付，原則上你只要是法律所定的強制投保的保險範圍，由於法律明定，在此限度範圍內裡面受到強制的行為，本質上就把他排除在所得的適用範圍之外，也就是不是所得。這是來自於法律的明文規定，這個限度範圍內（不是所得的範圍），解讀為給付行政。可是我如果是投保商業保險產生出來的人身保險的給付，理論上而言，他是一個照顧自己老後生活的保險給付的話，這個是因為你投保，所以你有獲得保險公司對你的保險給付，是一個經濟成果的類型。在這裡面，因為第七款的規定沒有給予一個定額的保險的額度，從而就會產生過度優惠的狀態，人們就會利用人身保險，來做比較高額的投保，這就是為什麼實務上投保保險可以節稅的一個很重要的原因。人身保險在保險金給付多少額度範圍內，沒有一個上限規定，正是因為沒有上限規定，從而人們會願意只要行有餘力，有可能，我會把我的儲蓄投資改成用保險的形式，我不要儲蓄投資，我不要拿去買臺積電股票，我改去買一張保單，透過保險的方式來把他轉換成人身保險的保險金，這個地方根據第4條第七款的規定全額免稅。這就是保險節稅規劃秘籍，來自於一個沒有上限的一個保險金給付全部免納所得稅的規定。財產保險不會有這個問題，死亡保險原則上也沒有這個問題。問題通常都是來自於人身保險裡面的生存險，特別是年金保險，非法律強制規定的這一種人身保險的性質，會存在著過度優惠的問題。這是保險金給付的部分。

我們先休息一下。