# 20231127_01

---
課程：1121所得稅法一
日期：2023/11/27
周次：13
節次：1
---


## 【稅捐稽徵程序，結算申報繳納】

進入稅捐稽徵程序裡面的申報。

我們的所得稅法第71條的規定底下，是關於納稅義務人的結算申報的義務。

71條第一項的規定：「納稅義務人應於每年五月一日起至五月三十一日止，填具結算申報書，向該管稽徵機關，申報其上一年度內構成綜合所得總額或營利事業收入總額之項目及數額，以及有關減免、扣除之事實，並應依其全年應納稅額減除暫繳稅額、尚未抵繳之扣繳稅額及依第十五條第四項規定計算之可抵減稅額，計算其應納之結算稅額，於申報前自行繳納。但依法不併計課稅之所得之扣繳稅款，不得減除。」

條文規定是用納稅義務人，其實並不是所有的納稅人，應該是要比照71-1第一項的主體的規定，「中華民國境內居住之個人」。因為，71條的「納稅義務人」並沒有包括非境內居住者。非境內居住者之所得，是用第88條跟89條的就源扣繳的規定，去做所得稅的稽徵。

因此在第71條第一項規定裡面，境內居住之個人的納稅人，應該在每年5月1號起至5月31號止，他的協力義務是填具申報書向該管稽徵機關申報，他上一個年度內構成綜合所得總額的項目跟數額，以及有關減免扣除之事實，並應依其全年應納稅額減除掉，尚未抵繳之扣繳稅額，及15條第四項規定之可抵減稅額，也就是兩稅合一裡面，容許納稅人可以去用可扣抵稅額8萬塊錢的這個部分，計算其應納之結算稅額，於申報前自行繳納。

因為我們的法條規定，他是把綜合所跟營所放在一起，所以我剛剛在念的時候，特意把跟營所有關的，排除掉。

我再念一次。境內居住之個人之納稅義務人，應於每年5月1日起至5月31日止，填具結算申報書，向該管稅捐稽徵機關申報，上一年度構成綜合所得總額之項目及數額，以及有關減免扣除之事實，並應依其全年應納稅額減除掉扣繳稅額，及15條第四項規定計算之可抵減稅額，也就是兩稅合一的一戶8萬塊錢的可抵減稅額，計算其應納之結算稅額，於申報前自行繳納。

這個是我們的稅捐申報義務。

釋字531號認為，結算申報義務是合憲的。

71條的第一項第一句的規定，體現了，應納稅額減掉扣繳稅額跟可扣抵稅額，之後得到結算稅額，這個規範結構。

應納稅額，其實是要連接在前面的第17條。我們17條的規定是，依第14條所規定所計算出來的應納稅額的總額，減掉第17條的主觀淨值之後的應納稅額的淨額。這個是應納稅額金額的規定。透過這個條款規定之後，應納所得總額的淨額，還要再回過頭，乘以第5條第二項所規定的綜所稅的稅率，才會得到應納稅額的這個課稅結構。然後之後再依據71條第一項第一句之規定，減掉扣繳稅額跟扣抵稅額，得到結算稅額。

這個部分，雖然體系上放在第71條第一項，但到這個地方為止，還是屬於稅捐實體法，也就是所謂的法律效果的規定。也就是說，我們在課稅構成要件裡面屬於稅捐實體法的部分，包括主體、客體、稅基、稅率。這個都是屬於課稅構成要件的規定。稅基乘稅率，會得到應納稅額，再減掉兩項。性質上，第一項，扣繳稅額，是預先繳納的稅額，是納稅義務人透過88條跟89條規定做就源扣繳程序，所以是事先繳納的稅額。而第二項，可抵減稅額的部分是某種程度上，稅捐優惠的性質的可扣抵稅額。

如果假設我們的第2條第一項是採全球所得來源都課稅的話，這個部分也會包含外國可扣抵稅額，只是我們的綜所稅沒有這樣一個外國可扣抵稅額的制度設計，因為我們本來就是採屬人主義。

到下個學期，我們下一次上到營利事業所得稅的時候，就會有這個部分。而所得營利事業所得稅，會有3個可扣抵稅額，包括了暫繳稅額，包括了被就源扣繳的扣繳稅額，以及可扣抵的稅額。而可扣抵稅額，裡面包括了外國可扣抵稅額，以及稅捐優惠提供給他的可扣抵稅額。最後算出來的結算稅額，才是實際上應該要繳納的稅額。

老師個人是認為說，在那個地方規範的結構上面，不太看得出來實體法跟程序法的區別。基本上實體法規定應該是要一直到結算稅額出來。出來以後，所得稅法第71條的規定，才將前面的結算稅額，再依照我們今天所剛剛所念到的規定，你應該在每一年5月1號到5月31號這一段時間裡面去做結算申報的程序，這就是你的協力義務的規定。

這個是我們跟各位去談到關於，課稅法條規範的結構的關係。從稅捐稽徵法這個部分的規定，如果我們的稅捐稽徵法能真的擔負起總則性規定的話，原則上這個部分他就是全部放到稅捐稽徵法裡面去規定。

德國稅捐通則就是這樣一個規範結構，把所有的稅捐稽徵程序，跟制裁規定全部都放到他們的稅法通則裡面去。所以他們的所得稅法的規定，就只限於是稅捐債務法，也就是構成要件跟法律效果的規定。課稅規範的結構，如果體系能夠比較清楚呈現，會是這個樣子。

當然，如果一個國家可以制定出一部統一的稅法典，統一稅法典的課稅規範結構的規定，也會是類似這樣一個情況。有總則法的結構。

總則法，從稅法的基本原則，到計徵程序，制裁的規範，然後接下來各稅，有點像我們的刑分，有稅法的各論，從所得稅法，一直到財產稅交易稅跟營業稅。這樣的那個規範結構，就會變成是一部統一的稅法典。

不過統一稅法典不太容易做得成哈。至少到目前為止，如果從各國的比較立法來講的話，是美國有做到，因為他有一部IRC（Internal Revenue Code）這樣子的一個聯邦稅法。因為他是一個聯邦制的國家，所以他把他們所有的聯邦課徵的稅捐，基本上都是放在聯邦IRC裡面去。我聽黃源浩老師說，法國也有，法國也可以做到這個。因為我不會讀法文，所以我不太能夠有這個智慧去講到這個。


我曾經有對我德國的指導老師，跟來臺灣的德國教授問過，說德國有沒有可能做一部統一的稅法典。因為這也是稅法學者的，共同努力的目標啦。那我問到的教授是跟我說，這個以德國的政治環境不太容易啊。德國，基本上也就是稅總，把所有的稅捐稽徵程序、制裁，全部都放到德國稅捐通則。各稅基本上也是分散式的立法。

那我們臺灣的稅制規範的結構是，各稅裡面有稅捐稽徵程序。稅捐稽徵法這個名目，並不是真的是總則法，毋寧是把各稅的稽徵程序又放到我們稅法的各稅法裡面去。所以你看，我們現在在所得稅法71條底下，有結算申報程序，而且這個結算申報的「結算稅額」，這個概念在所得稅裡面才有。其他稅沒有。其他稅，只有「應納稅額」的概念。其他稅裡面，算出稅基乘稅率，之後就是得到應納稅額了，因為沒有預先繳納的問題。


在所得稅裡面才會有「結算稅額」的概念。當然，我們沒有上到那個財產稅。財產稅裡面，地價稅跟土地增值稅裡面，其實也有一種調整土地地價稅的稅額，可以去扣抵土地增值稅的稅額。那就是說，誒，你把地價調高，多增加繳納出來的那個地價稅，可以拿去做扣抵土地增值稅的稅額。但那個地方我自己個人認為說，那個土地稅法規定是一個不對的規定，是一個錯誤的規定。因為地價稅是財產稅，跟那個土地增值稅，他是資本利得稅，他是所得稅，性質是不一樣。

你不能拿財產稅來去扣抵所得稅額。只有同類稅額才可以扣抵。財產稅是所得稅的所得經濟成果的前提，所以財產稅可以當成本可以當費用，但是就不能扣抵稅額。我們沒有要講財產稅。我只是說，前提要件的這個課稅，要做稅額扣抵，必須是同類型的所得。所以我們到遺產贈與稅法裡面，也會提到，贈與稅可以去拿去扣抵遺產稅，同類才可以扣抵。同一個類型的稅額，才會具有互相計算扣抵稅額的問題。那這個我們到所得稅法三的時候會再另外去談到，被繼承人死亡，然後繼承人繼承，然後繼承人又很快又死亡。前面繳的那個遺產稅，可以扣抵後面的遺產稅。


視為遺產，裡面也會有把前面的人繳過的贈與稅，拿來後面在遺產稅裡面去做扣抵。同類的，可以扣抵，不同類的，沒有扣抵的問題。不同類，原則上是要看，可能是成本，可能是費用。

其實到這個地方都還是屬於稅捐債務法的規範的內容。


這個之後就是，納稅人應該在每年5月1號到5月31號結算申報繳納。在此之前，國家沒有稅捐債權的期前請求哦。在此之前，即使課稅構成要件該當，國家沒有期前債務的請求權。除非他另外構成該當稅稽法第25條的規定，期前請求。

因為這個履行期限是法定的，提前請求必須要有稅稽法25條所規定的納稅人隱匿或者是脫逸財產執行的情況，國家才可以去做期前請求。

不過這個期前請求，目前為止沒有看過稅捐稽徵實務上用過。稅稽法24條的稅捐保全手段，常用，包括假扣押、未供擔保假扣押，或者是那個限制出境，這個還蠻常用的。可是25條的期間請求，我嘗試查過實務上的判決，基本上沒有找到。

期前請求的概念就是說，在稅捐構成要件該當之後，到稅捐債權債務以法律規定來請求之前，也就是在申報期限之前，那如果有產生了那個納稅人隱匿，或者是脫產啊，就是規避這個稅捐執行的跡象的時候，稅捐稽徵機關，可以在期前的時候，來去做稅款的保全動作。

因此稅稽法25條也是一種稅款保全程序的一環。

回到我們這個地方來。在5月1號到5月31號之前，這一段時間就是申報期間，這也是納稅人自行申報繳納的期限，因為我們是報繳合一。申報跟繳納，報繳合一。那這個報繳合一制度，根據立法者的說明，認為說，如果採取申報，待核定之後再繳納，就是，申報、核定，然後再繳納，會因為稅捐稽徵機關核定時間的長短，產生了繳納期間差異的問題，被認為不公平。所以我們的制度把繳納制度移動到前面來，也就是申報跟繳納合一的制度。這就是71條第一項第一句的報繳合一制度。報繳合一制度，因此構成了我們稅捐稽徵程序裡面，我國主要稅捐徵收的一種最主要的型態。

在稅法總論裡面，我們按照稅捐稽徵程序的方式裡面的申報、繳納、核定，或者是申報、核定、繳納，而去做一些區別。

那這個地方我們的法律規定，確實是比較紊亂的。

德國，稅制基本上是，申報，之後待核定，之後做繳納。所以德國人的解決問題的方式是這樣，你申報之後，我就我也怕剛剛講的那個情形。就是在德國來講，也可能會有這種，比如說柯格鐘納稅的時候，你就等了一年才給他核定，那柯格鐘就可以合法有效地一年之後再來繳稅。那如果是柯小鐘的，就6個月就給他核定，那這個時候是不是很快就要去做繳納？

所以德國人的做法是一個，先按照申報數去做核定，然後做一個「事後查核權保留」的附款。簡單來講，核定，為了要保持原則上先後不差超過6個月以上的前提底下，稅捐稽徵機關會先依照你申報的數額，來做一個附事後查核權保留之行政處分。核定當然是一個行政處分，所以各位去看行政法的教科書，裡面，行政處分，有附條件、附期限、附負擔，還有一個叫附事後查核權保留。這一類型專門就用在稅制裡面，因為稅捐本身是大量行政，你申報過來的，我需要好好地調查，那我不可能每一個都6個月內都核定完成呀。這個時候，他做這個程序，就是讓稅捐機關，在適度地有這個時間去調查的前提底下，事後查核權保留，也讓法律行為本身構成了明確性。

你這個案子，我還需要再進一步調查，那我就跟你講一個事後查核權保留。行政實務上，德國是會直接講明，我還需要多久，比如說我還需要6個月，那我就寫，事後查核權保留6個月的時間。好，到了時間到了，如果稅捐稽徵機關仍然還沒有調查完成，特別是涉及到境外課稅事實的調查，那稅捐稽徵機關，可以再説明，基本上是不附理由的說明，他還可以因為這樣一個調查的因素，還可以再延長，可以繼續延長。而這個繼續延長，都是為了讓納稅人明確地知道啊，你這個案子還需要更長的查核時間，而這個地方構成了一個信賴基礎。

也就是說，在這裡面，一方面是行政機關保留事後查核權，是一個期限的保留，而這個期限的保留，納稅人可以信賴說，好，原則上6個月後，這個案子應該就會確定。可是如果6個月之後，稅捐稽徵機關仍然還是有待證事實未查核。比如說境外課稅事實，因為特別要經過稅捐資訊的交換，需要一段比較長的時間。稅捐稽徵機關還可以再做一個延期，而這個延期最後不能超過整個的核課的期間。因為這個是國家稅法上債權行使的核課期間，也就是請求權的期間。

因此整個德國的稅捐法制的結構跟精神，就會彰顯在法律行為的明確性，也就是行政處分的明確性、法律上的明確性，以及提供行為人足以作為信賴基礎的這些明確性的行政處分。

在臺灣，用的結構不太一樣。就是我們把繳納放到前面來，後面的這個核定，早期的所得稅法是連核定都沒有。也就是說申報繳納，如果稅捐稽徵機關認為沒有錯，沒有核定的處分。一直到民國98年，我們才以公告代核定，用公告的方式代替實際上的核定。也就是說，因為我們一開始我們採取的立法的體系，是國家先收到稅款，那假如他收到稅款以後，認為沒問題的話，那麼早期是沒有核定，就沒有任何事情發生。

如果你被查到應繳納稅款的事實，但你沒有申報，那這個時候他當然就會做一個補稅單，補稅，就有一個補稅的行政處分。補稅當然是一個行政處分。就算稅稽法第16條跟你講，補稅通知單，用通知這個概念，他仍然是一個具有規制效力的對外的行政處分。補稅，當然是一個行政處分。


## 【溢繳稅款返還 vs 退給稅款】

即使是退給稅款好OK，因為有可能你自己自行計算錯誤，你算錯了，稅捐稽徵機關主動發現，他就退給你，這個退給稅款。理論上來講，應該是不構成行政處分，應該是不構成。但如果說稅捐稽徵機關沒有去做這個返還稅款，這個時候，納稅人可以根據當時候的稅捐稽徵法28條的規定，可以去申請，他自行計算錯誤，因為是我自己報繳的，那我算多了，算錯了。因為以前特別是用手算、人工算，沒有電腦的時代啊，容易會算錯。在這種情況底下，稅稽法28條提供一個機制。理論上，本來稅捐稽徵機關要主動發現計算上的錯誤。總而言之，你報繳稅捐都是納稅人自己自行申報的繳納的，然後他繳納了100塊錢，結果他最後面，因為他算錯了，其實他只需要繳50塊。本來稅捐機關應該要主動退還給他稅款50塊，那個理論上是個事實行為而已，因為國家的課稅債權只有50塊錢要滿足。那你自己繳納100塊，是不是多了50塊，那我就還給你50塊。可是如果稅捐稽徵機關沒有還，那這個時候28條給納稅人一個公法上的請求權，讓他可以去請求稅捐稽徵機關，因為我自己計算錯誤，從而我請求你退還給我溢繳稅款，有一個溢繳稅款返還請求權。這個時候就產生了我們當時的稅稽法28條的規定。所以當時98年以前的稅稽法28條就是納稅義務人因自行計算錯誤，可以向該管稅捐稽徵機關申請為溢繳稅款返還，當然他法條文字都還是寫退給稅款。


那我在稅法總論裡面，我都會講，這個叫返還這個叫溢繳稅款返還。就是國家稅捐債權只有50塊，納稅人自己算，算錯了，算100塊，那當然那另外50塊是無法律上原因啊，國家不能保有，所以當然是一個公法上不當得利的返還。本來應該是要稅捐稽徵機關主動發現，要還給人家的，但沒還，給納稅人一個公法上請求權，讓他可以去請求，所以請求該管稅捐接機關去返還他。

所以我個人一直講，那個是「溢繳稅款返還」，返還，不叫「退給稅款」。因為退給稅款是有公法上的原因，有法律原因的退給。這種退給必須要有法律的明文規定作為依據。

一個叫有法律原因的退給，一個叫無法律原因的溢繳稅款返還，這兩個不能分辨清楚，一直都是我們稅捐稽徵實務，乃至於學界，很大的問題所在。因為兩個的舉證責任分配是不一樣的。

溢繳稅款返還，是稅捐課稅構成要件的該當與否的問題，原則上是稅捐稽徵機關要負舉證責任。

相反的，退給稅款，因為是依法律規定的退給，從而是要有主張有退給權的請求權人，也就是基本上是納稅人，這一方要來負擔退給稅款的舉證責任，證明各項退給稅款的構成要件該當性。

這個是完全不一樣的概念，到目前為止，還是很多人不太清楚這個依法退給，跟不當得利的溢繳稅款返還的概念。


## 【報繳合一】

回到我們這個地方的報繳合一制度。在報繳合一制度，我們的早期的稽徵實務上面，除非是補稅，不然不一定會出現一個核定稅捐的行政處分。

從民國98年之後，有一個公告代替核定的處分。因此公告就變成是代替個別核定，到目前為止沒有特別去說明這一個性質到底是什麽。因為公告，顯然不是法規命令，不是一般的抽象性的命令。他是可以被具體化的，對特定人產生效果，至少是宣示了一件事情，說，欸，你申報的稅款跟繳納稅款，我收到了，目前為止沒問題。因此他不會是一般性的抽象的命令。這個公告的性質還是要請各位特別留意哦，因為在不同的法律規範裡面，比如說公告地價公告現值的公告，在財產稅裡面的那個公告地價跟公告現值，目前實務上是把他當作法規命令喔，他是不能救濟的。地價的公告是非具體的行政處分。

好，但接下來我們講的，如果是處分，具有個別具體規制的。這個是對物對人所做出來的一般處分，或是個別具體的行政處分？一般處分，或者是行政處分？欸，這個是沒有特別被探討過的喔。我個人比較傾向，他不是一個對物，或是對事件的公告，公告的方式，上面有講你的稅捐申報的單位，是有編號的。所以他的公告是一個具體的，集合在一起做成的，對數個可茲辨識的納稅義務人跟申報戶的一個行政處分，所以他是一種集合性行政處分。


比如說，今年大家所有的同學都申報稅捐了。假設今天A同學，我看到他漏報所得，我就給他一張補稅單，這個當然是個別具體的行政處分，沒有問題。好，其他同學，沒問題，我就貼一個公告，就像我們考試院的榜單公告一樣。那個是具體的吧？但他不是一般處分哦，他是集合在一張榜單上所對外所做的一個具體的行政處分。

從而他在公告的性質上面來講，比較是一個集合性的行政處分，也就是數個行政處分，在一張公告上去做完成。

我要跟各位去說，公告這件事情，在不同的稅法裡面，同樣的公告有往往有各式各樣不同的可能性。我剛剛講到公告地價、公告現值的公告，他本身是抽象性的法律命令。房屋稅的房屋評定標準價格的公告則又構成具體的行政處分。開徵的公告，每一年地價稅開徵時期裡面所做的開徵公告，這個又不構成具體的行政手段，因為這個公告他是一個法規範遵循的宣示，也就是宣示，請大家注意，請大家注意，什麼時間開始，我們要開始開徵地價稅了哦，有要申請稅捐優惠，要申請稅率上優惠或是什麼優惠的，請趕快在什麼時間以前，備齊你的資料。這種公告不具有個別規制效力，不能作為行政救濟程序的標的，那也不是一個所謂的可以被提起行政程序的一個標的。

也因此，公告的這個法律性質要做個別的判斷。當然了，回到我們所得稅法裡面，由於是公告代核定的方式，因此公告可以被理解為是一個行政處分，但，問題是，現在目前實務上沒有人就這個公告核定來要求，如果我有請求要做溢繳稅款返還，不需要對全體的公告來去做行政救濟程序的處分的救濟。簡單來講，就是也沒有去對這個公告來去做行政處分的救濟。相反的，納稅義務人如果應繳未繳，沒有繳納足夠的稅額，稅捐稽徵機關也一樣會透過補稅單的方式，無視於這個公告的存在。也就是不管他有沒有信賴基礎可言，無視於這個公告的存在。

當然啦，你可以講一件事情，就是說，因為納稅人申報的數額，沒有把他應繳納所有的稅款的事實，全面性地去做申報，從而稅捐接機關在不變動前面公告的前提底下，另外，再就他稽徵所查到的漏報繳所得稅的事實，再來去做補稅的行政處分。

所以我們實務上就會構成了，你先前所做成的申報核定，構成一個行政處分，後面我再查到你有臺大所得，你有成大所得，但你只報臺大所得，成大所得沒報，那我就再根據成大所得查到的事實，再給你一張補稅單，構成並存式的兩個行政處分，並存式的行政處分。



德國，會是撤掉前面的行政處分，以新代舊，也就稱之為叫取代說，變更說。就是以新代舊。你成大臺大所得全部都加起來算出一個所得額，這個就是總額主義的總額。

所以，永遠，一個納稅義務人的一年，當年度的一個稅捐事件，只有一個課稅處分上面所載的數額，永遠都只有一個行政處分，救濟程序的標的就是在上面所載的稅額。這個就叫總額主義。透過這樣子的總額主義，原則上一個稅捐救濟事件可以在一次的紛爭解決程序裡面把他解決完。

德國的稅捐法律體系，比較體現出一個稅捐債權債務關係，一個課稅的行政處分。一個課稅的行政處分，提起一個稅捐救濟程序，在一個程序裡面就把他全部解決掉。

臺灣的稅捐實務，基本上，法律行為明確性不足，信賴基礎沒有什麼可主張保護的餘地。我們又構成兩個行政處分，因此開啟兩個救濟程序，毋寧是常態，不會一次就把紛爭解決。我要有可能，我每一次短漏一個稅款，短漏一個稅款的補稅跟裁罰，我可以再繼續拆分。所以一個年度的課稅事件可以有數個救濟程序的進行，在我們是每一天的日常，每一天都有可能發生。


好，這個是我們的所得稅的稅捐申報程序。


## 【婚姻跟家庭】

儘管談到這裡，我們接下來還是要回過頭來，因為當納稅人是一個群體的時候，也就是當他有婚姻跟家庭存在的時候，我們這個時候，本來所得稅法第71條，這個地方才開始了申報稅的申報協力義務的規定，釋字531號說這個是合憲的。

我們先講婚姻的概念。夫妻，是婚姻共同體。我們現在在釋字748號施行法之後，把異性婚姻也放進來好，所以我先按接下來講了，我們就基本上都用婚姻共同體，來包攝，主要是由兩個人，異性的就是民法上的婚姻，同性的則是釋字748號施行法裡面的同性婚姻。這個是婚姻的概念。他是兩個自然人，以永久共同生活為目的，所組建而成的共同生活、消費共同體。這個是婚姻。


至於家庭，以婚姻為基礎，但不一定完全以婚姻作為限制。因為家庭的成員除了可能是從婚姻而產生出來的，所從出的這些直系親屬以外，也包含了韓旁，也可能包含了沒有血緣關係，只是單純同住在一家，但以永久共同生活為目的的，這我們稱之爲叫家庭。


婚姻跟家庭的概念，因此是稅法上密切連結到民法，乃至於釋字748號施行法的同性婚的這個概念，全部把他搬過來。在這裡面，基於制度的連結，原則上，稅法根據民法的觀念，來建構自己的婚姻跟家庭課稅制度。


因此我們接下來跟各位討論到了所得稅法第15條的規定，裡面所講的婚姻跟受扶養親屬沒有特別規定，原則上就是回到民法，跟後來我們增加制訂出來的釋字748號施行法裡面的同性婚好。就這樣一個課稅上的稅法跟民法的連結。


除了婚姻跟家庭制度有這個連結以外，我要跟各位講，其他沒有所謂的稅法一定遵民法的問題，沒有這個問題。我們國內很多學者一直認為稅法必須要遵照民法。稅法跟民法是同位階的，沒有誰一定要遵誰的問題。民法，你訂立為僱傭承攬委任，稅法就一定要照你的方式去解釋嗎？那個不是這樣子的，因為各自的法律，本身就有各自的規範目的。

私法是私法自治，這一點沒人否認。我們從來就承認私法的私法自治原則，但私法自治原則裡面，私法自治，自己本身也講到，不能「以名害意」啊。你的名目，解釋契約的時候不能拘泥於其文字，而忽略其本質上的爭議嘛。所以在這個地方有所謂的法律上的形式跟法律上的實質啊。這個是民法的概念。


稅法，除了婚姻跟家庭這個概念，是直接聯繫到民法上的規定以外，基本上沒有用同一個名詞必然會去拘束稅法名詞的問題，因為這個本來就依據個別的規範目的而去做解釋。

在稅法裡面的基本原則是量能課稅原則。簡單來講，這個「能」是指一個人的能。當一個自然人有所得、有銷售，有這個能力的時候，作為一個「能」的一個主體來講，這個人並不應該任意地被忽略跟消滅。因此我們進入到婚姻跟家庭課稅制度的時候，首先婚姻是由兩個自然人，不管你是同性婚還是異性，就是兩個自然人，不會更多，也不會更少。所以基於所謂對同性結合為共同體，說會多夫多妻，根本就是無稽之談。因為再怎麼講，婚姻一定是兩個人，只是同性或異性的差別，還是以兩個人結合為共同體作為前提，所以不會搞成一夫多妻，一妻多夫或多夫多妻，這個是不存在的。

即使是用德國的婚姻家庭婚姻制度保障概念，他還是講自然人兩個。所以不會一人一獸，你再怎麼愛你的毛小孩，你也不會是婚姻共同體。

德國現在在講制度保障這些概念的時候，制度保障是對於人。在這裡面，婚姻裡面的人只有兩個自然人，只是差在是同性或異性。德國因為受到德國基本法第6條第一項規定的關係，Ehe und Familie，Ehe，就是講異性婚，就專指講異性婚，可是在德國法制上的建構，是盡量讓同性的可以進入跟異性婚Ehr這個概念，可以受到相同的規制跟受到相同的保護。講白一點，就是只要進入這個婚姻共同體，原則上不管你是同性跟異性，德國民法確實只適用異性婚，但德國也為了同性的成立一個同性伴侶法。

當然，在臺灣，有些人認為只要名詞區別就有歧視。其實也會有對於Separate but equal的概念的爭議。美國南方的這一種，不允許黑人去白人學校。白人都上這個學校，那只要黑人也辦一個學校，跟白人一模一樣的學校，但是就是不讓黑人進入我們白人專屬的學校。這就提起了這一種，分離但平等，不是真平等的概念的時候，大家當然會覺得，哇，有道理。

在我們釋字748號通過之後，在我們國內確實掀起一個非常大的爭議。我無意在這個地方更進一步去講，如果講實質上的平等的話，同性跟異性，當然在婚姻共同體這個概念底下來講，他們是不分區別的，彼此有同樣的權利義務的關係，但他就是兩個自然人組成的一個生活、消費的共同體。原則上連結到民法上的婚姻的概念。

家庭則是以婚姻為基礎，不只是婚姻而已。因為家庭的概念，仍然還是必須要有一個永久共同生活而目的的，數個自然人。

家庭不一定來自於婚姻關係。所以單親家庭式的家庭就是一個爸爸或者一個媽媽，帶著一個兒子，女兒，這樣當然是一個家庭啊。

我們都有知道，所謂的收養制度，我們也知道，家庭中，家長家屬居住在一起，只要以永久共同生活為目的的話，就是一個家庭的概念。因此我們民法上的家庭概念基本上會決定了在我們稅法裡面的婚姻跟家庭的概念。

但如此而已，稅法跟民法的關係基本上是個別依據個別的規範目的，而來去做獨立的解釋。

這也是我們今天要開始去談婚姻跟家庭的合併申報、合併計算稅捐、合併繳納稅捐的基礎。

71條是結算申報的規定。理論上第15條的夫妻合併結算申報規定，他是一個進入個人綜合所得課稅到結算申報制度的時候，把兩個以上的主體合在一起，不管是婚姻或是家庭，都是兩個自然人的結合，合併去做申報。

合併申報，沒有必然要合併計算所得的問題。因為一個是程序法，一個是實體法。學過法律的各位，一定要有基本的概念。共同起訴，不必然叫做必要共同訴訟。這不是常識嗎？連這個常識都沒有，這就是我們的所得稅法第15條所有一切問題的來源。

其實15條的位置，本來應該是在71條這個地方，也就是結算申報，他是因為合併申報，然後又回過頭來說，你們的所得要合併計算。這個從程序法回過頭來變成實體法裡面的所得額的計算。所以早期的合併計算是對婚姻跟家庭極為不利的，因為他把兩個人所得算成一個人的所得。這個就是釋字318號的背景，釋字318號還仍然認為那是合憲的制度。這個我們待會跟各位去談，所得稅法第15條、第16條、釋字318、釋字696，乃至於家庭合併申報制的釋字692號、694號、696號。那時候一年出了三個跟婚姻跟家庭制度有關的大法官解釋，但這個地方當然有許多的問題值得進一步去加以說明。

我們先休息一下，大概回過頭來再來跟各位談婚姻家庭的課稅制度。