# 20231204_02

---
課程：1121所得稅法一
日期：2023/12/04
周次：14
節次：2
---

剛剛看到助教太忙了，非常謝謝助教，因為待會在隔壁那個1301的教室裡面，有一個「稅捐法中的基本權保護」的研討會，那如果各位同學時間上允許的話，也歡迎各位參加。主要是我們臺灣財稅法中心辦的活動，想說年底之前，趕快寫個議題去做討論。那個比較偏向，就是剛剛我跟各位談到的所謂的憲法審查的部分。

老師，這些年的研究，都會發現，其實很早就有這個想法了，就是說，通常問題都是出在立法的問題。立法問題，在法治國家，我們只有一個憲法審查的機關。其他機關其實不是不能做憲法審查，其實其他機關可以，特別是行政法院一定可以去做憲法審查，只是他不能得出違憲的結論，拒絕適用。也就是說，行政法院在解釋上，其實要盡可能把那個法規範在文義可能的範圍內，往合憲的方向去做解釋。這是法院的職責所在。所以，我在那個《稅捐法秩序》裡面就談到說，其實行政法院不是沒有做憲法解釋，每一個行政法院案件都是在做憲法的具體解釋，只是由於行政法院在這個權力分立的結構之下，至少在法院組織裡面，本身並沒有違憲宣告的權利，他不能拒絕一個法規範的適用，他必須要停下來，讓憲法法庭去做違憲的宣告。因此才會說，行政法院，當他對所適用的法律位階法規範具有違憲的確信的時候，那原則上他就要依憲法訴訟法11條規定，去裁定停止具體個案當中正在進行的訴訟程序，然後提到憲法法庭那個地方去做法律位階法規範的憲法審查。

這一塊算是我個人認為，在稅法裡面，你要回到憲法法秩序的這樣一個非常重要的路徑。這也是我很一直期待能夠在我們法律人的這個稅捐法的課程裡面能夠做的。不是說會計師不行，而是這個本來就是法律人的角色，要特別去著重到這樣一個法規範的正當性。那會計師們的訓練本質上就不是在這個方面，這個真的不是會計的任務，這個是法律的任務。







## 【扣繳義務的內容】


除了88條跟89條規定以外，還有第94條的規定是蠻重要的，是扣繳行為義務的內容。也就是說，剛剛的這個PAYE的扣繳程序，有適用的客體對象的設定，也有適用的行為義務的主體的設定，在第88、89條的規定。那我們來看一下第94條，這樣我們才能夠對於PAYE的制度，做比較能夠全面性的了解。

第94條的規定：「扣繳義務人於扣繳稅款時，應隨時通知納稅義務人，並依第九十二條之規定，填具扣繳憑單，發給納稅義務人。如原扣稅額與稽徵機關核定稅額不符時，扣繳義務人於繳納稅款後，應將溢扣之款，退還納稅義務人。不足之數，由扣繳義務人補繳，但扣繳義務人得向納稅義務人追償之。」


第94條規定的內容，其實規定了，就源扣繳的行為義務的內容。根據94條的規定，行為義務的內容有這一些


我們又回過頭來看92條，但在這裡面，我們把扣繳義務的內容做一個比較細的切割。



我們來看一下92條的第一項規定：「第八十八條各類所得稅款之扣繳義務人，應於每月十日前將上一月內所扣稅款向國庫繳清，並於每年一月底前將上一年內扣繳各納稅義務人之稅款數額，開具扣繳憑單，彙報該管稽徵機關查核；並應於二月十日前將扣繳憑單填發納稅義務人。每年一月遇連續三日以上國定假日者，扣繳憑單彙報期間延長至二月五日止，扣繳憑單填發期間延長至二月十五日止。但營利事業有解散、廢止、合併或轉讓，或機關、團體裁撤、變更時，扣繳義務人應隨時就已扣繳稅款數額，填發扣繳憑單，並於十日內向該管稽徵機關辦理申報。」


「每月十日前」，我們扣繳義務是一個月一次喔，蠻頻繁，密集的。


92條的第一項規定還在講扣繳憑單，但扣繳行為義務的內容，其實嚴格來講，可以切分成以下這幾個階段：扣取、繳納、申報、填發扣繳憑單

第一個叫扣取。就是付錢給納稅義務人的時候，要做一個事實上的行為，這個叫做扣取行為。

第二個，繳納。一樣，其實這也是一個事實行為，就是他去向該管的稅捐稽徵機關去做稅款的付。

第三個，申報行為。申報，是一個具有對外發生法律效力的一個法律上的行為。

第四個，第92條跟第94條所共同建構起來的，叫做填發扣繳憑單。填發扣繳憑單有兩個對象主體，一個是納稅義務人，一個是該管稅捐稽徵機關。那個扣繳憑單，不是單純只有給該管機關而已，還要給扣繳義務人。因為根據94條的規定，其實他是要隨時通知納稅義務人。


所以，我們的扣繳義務的內容，包括了扣取、繳納、申報、填發。填發，有兩個對象，受領這個扣獎憑單的對象主體，有兩個，該管稅捐機關跟納稅義務人。這個是我們從92條跟94條我們共同建構起來扣繳行為義務的內容是如此，包括了一些事實上的行為，包括了具有告知相關稅款以及讓權利義務之歸屬主體的納稅人跟稅捐接機關都能夠去知悉，究竟這個錢是算誰的錢，我是幫誰來繳納這一筆稅款。該管稅捐稽徵機關，在你申報出你的納稅人之後，他才有辦法去做相互勾稽。因為接下來就是國稅局他們內部裡面去做作業，讓你這個納稅人在他年底之後5月份去做結算申報程序的時候，能夠知道這筆錢歸誰，誰享有可扣抵稅額的扣抵權。

這是我們第92條跟94條所建構起來的扣繳行為義務的內容。


## 【扣繳義務人的補繳】

回到第94條的規定，我剛剛念了一段話，就是當你扣太多的時候，你要把溢扣之稅款還給納稅人。但重點在後面那一句話，如果你扣不足額的時候，是由扣繳義務人去「補繳」稅款，再由扣繳義務人向納稅義務人去做追償。我們在稅法總論裡面，我們談到稅捐債務法，有講責任債務人。這個就責任債務的一種表現。扣繳義務人本身並不是納稅義務人，其實不是依法律規定所產生稅法上權利義務之歸屬主體，他是以第三者的身份進來，變成是在這裡面第94條規定的補繳的主體，從而他是一個德文稱之的叫Haftung，中文其實叫責任。但是我們沒有在制定法裡面說，這個是責任，而是直接用補繳這個概念。

我再講一次，責任這個概念是學理上引用德國法去做延伸的闡明或解釋。這是一個責任，所謂責任的意思，他跟納稅人是處於一個兩個債權債務關係，都為了滿足一個國家的稅捐債權。所以我們把這個扣繳義務人的補繳責任，稱之為叫責任債務。因為主債務人是納稅義務人。取得所得者有稅捐負擔能力的是納稅義務人，不是扣繳義務人。


扣繳義務人，毋寧是以第三人的身分，依照所得稅法88條跟89條的規定，特別是89條的規定納入稽徵程序裡面，成為這裡面的第三人，被課予一個公法上的義務，而讓他去承擔起92條跟94條所規定的扣取、繳納、申報、填發，這些義務。這些行為義務固然不直接讓他變成是稅捐債務的主體，但是當他扣繳不足額的時候，根據94條的規定，他必須要去補繳。


法律條文規定是說補繳，學說則是稱之為叫責任債務。其實如果是講「補繳」，我毋寧會比較偏向認為，納稅義務人才是補繳的主體，因為納稅人在稅捐債權債務沒有被滿足的時候，他依然對國家負擔起繳納稅款的補繳責任。這個地方比較正確的名詞比較接近責任債務，應該用「賠繳」的概念。「賠」，就是你沒有做好你法律上的行為義務，那我讓你去賠。其實本來你不是義務人，但你沒有做好92、94條告訴你的扣取、繳納、申報、填發，所以我要你賠。

國家，特別是在他的稅捐債權沒有滿足的時候，他要求這個責任債務人去賠繳，那這個會比較符合責任債務的本質，只是問題是我們的法律，第一方面並沒有去講責任債務的概念，那他的法條規範的名稱也是寫扣繳義務人是補繳。但無論如何，在學理上並不認為補繳義務人是原先的納稅義務人，因為這個地方很清楚地透過後面的「追償」的規定，可以看到，即使我們的立法者也認為真正該要負責任的是納稅義務人，因為他沒有繳到該繳納的稅款，從而要讓納稅義務人去負起最後的補償稅款的這個責任。

這也是第94條規定。我們這整體去看到我們的扣繳行為義務。扣繳程序適用的客體，在88條的規定。扣繳行為義務的主體在89條的規定。扣繳行為義務的內容在94+92條的規定。扣繳，如果沒有在法律規定裡面去做如期如額的申報的時候，94條是補繳的責任，但容許扣繳義務人在事後再去向納稅義務人去做追償。


## 【扣繳義務人的制裁】

我們請同時翻開第114條的規定。扣繳義務人還會在沒有履行義務的時候受到一個制裁，因為他有一個協力義務的違反，因此還有一個114條的未依扣繳程序去做的時候的處罰的規定。我們來看一下114條。

114條一樣非常囉嗦而又複雜，用各款的規定。我們分開來好。來看一下114條的第一款規定。「扣繳義務人未依88條規定扣繳稅款，除限期責令補繳應扣未扣或短扣之稅款以外」，一樣，跟94條一樣，這邊用「補繳」。還要補報扣繳憑單以外，並按應扣未扣或短扣之稅額處一倍以下之罰鍰。


第二分句：「其未於限期內補繳應扣未扣或短扣之稅款，或不按實補報扣繳憑單者，應按應扣未扣或短扣之稅額處三倍以下之罰鍰。」

簡單來講，扣繳行為義務，當你短扣或者是應扣未扣，沒有去繳納稅款，國家認為他會有一筆稅款短收之風險存在，這個時候根據你的態樣，而去做三倍或一倍以下的，性質屬於漏稅罰的處罰。


第二款規定：「扣繳義務人已依本法扣繳稅款，而未依第九十二條規定之期限按實填報或填發扣繳憑單者，除限期責令補報或填發外，應按扣繳稅額處百分之二十之罰鍰。但最高不得超過二萬元，最低不得少於一千五百元；……」


這個全然針對的是剛剛我們所提到的扣取、申報、繳納，之後的第四個義務，叫做填發扣繳憑單的義務。你雖然已經有扣取申報繳納，國家其實理論上沒有短收稅款的風險，但仍然還要做最後一個讓國家可以對帳的義務。因為我剛剛有講過，填發扣繳憑單是同時對納稅義務人和該管稅捐稽徵機關。如果沒有這一個填發扣繳憑單，從國家的角度就是，他收錢，不知道到底收了誰的錢。有這樣一個意味存在。透過這個規定，他說，你還是要來做一個填發扣繳憑單，我可以對得起帳。

所以第二款規定是一個行為罰的概念。因為國家其實已經收到錢了，理論上沒有短收稅款的問題。但因為國家對不起帳，他收到錢，他不知道誰是納稅義務人，所以在這裡面有一個第二款規定，應按扣繳稅額處20%的罰鍰。這一種行為罰，但按所謂的扣繳稅款，用一個比例的方式，雖然不是像前面的一款的一倍或三倍，是20%。那正是因為這個是行為罰，從而他曾經被大法官做過解釋說，這一種沒有限度的處罰一律按20%是過度的過重的責罰，從而後來才加進來一個我們這裡面講的不得超過2萬塊錢，但最低也不得少於1500。

這是一個行為罰，但以所謂的扣繳憑單上所載的那個數額，扣繳稅額，來做為量罰時的唯一基準。這個本質上應該是行為罰，可是這一種處罰的方式又非常接近是漏稅罰的制裁的方式，因為只有漏稅罰才會按應扣未扣短扣稅款的額度來做為處罰的標準。但正因為用這一種比較怪異的規定的方式，所以我們經過大法官解釋以後，他就設定了一個上下限的一個處罰規定。

第二款的第一句的第2分句的規定：「逾期自動申報或填發者，減半處罰。」

然後第二句開始：「經稽徵機關限期責令補報或填發扣繳憑單，扣繳義務人未依限按實補報或填發者，應按扣繳稅額處三倍以下之罰鍰。但最高不得超過四萬五千元，最低不得少於三千元。」

一樣，他還是按扣繳稅額處以一個倍數的裁罰，但是有一個上下限的規定。本質上應該是填發扣繳憑單，沒有辦法對帳的問題而已，國家沒有短漏稅款的問題，但在這裡面的處罰規定，法律規定性質應該是行為罰，但這個處罰規定有看起來非常像漏稅罰。後來因為被大法官解釋過以後，就設了一個上下限規定。

這樣一個罰鍰的性質，仍然具有相當大的疑問，他到底算哪一種啊？我們剛剛所提到的，本質上，他有扣取申報繳納，其實國家已經取得稅款，但沒辦法讓國家對帳的，沒有填發扣繳憑單申報給該管稅捐稽徵機關，讓他知道這筆錢是誰的錢，從而在這裡面，他就存在著這樣一個違反義務的裁罰。


114條第三款規定還要加徵滯納金。每2天加徵1%的滯納金。這個是所得稅法第114條規定，對扣繳義務人所做違反義務的懲罰，違反義務的非難。但實際上不只如此而已，其實還有一個條文規定，不在所得稅法，而在稅捐稽徵法。

在我們稅捐稽徵法第42條的規定，也針對扣繳義務人做了一個跟納稅義務人幾乎同樣內容的裁罰。

稅稽法（0790116 修正）41條：「納稅義務人以詐術或其他不正當方法逃漏稅捐者，處五年以下有期徒刑、拘役或科或併科新臺幣六萬元以下罰金。」

稅稽法（1101130 修正）41條第一項：「納稅義務人以詐術或其他不正當方法逃漏稅捐者，處五年以下有期徒刑，併科新臺幣一千萬元以下罰金。」


稅稽法的第42條針對扣繳義務人也做了是同樣內容的裁罰。在稅稽法第42條規定：「代徵人或扣繳義務人以詐術或其他不正當方法匿報、短報、短徵或不為代徵或扣繳稅捐者，處五年以下有期徒刑、拘役或科或併科新臺幣六萬元以下罰金。」


這個刑度，基本上跟41條在110年稅稽法修正之前，納稅人的違反自己的稅款繳納義務是一模一樣，就是當時的法律條文規定，基本上都是對扣繳義務人跟納稅義務人是同樣對待。

從國家的角度來講，他覺得我收不到錢，就是客觀事實，所以不管今天我要處罰你納稅義務人，跟處罰你扣繳義務人，都一樣。在我們的稅捐法制裡面對扣繳義務人是如此地看待。這樣一個扣繳的義務，內容跟制裁有沒有違憲呢？


## 【釋字673號】

大法官在民國99年做出釋字673號。這一號解釋基本上決定了我們的扣繳義務的合憲性與否的說明，雖然當時的這個釋憲的程序標的的法律規範其實不全然是現在的現行的所得稅法第89條的規定。不過我們來看一下，在這裡面的解釋文第一段，正是我們現在目前的法條規定的原型：「中華民國七十八年十二月三十日修正公布之所得稅法第八十九條第一項第二款前段，有關以機關、團體之主辦會計人員為扣繳義務人部分，及八十八年二月九日修正公布與九十五年五月三十日修正公布之同條款前段，關於以事業負責人為扣繳義務人部分，與憲法第二十三條比例原則尚無牴觸。」

這個地方就看到，以前的法條在「責應扣繳單位主管」之前，是以「主辦會計人員」為扣繳義務人。

我們的釋字673號解釋認為，不管是你之前的主辦會計人員，自然人作為義務人，或者是現在法律裡面的事業負責人，其實都是合憲的


接下來，解釋文第二段：「七十八年十二月三十日修正公布及九十年一月三日修正公布之所得稅法第一百十四條第一款，有關限期責令扣繳義務人補繳應扣未扣或短扣之稅款及補報扣繳憑單，暨就已於限期內補繳應扣未扣或短扣之稅款及補報扣繳憑單，按應扣未扣或短扣之稅額處一倍之罰鍰部分；就未於限期內補繳應扣未扣或短扣之稅款，按應扣未扣或短扣之稅額處三倍之罰鍰部分，尚未牴觸憲法第二十三條比例原則，與憲法第十五條保障人民財產權之意旨無違。」

也就是第二段針對所得稅法114條第一款規定，我們剛剛念到的那個第一款規定，因為那個地方存在著國家收不到稅款的風險，因此從漏稅罰的角度去理解第一款規定的情形，他認為，這個地方用三倍以下裁罰並沒有過度責罰非難的問題，這是第二段。

剛剛我們講了，這個看起來應該是行為罰，但是又用漏稅罰的這一種按扣繳憑單上所載的扣繳數額來做為裁罰標準。這個是接下來第三段要講的。

「上開所得稅法第一百十四條第一款後段，有關扣繳義務人不按實補報扣繳憑單者，……」

跟第二段不同的地方是，第二段是你沒有及時報繳稅款，就是你扣繳義務人，你沒有及時把稅款送到國家的手裡面去，國家覺得他有短漏稅款、短收稅款的這個危險存在。

扣繳義務，分成兩個階段。一個是扣取申報繳納，這是第一個階段。還有第二個階段，你要在每一年1月的時候去告訴國稅局說，你這筆錢是扣誰的，讓稅捐稽徵機關可以去對起帳來。

所以這個部分在第三段裡面說，「……，應按應扣未扣或短扣之稅額處三倍之罰鍰部分，未賦予稅捐稽徵機關得參酌具體違章狀況，按情節輕重裁量罰鍰之數額，其處罰顯已逾越必要程度，就此範圍內，不符憲法第二十三條之比例原則，與憲法第十五條保障人民財產權之意旨有違，應自本解釋公布之日起停止適用。有關機關對未於限期內按實補報扣繳憑單，而處罰尚未確定之案件，應斟酌個案情節輕重，並參酌稅捐稽徵法第四十八條之三之規定，另為符合比例原則之適當處置，併予指明。」

所以他告訴你說，你應該要去停止適用，這個是違憲的，因為可能會有所謂的過度責罰非難的問題。正是因為673號解釋的這個第三段宣告了剛剛我們念到的這個第二款的這種情形。所以後來立法者就根據財政部的建議，就上去做一個修法，有一個上下限的規定，但是他的規範結構仍然用一個蠻怪異的狀態，就是本來是行為罰，但是按一個所謂百分比的方式，也就是按扣繳憑單上所載的扣繳的數額來作為一個量罰基準的因素。

透過第三段的解釋，大法官認為，只有這一個部分才會違反比例原則。所以我們673號解釋原則上肯認了扣繳PAYE制度，對扣繳義務人的設定、扣繳義務的內容，基本上都是合憲的。只有對扣繳義務內容裡面的違反，特別是在後半段的扣繳憑單的填發，關於他的責罰，有過度非難的情況，違反比例原則。我們大法官在673號解釋裡面，原則上肯認了我們的就源扣繳制度本身的合憲。但正是這個肯認，讓我個人自己寫的德國博士論文，就是就源扣繳程序，完全是一個違反比例原則的狀態。


比例原則，在審查自由權的干預侵犯裡面，是一個在德國法制上非常重要的違憲審查的基礎。也就是當一個人他的營業自由，他的工作權因為法律的規定而受到限制，在這種情況底下，那我們在往往在規範的憲法審查上面，會用比例原則。這也是德國法治的特色。


其實在美式的違憲審查裡面，不太會用比例原則這個概念，美國比較偏向這個是讓立法者可以去做形成的。他們的審查往往一直都是根據個別不同的基本權內容，去發展出一套獨特的標準。那這一些比較重要的基本權裡面可能會用平等原則來作為一個審查的標準，不會用比例原則。

德國式的規範審查往往在自由權裡面都比較用比例原則。

我們回過頭來看這一個問題，我們來看一下，我們剛剛從88，89，92，94條，扣繳義務人的設定。673號解釋說這個是合理比例原則的。


首先第一個我要跟各位說，這個制度的本身，我們的就源扣繳，各種所得類型幾乎全部適用。因為我們這一套制度是來自於分類所得稅時代的概念。也就是我們這一個綜合所得稅制度，其實是民國46年，我們的所得稅法才全面地從分類所得改成現在的綜合所得。在此之前，分類所得稅，跟綜合所得稅最大的差別就在，分類所得稅，因為是就不同的類型，個別做稅捐稽徵程序，所以分類所得稅的最重要的稅捐稽徵程序是就源扣繳。

分類所得就是不同的所得來源，就直接，在給的時候就直接就源扣繳，報給稅捐稽徵機關。所以分類所得稅的稅制，本質上他會用就源扣繳制度來確保國家稅捐債權的實現。分類所得稅的稅制，原則上，並沒有綜合在一起去做結算申報。

結算申報自是綜合所得稅的類型特徵，也是他做稅捐稽徵程序的主要手段。一般而言，綜合所得稅制的國家為了要去對一個人的稅捐負擔能力去做正確的考量，通常是課予取得所得者一個，在特定期間裡面自己來報告自己來說我有多少所得的義務，把你的各類型所得全部都放到同一個稅基底下，這個就叫綜合所得稅加結算申報制。你自己告訴國家稅捐稽徵機關說，欸，我有哪些類的所得，原則上全部所得都放在一起，這個就叫綜合所得稅。

綜合，所以是分類的對立名詞。綜合所得稅要如何去課稅？他可以借用就源扣繳，但一般來講，因為就源扣繳不足以反映最後真實的所得，所以一定會有一個納稅義務人自己，在一定的時間裡面去做結算申報的制度。在綜合所得稅制中，爲了正確計算稅捐負擔，原則上都會有納稅義務人自行在一段時間內去做結算申報的制度。因此採綜合所得稅制的國家，例如美國、德國、日本，包括民國46年1957年之後我們的綜合所得稅制引進的時候，我們就慘結算申報。

這種結算申報制，只有納稅人自己最清楚自己有所得，但是如果當納稅人本身就不是結算申報的納稅義務人的時候，也就是他是一個境外所得者，請問這個時候我要怎麼讓他報稅？因為他不會來做結算申報，他不會呆到每一年的5月才來做結算申報，他拿了錢就走人了，從而他才會用就源扣繳的程序。

所以綜合所得稅裡面，通常會讓境內居住者去做結算申報，非境內居住之納稅人則按就源扣繳程序，也就是PAYE，就是你賺錢的時候，就直接讓所得的給付者直接在給你錢的時候，就要去做就源扣繳。那如果是境內居住者，對境內居住者，我給錢的時候基本上是沒有扣繳的義務。

因此有些國家，為了要避免他對各種所得來源，沒有辦法去查核，所以通常他們會對第三人，也就是所得的給付者，給予一個通報義務，課予一個協力的義務。那個義務叫做通報。我付多少錢給柯格鐘，這個時候我不是去做就源扣繳，而是我付錢的時候，我就告訴稅局，說，欸，我付多少錢給柯格鐘。這個叫通報義務。像比如說在荷蘭、比利時、盧森堡這三個國家低地國家，他們基本上並沒有要求所得的給付者要去做就源扣繳，他就是付錢出去以後，告訴國稅局說，哦，我給柯格鐘多少錢。那這個人在做結算申報的時候，原則上因為國稅局也取得了通報者所通報的資料，這個時候我就可以去核對，稽核柯格鐘有沒有在結算申報制度裡面去做正確數額的申報。這個是最小程度範圍的干預吧？對吧？對於一個第三人的身份，納入稅捐稽徵程序，他既不是稅捐債權人，也不是稅捐債務人。


從自由權的干預的角度來看，扣繳義務遠比通報義務是更高程度的干預，我想各位學過自由權，應該都不會否認吧。通報義務本身就是個干預了，只是算比較低的程度。當你存在著有通報義務跟扣繳義務之同時，如果你真要用比例原則裡面所稱之為叫必要性審查，我看應該通不過。因為有通報義務存在，就意味著，其實扣繳行為義務是蠻高度的行為。扣繳義務人，我要做扣取、申報、繳納，還要做填發，然後沒有做好，我還要賠，我還要被罰，還被罰到跟納稅義務人的本人一樣的程度。哪一個國家是這樣苛責第三人的？這個叫不違反比例原則？法律規定就長這個樣子。

好，如果法律不改，我就跟各位講，千萬不要當事業負責人，要找也要找個人頭哦。我們法律是這樣規定。扣繳義務人，在事業，是事業負責人。在機關、團體、學校，88年以前叫「會計單位主管」，主辦會計人員。那時候就是因為發生中科院的案子。

中科院裡面，民國80到85年之間，長達5年的時間，有一群本來是軍職人員，因為當時的所得稅軍人不用繳，可是他轉民職，就退伍之後，他變成是民職的人，還是一樣在中科裡面任職。他的薪水並不是免稅所得了，因為他不再具有軍人身分，這個時候，其實要做就源扣繳。可是這一些主辦會計的人，他們以為這些人員仍然是為國家貢獻，所以就不做就源扣繳，在5年以上的這個時間裡面，多達上萬個人都沒有做薪資所得的就源扣繳。

當時的法律規定，就是對這些主辦會計人員說，對不起，你沒有扣繳，根據94條規定你要做補繳。而且補繳不打緊，再加上114條的規定，你還要再罰三倍以下，所以這9個會計單位主管總共被命補稅9億元再加罰18億，加起來是27億，請你們這9個人補繳連帶處罰。那個時候才產生這個案子，釋字673號解釋。

主辦會計人員，他們認為說為什麼要叫我們負責？第一段的解釋裡面，他說這個沒有違憲，所以並沒有找你們找錯。可是立法者後來覺得我找會計弄錯了，所以後來才改一個條文，就是「責應扣繳單位主管」，我剛剛有跟各位講過。當時他改的背景是，有一位被被拜託陳情的立法委員就出來開會，開了研討會開了好多喔，就説，會計師管帳的，他們不管錢，所以責應扣繳單位主管，他說，欸，弄錯了，應該要找出納才對，他又不好直接寫出納，所以就用一個很抽象的名詞叫責應扣繳單位主管，因為你也不知道責應扣繳單位在講誰。

但那個修法，從「主辦會計人員」變成是現在的「責應扣繳單位主管」，其實基本上都是在找自然人，只是不是會計，而是當時認為應該是出納。結果這個抽象名詞哦，這個「責應扣繳單位主管」在我們現在機關團體裡面，原則上還是找出納主管，可是在我們學校，我有注意到，我們學校早期都不是找校長，可是近幾年來責應扣繳單位主管就變校長。

所以「責應扣繳單位主管」，這個概念本身還是一個很抽象的名詞，在機關團體裡面不是指首長，而是通常是指，裡面的那個出納組的組長，跟從事出納業務的人，也因為他們認為這個是付錢的人，你在付錢給他的時候，你馬上就要就源扣繳下來。但到學校的時候，本來其實以前早期，因為學校裡面辦行政的大部分都是老師兼差，覺得找老師實在是很不公平，老師自己平常就業務很忙，又要教學生又要跟學生做課業輔導，好忙好忙，做行政，已經大家都不願意了，結果去做了這一個出納的時候，哇，我又要負起這個責任，所以後來，我們財政部就改成找學校的校長。所以現在是校長變「責應扣繳單位主管」。

好，我們現在就變成，機關團體是出納，學校是校長，事業就是負責人。根據釋字673號解釋，這個都全部合憲。


## 【扣繳義務主體的錯誤設定】

我們再回過頭來，我剛剛講的一件事情，這個扣繳義務人，他本質上是第三人。扣繳義務其實已經比通報義務是更嚴重的干預了，好，我們就姑且不講這一件事情。這個義務主體的設定也是錯誤的，因為我剛剛跟各位講過，我自己在德國就寫這個論文。德國雖然也有扣繳義務，但扣繳義務人不是那個自然人。扣繳義務人是組織團體學校事業本身。他們的名詞叫雇主。我剛剛有跟各位說過，在德國，因為他們的原則上是結算申報制，他們的就源扣繳是有限度的就源扣繳，因為他主要是納稅人自己的結算申報義務，自己稅捐自己負責申報繳納，有問題嗎？你要找人，你總是要做一個最低限度最小範圍的干預吧。在德國就只有兩個。一個是薪資所得，找誰，找雇主。另外一個叫利息所得，找金融機構，因為金融機構會付利息給存款的人。就只有這兩類所得需要做就源扣繳，其他所得全部都回去讓納稅人自己去做結算申報。


根據臺灣的法律的規定，我們的納稅義務人有結算申報義務，釋字537號說這個是合憲，這個沒有問題。因為這個不管在德國，臺灣都是合憲的制度，申報制度是為了要去確實履行憲法上的依法繳納稅款的義務。因為沒有你來申報，其實要職權調查無從查核起，大海撈針。從而結算申報制度是為了要履行依法課稅、量能課稅原則的目的的必要手段。

但我們回過頭來再看，當結算申報制度，這個存在的時候，我們有對極為廣泛的所得類型，設定以這一些機關團體學校事業裡面的不同的主體。機關團體以前是主辦會計，後來改成責應扣繳單位主管，實際是找出納組長。學校則是一樣，是找責則應扣繳單位主管，但是是找校長。事業，則是找負責人，也就是臺積電，鴻海，你找他們的董事長。我們的大法官解釋說，這個全部都合憲。

機關團體的首長不用付機關執政成效的成敗嗎？你憑什麼認為？因為大部分都是在行政機關嘛，不管你今天是國家級的或地方級的行政機關，執政的政策其實也是一樣，是首長來負責啊。為什麼機關你就講責應扣繳單位主管，結果事業，你就講負責人。請問就算從平等原則來看，你告訴我這樣叫平等嗎？

找錯主體了，因為你不是用這個事業機關團體組織，不是用這些法人本身，而是用他們底下這一些自然人。而自然人裡面你又對機關團體學校跟事業做區別對待。這樣的一個就源扣繳制度，673號解釋，第一段，合憲。不僅違反比例原則，在我來看，也是違反平等原則。因為他在機關團體學校跟事業當中做區別對待，無理由的區別對待。

根本不應該是什麼事業負責人跟這個所謂的機關團體責應扣繳單位或主辦會計人員，因為這些自然人的勞務，其實都是歸屬給法人本身。機關團體學校事業的這一些實際執行扣繳或給付所得款項業務的人，其實他的勞務都是歸屬給事業組織本身吧。各位都學過民法的規定啊。自然人的勞務是歸屬給法律本身。連這樣一個基本的概念都分不清楚嗎？所以臺積電誰要付扣繳義務，不是劉德音，也不是張忠謀，是臺積電本身。行政院跟臺北市政府，誰要付扣繳義務？不是蔣萬安，也不是現在的陳建仁，都不是，更不是他們底下的所謂責應扣繳單位主管，出納組長，而是臺北市本身，行政院機關本身。


這才是正確的，所謂的雇主，你付出薪資所得，應該是以雇主本身作為納稅義務人。我們的釋字673號不僅錯誤地設定行為義務主體，而且課予過重的責任，他的責任就在於他一路過來，第一順位的補繳責任。因為在責任債務裡面，理論上應該要由納稅義務人先付第一順位，也就是國家自己要去對納稅人去追償，國家自己去跟納稅人要錢。第三人，他是無償來幫你國家完成這個任務，結果做好沒賞，打破要賠，而且還賠到底，你跟納稅人一樣的責任，這一點，還說沒有違反比例原則？

你只要從比較法制來看，就可以完全看出我們現行法制之對扣繳義務人的責任之苛刻之重。我都錢繳進來了，只是扣繳憑單沒給，讓你沒辦法對帳。國家當然用很最低的成本，因為國家是坐著等收錢，所以他有最低的成本費用，可是我們的扣繳義務人是無償為國家完成公法上的任務欸。在這種情況底下，完全是一個違反比例原則的侵害扣繳義務人的職業上的工作權，跟他的營業上的自由權。我完全不能贊同673號的結論，我只贊同第三段，因爲那是過度責罰。第三段是對的，但第一段完全是錯誤的。很可惜的是，673號解釋作成之後，立法者當然不會覺得自己有什麼不對。


我們的現制就是一直到目前為止。未來沒有新的立法之前，我也只能跟各位講，你千萬不要去當機關團體學校裡面的出納。千萬不要當出納，要趕快轉職，從那個地方移開，申請轉去任何業務都好，就是不要當出納，因為你不知道在你任內，少扣繳稅款，找你負責。

我是出納，我也是個薪資所得者，為什麼中科院這些主管跟出納要為全體的人的扣繳義務，要補繳稅款要負責。我不能明白，這怎麼會不違反比例原則。

我們先跟各位談到這裡。下個禮拜還有一點點關於扣繳義務的這個部分，再做補充上的說明。

我們最後面還進入結算申報跟協力義務違反的制裁，也是我們最後一次的所得稅法上課。