# 20230918_01

---
課程：1121所得稅法一
日期：2023/09/18
周次：3
節次：1
---

## 【量能課稅原則的憲法上意義】

綜所稅，適用各項從憲法平等原則具體化的量能課稅原則，然後再進一步具體化的各項子原則。綜所稅是體現所有量能課稅之原則最完整的法律的領域。
其他的包括營所，營業稅都是部分反應而已。量能課稅原則會在綜所稅裡面做最完整的呈現。

我們課程沒有要求，各位非得要上過稅法總論，但對於量能課稅原則的各項子原則，還是希望各位無論如何去把他補起來。
因為你只有在這些子原則的指導底下，你才能知道我們現行的立法跟法律解釋方向。
我再一次強調，作為憲法位階具體化的原則，他是具有行政立法司法的上位的效力。簡單來講，就是立法者應該往那個方向去立法；法律，在沒有變更之前，不管是行政或司法，在可能的文字範圍內，他要盡可能往那個方向去解釋，這是作為一個法律為憲法位階的基本原則的功能跟作用。如果這個原則不能夠起到對立法指引跟法律解釋適用的指引的效力，那我們講這些東西是沒有太大意義的。

當然個別原則他會有一些取捨，我們會在接下來的課程裡面去看到各種不同原則，會有做不同程度的取捨。所謂的取捨的意思，就是他有一些這些子原則在綜所最裡面做了一部分的退步退讓，但他不是全然放棄。打個比方，各位一定學過的私法自治，在民法裡面擁有無可置疑的最重要的主要原則的適用地位，可是私法自治仍然在，比如說定型化契約條款，比如說對未成年人的保護，裡面他要退讓一步。不是因此他就放棄了作為私法自治作為私法裡面最高指導原則的地位，而是在那樣一個，如果透過定型化契約條款，透過經濟上的強弱勢，將以契約自由之名行剝奪自由之實的這一種的契約條款的話，我們仍然可能會透過立法乃至於法律的解釋適用，去做部分的調整退讓。如同這樣一個私法自治，跟弱勢消費者的保護，或是對未成年人保護，是同樣的概念跟原理。也就是說，在那個地方，私法自治作為私法最重要的基本原則，他並沒有因此折損他的地位，只是在這樣的一個對消費者的保護，對未成年人的保護這樣一個前提底下，他能夠更完整的展現。其實私法自治，就是要展現一個人作為一個人的，可以就自己的事情做充分自主完全決定的這樣一個概念。未成年人，因為他可能在他的意思表示形成過程當中，他還沒有辦法，完全會自己做最佳最正確的考慮，因此才會有一個代理人，法定代理人來協助他為了未成年人的利益而來做最有利，保護他利益的一個解釋。

從而他其實回到我們憲法裡面。我們憲法雖然沒有寫得這麼清楚，但各位一定都會聽過人性尊嚴這個概念。因為我們從比較法來看，比如說德國基本法第一條，人性尊嚴是不可以與貶損的這樣子的一個基本價值跟原則，所以從而私法自治也同樣在體現人作為人，對於自己本身所有的事物，享有自己自我做決定的最終的權限。在這樣一個前提底下，如果透過契約上的強弱勢的經濟地位的安排，要求相對人去做退讓，這個毋寧才是一個假自由之名，而去剝奪對方的作為一個人的人性尊嚴的一種做法。這也是我們在私法裡面各位都學到的基本的概念。

來到了稅法亦如是，量能是在稅捐法律體系裡面作為，我們可以講，他跟私法自治在民法一樣的最高位階的地位，簡單來講就是說，雖然量能本身並沒有直接被稱之為叫做等同於所謂的平等原則，可是正因為平等是一個蠻抽象，某種程度也是空洞化的一個原理原則，因為他必須要去比較兩個群體之間的所謂等跟不等。基於這樣子的一個概念，所以他透過一個所謂的分類標準去確定A跟BA群體跟B群體之間為什麼他是不等，為什麼他們是相等？ 那稅法的話，就是去憑這個所謂的分類標準，就是透過稅法裡面的量能原則來去鑑別，為什麼兩個人在這個地方做不同的稅捐負擔的不同的待遇，跟為什麼做相同的稅捐負擔的待遇。這也是我們在稅法總則的課程裡面，我們會特別去交代，為什麼可以從憲法平等原則到稅法的量能課稅原則。
如果沒有這樣一個分類標準的話，平等原則，是空洞的，因為他講不出更多的內涵，什麼叫等者等之，什麼叫不等不等之，又究竟又要多麼大的不等，才叫做不等而違反平等原則。
以打分數來講的話，就是一個很典型的例子，我不可以說，坐在左邊的一律及格，坐在右邊的一律不及格來作爲一個分類標準，因為這明顯的是老師的恣意。我不可以有戴眼鏡的沒戴眼鏡的來作為分類標準，這個也很明顯的是一個恣意。那我究竟要用什麼標準來評價各位的考試分數？很簡單，你來考試。符合於事務之本質的分類標準，就是一個最為適當的分類標準，因此等者等之這一件概念，在稅法裡面就是用你有你能你可以。你能，你可以你賺到錢，你有錢，你有辦法消費。就這樣一個基本的觀念，去建構起我們整個稅法裡面所謂的憲法平等原則。

因此量能跟平等是結合在一起，除卻量能的平等是空洞化的原則，沒有辦法去做具體的操作。這也是我強烈的要去說，我們國內如果還不能夠一直學憲法的學者一直在講平等原則，那量能就是讓他落地化。沒有這樣一個原則，你根本就無法去評價，為什麼，賺同樣100萬的人可以有不同的稅捐負擔，或者是為什麼賺100萬人跟賺1000萬人，為什麼稅捐負擔差異可以這麼大或差異這麼小？他的標準就建構在我們剛剛所講的平等原則裡面的具體化的量能。

體現量能最完整的各項子原則，就在我們今天跟各位講的綜所稅。上個禮拜，我很快地交代了十項子原則，其實各位如果有興趣，你當然可以再參考老師寫的，《稅捐法秩序》第541頁以下，全部都是以所得稅法為例子。總論跟各論，其實本來就相互結合，就像各位在學刑法總論跟刑分，各位在學民總、債總跟債各之間的關係。

我們教學上固然把他體系化切割成每一個細分的部分，去做體系化的教學，但請各位同學，務必時時回過頭來來想整體。整體跟個體之間兩者之間的梭巡來回，是各位對這個法領域裡面充分掌握適用的一個前提構成要件。我們不是在背法條，而是在總則分則、原理原則到個別具體法條之間的解釋適用，又回過頭來來去看他到底有沒有符合原理原則的，這一個過程的充分的一個學習。

各項子原則，包括了，普遍原則、全部、實現、實價、客觀净值、主觀净值、個人、終生、綜合、比例。還有另外一個，跟這幾個原則會混雜在一起去做討論，就是所謂的實值課稅原則，即實價課稅原則。實值，就是真正的價值的意思。我們後來還有一個叫實質課稅原則，這個地方也請各位稍微分辨一下。

因為，法律的精細是在使用標準正確的文字去描述你要描述的對象，如果這個詞雖然中文發音聽起來一模一樣，但如果在考試的時候，我看不到正確的字眼，我就會懷疑到底是我沒講清楚，還是你沒聽清楚。
如果我現在都已經特別講了的話，那我當然就會評價你可能沒有聽清楚，也沒有搞清楚，這就是我們在考試裡面所想要做的檢驗，希望各位透過考試，可以檢驗自己，這些基本原理原則，能不能很清楚而充分的純熟地去做運用。

## 【量能課稅原則的各項子原則在綜所稅上的違反】

接下來談量能課稅原則的各項子原則。

### 【第一項普遍原則】

第一個我們稱之為叫普遍原則，也就是中華民國人民基本上不分男女性別黨派居住區域、身份階級。就像我們的憲法第7條的規定一樣，一模一樣。
只要有所得，你賺到錢就要課到稅，這個就所謂的普遍原則。這個看起來是一個似乎普世皆然的一個原理原則，但其實包括臺灣本身在內，在民國100年以前，其實我們並沒有實踐。因為我們有一群在所得稅法第4條第一款跟第二款規定（現在已經被廢止，所以現在你看不到），我們在100年之前的軍教人員免稅，就是因為階級、職業別而產生的區別對待。待立法者在他的立法明文裡面去做了這樣一個區別對待。理由呢？因為認為軍教人員待遇低、辛苦，所以透過這種免稅的待遇來給他實質上的補貼。當時候的大多數的正當化，也都是建構在對國家有特殊貢獻，以這個為前提或理由來做的違反普遍原則的規範。

我要強調，違反平等原則，其實不是因為這樣違反，所以就被認為違憲，而是違反在這個地方立法者有沒有足以正當化這樣違反或這樣偏離的一個正當化理由。在這裡，平等原則跟比例原則的操作上面有一點最大的不同。比例原則，你也可以講就是過當就是一個違反比例的一個國家過度干預行為。平等原則的操作，是我們先辨識了這個地方，確實立法者做了區別對的，也就是說，我們先辨識了立法者在這個地方做法律上的不同區別對待。因為平等原則並沒有要改變事實上的不平等，比如說男女的性別不一樣，比如說年齡的不一樣，立法者再怎麼立法，也不可能改變這種客觀現實的不同。這個就是一個客觀上面、事實上的不平不是立法者要改變的任務，立法者也做不到這件事情。可是法律上的區別對待這一件事情，卻是我們在對國家的行為檢驗他是否合於平等原則的時候，第一步先辨識在這個地方，法律上做了一個不同的區別對待。

第二道步驟，就是在檢驗為什麼要做這樣一個不同的區別對待，也就是第二道，我們稱之為叫基於什麼樣的正當目的，而做不同的區別對待。所謂平等原則，我個人認為就是階段理論，就一個階段一個步驟。平等原則，不會因為他違反量能，就直接違反憲法平等原則，所以就宣告違憲。而是在一步一步的檢驗過程當中，你們我們去檢視立法者做這樣一個區別對待的正當性，跟這樣一個區別對待的理由背後是不是足以說服、說明這樣一個區別、不同的對待，具有足夠的正當性存在。

因此這裡面確實存在著所謂的價值判斷。我們只是先第一階段區辨了這個地方做了法律上的不同對待。第二個，他是來自於立法者自己所說明的追求某一個目的，而那個目的接下來才是去講變辨別，關於他偏離平等原則的這種不同對待，跟這個正當化理由之間，他是不是能夠符合我們在價值判斷裡面的正當性。

因此我們進一步的檢驗，以剛剛所講的軍教人員免稅爲例，透過所謂的對軍人或教師（當時候的教師，並不包括高等教師，而是包括公私立屬於義務教育裡面的教師，也就是說中小學，基礎的義務教育這個部分）是有稅捐優惠。高中之後顯然就沒有。所以包括我自己在內，高等教育的老師，基本上是沒有在軍教人員的免稅這個階段，透過這個所得稅法第4條第一款第二款的規定被優惠到。

那他的正當性就如同我剛剛所提到一般而言，我們的立法者會在他的立法理由沒有理由裡面去說明，說，哎，為什麼要給他一個特殊的待遇？但我也要強調跟各位去強調，在我們的立法者往往會懶惰，甚至是恣意到連交代立法理由都不交代，這種情況在稅法是很可能發生，而且會經常發生的就是立法理由裡面寫按黨團協商條文通過。我要是大法官，我就直接宣告違憲。那個就是明顯的恣意。我知道政治是妥協的，所以有時候必須要發給。連理由都不寫，這個在法律上絕對過不了平等原則講的第三階段，就是你要有一個正當理由嗎？你連理由都不給。就更不用講，在稅法的條有一些是直接寫，按照某黨建議修正條文通過。我不一定有那個機會，但各位將來有有一天有機會當大法官，你一定要勇敢宣告違憲，這個就很明顯的恣意，就是無正當理由而做區別對待。你連立法理由都不寫的，那當然是一個不正當理由。有膽量你就寫出來，就是說軍教人員對國家特殊貢獻，薪水又少，所以我們給他特別優惠，當然接下來呢，就會涉及到很多更複雜的就是這個地方的區別對待，有沒有足以反映出這樣一個價值的判斷？當然這個地方我承認會有見仁見智的看法。

說軍教人員對國家有特殊貢獻的人，他也許並沒有強調，不是這個領域的人對國家就沒有特別貢獻。比如說我作為一個教育的從業人員來講，當然不會說，因此我們高等教育就完全不重要，基礎義務教育很重要，但為什麼在這個地方做了對同樣從事於教育，做基礎跟義務的區別對待，也許是在這裡面國家認為他的薪水或者是他的職務，或者是他的階級更為辛苦，也許是這樣。好，那就看，如果個案裡面就看你怎麼去說理，你認為軍人跟教師對國家有特殊貢獻，那公務員沒有貢獻嗎？農漁民各行各業難道不是在自己的職業跟崗位上面去對國家所謂的做出貢獻嗎？做區別對待的理由又在哪？如果說他的薪水少，時代變遷了以後，難道沒有與時俱進檢討的空間跟可能性嗎？ 在這個過程當中，無疑是立法者的怠惰。
縱使某個時代背景裡面有其正當性跟必要性，但並不代表著每一個時間每一個時代都認為這樣做是有正當性的，特別是在當今，勞動環境急速惡化，特別在二戰之後的勞動環境急速惡化，因為全球化帶來全球勞動力，或者工作機會的移轉，其實很大程度上會把高所得國家的勞動機會帶往低所得國家的勞動市場，這個是二戰之後的全球化帶來必然造成的一個趨勢。
所以勞動環境的惡化，薪資長期的無法上升，在這一種環境大變化下，所謂的教師、軍人是否有足夠的正當性去獲得這樣的特殊對待？

當然，軍人是一個比較特殊的職業，這一點我是承認。因為軍人是一個極為特殊的行業，在一般時期裡面，軍人這個行業，如果你自己脫逸軍隊的控制，他就是殺人，他就是強盜的行為，他是一個構成一個犯罪的一個行為。很多人基於良心或宗教的因素，根本不願意進入軍隊去。

但我們還是要回過頭來去講一件事，就在這個地方裡面，教師跟軍人究竟有沒有正當化的理由的區別對待，也許我們在稅法總則的課堂上裡面做進一步的討論。

回到我們的所得稅法裡面，我們這個地方，因為目前為止我們軍教人員的免稅已經被廢止掉啊，所以目前為止不太會有這個問題。

唯一剩下來留下來的是上個禮拜有跟各位提到，直接稅處26.4.21.處字第203號訓令，民國26年4月21號，你光看那個民國26年，大概就知道，這個直接稅處是因為當時候還沒有財政部，他是，直接稅處。

訓令就直接提到關於從事性工作的人是不用課所得稅。這是一個很典型的因為工作而做的區別對待。曾經在我們在宣告，關於從事性服務這一件事情是不是要把他合法化，特別是在罰娼不罰嫖的時候，我們在大法官解釋的時候，那時候一個非常大的爭議就是關於這樣子是不是強迫了更為弱勢經濟上更為弱勢的人，也就是從事與性服務工作的女性，因此在地位上面有更不利的待遇。那么這個訓令的背後邏輯是認為從事與信徒工作這個是被禁止的，也就是不法的行為，優先被取締，而不是透過課稅的方式予以正當化或者合法化。直接稅處的邏輯基本上是建構在所謂的課稅就帶來正當化的這樣子，或者是合法化，這個邏輯基本上是錯誤的。

最近也看到有一個政治上的新聞爭議，違章建築要不要課房屋稅？倒過頭來，房屋稅的課稅可不可以證明他不是違章建築？ 答案是，建築法歸建築法，稅法歸稅法。我們並沒有比建築法更低位階，我們也沒有比建築法更高位階，因為我們是各自管轄。在建築法裡面沒有取得建築執照、使用執照而蓋成的房屋，我們稱之為叫違章建築。因此，依照法律上的規定，原則上他必須要被拆除，否則他就是要依照法律去做相關執照的申請或者是做改建，那個是建築法的規範。對稅法而言，一個東西，只要他被蓋成四有周壁上有頂蓋，作為一個房屋，我們就可以課稅。對稅法來講，就是他是不是構成房屋，而不是他是不是有合法使用執照建築執照的房屋，所以違法的房屋仍然有課房屋稅的可能。回過頭來，如果違法的房屋不課房屋稅，只有合法的房屋才要課房屋稅，他反而會在稅制上形成一種不中立，反而是讓多數人會取向，未取得合法建築執照使用執照而去建住房。

也就是說，在稅制上面來講，我們不管原則上不管前端的他到底行為的合違法性，或者是那個財產的取得本身得很違法性。我們只看後面我們看稅法的價值，這一點也是要跟各位要特別強調稅法的價值是在量能而不在前階段，他是什麼手段去除的？所以殺人放火賺到的錢也是錢。

在羅馬帝國時代的時候，曾經有課過，上去上公共廁所要尿尿稅。尿尿會臭，但錢不臭啊，就是你去使用公共廁所的時候他他可以徵稅。因為對那個這個皇帝來講的話，認為說，哎，你去使用公共設施，你是有能力的，所以從而他要跟你課一個稅捐負擔。我們在這裡面主要是去講，不管你前面的行政法的規範，認定他是合違法性如何，我們在稅裡面的標準就是當你取得所得，當你有財產，當你有消費行為的時候，原則上根據稅法的標準跟講，你有稅捐負擔能力，原則上你應該要去課稅。

回過頭來去談到這一個從事於性服務工作這一件事情，不管我們國家的行政法的規範究竟開放或禁止到什麼程度。原則上只要有所得，就應該被課稅。所以即使是從事性服務工作，我們稅法還是毫不留情，也毫不猶豫地認為，你有賺到錢嗎？有，就請你繳稅。性工作本身的合違法性或合法化跟稅法是沒有關聯性，因此到過頭來，同樣的道理就是課稅這件事情無法去回頭證明這個行為本身在該國家裡面是不是取得合法地位這件事情。

我們提到的普遍原則，剛好會跟我們今天講的稅捐主體構成要件是有關聯性的。量能課稅的這10個子原則，基本上都是對應某一些稅捐構成要件，那這裡面對應著稅捐主體構成要件的就是普遍原則。目前為止，我們的所得稅法第4條第一款第二款違反普遍原則的條文規定，在現行立法上面已經被廢止掉，從而我們現行立法上並不存在著因為職業身份性別階級而做的區別對待。但我們實務上確實仍然存在著對性工作服務者因此取得的報酬。在財政部的前身直接稅處26.4.21.處字第203號訓令底下，這個還存在財政部編的每一年的所得稅法令彙編，他就放在第4條之後的附錄，也就是他沒有辦法被涵攝到所得稅法第4條裡面。所以他是透過我們財政部長期從大陸時期的直接稅處就把他既受過來，然後一直沿用至今，認為是仍然有效的一個解釋函令。很明顯，這個解釋函令，既無法律明文規定作為其依據，又不符合量能課稅的平等原則，更是違反稅捐中立的一個違法解釋案例。因此老師個人認為，像這一種違法解釋函令的存在，應該要加以改變。至於要怎麼改變？我上個禮拜，我跟各位提到過，有些學者認為這個是構成行政慣例。很抱歉，違法的解釋函令，不會讓你變成是一個具有法律確信的行政慣例，也就是這個地方，根本不構成行政上的習慣法。因為在行政法裡面，認為習慣法是一個法源。但稅法強調的依法課稅原則，並不承認習慣法具有這樣的一個法律地位，我們只承認制定法。制定法才有能夠確認國家跟人民之間稅捐法上權利義務關係的法律上的地位。習慣法，沒有辦法透過反覆之慣習人民之確信，而因此證立稅捐負擔義務。同樣的道理，人民也不因此證立不存在繳稅的義務，因為依法課稅，依法才能免稅。

我們不是一個單純依法免稅，不是一個單純的給付行政，他是一個依法課稅原則的反面構成要件。因此只有制定法才能夠成立發生人民的稅捐負擔義務，相反的，也只有透過制定，最低限度就是他授權的法規命令來做稅捐負擔義務的免除，而不可以透過行政上的慣例。行政機關無權去變更、創設人民的稅捐負擔義務的免除，即使他在結論上是對人民有利的。所以老師個人認為從來沒有所謂的，因為對人民有利，所以就可以，這樣子的一個所謂的行政慣例。從而這個行政慣例不成為法律，他就是一個很單純的違法行政上的慣例，違法的行政規則。

違法的行政規則，第一個，他不可能有稅務訴訟，因為被優惠的人不會去接到稅單。不被優惠的人，可能從事於同樣類型服務的工作，他並沒有辦法去主張說，哎，為什麼他從事性服務工作可以免稅，我不是做這個，可是我從事類似的工作，但為什麼我沒有稅捐優惠。如同那個道理，就是我從事高等教育的我沒有辦法去主張說今天國家對我徵稅，我拒絕繳稅，因為你應該要先對那些基礎義務教育人也同樣徵稅，我們大家都做教育的，為什麼他可以免稅，為什麼他可以享受稅捐優惠，我卻沒有享受稅捐優惠，以此為由來主張要求要平等原則的對待。因為當我主張這件事情的時候，他可能就涉及到，這根本不是權利，而是一個不法的主張，也就是說，我要求國家應給我一個免稅的優惠待遇，以讓我跟我認為是相同地位的人處在相同的地位上面。因為我不存在著這一種對國家主張應給我免稅優惠待遇的所謂權利，從而無法正當化，我透過拒絕繳納稅捐的方式去抵抗國家的稅捐徵收的行為。同樣的道理也存在，對從事於非性服務工作，但他主張我可以同樣滿足跟性服務一樣的，比如說身心靈的一樣的滿足的工作。你沒有辦法去主張，因為我們任何這一類的勞務或服務這一個的投入的行為，其實他都會被課薪資所或者是執行業務所得，他都會有相同的這些稅捐負擔的存在。

因此，第一個我們談到普遍課稅原則，尤其在所得稅的稅捐主體上，理論上來講，就是中華民國人民不分職業身份階級黨派原則上都只要有所得就應該課稅，這就是普遍性。那在普遍性原則底下，我們過去曾經有軍教人員的免稅原則上不符合這樣一個普遍性原則，他不構成行政慣例，他因為沒有個案的司法的判決出現，所以從來沒有被挑戰過。那也因此，學者也有一些建議，說我們可以立法的方式去改變他。因為延續著前面剛剛講就是行政習慣法。所以大家通過制定法的方式去加以改變，因為這個地方我個人是非常懷疑。我在想說，立法者怎麼會定一個法律條文說從事性服務者應繳稅並與敘明。這個是誰捅出來的簍子？是行政的問題啊，你怎麼會叫立法者去補你的漏洞呢？所以換言之，很簡單，這件事情就是財政部自己把他刪除掉就好了。好簡單的一個方法，結果到現在還刪除不了。其實刪掉的用意只是告訴你賺到錢要繳稅跟性服務工作的合法化是沒有關聯性。不能拿這個來換這個。有一些看法是這麼說，他可以用繳稅來代替行業的合法化，其實我也認為這個行業應該合法化，但是跟繳稅真的是兩回事。當然，接下來的困難就是從事於性服務工作，他究竟是執行業務者還是哪一種受僱的薪資所得，還是他是一個獨資商號，會有成本費用扣除的問題？ 這些是進一步去加以面對的問題。

所得稅不會只有在應課稅跟非課稅這個單純問題，因為接下來就是一連串的問題，就是如果你要課稅，我們要怎麼課稅、我們要怎麼樣的手段，是後面連續的問題。

### 【第二項全部原則及其後各項】

十項子原則裡面第二個叫全部原則，就是所得不分境內外，原則上你只要是所謂的稅籍居民，原則上，中華民國來源所得跟非中華民國來源所得錢就是錢，我們紛紛全部所得都應該課稅。

第三個叫實現原則，他要現實上實現，因為錢他這一個作為以通貨表彰出來的稅捐負擔能力，是一種現金支付能力，原則上是以拿到錢為基準。你設想預想他將來會拿到，那你那個預想跟設想將來可能會產生預估跟現實的差距。然後另外第二個就是時間，你太過早實現這個稅捐負擔，這個會是一個可以在實現原則裡面進一步去討論問題。

第四，實價（實值）原則。實價，應該依照真正的市場上的價格，售價，來做實價課稅原則。

第五，客觀淨值。這個我們在後面的法條裡面會一再地跟各位去談到。

第六，主觀淨值，是我們這個學期上課的一個重心所在，也就是個人賺的所得，原則上是要先扣掉維持自己跟扣掉維持配偶及受扶養親屬的費用。因為配偶實踐了婚姻保障家庭的制度，受扶養親屬是實踐家庭制度保障的一環，從而維繫自己個人生存配偶配偶的生存，以及維繫家庭的親屬的這些受扶養親屬的生存，這個會是主觀淨值原則。這也是我們這個課程裡面，在相對處理上面來講比較複雜，因為他要涉及到不是只有所得稅法要涉及到我們後來105年修法制訂的納保法，然後他又跟社會法裡面的最低生活費有密切的關聯性，因為他那個地方反映出來一個社會的最低生活標準，最低生活的所需的財產究竟有多少。

第七，個人個別主體課稅，就是individual，每一個人是每一個獨立的主體。但我們很快在我們綜所稅裡面會發現，我們個人到第15條規定的時候，變成家庭家戶所得課稅之在那個地方配偶跟受扶養親屬，從法律的意義角度來看，他不是納稅，艾薇兒是附屬在納稅人身上的另外一個個別的足以他是一個被扶養的對象而已，這個法律的體系，我個人認為是一個違反現代法律體系建構的基本精神就是個別主體，個別原則。但我們的大法官解釋裡面有許多大法官稱這個是見仁見智的立法價值抉擇，這個我看到這裡真是全身冒冷汗，這個怎麼會是這樣？現在法律就建構在每個人是自己的行為主體，私法自治，在講個人啊；刑法呢，個人罪責原則啊，這個最典型的就是每一個人就自己的行為去負責啊，我為了別人負責這種情況，怎麼能夠在現代法律裡面去發生了這種情況？什麼轉嫁罰大法？這是什麼概念啊？ 轉嫁把你做不對的事情，結果把那個處罰罰到我身上。其實在我們的文化裡面，往往有這一種連坐的概念。連坐處罰跟這個是不符合現代法律基本的精神，我們是個別權利。原則上。為自己的行為做起最終的決定，私法自治就這樣。那如果自己的行為啊，有可歸責的事由，那要去對這個行為去負起責任，這是個人罪責。我們的民法，我們的刑法是這樣一個基礎，而典型的以個人為主體。當然個人在憲法裡面被上升提升到所謂人性尊嚴的層次，這樣一個層次，這是整體現代法律制度的精神。我不否認，在進入近代化之前，確實有許多不同的國家區域，會有一些不太一樣的概念，特別是像部落。部落，不是一個個別所有權，他是一個集體所有權的概念，這種集體也沒有強調個別的權利，而是在強調這整個部落這整個族群本身對某一個特定事務或是特定區域的這樣一個享有特定事務的權利，這一個確實是跟近代的法律權利思想有所區別而有所差別的。這一點我承認，這也是我們現在目前在建構原住民族或者是少數族裔，特別是在，現代社會裡面，由於在經濟跟許多教育資源的弱勢的情況底下，現代法律制度裡面的精神，特別是所有權跟所有財產權的保護，也讓他們不太能夠維護這樣一個自我認同的一個價值。這個是一個現代法律裡面，我們個別還需要再進一步去做處理的問題。
但我還是回到，如果以我們現在法律基本上的精神是個別主體的話，課稅也是個別主體算。原則上特別注意算我跟另外一個人結婚，我要養他，那我會因此我付錢給他，他也是一個主體，他並不付出於我。他並不附屬於我，所以我只付給他的是他來維繫他的生存需求，而你容許我去扣除掉我支付給另外一半的這一個生活費用是維護了婚姻。他其實在說理上並沒有困難之處。不要把特別主體責任個別主體課稅原則在這個地方動搖，說我們採家戶課稅制，這個是我們現在目前的一些法律的部分的困難理論說理上的困難，跟一些法律建置上的困難

第八，綜合所得課稅原則。原則上所有的所得放在同一個稅基，我們不分離開來，當然這個其實是有很大程度的立法價值選擇，包括以英國為主的各個所得稅，或受英國法律體系影響的，譬如說香港新加坡，他們就是分離所得課稅制。在香港是個別所得的來源，他沒有放在一起去做出綜合所得稅的結算申報，那也因此在香港新加坡或是受英國法律體系所影響的。他們的稅制跟歐陸法系跟美國的法法的法律體系所表現出來類似。我們是綜合，我們是放在同一個稅基底下，這個就叫綜合不分類。我們講到第14條的時候，會去跟各位去談這個綜合所得課稅原則。

第九，終生所得原則。終生，意思是跨期間的意思，跨一個課稅期間。我們會到跨年度盈虧互抵跨期間盈虧互抵的地方跟各位去進一步去做說明。

第十，比例課稅原則。所得稅法我們在綜合所得稅是用纍進稅率，但在營所，我們卻是採比例稅率。就大概是這樣子的一個，各種不同態樣的實然跟應然之間的討論。實然也就是現實狀況的時候，這個地方從量的課稅原則的角度來講，他本來應該是這個樣子一個規定，但我們現在實務上的規定並不是如此。那是不是因此就因為違反量能、就違反平等原則，所以被宣告違憲？那也不盡然是如此，還是要看他在那個地方個別的價值判斷，就是立法者有沒有說出一個正當化的理由，而足以去正當化偏離量能課稅原則的這樣子的一個正當性

我們先休息一下之後我們來開展，今天我們想到的第一個，所得稅的構成要件，就是稅捐主體，也就是納稅義務人的概念，境內居住者、非境內居住者之納稅義務人。
所有的法律都有主體概念，民法有權利主體、訴訟法有當事人能力這種主體概念的意涵。我們先休息一下。
