# 20231023_02

---
課程：1121所得稅法一
日期：2023/10/23
周次：08
節次：2
---

我們到這個階段，主要就是經過了所得跟非所得的分類，然後所得裡面又分成應稅所得跟免稅所得的這個分類，那麼也進入到所得的類型。

## 【所得之實現時】

我們接下來進入客體的最後一個階段。原則上所得是不管是勞動力或者是資本投入，不管是繼續性或一時性，你只要因此產生所謂的經濟上的成果，被稱之為叫所得的這個成果出現的時候，在實務上面就會開始要去對你去做所得額的計算跟課稅。

但最後一個階段，我們仍然還是必須要去講，這個經濟成果的表現的方式，因此我們要判斷，所得的實現（實現了沒有）、實現的時間，以及所得的實現地點在哪裡？實現是一個經濟成果的表現方式。要討論實現時的問題，是因爲由於稅捐是以金錢為內容的給付義務，所以所得的實現就是經濟成果的實現，原則上是以金錢為內容的實現，這個時候我才會產生稅捐負擔能力。當我沒有實現以金錢（通貨）表現的方式的話，這個時候雖然我有可支配性，但我沒有辦法拿來做繳稅的内容。

我跟人家做交易，我拿到一張票據，原則上我不能拿這一張票去繳稅啊，因為國稅局不收票，尤其是不收客票。不是你自己本人開啊，那是你本人開可以嗎？也不可以，對不起。國稅局原則上只看到通貨，或者是約當通貨的現金的這些表現的，也就是我們在所得稅法第14條第一項第四類裡面，短票。

「三、短期票券指期限在一年期以內之國庫券、可轉讓銀行定期存單、公司與公營事業機構發行之本票或匯票及其他經目的事業主管機關核准之短期債務憑證。」


也就是，所謂的短期票券，被稱之為幾乎約等於現金，因此又被稱之為約當（約略該當）現金的短票。當然，約當現金，你也可以說他不是現金，因為只有中央銀行發行的法定貨幣才會具有完全的作為通貨的本質跟功能。通貨是拿來作為一種支付工具，除了通貨膨脹或緊縮產生實質購買力的差異以外，原則上一等於一，我們不在這上面去做價值上的變換。通貨膨脹或緊縮，在稅裡面，是被忽略掉的。當然例外的情況，通貨膨脹或緊縮，當一個國家的幣值變動很大的時候，國家必須要有一個反應機制去反映出人民的這個幣值變動極大情況底下所產生的實質購買力的差距，簡單來講，就是依據通貨膨脹去調整當代的那個幣值，透過直接用免稅額後扣除的方式，直接去把通貨膨脹或緊縮所產生出來的差異給消減掉。但原則上通貨本身在稅制裡面來講，就是一個全然的支付工具，而不計算其跟實質購買力之間的差距。

所得之實現，以現金跟約當現金為標的，因為我們繳稅，原則上是以金錢為內容，所謂的金錢是指國家發行的法定貨幣，而在我國的稅捐實務上面來講，跟現金接近的約當現金的這些短期票券，原則上也被認為他已經實現了稅捐上的負擔能力。


所得稅法第14條第二項規定：「前項各類所得，如為實物、有價證券或外國貨幣，應以取得時政府規定之價格或認可之兌換率折算之；未經政府規定者，以當地時價計算。」

這個地方那個取得時啊，取得時就是我們關於所得的實現時的基準點。原則上是以你可排斥他人去干預而取得該項標的或標的物的支配權力之時作為取得時間點的一個判斷基準。所得稅法第14條第二項規定的另外是針對你取得的，如果不是現金或約當現金之實體物，包括有價證券或外國通貨，這個時候則以表定價格，也就是表定的兌換率，換算成以新臺幣，也就是我們的現金為基準的計算標準。

這個就是14條第二項關於實現時間的規定。不是很清楚，因為他其實並沒有直接表現出來現金跟約當現金作為一比一的計算標準，他的表現方式反而是用所謂的，如果你取得的是實物有價證券或外國貨幣，由於他不是本地的通貨，因此他透過一個用政府表訂價格的方式也就是兌換率去折算成本地的通貨，這個時候才實現了稅捐負擔能力裡面的稅捐負擔能力的計算基準。

簡單加以說明，14條第二項是我們的實現時間點。因此，任何只要具有市場流動性之物，只要可支配，也就是可排除他人之干預而歸屬於所得的取得者，這個時候就是一個取得的時間點。儘管沒有換算成現金，在計算上面來講，是用政府表訂價格去計算現金支付的能力。這個14條第二項因此是我們現行法裡面唯一一個表述實現時間的法律的明文規定。

從稅捐本質上是金錢出發，但你取得的標的物或標的本身不是現金的話，則以政府表訂價格，或者是政府規定的兌換率去計算你的現金支付能力，成為稅捐負擔能力，這個是14條第二項關於實現時間的計算標準。也就是在這裡面，政府表訂價格雖然並不代表實質的購買力，因為這一些表定價格往往跟現金會有一段差距，而且因為不是現金通貨，從而他會有所謂的變現的風險。

我拿到一個有價證券，但這個有價證券也許有市場上的價值，有財產上的價值，但仍然不是現金啊。因為我不能直接以這個有價證券去繳稅。因此在這裡面會存在著一定程度上的現金支付能力計算上的差距。就這一點而言，只要變化不大，是屬於立法者價值決定，我個人認為應該基本上尊重這個決定，因為他的變化不大。他的變化是在假設現金，因為本身沒有價值的變化。當然你可以跟我跟我講說我現金怎麼會有價值的變化？柯老師，你到底是活在哪個世界裡面。對了，我知道，但是稅捐裡面，他必須要有一個基準點，就好像我們任何象限，我們怎麼樣，都是要畫出一個零點嘛。這個零點就是假設現金本身實質購買力不變，在這種情況底下，你拿到的東西，好特別是比如說你在外國工作，那你取得的是直接人家發給你美金或港幣啊，那你這個時候你不能繳美金跟港幣啊，那這時候我要怎麼算我們的稅捐負擔能力，那就是依政府表訂價格，把你的美金跟港幣換成新臺幣。

雖然政府表訂價格不是時時刻刻即時對應真正的實質的購買力，比如說現在新臺幣在貶值的情況底下，照道理來講，我應該算比較多一點啦，對不對哦，這個著理論上來講是這樣，那我現在幣升值的前一陣子，新臺幣兌日圓升值的時候啊，那我到來講，我應該沒有那麼高的稅捐負擔能力啦。那這件事情是14條第二項跟你講，立法者就這樣說了算了。在總是會有一個你沒有辦法完全接近的這個情況底下，原則上只要沒有差距太遠的話，那這個通常就會被認為這個是符合稅捐負擔能力的量的課稅原則，特別是在以實現的時間點。

比較大的可能問題，會是出現在依權責發生制。權責發生制是你沒拿到錢，但權利義務已經發生的話，那這個時候我就算你有所得，權責發生制是權利義務發生時就入帳，就算有所得，你比較容易產生那個時間差。

好，回過頭來，那為什麼營利事業就用權責發生制？這個是又是另外一個層次，因為在營利事業，原則上，他就假設你會按商業會計法編列財務報表。所以當你有財報，我稅務我就遵財務直接用一套帳。從財務到稅務裡面就一次去算你的所得，不然我每一次都要去做這種調整很累啊，營利事業要做一個財報給債權人跟股東看，又要做一份稅報給國稅局看，搞死人的。所以稅務遵財務。所以我們才一律採權責發生。避免營利事業的納稅義務人的依從成本過高。在這個情況底下也是一種實用性原則。

因此，量能課稅原則裡面的實現原則有比較高的彈性。原則上是現金收付。但營利事業權採用責發生制，這是另外一個層次的實用性原則，也就是因為稅務遵財務，營利事業不用做兩次帳。兩次帳的意思，不是指內帳外帳，是財報一份帳，稅務又做一份帳。這樣很麻煩。所以現在稅務遵財務，就只要做一份帳，再做稅的帳外調整，這樣就可以。這樣聽得懂嗎？

兩份帳，內帳跟外帳，這絕對是逃漏稅行為，不要在那邊胡搞瞎搞。兩份帳的意思是指說，如果營利事業賺錢，通常一般的情形是他要做一份財報給債權人跟股東證明我棒棒嘛，我好厲害，我賺到錢，對不對？相反的，他面對國稅局的時候，因為我的好棒棒，這是我的經濟成果，國稅局會以之作為課稅基礎，所以我會再做一份的稅務的帳冊來跟國稅局申報我賺多少錢嘛。那這個時候，基於實用性原則底下的我們稱之為叫稽徵經濟原則，那簡單來講就是我讓你只做一套帳就好。那你就做出財報，然後稅務在做個別帳外調整，那這個時候降低了納稅義務人為了要提供財報跟稅報的兩本帳的差異產生出來的依從成本，從而讓營利事業可以在計算所得的時候，直接用一套帳來記帳，來做課稅所得額的計算。只是指依照個別法律規定去做稅的帳外調整，基於稅務目的去做帳外調整。

最典型的帳外調整，權責發生制是這樣，比如說我今天因為排放廢水，被環保局裁罰。在裁罰的時候，這個就要入帳，在財務上權責發生了啊。你說我不一定要繳罰款，因為我會打行政救濟啊，沒關係，打行政救濟，你打不管你打贏打輸，這個是另外講。反正你被環保局裁罰的時候，你基本上就要先行入帳。入帳以後，作用就是避免營利事業膨風，說，我好棒我好棒，多發放盈餘。各位了解那個意思嗎？就是說，哎，我明明賺100塊，為什麼不能發100塊錢的盈餘？答案是因為你被環保局裁罰了50塊啊。雖然你現在實際上還沒有繳納罰鍰，你還在打行政救濟，搞不好你會贏，那沒關係，等你贏了再說，我現在要先入帳。先入帳，你的這個盈餘就只有50塊錢，因此你要發放盈餘是以50塊作為基礎，而不是以100塊作為基礎。

財務有一個叫謹慎或稱之為叫保守原則。這就是財務會計裡面的謹慎保守原則。在謹慎保守原則底下，權責發生的時候，原則上就入帳。當然還有更前端的，就是「期望」可不可以入帳？當然不可以。「期望」只是一個你主觀的想像，沒有發生法律上權利義務的那種期望，不能直接拿來做財務報表編製的基準。各位可以聽得懂嗎？我預期我公司10年後會上市，上市以後會跟馬斯克的那個特斯拉一樣，你信不信？反正我講你就信。可不可以把這種主觀期望放進去？不可以啊。謹慎保守原則說不可以把營利事業自己的主觀期望入帳，你必須要到法律上面的權利義務，也就是權責發生，這個時候，原則上就要入帳。對財務會計的人而言，他認為反而不要現金入帳，因為現金可以被操縱。各位可以知道，財務會計上的基本原則概念了。不能用主觀期望，也不是用後面的現金入帳，因為現金可以因為你現金的支付而去操縱所得實現的時間點，或是以盈餘發生的時間點。所以對財務會計學的人來講，他認為就權責發生是最典型的，這個就是他們講的實現。財務會計學者講的實現原則是指權責發生。所以當你今天賣出去，你有法律上的權利就要入帳，沒收到錢，只是應收款項，或者你應取得的債權，如果是現金直接就入帳，就這樣而已。相反的債務也是如此，應付款項，你沒付，你也是一樣要入帳，付出現金一樣會在你的帳戶裡面表現出來。

從稅務的觀點來看的話。所得的實現原則上是金錢的實現或者約當現金的實現，一旦用債權作為計算基準，反而會產生稅捐負擔能力的扭曲。只是這一種稅捐負擔能力的扭曲，在營利事業所得稅計算裡面，權責發生制是基於稅務遵財務的實用性原則，我們就用一套帳。但如果個人的話，因為個人原則上沒有商業會計法的適用餘地，個人就是用現金收付。現金收付才真正表現出稅捐是以金錢為內容的給付義務的本質。

好，我現在跟各位談一個釋字722號沒有很清楚呈現的一個概念，就是，當我是一個獨資合夥商號，而我的營業規模接近一個組織型態的營利事業，我只要依照商業會計法去記帳，你為什麼不給我用權責發生制？各位了解那個意思嗎？這個地方是不是跟營利事業所得稅接軌，對吧？只是組織型態的差別而已啊。

我現在假設哦，我是一個獨資合夥商號，我做的事業規模很大，跟你們營利事業沒差多少，而且重要的是，我也用商業會計法的方式去記帳。你為什麼不給我用權責發生制？因為你們營利事業這邊用權責發生制啊，我這邊用現金收付制啊。但當我的標準一模一樣的時候，我做的規模沒有比你差，我的記帳的標準也是一樣，我不是單純計日記帳而已，我還記到了商業會計法裡面的帳，那請問你為什麼在平等原則底下不給我適用權責發生制？

這樣各位清楚知道哪些地方是等跟哪些地方不等。你不記帳，就是現金收付，你記帳，依標準規格去記帳的話，讓你有機會轉成權責發生制。。

所以今天本質上相同的東西才同樣對待。等者等之，是指你們兩個做到一樣的方式，當然任何事物都會有等或不等的問題。其實獨資跟合夥就算營業規模大到跟營利事業一般的公司合夥組織一模一樣，你也可以講他們組織方式不一樣啊。這個不是這麼重要，真正的重點是在，在這裡面，如果他用商業會計法去表現出他的盈餘跟虧損，那他就有權利透過他的選擇權的行使，讓他自己轉換成一個用商業會計法用權責發生制來認列所得的，這種營利事業的態樣。

因此，當我一個事業組織體，不管我是農林、執業或者是營業，當我是用商業會計法的方式去做記帳，我的營業規模到達一定程度的話，我的資本的這個勞務的經營有獨立性，要繼續性，我的勞務做到這種程度的時候，我原則上可以轉成用營利事業的方式去課徵我的營利事業所得稅。

這正是我們在釋字722號裡面大概所提到的，就是說一個執行業務者，他不能只是因為工會的代收轉付這樣子一個形態，因為公會代收轉付，根本沒有改變他的性質。而是看執行業務者本身的執行業務的內容，他本身是不是以商業會計法上商業會計的方式去表現出來他的盈餘跟虧損。

這個地方，特別是對醫生，醫生從他的診所業務開始出發到社團法人型的聯合診所，聯合的這個醫療服務的提供，甚至是到大型醫院的提供，基本上只要用商業會計法的方式去記帳，容許醫生們可以選擇用權責發生制，因為醫生最容易有諸多的機器設備，他需要按逐年提供逐年認列的方式去認列。牙醫師要有機器設備，或者是一個醫院，只要一定規模以上，就會有需要。所以你會看到實務上大部分都是醫生，希望自己是執行業務者，可以比照營利事業。他們當然還是不認為自己是營利事業，但他們希望比照像營利事業的權責發生制，可以把他們的機器設備的成本給攤提在這一段經營期間當中。那我們律師跟會計師，剛好我們比較是人類精神的創作啊，我們的機器設備基本上不太多啦，我們不像醫生，機器設備，他們相對比較多，所以律師跟會計師事務所裡面，如果嚴格來講，不是不可以，但比較少。因為做比較複雜的會計帳冊用商業會計法的話，就代表著你的相關的東西，沒有學過會計的大概不會怎麼去記那個帳。會計師自己做自己的帳當然是沒問題，律師大概就會有這個困難。


所以一般而言，你想要改用權責發生制，那個過橋的做法，基本上就是按商業會計法去做，那理論上來講，在這裡面獨立的勞務就有可能讓你應該要有這個機會，可以選擇用權責發生制來認列你的課稅所得。

回到稅捐本質上是金錢給付，就是現金收付，特別是對不記帳的所有的這些人，這一些人基本上一定都是用現金收付制。14條第二項並不是很明顯的，理由在因為沒有講你的所謂的取得時間，也是一個排斥他人的干預，而可以支配，原則上是取得現金，而是他直接跳過去，就規定說，如果你是拿到現金以外，有體物或外國通貨，則以政府核可的兌換率或者是比例去做計算。為什麼要做這樣一個比例計算？答案是因為我們要用我們的通貨來計算你的稅捐負擔能力。這個是14條第二項的規定。



## 【所得實現地點】

OK。最後一個問題。實現的地點，原則上必須在中華民國境內。因為我們的所得稅法第2條第一項跟第二項都必須，所得實現在中華民國，才會有中華民國來源所得的問題。因為我們綜所稅的所得，是沒有就境外來源所得課稅的，我們只就中華民國來源所得。不管你是我們的境內居住者或非境內居住者。我們的所得稅法又更強化了那個屬地主義的判斷。相對於此，如果是德國跟日本的所得稅法，你是我們的稅籍居民。稅籍居民，不管你是來自於德國和德國以外的所得，原則上都要課德國的所得稅。日本亦如是。你在日本取得跟日本以外取得的所得，你只要是日本的稅籍居民，他就要課全球來源所得。這都是採屬人主義的國家。因此對他們來講，分辨實現地也許沒有你想像的那麼大的區別實益。


好，回過頭來。我們還是要去講為什麼實現地這一件事情在我們的法律裡面很重要，是因為從民國96年開始，我們已經將境外來源所得，改課所得基本稅額條例的最低稅負制。所以不要說再用以往的觀念，所得稅法只就中華民國來源所得課所得稅所得，所以我們就不需要去辨別實現地。

不是這樣，因為臺灣並不是真的全然採用屬地原則，我們其實是變相地從民國96年開始，2007年開始，我們改課所得基本稅額條例的最低稅負制。所以我們的所得稅是境內來源課所得稅的所得，非境內來源所得改課所得基本稅額條例的所得。就這樣而已。這個立法者的價值決定，我認為違反平等原則，但他仍然是立法者的價值決定，沒宣告違憲之前，他就是長這個樣子。

所以為什麼我們最後一章還是要去辨識，是不是中華民國來源所得，是有區別實益。因為中華民國來源所得課所得稅所得。因為非中華民國來源所得不課所得稅所得，改課所得基本稅額條例的個人所得基本稅額，個人的最低稅負制。

立法者做了一個不同的決定。原則上我們就稱之為叫立法者的價值決定。德文講價值決定臺灣到目前為止沒有統一的翻譯，那我直接就用德文的【Wertbestimmung】，所謂的價值決定。


好，這個價值決定有沒有合憲，我個人認為是不合憲。我已經跟各位講過，綜所稅所得免稅額一點點，累計稅率最高到40%？所得基本稅額條例呢？他是把境內境外合在一起給你一個670萬的免稅額，然後稅率比例稅率20%。所以光這個稅制並排出來，你就知道，臺灣，你取得境內來源所得，你可以被課到最高40%。可是如果你同樣這一筆所得，取得全部都是境外來源所得670萬免稅，就算要課，也是20%。這不是標準的差別對待嗎，對你取得境外來源是提供優惠鼓勵，請問還有什麼情況底下可以正當化這種立法者價值處境？他就是歧視你，怎樣，你跑不掉，關起門來自己打，就這樣。這是一個明顯的對自己本國的取得本地來源所得的稅負上的不利益對待。當然你取得比較高的境外來源所得的話意思是你很有本事，很好，我們可以670萬的免稅額度。因為我們的所得基本稅額條例是境內境外合在一起算一個670萬的一個免稅額度，所以我現在必須要假設，如果境內零，你全部都是在美加取得所得，那這種情況你真的是蠻被鼓勵的，因為你只有超過670萬以上才會被課稅，而且就算被課稅是20%。所以假設你賺1000萬，你炒美股，炒日本股票你賺了1000萬，講白一點，就是在我們的稅制裡面，就是減掉670萬，然後再乘以20%。可是你如果在境內，你當然炒臺灣的股票更好，因為臺灣根本連證所稅也都沒有喔，那你在臺灣如果有1000萬的所得的話，你一定是最高邊際，因為我們的免稅額就這麼一點，那原則上就適用最高邊際稅率的40%，你可能就會有比較多的稅負。


這個是我們的這個，實現的地點，是有重大的區別實益，因為我們的立法者在這個地方做了所得基本稅額跟所得稅的差別對待。在進入真正要去談中華民國來源所得的那個認定標準之前，我們還要先跟各位說一下，在兩岸人民關係條例裡面，我們是用臺灣地區居民跟大陸地區居民去描述我們的稅籍居民。因此，根據兩岸人民關係條例第24條的規定，只要你是臺灣戶籍，在臺灣，他把臺灣地區來源所得跟大陸地區來源所得全部算做中華民國來源所得課所得稅所得。如果你是來自於港澳地區，根據港澳關係條例28條的規定，你如果取得的是港澳地區來源所得，則不認為是中華民國來源，所得是境外的所得，就是不是課徵綜所稅所得，而是改課所得基本稅額條例的所得。如果你是美加，那就真的本來就是境外，所以他就一定是課徵所得基本稅額條例的所得。

你只要是設戶籍在中華民國境內。你取得了臺灣地區跟大陸地區來源所得，所以臺幹，我不管你派到那邊多久，你只要在那邊取得大陸地區來源所得，你也是綜所稅所得。

如果你是被派到香港，好，派到香港去的話，那就香港地區來源所得，根據港澳條例的規定，不課綜所稅所，改課所得基本稅額條例的所得。

那你如果更有本事，你跑去美加賺到錢啊，那就本來就是境外啊，這個本來就是所得基本稅額條例的所得。

所以我們這樣子哦，錢不一定全部都課綜所稅。當你是我們的稅籍居民，戶籍設在中華民國境內，那你就會是臺灣跟大陸算綜所稅所得，香港跟美加都算所得基本稅額條例。

我們接下來講第二種情況，你戶籍不設在臺灣啊，你戶籍改設在大陸，也就是你現在已經變成是大陸中華人民共和國的戶籍的居民的話，你僅就取得臺灣地區來源所得課所得稅所得。

他透過戶籍的方式去區別區辨課稅所得的來源的課稅的稅負，所以你是設籍在大陸。哦，當然了，這個其實到底設籍在大陸還可不可以繼續保有中華民國國籍，這個我不太確定，這個我不敢跟各位100%地說，我只能說確實我們用戶籍去做區別啊。在臺灣跟大陸之間不用國籍區別，他是用戶籍做區別，因為我們兩岸人民關係條例適用戶籍去做區分，臺灣的地區的居民跟大陸地區的居民。好，這個的區別，他的區別實益是臺灣地區的居民，不管你是來自於臺灣跟大陸，全部都課所得稅所得。如果你是大陸地區的居民，那只就臺灣地區來源所得。

那我們想，大陸地區居民取得大陸地區來源所得，你可不可以課稅？你敢課稅試試看，習近平在北京賺到了錢，你可以跟他課稅嗎？你課不到的，在想什麼。

大陸地區的居民，他只有取得臺灣地區的來源所得，這個時候他才課我們的所得稅的所得。

大陸地區的居民如果取得港澳地區來源所得跟美加地區來的所得，講白一句話，干你屁事？干什麼事？你能課稅嗎？你當然課不到稅了。你能怎樣？香港政府給你申報資料嗎？或者是你期待他們進來的時候，希望他們過境給你提交稅捐申報書嘛？那不可能啊。所以，如果真正是第三地的人民。港澳地區在我們的法制現況裡面，稅制的現況裡面，基本上都是當作境外地區，所以香港的居民澳門的居民，他到這個到大陸地區取得所得，因為香港澳門地區有很多人跑去他們北上進内陸去發展，這個當然不會課我們中華民國所得稅，也不會跟我們有什麼所得基本稅額條例的連結。

港澳地區的居民如果真的來臺灣取得臺灣地區來源所得，而這個時候，我們一樣是課所得稅的所得，因為他是我們的屬地來源所得，他不是我們的稅籍居民，但他會取得屬地來源的綜合所得稅所得。那港澳地區的居民，如果他取得美加來源所得，那當然就不干你事啊，你跟他沒有稅制上的連結。

所以我們大致上就跟各位以這個我們的兩岸三地跟真正的境外地區基本上做一個區別。立法者的價值決定在兩岸人民關係條例，跟港澳條例，以及所得稅法裡面去做稅基上的不同切割跟對待。這個就是我們的偉大的稅捐立法者所做出來價值決定，這種價值決定，基本上體現在實現地的不同，會有稅負計算上的差異。稅負計算的真的差異很大。講白一點，到大陸發展的臺幹，基本上綜所稅是很多的。就賭你不敢換戶籍，你敢勇敢地換戶籍，還真的只課臺灣地區來源所得，就改課大陸的所得稅。

## 【結語】

我們今天先暫且到這裡。因為我們下個禮拜，請各位務必準備一個「中華民國來源所得認定原則」，因為那個是一個非常長的財政部的解釋令，請各位先把「中華民國來源所得認定原則」先下載。我們下個禮拜要講所得稅法第8條的規定，但第8條的規定有寫跟沒寫差不多，因為他幾乎是14條的重聲，再加一個中華民國來源。我們真正實務的判斷上，則是要回到剛剛跟各位講的中華民國來源所得認定原則。這一個中華民國來源所得認定原則，根本不長期為法規命令，就是一個行政規則。一個行政規則，實際決定的到底要課綜所稅所得，還是是課所謂的所得基本稅額條例的所得。這個基本的價值決定，這個是重大的價值決定，如果用依法課稅原則來講，我國稅法根本就沒有遵守依法課稅原則，因為所得稅法第8條根本就沒有規定這麼細的事項，這些全部都是用剛剛所提到的認定原則，去做一個行政規則上的調整。看起來是一個事實認定規則實際上則是切割稅基的規則規定，所以在依法課稅原則底下，我個人認為應該要用制定法或者是法規命令的這個長期的規定。我們的所得稅法第8條要重新調整才對。但如果所得稅法第8條把整個所得來源地認定原則塞下去，你就知道我們所得稅法會膨脹多大。

我們下個禮拜會再跟各位去講這裡面的來源認定原則其實是有秩序的標準的認定。下個禮拜，除了那個所得來源認定原則以外，我們就是要按這個（所得類型）圖表來跟各位去講他的來源地鎮定大致上是按你的所得類型去做區別的。法律完全看不出來，但是所得的分類真的是決定我們在判斷你是不是中華民國來源所得的一個非常重要的區別標準。大致上我們做一個對照就可以比較清楚的知道背後的基本原則。

今天先到這裡。