# 20231127_02

---
課程：1121所得稅法一
日期：2023/11/27
周次：13
節次：2
---


關於受扶養親屬，在我們的課稅制度裡面，婚姻跟家庭就是結合在一起。我們還是要跟各位做一下區別。


對於受扶養親屬，會為了要說明方便起見，我還要再繼續分成直系血親的尊親屬跟卑親屬，那么當然也有旁系，甚至是根據我們的法律規定，你只要以永久共同生活的目的在一起的家長跟家屬，這個都會是。

直系血親卑親屬裡面，我們再把他分成了一親等的子女，跟二親等孫子女以上。子女這個部分，我再把他分成成年，跟未成年。這個分類，待會有說明的必要。

## 【婚姻跟家庭的合併稅制】

我們的合併申報制度，根據我們所得稅法第15條。在釋字318號解釋之前，他基本上都一直延續著這個精神，就是合併計算、合併繳納。

合併計算，這個是實體法的規定。從申報繳納開始應該是程序法上的規定。

根據所得稅法第15條的規定，納稅義務人在做結算申報的時候，當構成數個主體合在一起，共同組建婚姻的時候，我們的法律制度基本上是強制性的，合併申報。也就是納稅義務人跟配偶，原則上必須要強制合併。只有在例外的情況底下。法條本身並沒有規定例外的情況，釋字318號甚至696號之前，我們法條並沒有任何規定，可以分開申報。但是當時候透過財政部的74年的解釋函令，裡面提到，如果你是分居的話，則無庸合併申報，分居的話就不用合併，可以分開個別申報。但稅額還是要合併計算喔。我只是讓你可以分開個別報，但你的所得額原則上還是要合併計算喔，那當然繳納還是合併繳納囉。只是讓你在74年的解釋函令裡面可以去做分開申報。因為你是分居的情況，我沒辦法強制你要合併結算申報。從而這個74年的解釋令，讓納稅義務人可以跟配偶可以去做分開來的申報，但是所得額還是要合併計算。


就因為所得合併計算，在合併計算底下，由於他有可能稅負會提高，因為這個基本上是常識啊，因為我們綜所稅是累進稅率，是超額累進稅率。兩個人，只要都有所得，加起來一定比一個人所得多啊，這還用講嗎？除非你的級距夠寬大，不會跳一個級距，不然的話，兩個人所得加起來一定比一個人所得更高，這還用講嗎？除非另外一個人完全都沒有任何所得。或者加起來以後，他們還是在同一個級距內。


我們在此之前跟各位講過，我們的所得稅法是五個級距。這個寬幅度，這個叫級距。假設這個是50萬，這個是100萬，這個150，這個是200，這個就是級距。兩個人的所得，100+100，跳一個級距，你的稅負自然就會比較高啊。所以這個是你可以算得出來的。當兩個人所得被強制合併計算的時候，當時我們的所得稅法是容許只有薪資所得分開計算。如果你們夫妻兩個，其中有薪資所得，那薪資所得可以分開。只有薪資所得可以分開。因此配偶可以就薪資所得拉出去，個別計算，但還是要合併報繳。

74年的解釋函令就是以這個作為基礎，因為你合在一起算，適用累進稅率一定會比較高，所以這個時候你們兩個要根據你們的所得額，比例分攤那個高出來的稅負。

釋字318號當時面對我們的所得稅法第15條規定，納稅義務人只要結婚之後，原則上當年度開始就要強制合併申報、合併計算，只有薪資所得可以分開來計算。配偶，如果有薪資所得，可以就個人的免稅額及薪資所得扣除額，個別計算，其他還是歸納稅義務人歸戶，由納稅義務人計算所得稅，然後來繳納。誰繳？納稅義務人繳。分開是只是計算而已，回來還是納稅義務人繳納？這個就是我們釋字318號當年的所得稅法，是長這個樣子。當年釋字318號說，合憲，哦，我警告一下哦，這樣可能有增加稅負之虞，請主管機關與時俱進檢討一下。警告性的宣示，但沒有說他違憲，或與憲法的平等原則的負擔不符合。

合併繳納，沒有講。合併申報，爲了減少申報單位，合憲。合併計算啊，這個可能會增加稅負，這個請主管機關檢討，與時俱進改進。好，後來當然沒改，因為後來實務，稅捐稽徵機關說，連318都說我們合憲啊，他也沒有說違憲，如果違憲，他就會宣告違憲啦。


## 【婚姻】

就這樣，釋字318號就一直維持這個制度。所以我現在舉個例子來講，假設各位同學，兩個畢業之後，你們在學校的時候相認相識之後步入婚姻的禮堂，就結婚了，兩個人都做執業律師。一個賺200，一個賺150，加起來，350，適用到30%邊際稅率。如果你們個別分開來算，你們可能個別都是適用最高邊際稅率20%。我這個地方只是為了簡便去反映出稅負的差異，不考慮前面的級距，實際還要考慮累進差額。

甲乙結成婚姻共同體以前，他們總共要繳的稅負是70萬。可是照我們當時的所得稅法的規定，由於兩個都是執行業務所得，所以他是200+150，執行業務所得適用邊際稅率30%，因此他會變成是350×30%，105萬。這個中間的差額，105-70多出來的35萬，這個怎麼會不是增加婚姻共同體的稅捐負擔？

之前兩個人個別賺來的錢，他們兩個就算同居在一起，也只需要繳70萬。結果有一天他們想不開了，進入婚姻禮堂以後，竟然國家說，你們要繳105哦。為什麼？因為你們強制合併。你沒分居，趕快分居啊。請問這個制度怎麼會對？你還敢說婚姻有制度保障？連平等對待都沒有，婚前婚後平等對待都沒有的制度。釋字318，還認為合憲。我還真輸給你，這樣叫合憲。這不叫合憲，這個是對婚姻，對進入婚姻的人的處罰。不僅是對進入婚姻的財產權的違反平等原則課稅，也是同樣對我們大法官向來一直宣示的婚姻應受憲法制度保障的背離。

進入婚姻的人沒有受到保障，反而是更不利。其實如果是兩個都是執業律師，我教各位一個方法很簡單，就可以規避這個條款規定。我當時在學校上課的話，我都會教這一招。你們兩個都執業對不對？你就請他就好，他受僱於你。反正事務所都是你們在經營的。各位聽的懂嗎？兩個律師，你們幹嘛合夥？一個受僱於另外一個，另外一個就叫薪資所得。這麼簡單就可以規避。所以當時的制度是在對不懂稅法人的懲罰。因為你們不懂稅法，那你就很自然被懲罰。但這個制度，如果兩個都是不同的執行業務者，就沒這個可能性。比如說律師跟會計師結婚，會計師跟醫師結合，就沒有辦法。兩個都是律師，兩個都會計師可以，兩個都醫生互相僱來僱去，這個都可以。但是兩個人一個律師一個醫生就是不能這樣，因為非律師不能聘僱律師執行律師業務。


這完全不是立法形成空間的問題。因為從量能課稅、個人課稅原則，就知道這個制度是在對婚姻進入婚姻的個人的歧視。一直到696號，我們才終於說這個制度，這樣不可以。


我回到這裡面講，對於分居，其實沒有立法，是財政部自己做出來的解釋。到我們現在的法律裡面才加進來分居。696號解釋之前的分居一直只存在財政部的解釋函令裡面，他沒有一個條款規定說夫妻在結婚之後，如果你因為分居，你可以分開申報。夫妻，照我們的法律15條第一項規定，一直都是強制合併，所謂的強制，就是你沒有選擇不合併的理由。

不合併的理由，是到696號解釋之後，大法官做成解釋以後，我們之後才把分居這個要件放到我們現在目前的所得稅法裡面，如果你有分居則可以分開。那我現在就問各位一件事情，在臺北市共同執業的夫妻兩個人，他們兩個同床異夢，完全就是沒有辦法跟對方分享，我們兩個報稅的時候，為什麼不可以分開來報稅？我們沒有分居，我們還是同住在一起，因為我們沒錢買另外一棟房子。你叫我搬，那你搬呢，為什麼不是你搬？

請問為什麼要設定分居這個要件？為什麼一定強制夫妻得要合併申報？強制夫妻合併申報，意味著我在申報出去的時候，我必須要告訴另外一半，我的所有的所得的資訊，我要告訴你，才能告訴國稅局。這個是一個稅捐資訊自主權的干預。

我協力義務確實是要求跟國稅局去做申報。但沒有必然要透過另外一半才跟國稅局申報的道理，這個轉彎，繞道是不必要的過度干預。因為我這個申報，我就必須要告訴我另外一半，我哪裡有所得。沒錯，我是生活共同體，但我不想跟你分享我的所得，不可以嗎？我出去上課的時候，幾乎都會問在座的每一個人，請問一下你會跟你太太或是先生報告你有賺多少錢嗎？有的請舉手。

我們現在夫妻早就分別財產制很久了，有一定要跟對方講多少所得嗎？那為什麼強制合併申報呢？請問你的道理在哪？696號仍然說強制合併是合憲。強制本身就違憲。

資訊的告知是要得其同意，我今天不跟你合併申報，就代表著我不想告訴你另外一半，即使是生活共同體，我也沒有必要非得要告訴你。所以德國的婚姻合併申報制，是任意性的。任意性的意思就是，你可以個人申報，無需要理由。你個人申報就跟你婚前的狀態一模一樣。因為你們婚前本來就是個別申報。結婚之後，你也可以選擇個別申報，也可以選擇合併申報。因為申報只是程序法，只是共同把你們的所得寫在一張結算申報單上，如此而已，沒有更多，也沒有更少，就這樣。

就像共同起訴執行訴訟的當事人，他沒有必要非要必要共同訴訟，訴訟標的要合一確定。一樣的道理。這不是很難的概念，我也不認為是很難。合併申報就只是兩個人所得的寫在這一張單子上。各自對自己的申報的所得額項目、扣除額項目，負擔誠實申報義務，這樣很難嗎？

當合併申報以後，我們現制是這樣，合併申報的納稅義務人要對配偶申報的這些所得全部都由納稅義務人合併計算、合併繳納。

所以我現在跟各位講一件實際上一定會發生的，你們那一年的時候，你們是配偶，但是你本來應該要繳納稅款的，都是納稅義務人繳，但是之後你們兩個離婚了，當年的所得稅還是要你繳。啊，不然要叫誰繳？因為當年你是納稅義務人。所以我現在上完這一堂課以後，大概就跟各位同學，以後報稅，千萬不要自己當納稅義務，你應該鼓勵對方成為納稅義務人。因為你要準備要有自己私房錢的時候，你就準備好，讓對方當納稅義務人啊，離婚之後再去檢舉他。讓他被處罰，誰叫你要離婚？你不覺得很荒謬嗎？


請問這裡面有幾個主體？兩個人啊。婚姻裡面是兩個主體。所以德國不僅是任意合併申報，德國的制度裡面是容許納稅義務人，因為他們是生活共同體，所以他也可以把所得額透過因為是合併申報，所以他們可以「折半乘二」。這個制度被稱之為有利於婚姻的家庭課稅制。

因為當我一個人賺200，一個賺150，雖然都是用20%的稅率，可是如果我能夠加總以後除二，也就是加總以後折半，我就有可能適用比較低的累進稅率。簡單來講，就是我一個人賺200，另外一個人假設賺50萬。250+50變成250，250÷2，125，他就有可能是用比較低的邊際稅率10%。這個制度在德國因此就被認為是對婚姻制度的促進。對同性伴侶也同樣適用。這個制度會讓進入婚姻的人，如果一個人賺200，一個人沒有賺錢，或者只有賺很低的數額，因為折半乘二會可能讓他稅負計算的稅額降低喔。


比如說200+0，因為另外一個沒有賺錢，折半是100，100去適用的邊際稅率只有10%。所以只需要繳納10萬塊，再成二，因為是兩個人，所以10+10，所以他們家庭總稅負是20。如果各自分別計算，200適用20%稅率，稅負是40。

德國制度的操作，第一方面是任意合併申報，你可以選擇跟另外一半要和要不要合併，但如果你選擇合併，你可以勾選合併計算所得額，折半乘二計算。這個時候的另外一半合併申報就有一個誘因，讓他可以在這個制度底下降低稅負。

但這個制度，在德國被左派認為是對於進入婚姻的人有利，但是對單身者不利。單身者沒這個機會跟可能，因為德國現在很多人不願意進入婚姻。所以當他們是事實上同居狀態，就沒辦法享受這個制度。所以當然，沒有辦法每一個人都滿足啊，像我剛剛講的這個德國的婚姻制度，即使是對同性婚的人，也同樣適用，可問題是，對沒進入婚姻的，不管你是男男女女，或者是男女，事實上同居，一樣還是沒有適用餘地。

這就是德國制度一直以來有他的爭議性所在。

但反過頭來臺灣的制度是從釋字318號開始，就是一個對進入婚姻的人不利的制度。到了696號，我們仍然強制合併申報，但對於合併計算所得，就宣告違憲。所以696號之後我們就改成了幾種可能性，第一種就是原則上全部合併，第二種，就是以前的薪資所得可以分開計算，之後我們因為696宣告違憲，所以我們現在還有其他所得可以分開計算。

這就是我們現在目前的所得稅法第15條現在的樣子。15條的第二項規定。

第一種就是全部所得合併計算。

第二種叫薪資所得的分開計算。

第三種計算方式，叫做各類所得，就是其他所得的分開計算稅額。

我們的法條規定就因此看起來極度地複雜。但第一種合併計算所得，只要你們夫妻double income，我才不信你們要合併計算所得。除非你們沒有變更課稅級距，不然一定很不利。第二個，薪資所得分開來計算。現在在實務上，這一類型確實很多。因為在實務上，大部分人取得薪資所得，大概在納稅義務人佔七成左右，所以大部分人都可以有薪資所得可以分開來計算。最後一個叫做，各類所得的分開計算，也就是將14條第一項各類所得分開計算。其實這一個條文規定，本質上本來就是把第二款規定的薪資所得分開計算，再把擴大化而已。其他各類所得都可以分開計算，他的極致就是個人個別計算所得額課稅。符合量能課稅原則的基本上是個別主體課稅。


雖然婚姻跟家庭會讓數個主體有一個生活共同體的概念，但是在個別主體課稅的原則下。個人基於扶養另外一個人，包括配偶及受扶養親屬，這一個法律義務範圍內，屬於當事人納稅義務人不可自由支配的所得，所以承認只要越親近的親屬，會有比較高的扶養親屬的扣除額，是現在OECD大多數國家的課稅立法。

OECD大多數國家都是個人課稅為原則，再按照配偶、親屬，直系關係旁系關係，或是家長親屬的這些關係的親疏遠近再給他不同額度的扶養親屬的扣除額。這正是大多數國家的課稅立法的現況。這一種數額的反應，原則上要反映出你們各自國家法律裡面的法定扶養義務的範圍。簡單來講，夫妻是同林鳥，一般來講，配偶的扶養扣除額的扶養費用額度是最高的。因為他們是共同的生活水準，只要他們沒有長期處在分居狀態底下，配偶之間的扶養費用扣除額是最高的。其次，接下來呢？未成年子女。因為未成年子女自己沒有扶養自己的能力，仍然必須要讓父母親去照顧他。從而大多數國家的所得課稅法制，稱之為綜合所得稅的，基本上一定是納稅義務人個人先算，再扣掉我付給配偶、未成年子女以及其他受扶養親屬，根據你的關係親疏遠近，你要劃分幾級，我沒有意見，但原則上立法原則就是反映出你的法律扶養義務的範圍。


這個制度本來，理論上也應該要反映出民法裡面的受扶養基礎的範圍的制度。在這裡面，稅法應該以這種面貌去跟民法的受扶養親屬的範圍去做結合。但很可惜的是，我們的所得稅法跟民法之間的結合關係，卻是以一個很怪異的方式去做結合。特別是婚姻制度的結合，這個部分我們強制合併申報。分居例外可以，分別申報，我們在696號之後的所得稅法修法，現在是可以分開計算申報。計算計算稅額，有三種可能性。這個當然更接近於個人所得課稅原則。但後面的繳納，這個就沒變。

合併繳納。什麼叫合併繳納？你們怎麼算怎麼算，不管，最後面就是一個人繳稅。最後面，這個人繳稅，就形成了一個問題。所有的所得，全部都這個人繳稅，那萬一這個當事人的婚姻狀態有變更，那怎麼辦？如果事隔多年之後，國稅局發現配偶有應報稅所得，沒有報稅，請問是命誰補繳？納稅義務人補繳。誰叫你時候要嫁他娶她。好，問題不是只有如此。裁罰呢？違反誠實申報協力義務的裁罰。我們後面還有裁罰呢。

誰漏報，理論上本來應該是處罰誰。但很抱歉，配偶不是納稅義務人。所以不是罰配偶，是罰納稅義務人。納稅義務人哦，既然被要合併申報，你就要好好地好好地仔細詢問一下，你的另外一半到底有沒有隱匿所得。沒有交代的話，將來的處罰，還是處罰你？


在德國，強制合併申報不存在，是任意合併申報。當他們兩個任意合併申報的時候，稅款的負擔，他們是一個連帶債務人，可是個別對自己的申報負擔誠實申報的義務。所以稅款確實會有連帶債務，由納稅義務人來幫另外一個納稅義務人負擔的可能性。但誰隱匿，誰就該受罰。不應該是配偶隱匿，卻讓納稅義務人受罰。這個叫個人罪責原則。這難道不是現代法律的基本精神嗎？個人罪責就是個人隱匿個人承擔責任，個人要被處罰。

所以，我們的稅捐法制完全沒有建構在以個人作為權利義務主體的基礎上。個人才是稅捐法上權利義務的歸屬主體。個人才是制裁法上的歸咎主體。要歸咎，也要歸咎隱匿課稅行為的那一方當事人。不能因為他是配偶，不是納稅義務人，就讓納稅義務人去替隱匿所得的這個配偶來負起責任。

這個是我們的整個婚姻合併申報制。到目前為止，696號之後，我們現行的法律規範狀態是，原則強制合併，例外法律規定分居的時候可以分開申報。分開申報的時候，原則上計算所得額有三種計算方式，大多數的納稅義務人基本上會選擇第三類的其他所得的計算方式。但是繳納，仍然還是所有人都歸到納稅義務人去做繳納。正因為所有都由納稅義務人去做繳納，當如果有其中配偶有漏報所得來源的時候，裁罰還是對納稅義務人去做裁罰。

我們目前的實務基本上一路都是這樣子操作。那我自己，特別是對財政部的所屬的公務員，我都跟他們一定要求，說今天合併繳納我動不了，但是裁罰，我一定要找出為什麼納稅義務人不知道這個事實，他有可歸究的事由，不可以直接因為配偶漏報就直接罰納稅義務人。不可以，你必須要有足夠的證據資料顯示，納稅義務人知悉資溪配偶有該項所得，但他卻沒有誠實申報。


像在臺中，有發生一個案例，那個案例是臺中以前一個很知名的政治人物，議長。議長在外面受賄。太太說，我不知道他在外面受賄。因為那一年報稅的時候，議長，有好好請教過稅捐顧問，叫太太當納稅義務人。根據太太自己的說明，常年在國外帶小孩，不知道先生在臺灣幹什麼事情，不知道，收多少錢，都不知道，全部都不知道。報稅的時候，太太是納稅義務人。先生是配偶。所以配偶在外面受賄。納稅義務人說，我不知道，不能罰我。不能罰你，那罰先生？也不是。因為先生不是納稅義務人。那罰納稅義務人，就是太太。太太主張，我是家庭主婦，我根本不問政治。我長年都在美國，都在照顧小孩，所以我不知道這件事。

國稅局就只好翻出來，太太幾年到幾年在臺灣待多少時間，平常在外面做哪些事情，一律調查。調查說，你怎麼會不知道收了幾千萬這些錢？賄賂，也是所得。再用這個方式，叫議長夫人，繳納、裁罰。

回過頭來，我就問各位，為什麼是議長夫人要繳納，為什麼是議長夫人要被罰？錢難道不是議長收的嗎？他們如果還維持婚姻，那就算了。如果他們已經沒有婚姻關係，你的補稅和裁罰的對象，不是錯了嗎？

所以我們的制度，我個人認為我們的婚姻合併申報制度是一個違憲法制。所以老師準備，我是有婚姻狀態的，報完稅以後，我就……

但現在，我有一個有一個很大的心理障礙。因為我去提起訴訟啊，所以我一定會一路輸。啊，報紙就會報，臺大稅法教授啊，打稅法訴訟，一路輸！

（笑）

陳清秀老師當年就是這樣，釋字745號就這樣。國內知名稅法教授打稅法訴訟一路輸。你搞清楚了嗎？那是法律違憲，所以當然是要一路輸。而且我們還希望輸得快一點，輸得乾脆一點，不爭執，來啦，直接判我輸啦。因為我們要窮盡救濟程序，我們才能提起規範的憲法審查。所以只是這樣。

但各位同學如果要比老師快一點，我也很高興，歡迎各位同學，有這個可能性，要歷史上留名，這個機會留給大家。

這個法制，強制合併本身就違憲，因為他是一個稅捐資訊自主權的干預。

早期74年，更早之前，沒有那個分居解釋函令之前，實務上有更悲慘的案例。因為當你結婚之後，兩個人的稅捐資訊要合在一起對不對？所以你知道嗎？我現在去申報的時候，我可以直接就知道我另外一半的所得，我不用再經過他的同意哦。早期有人就透過這個資訊，來找到自己的另外一半有所得，在哪裡啊，就站到他工作的場所這邊跟他要錢。

那個個案，是一個被打到離開逃家的女生，被她先生就這個酒醉之後家暴，就逃出去，跑出去以後就到臺北橋下去打工。去打工以後，她每一年報稅，最怕的事情就是她先生。因為你不是要合併申報嗎？就會告訴國稅局，哪裡有所得來源啊。那個先生就跑去跟國稅局講，哎唷，這個，我們最近要報稅了，因為我想要誠實履行申報義務吼，我不知道我太太哪裡有所得，我怕漏了。所以他就用納稅義務人的名義去申請，他太太哪裡有所得，賺多少。下班後，他就跑去等太太，跟女生要錢。不給，就打。每一年報稅，等於是把這些你在哪裡工作，你賺多少錢，全部都主動告知給另外一半。所以我現在報稅的時候，我一用自然人憑證插進去，我都可以立刻拉出來，哦，哪裡有所得，一一對帳。而且不用再經過同意哦，就是去年有所得的資料，只要合併申報，用自然人憑證，立刻拉出來全部的資料。


請問這個怎麼沒有個資法違反問題。今年跟去年一定一樣嗎？受扶養親屬推定一樣？

這就是我們現在婚姻合併申報制的現況。

好，釋字696號以後，目前的現況，合併計算這個問題解決掉了一大半。合併申報這個部分還是存在著，分居這個情況才可以。沒有分居的話，基本上沒辦法分開申報。所以稅捐資訊仍然要洩漏給相對人。

合併繳納跟裁罰，這個情況問題依然沒有解決，因為我們的實務基本上都是對納稅義務人去做補繳跟裁罰。

我雖然可以盡力地要求稅捐稽徵機關必須要查明，納稅義務人確實對合併申報的配偶的所得，應該知悉，但往往還是會存在著個案裡面，如果其實沒有其他更多的證據資料知悉的話，我們其實都是不太能確定究竟納稅義務人是否明確知悉這一筆所得。這個，尤其是配偶，如果有不法行為的所得的話，我們不太能夠去確認納稅義務人是否知悉這個狀況。

## 【家庭課稅制】

我們進入家庭課稅制。在家庭課稅制裡面，各位都看得到，我們家庭成員可以有許多。這裡面我必須要先特別強調的，就是未成年子女。未成年子女，在法律上他是受納稅義務人扶養，因此他取得的所得，雖然有取得所得，可是只要他還不足以維繫生存的需求，一般而言，他一定必然會跟納稅義務人去做合併申報。

我們現行的制度，所得稅法第15條第一項的規定，這個部分也是強制合併的。未成年人的所得基本上是強制合併。除此以外的其他成年的直系血親尊親屬，成年的直系血親卑親屬，也就是成年的子女、旁系跟家長家屬，這一些，原則上，你只要成年，都可以選擇分開申報。

我們的法條規定雖然看起來是強制，但是事實上，成年人可以任意選擇分開申報。所以假設各位將來賺到錢，你的爸爸媽媽要不要跟你合併申報，你的爸爸媽媽可以自由決定。因為我們的法律規定，雖然看起來是應合併申報，但實際操作則是成年人可以選擇分開申報。所以你的合併申報這個事情是任意性的，在成年的這個部分。直系，成年了都可以分開來，更不用講旁系或是家長家屬之間的關係，一樣的道理，只要成年就可以分開來。

目前為止，只有未成年的子女被強制合併申報。當然，你如果是孫子女未成年，原則上你的未成年孫子女是歸屬給他的父母親一起合併申報，不一定會跟祖父。原則上是未成年子女會跟他的父母親合併申報。

在這一個強制合併的前提底下，我們現在來看，這個有沒有分開來計算的規定呢？沒有。因為我們的15條的規定，各類所得分開計算，只限於納稅義務人之配偶所取得的所得。因此未成年子女，假如有所得，理論上薪資所得還是可以分開來，但如果不是薪資所得的話，我們的未成年子女所取得的所得，原則上他沒有各類所得分開計算的可能。各位，你去看一下我們的各類所得分開計算，是就納稅義務人本人跟配偶。

所得稅法第15條，第二項第三款第一目，只有本人跟配偶可以各類所得分開計算稅額。所以第一目裡面只有本人跟配偶，然後第二目納稅義務人就前目跟他方受扶養親屬的各類所得，其他全部都是由納稅義務人合併計算稅額好。所以第二目規定，基本上未成年子女的，就回到由納稅義務人合併申報，因為分開來做各類所得計算的是第三款第一目的配偶的其他各類所得，並沒有受扶養親屬的其他各類所得。

薪資所得的部分，原則上是本人、配偶的薪資所得分開計算。也一樣，他就沒有其他的受扶養親屬的薪資所得，未成年子女的也沒有分開計算。


未成年子女的所得原則上就是全部合併計算，由納稅義務人一個人去做負擔。所以未成年子女的所得，全部都進入父或母的納稅義務人申報的所得裡面去。這個只要改變其課稅的級距，增加其累進稅率，就必然造成對家庭的稅捐負擔的加重問題。因為這個是邏輯上的必然。

納稅義務人跟未成年子女的所得，因為未成年子女的所得沒有分開計算的適用，是全部計入納稅義務人的所得裡面去，所以除非是同一個級距不變稅率，只要加進來變更級距，成為上面一個課稅的稅率的話，那這個時候一定會帶來對家庭的加重稅負的效果，因為這個是邏輯上的必然。在這個情況底下，目前696號解釋之後，如果未來還有面臨這個課稅制度要釋憲，或者是規範憲法審查申請的話，未成年子女的所得，加進納稅義務人所得裡面去做合併計算，因為要合併申報、合併計算、合併繳納、裁罰，這一路都是對納稅義務人作為家庭的家長，產生出來的加重稅負的效果。


這不僅影響個人的稅捐負擔的財產權，同時也是對家庭作為制度保障的一種侵害。這種侵害應該有違憲上的疑慮。

這個是我們對婚姻跟家庭制度課稅的制度。大致上，有比較高度違憲可能的是強制合併的部分。未成年子女跟父母之間的所得也是強制合併申報，這個部分涉及到稅捐資訊自主權的干預的問題。未成年子女的所得一定要合併計算，因此會對納稅義務人構成財產權的過度干預的問題。那么，未成年子女的所得併計之後，要求納稅義務人要去做繳納，甚至是做裁罰的部分。未成年子女如果有隱匿課稅所得，當然啦，實務上很難看到個案啊，但不乏這個個案可能。如果將來未成年子女，因為比如說在數位世界裡面有開放，甚至是參加比賽，有獲得很高的所得，這個時候加進父母親的所得裡面去，就會形成對家庭稅捐負擔加重的問題。


透過婚姻跟家庭的分別說明，大致上跟各位提到，在我們實務，這個法規範本身在適用上可能存在的違憲上的疑慮。至於不被強制合併申報的這些受扶養親屬，在實務上則產生另外一種怪異的現象。實際上並沒有受扶養，但是我如果在申報的時候，把其他受扶養親屬申報進來，那就可以實際上降低自己的稅負。在實務上因此產生一種怪異的現象，就是我實際上根本沒有扶養，但報稅的時候把你報為受扶養親屬。這種情形，在我們實務上，尤其是彼此之間不負法律上扶養義務的人，都有可能發生，因為在我們的所得稅法第17條裡面的受扶養親屬的範圍跟民法是不一樣的。

比如說所得稅法第17條的第一項第一款第三目的規定，納稅義務人及其配偶之同胞兄弟姐妹。我舉例而言，納稅義務人對配偶的同胞兄弟姐妹。納稅義務人對自己的兄弟姐妹，跟納稅義務人對配偶的同胞兄弟姐妹。納稅義務人對配偶的同胞兄弟姐妹，其實在法律上並沒有扶養義務。你會扶養你太太或者是你老公的兄弟姐妹嗎？你會扶養嗎？如果有，還真的給你鼓鼓掌。沒有法律扶養義務，可是我們報稅可以結合在一起。

沒有法律扶養義務，卻可以在申報稅捐的時候，可以合併申報成一個家戶。因此在實務上產生許多很怪異的現象。


怪異的現象是這樣，報完稅以後，那一些沒有實際受扶養的人，他可能是會去申請社會救助。然後去申請社會救助的時候，社會局拉出來資料就是，啊，你有受扶養啦，所以我不給你。因為你的有一個申報扶養的親屬，他的申報非常清楚，是適用20%。這個時候依照社會救助法規定，既然有人扶養你，我就不給你。所以他那個時候就趕快去跟國稅局說，撤銷被扶養。

前面我說我被我的同胞兄弟姐妹們扶養，或是我作爲納稅義務人的配偶的兄弟姐妹受扶養，沒有，我實際上根本沒有被他扶養。本來先前同意的哦，同意合併申報，但之後呢，就說我沒有，因為我拿不到社會救助金。所以在實務上就常常會發生這種情況，那請問這種情況底下你怎麼去做查核？過去的一段時間裡面有沒有受扶養的事實，怎麼去查核？基本上也無從查核起，所以通常都是看那個所謂被扶養的受扶養親屬，他自己有沒有來申請撤銷，沒有申請撤銷，那我們就繼續讓他們可以去做受扶養親屬，一直到有一天，終於被撤銷或者是有檢舉。但是這個實際上都甚難查核。實務的操作，基本上一直都是在現實跟法律之間差異很大的狀態底下。

我們今天大致上跟各位介紹我們的婚姻跟家庭的合併申報制度。有強制合併，也有任意合併。成年的受扶養親屬，其實是任意合併。雖然法條規定你再看一次，寫因合併申報，但實際上的操作是任意合併申報。合併計算所得，只有配偶的部分薪資跟其他所得可以分開來。那其他的受扶養親屬原則上是合併計算所得。所以在這一些操縱組合之間，納稅義務人個別都可以去計算對自己最有利的稅負計算方式，來選擇要不要合併申報還是要分開來計算，這個都是變成納稅義務人可以自由選擇的一個範圍，這也是我們實務上的操作。越懂得稅法的人，理論上來講，就會獲得比較高的稅捐上的利益，越不懂的稅法，理論上來講，他就越不會獲得這些稅捐上的利益。但這正是一個作為一個強行法律規範稅法最大的問題所在。

懂得的人可以盡量拿去用，不懂的人卻受到稅捐負擔的不利益。這個是我想在這個地方最後面談到這個問題，給各位做一個說明。

那我們今天先講到這裡。下個禮拜，我們再來講，關於就源扣繳程序。

我們剩下最後兩個禮拜。