# 20231016_01

---
課程：1121所得稅法一
日期：2023/10/16
周次：07
節次：1
---


上周講了應稅所得跟免稅所得的辨別，也就是在稅捐客體的辨認的第二個階段。

我們接下來今天進入第三個階段，也是跟稅捐客體有關。

## 【所得類型】

我們請各位看所得稅法第14條，也就是各類所得的類型的這個部分的說明。

首先從綜合所得稅的意義跟角度來看，照道理來講，作為綜合所得稅，名稱就叫綜合，分類是沒有意義的。因為，既然稱之為叫綜合所得稅，簡單來講就是薪資所得跟營業所得、薪資所得跟財產交易所得，1分錢就是1分錢，1塊錢就是1塊錢，那既然如此，為什麼還是需要分類？所以首先第一個我們必須要談一下，為什麼有14條這個規定的必要性，跟區分的實益。

### 【三點區別實益】

雖然我們的稅法稅目稱之為叫綜合所得，但實際上所謂的綜合所得，他的概念是將各類型所得放在同一個稅基底下，不分彼此你我，也就是如同剛剛所講的薪資所得，跟營業所得，乃至于跟財產交易所得1塊錢就是塊錢，沒有什么差別。但為什麼各國還是會有這一類關於類型的規定，主要是來自於，現實上，我們確實對不同類型的所得做不同的計算的方式，這個地方會導出他的所得的數額，也就是淨額，這個計算最終的標準是不一樣的。

我們舉例而言，薪資所得跟營業所得就有不同的計算所得額的標準方式。

薪資所得在釋字745號之前，原則上他的規定是收入等於所得額，並沒有成本費用可供扣除。相反的，同一個業務的同一個工作的內容執行，假如你是一個營業的狀態，或者是你是一個執行業務者的狀態，你則至少在一定的要件前提底下有一定的成本費用是可以做減除的。從而雖然叫綜合所得稅，但實際上在成本費用的認列上面，也就是最終的淨額所得的計算上面，其實還是有所差異。這個是特別在實體法的部分，因為說是綜合所得，但所得的額度的計算上面來講，會導致他真正在類型上是有所差異的。

正因為所得額的計算有所差別，理論上，綜合所得稅是不分類型，這個分別是沒有意義的，但實際上這個分別在各國的所得稅法裡面仍然會產生，因為他立法上面會產生一些差別。這是第一點我們所提到的。

第一個，理論上，綜合所得稅1塊錢的薪資所得跟財產交易的譬如說虧損，是得併計的。也就是你在不同的類型所得裡面，你在某一類裡面有盈餘有所得，你在另一類有虧損，所謂綜合所得的概念，應該是你可以甲類跟乙類盈虧互抵計算，這才叫綜合所得。但現實上我們并不是如此。我們各類型所得的實務操作，原則上所有的數額都只計算到零為止，沒有虧損的跨類型計算。雖然名稱叫綜合所得稅，但實務的操作上卻是跨類型的盈虧互抵不存在。一個薪資所得者，譬如說他有薪資所得，他有財產交易虧損。我舉例而言，一個公務員也是有薪資所得所得，他買賣黃金虧損，那可不可以把薪資所得跟買賣黃金的財產交易虧損來去做綜合所得稅概念底下的盈虧互抵呢？因為照綜合這個概念，應該是不分類型才對。答案是不可以。我們只容許同一種類型，在法律有明文規定的情況底下去做同一個類型的跨年度盈虧互抵。財產交易是唯一一個可以做同一類型內跨年度盈虧互抵，是唯一被容許的。其他的類型我們不容許跨類型，也不容許跨年度。

我們的實務操作並沒有很明白的依據，他是透過一種類型的解釋體系的解釋法，也就是法律有明定的只有給財產交易虧損做跨年度盈虧互抵，不給非財產交易所得的其他類型有這樣一個跨年度盈虧互抵。因此，他透過這種反面解釋的方式，法律給你這個類型的跨年度盈虧互抵。那至於為什麼跨類型不可以？待會我們來看一下所得稅法的14條文字，從那個地方裡面，實務上認為不給跨類型的盈虧互抵的這種可能性。

因此，這是第二個，為什麼在我們的稅法的規範上面，或是我們在法律適用上面，我們仍然還是必須要去討論關於所得類型這樣子的意義跟區別的實益所在。

這兩個都是實體法，也就是稅捐數額的計算上面是有直接密切的關聯性。剛剛第一個我們講到不同的類型，有不同的成本費用認列的方式、準許的範圍。在釋字745號以前，薪資所得原則上沒有成本費用可以做認列扣除，他是一種用概括形態的成本費用，去做薪資所得的計算，這個是我們到後面會配合主觀淨值原則的時候，會再跟各位去說。到所得稅法第17條的規定的時候，再一併去做更進一步的說明，先請各位記得有這樣一個實體的，也就是稅額計算上的區別實益。第二個是，所得稅裡面，儘管稱之為叫綜合所得稅，但實際上我們實務操作上是不容許跨類型的盈虧互抵的計算，這個也是一個區別實益。當然，更進一步去講的話，就是不同類型的所得會產生不同類型所得該有的成本費用，也就是說，為什麼去區別類型，原則上你的成本費用只能夠是來自於該類型直接產生出來的成本或者費用才準予減除，也就是在客觀淨值原則底下，所謂的所得額來自於收入減成本減費用減虧損後的净額，這個彼此都是聯繫在你所做的那個該項行為，他在事務之本質上必然會產生出來的或依照法律規定必然產生出來的增加或者減少。收入是增加，成本費用虧損是減少。從而在這裡面，特別在學會計學裡面，他們有稱之為叫成本費用去對應收入的對應原則，成本費用去配合收入的這個對應原則，在我們稅法上面把他稱之為叫關聯性，就跟你的活動有關，或者是因為那個地方翻譯不太一樣啊。他的德文叫Veranlassungsprinzip，因為那個活動的起因，因為那個活動跟那個活動有關的可以認列，跟活動無關的，不能夠認列該相關的成本費用。會計上是直接把那個數額裡面的成本費用去對應收入，這個從法律的觀點來講不太對。因為我們不是收成本費用去對收入，我們是對活動。會計學上面，在算他的會計淨值的時候，是成本費用去對應收入原則。法律上的概念是不是對應收入，萬一你的活動沒有收入，那怎么對？萬一沒有收入，我做這件事情完全沒賺到錢，但我有投入成本費用。只要是應稅的營業執業活動，對應的是活動，而不是對應收入。這個是我們跟財會之間的差別，我們講的對應是在對應那個活動，只要他是應稅活動，即使他沒有正的收入，產生成本費用，客觀淨值原則的計算底下他會有虧損，他仍然還是可以被認定為應稅的所得計算裡面的項目，因為，我因為該項營業活動或是執業活動，我沒有產生任何收入，但我有成本費用支出，從而成本費用減掉收入，我有一個虧損，那這個虧損等於是我營業或執業活動產生出來虧損，儘管這個概念似乎有這樣一個差別，但大多數非學會計或非學稅法的人不太能夠去理解這中間的差異。

稅法上，我們不是對應那個收入，是對應活動。翻譯上面來講，我目前為止，我自己也沒有找到一個比較比較合適的方案，因為他的德文Veranlassung，是一種跟某一個東西有關聯性，起因於這個活動而產生出來的收入或成本費用。那會計上因為是直接成本費用去對應收入，他就忽略了跳過去對應那個活動的那個概念。德文裡面是直接對應那個活動。那也因此，我最早自己是把他翻成關聯性，是因為我們的所得稅法24條，就是因為跟營業活動有關之一切成本費用，所以把他用這樣子一個方式去做說明。總而言之一句話，在這裡面，你的相關的收入跟成本費用，因為在各類型所得裡面他有對應的活動，而因此產生出實體法上的差異，也就是稅額計算稅負上的差異。


最後一個區別實益在稽徵程序上面，也就是說，各種不同類型所得，他會因為類型的不同，而可能會有不同的所謂的稅捐徵收的程序。一般而言，薪資所得者會有就源扣繳程序。但你如果是自營活動的營利事業或執行業務者，由於所得稅的收取，本身是不一定有就源扣繳。因為我如果做一個律師，我去執業，客戶並沒有必要要就源扣繳，所以是我透過結算申報程序。我如果是一個獨立開店的業者，我也沒有從顧客那個地方有就源扣繳程序，特別是對方，如果他也是一個境內的居住者，那這個時候他沒有就源扣繳義務啊，除非他是一個國外的納稅義務人，他是一個非境內居住者。不然的話對方也是境內居住者，我賣東西給對方，對方並不需要去做就源扣繳程序。我有所得，是透過所得稅的結算申報程序。


從而我們從實體法到程序法，因為有這些區別實益的存在，因此我們仍然還是必須要去談所得稅法第14條的各類型所得。簡單而言，就是綜合所得稅並非如其所名的所謂的綜合在同一個稅基底下去適用同一組的稅率。我們的綜合所得稅並不是如此的完整，其實還是有各類所得的區別實益，不管是成本費用的計算，不管是成本費用的歸屬認列的方式，也就是剛剛所講的關聯性原則，或者是在成本費用我們特別是在跨類型的盈虧互抵的計算上面來，至於稅捐的稽徵程序上面來講，我們的所得稅的類型分類是必要的。




基於這樣子的一個說明，我們展開今天所得稅法第14條的規定。所得稅法的第14條從歷史的演進而言，他是逐漸慢慢變化而來的。各位可以翻開來我們第14條的規定。我們的14條的規定，本身是一個在歷史演進的下的產物，也就是說，他本身體系不太清楚。

## 【第一類 營利所得】

所得稅法的第14條的第一類裡面，理論上，總共包含三種不同類型的所得。我們來看一下所得稅法第14條的第一類被稱之為叫營利所得的類型，實際上他包含了三種不同類型的所得。

第一種類型的所得，我們可以把他稱之為叫做獨資商號跟合夥事業經營成果的營業所得。14條，第一項第一類裡面，他稱之為叫營利所得。我先把其中一個類型叫獨資跟合夥經營成果的盈餘，這個部分我把他單獨拉出來，稱之為叫。
因為這一類型的所得，除了資本投入以外，一般而言還需要勞動力的投入。這個稱之為獨資合夥經營事業的營業所得。

第二種類型是純資本投入，也就是透過股本投入公司合作社或者是其他法人類型，比如說有限合夥啊，你透過股本的投入，因此而產生出來的不管你是公司合作社或者是其他法人類型，我們把他稱之為叫股利盈餘。他是一種資本投入所產生出來的孳息。

第三種，我們把他稱之為叫一時貿易盈餘，著重在他的一時性。上面的這兩個類型，在某程度上面，有繼續經營的概念，也就是他有一段時間的持有，因此才能產生包括孳息在內的股利盈餘，包括你的經營成果的營業所得。一時性，在這裡面，對應繼續性，沒有說出來的文字是，繼續性。上面這兩類，有一個繼續性這當中。這個不是我隨便亂說，因為待會我會跟各位重組排列我們的類型所得的概念。

這就是我們的稅法。根據立法者排列出來的體系，我們把他稱之為叫外在體系，是立法者自己的排列順序。但實際上雞跟兔放在同一個營利所得這個類型底下，是雞兔同籠，把不同類型放在同一個類型底下去做稱呼。我們透過類型，是一種價值判斷，也就是一個有意義的分類標準，去做分類，這個被稱之為叫內在體系的分類的標準。內在體系的分類標準可以讓我們有辦法去，對於同類做平等原則的適用。特別是在立法政策上，特別是在法律解釋適用上面，所謂的等者等之，你必須要同類才能等，雞跟兔沒有辦法比，雞跟兔是不能比的。同類這一件事情來講，必須要在本質上相同，像我們剛剛這個地方，我們的立法者的外在體系分類就是一類型分三類，但實際上在這裡面，他裡面有繼續性性質的勞動力加資本投入，其實他是勞動力為主，資本為輔的一種經營成果。也就是獨資跟合夥，不會只有資本投入，他主要是來自於他的勞動力投入，只是他是一個獨立性的繼續性的付出，而因此產生經濟上的成果。所以德國人的法律定義他就很清楚的告訴你，什麼叫營業所得？獨立繼續性地投入市場經濟活動。人家的法律規定就很清楚的告訴你說在這個類型裡面，該有的價值標準。法學後進跟前進的差別就在掌握分寸標準上的精準性。這就是我們跟他們的差別。不是我們不好，是因為我們這個部分，確實立法者反映出他的所處的社會的研究水準。簡單來講，就是學者分不清，立法者當然也分不清。反過頭來，立法者分不清楚的情況底下，法律適用的操作上面也就很容易類型混肴，放在一起。

比較法的作用就是我們看別人怎麼分類，哦，原來他這樣分類，他這個分類有沒有意義跟道理？我們學到這個分類標準，然後運用在我們自己本身的分類的適用上面，這就是社會科學。社會科學是透過一套可檢驗的標準來適用在自己本土的社會，而不是全然照抄。社會科學，是觀察自己所處社會的問題，運用一套可檢驗可被重複檢驗的方法，適用在你自己所處的社會裡面，這個才叫社會科學。

這也因此透過這3個，我們首先先跟各位去做分類，因為待會我要做重組排列。我們先把這個不同類型做區分。第一類的所得叫營利所得，其實包含了繼續性跟一時性的兩種經營的成果的所得，都放在這裡面。繼續性的這一類型裡面，區分純資本投入的跟所謂的資本加勞動力，特別著重在勞動力投入的這一種營業所得。這裡面總共三種不同類型的所得，這個區別是有實益的。你如果今天有勞動力投入的話，一般而言會有成本的費用的問題。可是如果你沒有勞動力投入，你就只有投入的資本裡面會產生成本，而一般而言不太會有費用。當然，交易本身會產生費用。

一時貿易盈餘，是著重在一時性，因此在實務上面來講，不以之為常業的這一類的，經營成果才會成為叫一時貿易盈餘的態樣。舉例而言，像老師也有一個一時貿易盈餘。雖然我的主業是教授，但我副業可能做別的工作的時候，這個時候我就可能會有一個一時貿易盈餘，待會跟各位作說明。

## 【第二類 薪資所得】

接下來第二類叫薪資所得。薪資所得的類型特徵在他是一個純粹勞動力付出，而且是一個非獨立性的勞動力。相對的，營業所得，也是一種勞動力付出，但是他是一種獨立性的勞動力付出。簡單來講，薪資所得的勞動力的付出，是有一個雇主的，因此薪資所得的類型特徵，在於透過勞務的付出，而該項勞務本身非具有獨立性——他是非獨立性的勞動力付出而取得的經濟上的成果。

這裡面的公教軍警公私事業職工，這個只是在跟你講，不管是公或私領域，只要透過勞動力付出而產生出來的勞務，提供產生出來的對價，因此就產生薪資所得，在這裡面不分你是在公共行政領域裡面或是私領域裡面的。包括公務員的薪水，雖然公務員是參政的一種形式。公務員的參與國家的政務，本身是一個參政權，不一定被理解為是一個工作權。當然這個跟各位在這個學憲法的時候，到底，成為公務員，是工作權保障的範圍，或是參政權的保障範圍，也許會有一些不同的歧義的看法，但這裡面不管是公或私，原則上是你透過勞動力付出，因此產生出來的取得的對價，就屬於薪資所得。

老師是在公立大學裡面授課，那我主要是透過勞務的付出，因此取得報酬對價。為什麼這是一個非具有獨立性的勞動力？因為我的勞務付出是國立臺灣大學底下的，只是我在禮拜一的下午1點20分的時候，來到1302的教室上課。所以，我的勞務付出是非獨立性勞務。如果我自己開班授課，各位來上課，這個叫獨立性勞務。這個時候我就是一個獨資商號，或者是合夥事業。

所以，陳清秀老師去東吳大學上課的收入，爲什麽不是一個獨立執業的律師的執行業務所得。為什麼？因為他是受東吳大學的指示監督，只是而在固定的時間地點付出勞務去取得對價。主治大夫也是如此，你的所謂的勞務付出是在醫院的指示底下而做出來的勞務付出。雖然在你付出的內容上面具有高度專業取向。例如說我上課的稅法的內容，國立臺灣大學，不會具體地指示我要上什麼，所以我其實可以唸法條就好，我唸完法條，大家混完兩個小時時間就可以回去了。你頂多就是評價我，老師教得很爛。但我已經是教授了啊，不然你是要怎樣？就算評分很爛，我也是這樣，我照領薪水。

這叫非獨立性的勞務的付出形態。勞務的付出，本身是受僱主的指示，雖然在勞務的付出內容上啊，具有高度的專業性，這個時候並不改變他在勞務付出上，原則上是透過雇主的指示而提供勞務，也因此他的報酬本身不直接來自勞務提供的相對人之間。例如各位就是顧客，國立臺灣大學就是雇主，提供勞務服務，只是柯格鐘到這個時間地點來對各位來付出這個非獨立性勞務。

假如我今天是開補習班，各位因為慕名而來，我收錢，那這個時候我就變成是一個前面講到的營業所得者。

我們跟各位去談到不同類型的所得，這個區辨是非常重要，就如同剛剛回到我們今天講課的主題，為什麼分類重要啊？因為這個區辨決定了你的所得成本費用的計算，乃至於稽徵程序，也會有所差別。


第三類薪資所得，這裡面，公教軍警公私事業職工的薪資跟提供勞務的所得，換言之，他這裡面一個重要的類型特徵有寫出來，叫做勞務，但沒有把另外一個重要的類型特徵叫非獨立性寫出來。公私事業職工，他意味著不管是公或者是私——在高權行政領域或者是非高權領域裡面的私法領域，只要有勞務的提供，但非基於獨立性的提供勞務的話，這裡面就會被認為是薪資所得的類型。這個是在這裡面我們立法者的外在體系，沒有表現出他背後該有的基本價值，因為你沒有去表現出那個獨立性，你就不容易去區辨營業所得，跟後面我們會講到執行業務所得，乃至于所謂的薪資所得，這三種不同的勞務所得的類型。他們有一個共同特徵，都是勞務付出，但獨立跟不獨立，結論差很多。


接下來我們跟各位提到薪資所謂的勞務付出，有沒有說是限於合法？答案是，沒說。沒說，代表在這裡面啊，你只要是勞務的提供而取得的對價，原則上就是薪資所得。在德國，是利用職務之機會而取得的這類型所得範圍。在臺灣的實務上，所謂的提供勞務，只限於來自於雇主提供的所得。所以，如果你是利用職務之機會而取得的業務回扣，或者是貪污收賄，不是來自於雇主，而是來自於第三人，不是來自於合法，而是來自於非法利用職務之機會而取得的所得，在我們的實務上不列入薪資所得，而是放到第十類，其他所得。

我們再講一次。我們的法律上的規定其實並沒有講合法非法，也沒有說是從雇主。理論上來講，不論合法非法，不論是不是從雇主或雇主以外之第三人取得。理論上如此，因為你只要是非基於獨立性勞務之付出，或利用其機會而取得，理論上應該都是在計算上面來講，列入薪資所得。因為他的條文規定只有講：凡公、教、軍、警、公私事業職工薪資及提供勞務者之所得。

所以，非法打工的人，他非法打工，他受僱主指示，在後面洗碗，就被查到，他是一個逃逸的外籍移工。那這一種情況底下，他一樣，有勞務付出，他的所得理論上還是來自於薪資非努力勞務的所得，但在臺灣把他因此變成是其他類型所得，也就是第十類，而不是第三類。我們的所得稅的認定對薪資所得是僅限合法，僅限雇主給付，第三人給付不算。所以例如服務費收入，像餐飲業的服務生。在外國很多餐飲業的服務生都會獲得額外的小費，小費是誰給？客人給的。特別在美國消費，往往小費是這一些服務生的主要收入來源，因為他們的起薪是比較低的，所以他們這個國家的文化，是透過他提供很棒的服務來獲得顧客的小費，不是固定的。所以如果你服務很好，你可以給到25%，這個是美國的標準。當然到後來慢慢變質，好像不給的話，就好像會覺得有一點不太習慣。比如說，明明這上面定價是100塊，付出去的時候要付125塊，那為什麼你支付我110塊？我服務很差嗎，為什麼你不給我25%？可能服務生會這樣問。德國的習慣是，給到整數。比如說27塊，那你就可以給到28，29，30塊，當然你的整數如果是40塊，服務生也當然很樂意。小費計算的方式跟標準，每個地方的文化不太一樣。要注意在臺灣並沒有這個文化。臺灣的服務費收入都是由雇主收走啊，所以他本質上並不直接成為受僱的這些員工的所謂的其他所得，還是會從雇主那邊進去，所以原則上還是屬於雇主給付的薪資所得。


我們在實務上面，第三人給付的所得，通常是代替原先的這個雇主給付。我舉例而言，在德國勞工做團結抗爭的時候，也就是工會出來去做罷工的時候，工會會發給代金。也就是你這一段時間裡面，假如雇主沒有依照約定繼續給付薪水的話，那麼他們的團結權裡面就包括了由工會給付這段時間裡面的代金。也就是，做抗議，假設你沒有拿到你該有的薪水的時候，你先前繳的這些工會的保險費就會支付你的這個代金。抗議用的這個代金，本質上是所謂的薪資的替代，從而他是薪資所得的類型。在德國，抗議代金理論上就一樣要計入薪資所得的類型，美國文化可能會有不太一樣的這個方式。但理論上基本的概念是，不論合法非法，不論來自於雇主或第三人，只要是因勞務付出而取得有關聯的所得，這個就是薪資所得的類型。


## 【第二類 執行業務所得】

我們回過頭來再來講第二類。第二類執行業務所得：凡執行業務者執行業務者的所得，這個就是執行業務所得。至於何謂執行業務者，則請各位去看所得稅法第11條第一項的規定。我們的所得稅法第14條的第一項第二類執行業務所得關於執行業務者的定義規定，在所得稅法第11條的第一項。

所得稅法的第11條第一項，本法稱執行業務者，係指律師、會計師、建築師、技師、醫師、藥師、助產士、著作人、經紀人、代書人、工匠、表演人及其他以技藝自力營生者。

我們的外在體系，也就是立法上的技術，是透過例示的方式列舉幾個執行業務者的類別，再加一個概括性描述的條文規定，也就是以技藝自力營生。從這個「自力」，你就可以看出來，這邊的勞務付出是一種獨立營業的態樣。自力營生者的所得，我們稱之為叫執行業務所得，我把他就直接寫執業所得。簡化一點，所謂的執行業務者，簡稱執業。

原則上以這所謂的四大師——律師、會計師、醫師、建築師啊，跟「師」有關的，被認為是一個執行業務者。

我們透過這些例示的規定，大致上理解立法者想認為心中所想的執行業務者有哪些，但他為了怕將來還是會產生疑義，怕未能窮盡類型，從而立法者在後面補上一句描述執行業務者的類型特徵。因此，執行業務者這個概念，他是一個類型概念，就像各位在學民法的時候的買賣、租賃、承攬、僱傭契約……他是在描繪客觀的社會現象，但有時候這種描繪在立法技術上無法窮盡其類型，從而立法者把幾個他認為比較典型類型先告訴你，然後為了怕這幾種類型以外，可能還會有其他類型的時候，那這個時候他透過這個類型的描述特徵，他說他們是用以「技藝」「自力」「營生」，去參與經濟活動，透過這3個類型特徵的描述，去進一步描繪所謂的執行業務者。

這個是我們在方法論上被稱之為叫概念底下的一種主要的類型叫類型概念。他的相對分類是這樣，就是法律概念不確定。法律概念是，例如常規交易，例如一般租金水準，這個本身就不特定內涵。

但屬於比較特定內涵裡面確定的法律概念裡面，我們有一個類型，叫典型的分類概念。典型分類概念就是法律，透過他的定義，以數字和公式的方式截然劃分區別的標準。譬如成年跟未成年、自然人跟非自然人。這個就叫典型概念，或者稱之為叫純正概念、分類概念，因為他可以透過數字和公式去做典型截然劃分。

譬如說，18歲成年。就算你聰明才智跟愛因斯坦一樣，你只要16歲，你仍然是未成年。在法律上面你18歲滿的那一天開始，你就成年了，你可以獨立的為自己去做契約上的締結行為。在此之前，你就是未成年人。當然還有什麼未成年人或者是限制行為能力人，他這個都是用透過一個數字的方式，可以去做一個截然劃分。這個稱之為叫典型概念。

大多數的法律概念不是這種典型概念，也不是不確定法律概念，而是類型概念。也就是透過類型的特徵描述去做一個法律涵攝內容的全面包攝，但這種包攝由於他本質上需要透過解釋，所以他的邊界類型是浮動的，是不清楚的。各位可以明白這3個之間的差別嗎？

不確定法律概念與確定法律概念。確定法律概念裡面，又再分成典型概念跟類型概念。

類型概念裡面，就是用類型特徵去描述類型特徵裡面的核心概念。

以執行業務者而言，就是以技藝自力營生。參與市場經濟活動，這個就是營生的概念。這個是他的核心概念的描述啊。透過例示類型的標示，讓法律適用者在適用上可以去特定他適用的範圍，所以他是一個確定法律概念的適用範圍，但即使是確定法律概念，他仍然也有一定程度上的不確定性。他沒有辦法像典型分類概念一樣，是可以階段劃分的。各位要瞭解這個差別，因為關於法律概念的分類，這個就是方法論的入門。

在這個情況底下，執行業務者是一種類型概念，透過四大師的描述，大致上讓你清楚知道何謂執行業務者。但這個描述往往雖然描述出來，仍然無法窮盡其類型，因為何謂「以技藝」「自力」「營生」，這幾個特徵仍然在實務上面難以絕對區分。技藝，什麼是技藝？比如說，醫師、藥師、助產士……復健師呢？復健師算不算執行業務？復健師如果是執行業務者，那幫忙喬骨頭的喬骨師呢？你可以取出各種很接近的類型，在這個地方我們仍然要去判斷他算不算以技藝自力營生？

這正是類型概念的不確定性，雖然說是確定法律概念，但其實包含不確定性。這正是所有的法律都需要解釋的原因。因為法律不在於背法條，而在透過這些類型概念，一方面去評價外在體系的判斷標準，有沒有把該有的特徵把他標志出來，另外一方面就是在這一些該有的特徵底下，我們去對個案個別裡面的涉及到的業務，我們去做判斷是不是所謂的執行業務者。

執行業務者的類型特徵是這樣，也就是這四大師的類型，其實他們有一個共同特徵是經由大學體系的教育底下所養成，再加上國家考試。這是「師」的內容。不管是對會計師、建築師……一般而言，在傳統的西方社會裡面都是透過學院式的教育，然後經過一定程度上的國家考試。換言之，一個執行業務者，他的執業內容是經過一定的養成以及國家考試而產生出來的業務內容。

非透過這個學院養成加國家考試，如果不需要這個內容，就可以自己出來付出勞務的，原則上就變成是營業所得。

我再講一次，執行業務所得是業務裡面的一種類型，這種類型是經由學院之養成加國家考試，這一種類型特徵把他獨立出來，就被稱之為叫執業所得。你先客觀辨識這事實，接下來再來談適當不適當的問題，因為我說到這裡，你很快就會發現，所謂的學院養成跟國家考試都是一個在遠古時代在前現代的時候，就延續而來的某種執業養成的路徑。

麵包師傅，就算沒有學業養成，他好歹也要經過國家考試，雖然看起來好像沒有上個禮拜剛舉行那樣子的全國大家結合在一起的律師考試。美容師傅、麵包師傅，大家也都是「師」，國家考試及格。你是國家考試，我也是國家考試，我只是沒有上你們的那個臺大法律系去上課的養成而已。沒有不同，沒有職業歧視。換言之，執業所得，某種程度上面來自於傳統跟文化裡面所承認的一種，要經過特殊的養成跟國家考試的及格的程序而產生出來的一種業務類別。執業所得只是一種特殊的業務型態，這種業務型態當然在某些國家裡面，特意給他一個比較特殊的定位。譬如說傳統上德國律師跟臺灣一樣不能廣告，無限責任——也就是執業上的疏失，是無限責任。他不能跟賣商品一樣誇贊他的功效。像我們律師，誇讚功效就是，委任我，一定贏。訴訟沒有穩贏的。醫療，沒有穩贏的，沒有一定會治好。醫生説，相信我，我幫你開刀一定沒問題，人就算死了也可以活回來。不存在這種可能性。而且律師負擔的是無限責任。這個被認為是一種特殊的信賴關係，也就是對他所提供的勞務的內容具有特殊勞務的信賴關係。

由於律師跟受委託人之間的這樣一個忠實保護的義務，要知悉的業務秘密，他必須要去忠實地去以他的利益來去做最佳的考量。

那麼同樣的，會計師跟建築師都同樣的有這樣一個類型特徵，被稱之為執行業務者。但論其實際，他是一種特種勞務型態。只是被國家考試跟特殊的教育養成被培養出來。

但實務的操作上，其實就算你沒有拿到國家考試及格，你出去執業，密醫算不算醫生？答案是，密醫也是醫生，只是他沒拿到國家考試及格的資格。所以如同我剛剛前面在講薪資所得一樣，非法執業，他只要是一個獨立性勞務，在概念上仍然是一個執業所得，跟他有沒有取得國家考試及格的證書是沒有必然的關連性。密醫理論上還是醫生執行業務所得，只是他沒拿到國家考試及格證書。那就更不用講，沒有經過學院養成，連我們律師考試都不一定要經過學院養成，你可以用同等學歷去報考，你只要拿到必要學分。

所以其實執行業務所得是一種特殊執業類別，我們把他從某些執業類別獨立出來而已。這是第一種執業所得。


第二種執業所得，透過人的智慧發揮而產生出來的這一些創作性活動，像作曲家、音樂家、表演家、舞蹈家，這些都是透過他的人類的智慧財產的創作活動所產生出來，這一類也稱之為叫執行業務者，這是第二類。我們沒有很清楚地去表示出來這一個類型特徵，這裡面只有一個很概括的叫表演人。表演人，包括作曲家、音樂家、作家、專欄記者——非受僱於報社，他不是直接受僱，他可能是一個很有名的專欄作家，像德國很多專欄作家，不一定受僱於圖報，或者是鏡報，結果他寫出來，大家搶著要。這一類的所謂的獨立專欄作家，這個就是所謂的以他的智慧財產而產生出來，獨立付出勞務因此而取得的所得。他是一種特殊勞務的類型。

第三種就是特殊技藝，這裡面就包含了工匠跟經紀人。這種獨立勞而這種勞務的態樣是跟，營業所得是不太容易去劃分的。像是，修鞋的師傅，算工匠，還是算獨資商號？商港裡面有一個引水人在幫忙，在外國輪船，要進港出港的時候，將船舶引出引進。引水人是算哪一種？因此，獨立的技術到底是哪一種？在這裡面，類型概念特徵存在著不確定性。

但歸類為營業所得，跟歸類為執行業務所得，原則上所謂的執行業務所得，就是以「四大師」為首的一個特定的養成國家考試為他的要件，但又被放寬認定到，以智慧財產的表演創作為主的，像舞蹈家、作曲家、音樂家、歌唱家，增加了這個剛剛所提到的這一些第二類的執行業務者，第三類的是以技藝自力營生，以經紀人跟工匠為代表，但這個工匠本身就是一個跟其他營業的類型難以區辨的。

我們待會會去講營利事業。你去看營利事業，就是提供工商農林漁牧礦冶，這裡面特別是商的裡面，商業包括貨物跟勞務的提供，那這裡面的勞務提供究竟跟執行業務者有什麼差別？歡迎各位去做個案個別的判斷，因為這裡面仍然存在非常高的不確定性。我們只能簡單來講，牙醫師幫你植牙，這個是他的執行業務，但同時間賣牙膏牙刷，別人都可以做，那這個時候的所得就會是營利所得。這樣各位該聽得懂嗎？同一個執業，我作為律師，我可以上法庭，這個叫執行業務所得，但我如果做諮詢顧問，做一個package的打包或銷售服務的話，那這個就可能是營業。這樣各位清楚嗎？分類很重要，因為涉及所得成本費用乃至於稽徵程序。這個是環環相扣的問題。


我們先休息一下。