# 20231002_02

---
課程：1121所得稅法一
日期：2023/10/02
周次：5
節次：2
---

跟各位提到關於保險之後，我們繼續進一步跟各位說一下，關於信託財產的移動，是不是課稅所得。

## 【信託財產的移動】

所得稅法3-3條的規定，特別就關於信託財產的設定，還有存續關係存續中裡面的這個受託人的變更，以及信託關係消滅後，委託人跟受託人之間的財產的取回。

請各位看到所得稅法3-3條，因為信託行為設立成立委託人跟受託人之間……我自己認為，這個法條規定這樣不是很清楚，他應該要很清楚地規範，因信託行為成立委託人，將財產移交給受託人，這個對受託人而言，不是他的所得。

3-3條，第一項第二款規定，信託關係存續中受託人變更，從原先原受託人變更成新受託人，你從A公司變成B公司作為受託人，信託關係不變，在這裡面，財產上的移動從原受託人移動給新受託人，這個不是市場經濟活動，這個是在設定信託關係裡面的受託人關係，從而對新受託人而言，不是他的所得。

第三款規定，「信託關係存續中，受託人依信託本旨交付信託財產，受託人與受益人間」。
這個地方在講什麼啊？！你如果在信託關係存續中受託人跟受益人之間有財產上的移動，這個正是所得稅法要掌握的所得範圍，不是設定信託的行為。你現在受託人拿著管理信託財產的利益，如果要交給受益人的話，這個正是整個信託法制要掌握的所得的範圍。

第四款的規定，又回來了，因信託關係消滅，委託人跟受託人之間，或受託人與受益人之間。這個後半段是沒道理的，但前半段是有道理的信託關係消滅的時候，受託人要把他名下的信託財產移轉回來給受委託人，這個是信託關係消滅時的一個標準做法，因為這個本來就不是受託人的，本來就是委託人的，那信託關係消滅的時候，你要回來給委託人，這個是本來信託關係消滅時該要做的事情。所以只有這個部分有道理。但對受益人之間，也就是受託人與受益人之間，這個地方，他想要去規範什麼情況？委託人當初在信託本旨裡面有講說，當信託關係消滅時，請把信託財產交給受益人。也就是受託人受到信託本旨的拘束，在信託關係消滅的時候，受託人要把這個信託財產交給受益人。他是本來是委託人的東西，信託關係存續中變成是受託人名下的財產，信託關係存續結束以後，本來應該要回去，結果現在依照信託之本旨，也就是當初設定信託的時候，委託人告訴受託人說，如果接下來信託關係存續結束的時候，請你受託人，就直接把東西給受益人。請問這個叫什麼？這叫委託人對受益人的贈與呀！有問題嗎？

還回去是本來的道理，你現在透過信託關係，就直接送給受益人，法律是這樣規定的。胡搞瞎搞，莫此為甚，胡說八道。

信託關係的設定存續跟消滅他有一個邏輯軌跡，就是為了要設定信託，委託人把名下財產從自己身上移動到受託人，好，這個對受託人而言，不是他的所得，這應該沒問題。待會再跟各位講另外一面的思考哦，不是理所當然都是如此哦。

好，信託關係設定的時候，從委託人到受託人。變更受託人的時候，從舊受託人到新受託人，這個當然都不是取得者的所得。

信託關係消滅的時候，你本來就應該要回過頭去，如果委託人已經死亡，那就會變成是他的遺產啊，你怎麼可以直接就透過信託本旨就直接從受託人就移動到受益人那個地方？如果直接就移動過去，那也要被認為是委託人對於受益人的一種財產上的贈與，或者是遺產的給予嘛。這才符合一個法律正常邏輯底下該有的法律規定，就這麼簡單一件事情。所以信託是一個好的財產規劃工具，尤其是對有錢人。

法律胡亂規定的時候，你就會看得出來，立法者究竟想要什麼樣的一個價值。最後面，第五款，「信託行為不成立無效或解除或撤銷的時候，委託人跟受託人之間」，那當然啦，因為你的信託關係，因為不成立無效解除或贈與或撤銷，要回復原狀啊，所以你本來從委託人到受託人，要回復原狀，從受託人又回到委託人身上。這之間的財產上的移動，原則上都不是取得者的所得，這個當然沒問題，因為是在回復原狀。

好，我們信託財產上的移動，根據3-3條，摒除掉少數，我個人認為很奇怪、立法價值不明的稅捐優惠規定以外，3-3條，基本上在體現一件事情，就是信託財產的移動，原則上不計入所得課稅的範圍，也就是非經濟成果。那個是純粹為了形成一個法律關係產生出來的財產上移動。

但，這個信託關係其實也很容易被利用作為一種實際上是作為財產上的移動，讓受託人實際上取得管理信託財產的所有權，讓他實質上享受該項利益的一種工具跟手段。信託也可以被利用作為實際上是一種贈與，不管是對受託人，或者是受益人。也就是信託行為，在這一個信託關係存續當中，不在委託人名下，變成是移動到受託人名下，受託人再經由信託本旨，再將管理信託之利益交付給受益人，請問這一個法秩序裡面難道不應該評價為，實際上是委託人透過信託的方式去對受託人或者是受益人，所為的贈與行為嗎？也就是看起來是信託，當然實際上就是以信託之名，讓他可以實際上管理財產，並且交付管理財產所獲得的利益給受益人的一種型態。

簡單而言，對於信託在法秩序底下的正確評價，我固然認為信託設定財產，這一種財產上的移動不是所得，但理論上他可以被評價為是一個將管理財產所獲得的利益做贈與的行為，也就是會落入贈與稅課稅的範圍，而不是所得稅課稅的範圍。也就是說在這個地方，適當的應對的法制是遺產稅跟贈與稅。所以我們把信託財產的課稅法制，我們到遺產贈與稅裡面再一併去討論。

信託關係存續當中，受託人管理信託財產一定會產生信託財產的利益，也就是所得，這個所得究竟要怎麼個計算？這個固然是所得稅法本來應該要關注的，但為了讓信託設定行為跟信託關係存續當中的這種管理信託財產所產生出來的增益一併去做規範，我們會到所得稅法三的遺產贈與稅法再來去談，關於信託行為的課稅。因為實際上信託行為正是拿來作為遺產跟贈與規劃的最佳的財富傳承的工具。

根據3-3條的規定，信託財產的移動，對取得者不是所得，他的背後原理在，他是一個設定法律關係的行為。因此，這個財產上移動，不是市場經濟活動。


## 【股款之投入跟取回】

最後就是投資的股款的投入跟股款的取回。股款投入跟股款取回，本質上是一個財產上的移動，沒有錯，但他沒有增益他人財產的意思，也就是他投資某一家公司或投資某一個自然人股東，都是一個投資上的行為，因此投資上的財產上移動，對於取得者而言，他是一個股本的取得，或者是股本的退回，都不是經濟活動的成果，因此投資海外而又再從海外匯回來，這個不是所得稅的所得，而是一個投資股款的取回。因此在境外資金匯回管理運用及課稅條例的規定裡面，這種匯到海外的錢轉了一圈又回來的情況，只要取得相關的證據資料，足以證明是當初匯出去的股本，那麼原則上就不是所得，就不應該課所得稅。可是如果你匯出去100萬，現在存在海外的有1000萬要匯回來，這一種超出原先股本的，就會被認為是屬於你納稅人所取得的境外來源的所得，因為這個境外來源所得，不是課綜所稅的所得，是課所得基本稅額條例的所得，有一個課稅門檻的100萬的規定，有一個670萬的免稅額的規定。這一些都是所得基本稅額條例裡面的規範，我們到所得稅法四的時候，再來跟各位做進一步的說明。因此在這裡面，關於所得跟非所得的概念，就請各位注意到，損害賠償、損失補償、保險金給付、信託財產的移動跟投資股款的投入跟取回，這幾個相關的議題。這個議題的重心，主要是在於有沒有法律明文規定，原則上不影響他應否課稅的本質。

如果他本質上是一個所得，但在法律沒有明文規定底下，是一個經濟成果或經濟成果替代的話，那我們會就進入到第二個層次的問題，也就是應稅跟免稅所得的議題，這就是我們今天要跟各位繼續去談屬於所得的範圍。

## 【應稅所得或免稅所得】

那么進入第二個階段，我們就要判斷他是應稅所得或免稅所得。應稅跟免稅的差異在於，他同樣是經濟成果或經濟成果的替代，免稅所得是基於立法，在不同的正當化理由底下，從而給予不同的對待，也就是免稅所得背後有一些正當化的理由，透過這些正當化的理由，沒有法律的明文規定，免稅所得不得給予法外的施恩、給予法外的稅捐優惠。也就是說，在這個地方，所有的所得原則上是應課所得稅的所得，那麼你要免稅所得，必須要有法律位階的反面構成要件的規定。所以，沒有法律明文規定，原則上是不成其為免稅所得的一個稅捐優惠的地位。這是第一個。我們在談完所得跟非所得概念之後，進入到所得這個概念第二個層次的問題，我們要探討應稅跟免稅所得的概念。在現行立法底下，會基於以下幾點理由對於所得稅的所得，給予免稅的優惠。


### 【實用性原則】

第一種，我們把他稱之為叫實用性原則，也就是說，這一類的所得，他的數額由於他數額微小，他是一個小額福利，那麼因為依從成本跟稽徵成本過高，換言之，微利，那我就算了，就不給予算入。這一種稱之為叫小額福利性所得。這一種小額福利表彰在我們所得稅法第4條第一項第五款：「公、教、軍、警人員及勞工所領政府發給之特支費、實物配給或其代金及房租津貼。公營機構服務人員所領單一薪俸中，包括相當於實物配給及房租津貼部分。」

譬如說，在公務員的薪水裡面，公務員有領受租金上的補貼。租金補貼其實理論上是因為來自於勞務的付出所給予的，雇主基於勞務上受僱人的雇主的這個付出，所以給予一個在外做租金補貼的經濟的成果。那麼由於這一類的成果本質上在當年最初最早的時候被認為是一個小額福利，也就是住宿上是一個小額福利，從而他是基於實用性原則，因為太小了，所以我們在課稅的時候就不算。這裡面包括了像交通津貼、住宿津貼還有你因為就職的緣故所產生出來的一些附帶的利益，比如給予一些夜點的給付。這個在實務上往往被以他是一個微小的福利。在英文裡面他叫做Fringe benefit，微小的福利，小額福利，就算了，因為要去做收入的核實計算有困難。
再例如，就職場所裡面所給予的住宿補貼。我舉個例子來講，我現在不住臺北，那我可以領國立臺灣大學給的住宿津貼，一個月700塊。這個叫小額福利，就算了。所以在課稅的時候，不會計算進入到我的所得的範圍。那為什麼會是700塊？因為從以前計算出來的標準，到目前為止都是這個樣。啊，我們當然後面會去跟各位去談，但現在的住宿，用700塊，你租得到，就輸給你。不可能是這樣，所以假設雇主提供住宿的地方，也就是有一個住宿的地方，特別像公務員，因為任職在公家機關單位提供宿舍。這個還可以叫做Fringe benefit的小額福利性所得嗎？這個會有問題喔。好像現在大部分的市長或者是大部分的首長，基本上都有配職務宿舍。職務宿舍就是因為一直都被認為說這個叫小額福利，就比如說我剛剛跟各位講，我沒有住學校宿舍的時候，我就領700塊，就這樣。意思就是你如果住學校宿舍，你也受益700塊。各位如果覺得有道理，我也是輸給你啊。這個700塊根本在實務上發揮不了作用，他的正當性理由就是這是一個小額福利性措施。
除了剛剛講的房租津貼，早期有交通車接送，這個也都是屬於一個小額的福利。

其實相對應的哦，這個在德國像他們在耶誕節由公司所提供給員工的耶誕禮物，不算入所得的範圍，這是同樣一個概念。剛好對應的，我們最近剛過完中秋，假設公司發給你中秋禮節的禮金或者是禮物，這個都是屬於小額福利性所得。所以以第4條第一項第五款的房租津貼或者是實物配給或其代金及房租津貼，這個部分最早的本意是認為他是小額福利，從而給予免稅的稅捐待遇。這是基於實用性原則。

### 【功績原則】

第二個，我們來看，基於獎勵給予社會捐優惠，也就是對於在經濟行政上被鼓勵的一個市場經濟活動，表現出獎勵也就是功績原則，因此給予稅捐優惠。譬如說，第4條第一項二十三款：「個人稿費、版稅、樂譜、作曲、編劇、漫畫及講演之鐘點費之收入。但全年合計數以不超過十八萬元為限。」這個是獎勵文化的這一種創造性活動，因此對稿費版稅樂譜作曲編劇漫畫及講演之鐘點費收入給予免稅優惠。就是說，對於這一種文化性的創作活動，以18萬元額度為限，給予獎勵，他是一個典型的依獎勵原則，和我們稱之為叫功績原則。在這種文化性的創作活動裡面，立法者鼓勵你創作，鼓勵你從事於文化性的創作活動，所以給你一個免稅的優惠。這個是功績原則。

### 【需要原則】

第三個，立法者會基於什麼樣的理由給予稅捐上的優惠？基於需要。也就是在社會國原則底下，對急、難、救助，對於處於生存有危害的這種情況，或者是老弱病殘，這種需要給予社會扶助或是社會法給予協助救助者這一類的情形，而給予的稅捐上的優惠，這個是應稅所得，但基於需要原則而給予免稅的優惠。那么，在我們的所得稅法裡面，沒有比較典型的需要原則的稅捐優惠，但在嚴重特殊傳染性肺炎防治及紓困振興特別條例第9-1條，受嚴重特殊傳染性肺炎影響，而依本條例、傳染病防治法第53條或其他規定，自政府領取之補貼補助津貼獎勵及補償，免納所得稅。從這個法律規範的角度來看，其實他也可以被認為是給付行政。也就是說，這個是一個政府在covid-19的非常時期對受covid-19影響而導致他需要國家提供給予協助或救急的補助，作為給付行政，因此不在市場經濟活動的範圍。從這個角度理解的嚴重特殊傳染性肺炎防治及紓困振興特別條例9-1條第一項之規定，他不是所得稅的所得啊。這個是第一個角度的理解。第二個理解，即使認為這樣子的所得，是一個市場上的經濟活動的所得，他也是在一個基於急難的緊急狀態，對於陷於需要國家提供協助的企業或個人，在這裡面依據需要原則，因此而具有正當的免稅理由的一個稅捐優惠的所得。也就是說，從他是給付行政的非所得，以及他就算是所得，但也具有依據需要原則，而給予稅捐優惠的正當性基礎的免稅所得，而來正當化對於應稅跟免稅所得的區別對待。原則上基於以上這三種理由而來，對一個本質上屬於經濟成果，但我們在稅捐法制上面給予一個稅捐優惠待遇的這一種做法，這個就是一個免稅所得的正當性。


### 【避免重複課稅】

還有第4個，為了避免重複課稅，也就是免稅所得是因為我們在法秩序上已經有另外一個有效課稅的稅目，去對該等所得去做課稅，從而我們在所得稅法裡面把他納入免納所得稅的範圍，是為了避免重複課稅，所以背後的本意是分離課稅。也就是在這裡面，基於避免重複課稅，從而把他從應稅所得規定成免稅所得，不課所得稅所得，但改課其他稅目的所得。基於這樣分離課稅的類型的本意，從而在現行法秩序底下才做這樣一個規定。體現這樣子的分離所得課稅的本意的有4-1、4-2，然後4-4搭配第4條第一項的第十六款土地、證交所得、期交所得，還有第17款規定的遺產遺贈跟贈與，因為我們有課遺產稅跟贈與稅。第4條第一項的第十六款的規定，是跟4-4條搭配，我們有另外課土地增值稅，那麼105年以後4-4條的規定，因爲有房地合一稅，所以這一類的立法本意在分離課稅，避免重複課稅，而不是一個真正意義底下的所謂的稅捐優惠。理由在於，因為立法的價值決定，決定採用另外一個稅目來替代所得稅。當然從另外一個角度，我們看所得基本稅額條例的境外所得，也是同樣一個道理，也就是依照我們現在的法秩序的價值的選擇，是採用所得基本稅額條例的最低稅負制來課所得稅，而不是計綜所稅的所得，課徵所得稅。這樣一個立法價值，背後的立法上的原意是在分離課稅，而不在稅捐優惠。當然這樣的分離課稅有沒有道理啊？這個又是另外一個層次的問題，也就是說，立法者的價值決定是分離，但立法者的價值決定卻不一定有他的道理，也就是在一個合理的立法形成空間範圍內


### 【證交稅代替證所稅？】

我認為最沒有道理的就是4-1，跟4-2的證交替代證所，證交稅、期交稅替代證所稅。這個是明文寫在4-1、4-2條立法理由裡面的規定，尤其是4-1條。我們大法官第693號解釋，也明白地認為證交稅是替代證所稅，以稅代稅。我建議，看要不要把他翻譯成英文，我們這個國家告訴你，交易稅可以替代所得稅。我學稅這麼久，我還不知道，原來這兩個稅可以互相替代。一個在經濟活動的末端，一個在經濟活動的前端。一個不管你盈虧，你只要有交易就要繳稅的，那一個是有所得，就要課稅，有虧損要准予減除。兩個稅目，在經濟活動的不同端點，然後稅制適用的法理基礎又不一樣的情況底下，如何能夠說他是以稅代稅，那大概是我們的立法者或者是我們國家的法制環境很特殊，認為證交稅可以代替證所稅。

簡單來講，交易稅並沒有辦法適當地替代所得稅，因為交易完全顯現不出稅捐負擔能力，所得可以顯現出稅捐負擔能力。交易，只能說顯現出他增加行政上的成本。理論上，交易在一個未受管制的情況底下，透過供需雙方看不見的手，有人需要有人想要，有人不要，那這個時候他們透過契約的締結，他們就可以自然形成交易行為。交易稅的課徵其實是在因為他產生行政成本。為了反映行政成本，製造行政成本的人要去負擔該項行政成本，因此交易稅的正當理由，在於費用的回饋跟負擔。你增加行政成本，原則上就透過你的交易稅的課稅來回復你增加出來的行政上的成本。所以交易稅本質上可以被規費給替代，也就是如果增加的行政成本是在行政機關裡面，其實可以收取行政規費來替代交易稅的課徵。那麼交易稅也因此在現代法秩序，特別是在量能課稅底下，並不存在著正當性。交易稅，毋寧是因為他的歷史久遠，到目前為止，我們仍然存在著許多的交易稅，作爲量能課稅原則的前導，但是不是真正反映出量能。因為交易之後就是消費，那麼原則上他只是去推定交易越多、交易越大量的，你消費能力更高，從而你應該要更有能力去負擔稅捐。那么，在這樣一個前提底下，交易稅基本上不足以適當地去反映出一個人的稅捐負擔能力，換言之，買賣越多的人不一定有更多的稅捐負擔能力。相對於此，有所得的人通常就有稅捐負擔能力。因此，在分離課稅的前提底下，證券交易所得，仍然應該要被核實課稅。

臺灣的證券交易市場基本上是集中交易市場，沒有道理不能核實課稅，所以不願意核實課稅，純粹就是一個政治上的選擇，就是要不要做的問題，要做可能會部長下臺兩次，就這個差別而已喔。不做，那就代表著我們國家的立法者告訴你，努力工作賺錢，你要被課40%的所得稅，但炒股票是不用繳稅的。就是在告訴你這個基本價值，歡迎大家來到一個炒地皮跟炒作股票不用繳稅的世界裡面。我們歡迎大家來到這個世界，就這樣而已。所以，不需要找好工作，你應該是想辦法裡面去股市裡面去賺到大筆大筆的錢，這個是立法者告訴你的立法上的價值。我同意資本利得的這種交易所得應該要低課稅，各國之所以對證券交易所得稅不會像薪資所得課這麼高的稅負，是因為資本很容易在全球化底下瞬間移動。哪個地方課高額的所得稅，很快資本就會流失到不課高額資本利得稅的地方，這一點完全可以清楚，可以完全理解。所以當周邊國家對資本利得不課高額稅賦的時候，在臺灣單獨要推出一個高額的資本利得稅，確實在現實上不容易可行，特別是當左右鄰近是香港新加坡。因為香港跟新加坡本來就把自己定位為是一個資金停泊港，就是要讓國際資金可以快速來回。香港確實真的不課資本利得稅，所以在當地炒的地、炒股票，原則上只課印花稅，相當於我們的契稅，相當於我們的交易稅，確實是不可所得稅。我們可以很充分地明白，確實，在客觀環境上面，如果周邊國家不課資本利得的所得稅，那我們要單獨去課的時候，我們確實不會讓資本停泊在本地。

但回過頭來，這個確實是一個價值上的取捨，在本地，如果當你課所得稅最高到40%的時候，也沒有道理，對資本的在本地的取得完全一毛所得稅都不課，因為他等於是在鼓勵人們用錢去賺錢，繳的稅負比用勞動力賺錢繳的稅負更低，鼓勵你去用資本的方式去賺取到報酬而不用課徵任何稅負。這個無論如何，在現代的立法者的價值底下，即使是在國際競逐資本的前提底下，是不具有正當性。

從而，資本利得仍然應該要以核實課稅為前提，也許稅率不高，但仍然必須要繳納一個最低該要繳納的稅負。以臺灣所謂的證交稅替代證所稅，他的稅率是3‰，簡單而言不到1%。雖然他是用交易總額的3‰，不能夠完全跟所得額的1%相比，因為交易總額的3‰不等於是所得額。我們可以統計臺灣的證交稅跟在市場上，因此如果有獲得所得的話，那麼他到底實質實際有效稅負是多少，如果不到1%，他就傳遞出，我們努力工作的人繳的稅，甚至是比在股市裡面炒地皮的某一些知名人士都還要繳的稅負更多。這是在講比例，不是在講數額，因為有一些人詭辯說，他就算繳3‰，他也是繳比你多。你還真的有夠悲慘，因為你很努力地賺了錢，你繳了5%以後，你的是我比他的3‰還少，因為他是賺幾千萬幾億的3‰，所以他的數額比你高。但在這種前提底下，我們還是會質疑這裡面的一個立法者的價值。資本利得稅，確實在全球化競逐資本前提底下，不太容易高課，但一點所得稅都不課，則是沒有正當性的。臺灣的資本市場裡面不課所得稅，也會扭曲我們的稅捐負擔分配。舉例而言，當你交易所得不課稅，股利所得卻要被課28%。你到底是在鼓勵長期持有，還是鼓勵短期的套利投機行為？這個是你的一個法秩序上的一個價值上的乖離，也就是本來你應該要鼓勵張忠謀先生長期持有臺積電股票，而不是鼓勵他短期套利。短期套利只有3‰交易稅，長期持有卻要交到28%所得稅，那我當然是選擇短期套利。當然，張忠謀先生不會用這個稅捐負擔來評估他自己要不要持有臺積電股票，這是另外一回事，我們剛剛講的是小股東的持有股票的方式。


那我們今天先跟各位談到這裡。

第二個階段，其實是在講應稅跟免稅所得，跟第一個階段的差別就在要有法律明文規定為前提，才可以享受稅捐優惠。第一個階段是沒有法律規定，從解釋上也應該做理所當然的推定跟推理，這個是他們的區別實義。

我們今天先跟各位談到這裡。