# 20231211_01

---
課程：1121所得稅法一
日期：2023/12/11
周次：15
節次：1
---

今天是所得稅法一最後一次上課。下個禮拜，請各位能夠參加所得稅法的期末考試。我們的學期分數的總成績，就是期中再加期末，然後老師會看一下大概同學們的分數的分布，再做一個整體性的調整。因為老師並不太希望在考試過程裡面考一個對每位同學都很難的。如果每位同學都答得很好，其實也沒必要調整。就是萬一有一個是大多數同學都不太會答的話，那我會做一個整體性的調整。那大致上就這樣。因為我們沒有其他的點名或者是出席參與討論的這個成績可以供參考。老師原則上就是期中跟期末加起來，然後去做一個整體的調整。那所謂整體調整的意思就是說，如果不及格的人太多的話，老師會看一下那個考卷的內容，深自檢討，是老師沒有把題目出好，鑑別度太低，所以會做一個整體，所謂整體調整就是大概整體的一個移動的方式啦。


## 【就源扣繳程序】

我們今天是所得稅法一，綜合所得稅的最終的部分。

我們上個禮拜跟各位大概談到綜合所得稅的稽徵程序裡面非常重要的一個程序叫就源扣繳程序，或者是PAYE，是pay as you earn的這個概念啊，就是說你的稅負，理論上來講，應該是到隔一年的5月，也就是說，你的繳納期限屆至應該是隔一年5月的時候，那這一種等於是稅捐立法者透過條文的規定，把你的本來可以享受到明年5月份的期限利益，依法課稅原則底下，你那個時候才需要去繳稅，把那個期限利益給取消掉。

簡單來講就是，就源扣繳相對於結算申報，其實是有一個期限利益被取消的問題，也就是說，他其實本來應該到隔一年5月，如果最長以01年1月份來算，他等於是有一個一年4個月左右的，相當於是國家期前去做徵收。因為照道理來講，本來應該是到結算申報的5月份。那也因此，就有扣繳程序，是一個在法制上面來講，應該要謹慎以對的制度。就不用特別再去講其他的事項，就光一個綜合所得稅制的國家，用了所謂的就源扣繳制度。就有扣繳制度，等於是讓納稅義務人本來依法可以享有的，依法課稅原則底下，有一個延扣繳納的這個期限上的利益，會因為就源扣繳程序，在他賺到錢的時候，立刻就被所得的給付則給依照法律規定的扣繳率，扣除掉。


這個問題的思考，老師給各位的建議，就是要依序地去討論以下幾個問題。

第一個是就源扣繳制度，這個本身的合憲性與否。對我們，特別是法律系背景的，我們不會因為只是法律規範有扣繳義務，所以我們就毫不質疑他的正當性與否。任何法律背景的同學們都必須要對既有的法律規範存有一個某種程度上，為什麼，為什麼，你為什麼要這樣做，這樣的思考。我相信各位作為法律背景，相對只是把現況當作現況，就是，啊，法律長什麼樣子，就這樣接受來講，我想在這個地方，如果各位背後要有一個思考哦。當然，在這個地方，你必須要分兩個層次，就是說現況就是長這個樣子，你必須要很清楚了解現在的規定是長什么樣子，然後其次才是所謂的正當性的基礎。

特別是在行政處分的適法性，這個階段，原則上就是行政機關，他必須要依照現行法律規範的現況去做出他的行政處分，不管他是不利益的行政處分，或者是裁罰性的行政處分，都是一樣的，你必須依照法律的規定。

但在此同時，行政機關在依法作成行政處分，乃至於當徵納雙方有爭議的時候進入法院，法院在做審理裁判的時候，他也必須要依法裁判。但作為法官，往往在這個地方，他也必須要去考慮這一個系爭行政機關，據以適用為行政處分基礎的法律規範，本身是否具有合憲性。

這個是，各位，特別是法律人，我會期待也會要求各位做這樣一個考慮。因為各位將來有一天，你可能會當法官，那你當法官的時候，你其實你必須要去看，

行政機關沒有釋憲的聲請權，我再講一次，行政機關的公務員，你再怎麼懷疑法律，你沒有辦法去背離法律，你沒辦法違背上級機關所公布的解釋函令，因為這個在行政一體底下，你就沒有這個權限，你不能自己恣意地去脫離法規範，跟上級機關依法所公佈的各項解釋函令或者是事實認定的行政規則。不要說法規命令，行政規則你也不能違背。行政機關的公務員沒有太大的可能性去挑戰法律本身。但作為法院的法官是有這個可能的。因為我們在憲法訴訟法裡面第55條規定給受理各該行政訴訟事件的法院法官聲請釋憲的權利，當他認為法律位階法規範具有違憲的確信的時候，他可以裁定停止訴訟程序去做釋憲的聲請。當然，在我們國家並沒有讓一般的法院直接有違憲宣告的權利。

我再講一次，一般的法院沒有違憲宣告的權利，可是他可以在法規範文義許可的範圍內，盡量去做合憲的解釋。這也是一種憲法意旨的表現。不是行政法院的法官就不需要有憲法意識，這個是完全錯誤的概念。行政法院的法官，他必須要依法裁判，他必須要有法規範，這個無論如何，他是去必須具備有這樣一個意識。因為他畢竟他並不是一個民選的機構。對法官來講，他是，依照法律，跟良知良能去做判斷而已。當然，在這個同時間，他必須要透過他的法律解釋的方式，透過個別行政法去體現憲法上的意旨，這個也就是我們稱之為叫合憲性解釋的一種方法。當法官認為無論怎麼去做解釋，我都得不到合憲的結論，這個時候必須要停下來，去聲請釋憲，去向我們國家唯一有權限宣告法律位階法規違憲的司法機關，也就是司法院大法官，去聲請釋憲。


這個層次要分開來。行政法院不能做違憲宣告，可是他可以盡可能在法律規範文義裡面去盡可能去做符合憲法規範意旨的解釋，這個是每一個行政法院的法官都可以做的。那行政法院法官做，他發現文義拘束了他，讓他怎麼解釋都逃不過那個文義可能解釋的範圍，這個時候，法治國家賦予給這個行政法院法官一個法律位階憲法審查的聲請的權利，也就是讓你可以去做這件事情。當然你不能直接宣告他違憲，因為在我們國家只有一個機關，可以宣告法律位階的法規範的違憲，讓他產生一般性的失其效力的這樣一個效力。

當然，作為司法院大法官，作為整個國家體制裡面唯一能夠去宣告法律位階法規範的違憲的這個司法機關，他當然必須要非常謹慎地去行使他的權限。


那么當行政法院法官不能夠做這樣合憲性解釋的時候，那么最後面，當然體制上面來講，我們只能夠仰賴司法院大法官對系爭法規範，在做具體的解釋的時候，能夠去體現憲法規範裡面的意旨。

我們在上個禮拜談到673號解釋。那673號解釋，其實有些他講的地方，並不完全是正確，那我現在把673號解釋裡面大概所提到的幾個問題點整理一下。針對就源扣繳程序，各位同學可以以下幾個層次去考慮這個問題。

第一個就是就源扣繳制度本身的合憲性。

第二個就是就扣繳制度制度是透過裡面的義務主體跟義務的內容去設定的，所以第二個就是你要看就源扣繳義務人的主體設定，是否是正確的，也就是說，是不是符合於事務本質，他找到對的人，在對的時間點去做對的事情，也就是第二個，義務內容的設定。

第三個，就源扣繳制度裡面的行為義務的內容。

673號，我在上個禮拜花了很多時間跟各位講，我主要是再跟各位講一件事情，他找錯人了。你不應該是找機關團體學校裡面的，不管你是負責人或責應扣繳單位主管，不管你叫做出納或是叫會計，你找錯人了，這個本身就違反比例原則。因為他找錯人，沒辦法達到目的啊。這個是我對673號最大的批評，也就是說，673號裡面他基本上是跳過第一個層次的問題，叫做就源扣繳制度本身到底合憲與否，沒有很直接正面去回答這個問題。

那我接下來今天也是跟各位去討論這個問題，就就源扣繳制度到底本身合不合憲。這個是第一個層次的問題，第一個過了才會有第二個。當然其實一二三毋寧是相互交錯作用的喔。就源扣繳制度本身、就源扣繳制度裡面的行為義務主體、就源扣繳制度裡面的行為義務的內容。

我們的行為義務內容對扣繳義務人課予扣取、申報、繳納、填發扣繳憑單，總共4個扣繳義務的內容。

接下來我們再來看，再下一個層次的問題是賠繳，也就是你沒有做好，我要苛責於你一個不具有非難，但是是一個不利益，因為賠錢本身就是個不利益。我們稱之為叫責任債務人，這個概念，其實我們在稅法總論裡面說了很多次，但我們現行法一個字都沒出現過。我們現行法完全沒有那個不同層次的納稅義務人的概念。

我舉個例子來講，我們到所得稅法三的時候，我們會去講到遺產稅的納稅義務人。遺產稅的納稅義務人，理論上他本來應該就是遺產的權利義務歸屬者，也就是拿到錢的人，他才叫做納稅義務人。也就是繼承人跟受遺贈人。那遺產的管理者跟遺囑執行人又是什麼身份地位？遺囑執行人，他是負責執行被繼承人立下來的遺囑，他是一個業務執行者，他本質上不是權利義務的歸屬者，各位讀過法律應該對這個算基本認識，在我來看，這個是基本認識。遺囑執行人跟遺產管理人根本不是權利義務之歸屬者。但他卻經由我們的遺產贈與稅法的規定，被納為權利義務之歸屬者，把他同視作為繼承人受遺贈人一樣的納稅義務人地位，這個本質上就是一個完全搞不清楚狀況的立法。

你絕對不能因為這個立法，所以你就認為，這個立法就長這個樣子，我還能怎樣。不對！各位，如果將來有一天當法官的時候，我是希望各位能夠勇敢地鼓舞起，聲請釋憲，因為行政機關是沒有辦法聲請釋憲的，只有行政法院的法官，他有這個機會跟可能。當然啦，其實人民窮盡救濟程序也可以去提起，但你看這麼多年來，之所以沒有人去挑戰他，就是因為人民打完救濟程序以後，他大概也累了，他大概也不知道原來問題出在法律本身，而不是稅官，也不是行政法院法官。

也因此，我請各位也當然要特別去注意，問題往往出在法律本身，而不在於為什麼他要這麼苛刻，為什麼要找我一個遺囑執行人？我常常以前上課的時候，有一些會計師或律師跟我講說，柯老師為什么要被限制出境，我幫忙做事情，我為什么要被限制出境？我說，對你限制，這個就法律規定的不義，法律規定不義，就是你要勇敢去提出釋憲啦，因為你只有你才是權利人，你才是一個被限制出境的當事人。結果你這個事情後來去財政部，財政部說，哦，對不起，我們弄錯了，你這樣是形式納稅義務人，那個拿到錢的繼承人跟受遺贈人，他叫實質那受益人。哦，突然出現一種分類，叫做形式跟實質納稅義務人。好奇怪。

但我不是非難財政部這個分類，因為其實他也想要嘗試著在立法的這個地方裡面，自己想要去找出一個出路，後來就形成了一個叫做形式納稅義務人跟實質納稅義務人。實質納稅義務人，才要真正被限制出境，形式納稅義務人不需要。我們姑且不講這一種分類到底從何而來，財政部想要去解決的，就其實他是職務管理人，職務管理人本來不是權利義務的歸屬者，真正被權利義務歸屬的人，其實是拿到錢的繼承人跟受遺贈者。你這樣一清楚去思考，你就知道問題本身，問題出在法律規範的本身。稅法這一類的例子還算不少。好，那也因此，回到我們的就源扣繳制度。

第一個層次是就源扣繳制度本身的合違憲性的問題。

第二個，扣繳義務人的設定。

第三個，扣繳義務的內容，是否過重的負擔。

第四個，賠繳義務人，也就是責任債務人的設定。賠繳責任就是，他其實是無償來幫國家完成扣繳義務。無償，這件事情，我做不好，拿不到錢就算了，我還要賠。這個概念會不會有過重的問題？

最後第五個，就是扣繳義務人的處罰受罰。一個扣繳義務人，沒有依法去做扣繳，他有違反的行為義務，這一點毋庸置疑。但他受的處罰，基本上跟納稅義務人相當，這個道理在哪？要考慮責罰的相當性。


這個是我們在扣繳義務裡面大概一路過來，可能會思考到了幾個問題點。

## 【就源扣繳制度之合憲性】

首先，第一個，就源扣繳制度本身的合違憲性。

### 【境外所得者】

其實這個部分，我們最早就源扣繳制度，有一個釋字116號，就國外廠商因分期付款所生之利息所得應如何扣繳所得稅，解釋文裡面提到：「支付國外廠商分期付款，訂有利息者，其利息所得，仍應由扣繳義務人於給付時扣繳之（稅款）。」

這個解釋當然是依循著當時的所得稅法第86條第三款的扣繳義務人的規定，後來就是變成了第89條的規定。納稅義務人，是取得利息的這個所得者，然後扣繳義務人則是89條所規定的。我們這時候的法律規定跟當時或法律規定不全然相同。我之所以會提116號，主要是，他在沒有直接提到這個概念前提底下，認為付給國外廠商的利息所得，用扣繳制度。他在這個地方，沒有討論跟辯證，他肯認的這個制度，本身的正當性所在。

也就是說，對於取得所得者，依照PAYE就源扣繳制度，我們要求給付所得的人在給付的時候直接做就源扣繳。釋字116號，沒有直接正面去談到正當性。但你可以認為，他是在這個前提底下去討論，關於付給國外廠商的利息所得的情形。

我個人也認為，如果取得一個屬於本地有課稅權限的所得，而所得的取得者，是一個國外的，非境內的居住者，那麼確實在課稅的手段裡面，你沒有辦法期待他在離境的時候就自然去做申報。因此我個人也贊同，境外所得者，也就是，取得我國來源所得的非境內居住者，適用PAYE制度，這個是有正當性的。也就是說，這個是為了掌握稅源，為了實現有所得就應課稅的基本原則，我個人認為他是合憲的一個手段。

### 【境內所得者】

那接下來我們來談，如果是境內的所得者取得我國來源所得，那這個時候是不是還有這一個就源扣繳制度的正當性，這個才是接下來的問題所在。

我們在此之前也跟各位去提到，在臺灣的所得稅法裡面88條，綜合所得稅納稅義務人的各類所得，基本上都會有就源扣繳制度的適用可能。我們的就源扣繳制度，是各種類型所得都有適用的可能。這其實是源自於我們在民國46年以前，是分類所得稅制。

所謂的分類所得，就是在課稅的時候，對於各類所得來源，直接做就源扣繳。分類所得稅，他沒有綜合在一起去做結算申報的制度。分類所得稅制的國家，對於所得課稅，原則上都是按就源扣繳PAYE制度。所以你可以看得到，大概是英國為主的，包含英國前殖民地國家或地區的新加坡香港，就是屬於這一類的。根據分類所得，就是你各類不同所得，比如說在香港，薪資所得直接就源扣繳12%結束。

英國是最早1799年引進全世界第一個所得稅，那時候為了要對抗法國的拿破崙，所以他需要這一些錢來支應，因為打仗就是錢啊。那在這種情況底下，英國雖然是引進了全世界第一個概念上針對你的所得課徵的稅制的一個國家，但英國到目前為止，他基本上都還是所謂的分類所得，也就是直接各類所得來源，直接在源頭那個地方按照一個固定比例的方式去做課稅。這個就是分類所得，他的稅捐稽徵手段基本上就是用就源扣繳。

可是採取綜合所得稅制的國家，意味著各類所得不分類，至少原則上不分類。什麼叫綜合所得？綜合所得，意思就是不分類嘛？大家放在同一個稅基。因此綜合所得稅制的國家，一方面受到19世紀的社會國思想的影響，一方面會在綜合所得稅基裡面搭配超額累進稅率。另外一方面，他在稅捐的稽徵上面，也會採取結算申報制度，因為只有你自己最清楚自己的所得。所謂的綜合所得的概念，就是不管你是租金，你是薪資，你是財產交易，全部的錢都放在一起，這個時候才有辦法去適用超額累計稅率，所以通常都會用結算申報，就是你自己來報。那我根據你申報的結果，我核定你一張綜合所得稅的稅單。臺灣只是把報繳程序合在一起而已，基本上也是你自己來申報，然後國家再根據你的申報的內容給你一張核定的稅額通知單，或者我們用公告的方式，我們待會會去講，會用公告的方式去代替核定的稅額通知單。大致上就是這個差別而已。但結算申報制度，一般而言就是搭配所謂的綜合所得稅制。


那我們民國46年從分類所得稅分類所得稅改制變成綜合所得稅制的時候，沒有放棄就源扣繳的制度，因為這對稅捐稽徵機關是一個最小成本費用，就可以拿到錢的方式。這個制度本質上是對國家極端有利，國家以最小的費用，如果這樣講最小費用，他應該講費用為零，因為國家把這些費用都轉嫁出去，讓誰負擔？讓扣繳義務人負擔。就這麼一個簡單的一個稅制轉換過程，我們從分類所得稅走向綜合所得稅，我們並沒有放棄在分類所得稅制底下的就源扣繳。我們要就源扣繳，我們還要做什麼？還要做結算申報。等於是為了一次稅捐的徵收，我們既要給錢的人要負責就源扣繳，我們還要拿錢的人也要自己來告訴我，你賺多少錢。

這正是這個制度本身，我們在第一個層次去講，就源扣繳制度對境內所得者究竟有沒有過度干預。是誰的問題？是誰是納稅義務人的問題，還是是扣繳義務人的問題？你覺得是誰的問題呢？我們先講納稅義務人。納稅義務人，你是取得所得者，所以要求你自己來申報自己的稅捐，你有問題嗎？釋字537號說，這個是合憲的。所以納稅義務人自己有所得，自己來申報自己稅捐，確實是最小干預手段。簡單來講就是，你自己告訴我你賺多少錢。稅捐稽徵機關根據你申報的事實，再去做查核。不然大海撈針我去哪裡查，我怎麼查？

你自己告訴我你在臺大有所得嘛，我再去發函問問看臺大究竟是不是給了你自己講的那麼那麼多所得。這樣他會比較清楚，因為他可以透過勾稽的方式。我說我是從臺大賺到的所得好，那稅捐稽徵機關就去問臺大，看臺大是不是在申報稅的時候，這裡面有一筆費用就是付給的柯格鐘，那這個時候我可以做交互查核，透過這種方式來去確認柯格鐘在申報所得稅的時候，是否做誠實的申報。

## 【扣繳義務人】

在這樣一個前提底下，我們還要再額外對一個第三人，賦予一個公法上的義務。

當然在這個地方，扣繳義務人的法律上地位，這裡面學說有不同看法。

扣繳義務人法律上地位，例如陳敏老師，他就認為這個叫公權力授予私人行使。也就是國家把課稅的公權力授予給扣繳義務人來對納稅義務人行使，換言之，納稅義務人不能拒絕扣繳義務人的扣繳。

葛克昌老師認為，他是一個行政助手，行政助手的概念就是他是一個沒有自主意識的手臂延伸而已。扣繳義務人沒有自主的意思，他只是受到稅捐稽徵機關的指示，然後去做扣繳。

公權力委託私人行使跟行政助手這兩個概念的差別，只是差在被委託的這個私人，扣繳義務人，他本身是否具有自主的意識，而決定要不要去做成該項公法上的行政處分的行為。差別只是差在這裡而已。

我個人則認為，這個地方不存在著公權力委託私人行使，也不存在著一個所謂的行政助手，因為，行政助手的概念，還是把扣繳義務人當作是公權力機關的手腳延伸，這是差在有沒有自主的意思形成而已。

其實不然。扣繳義務人毋寧是幫納稅義務人去完成公法上的繳納稅款的義務。各位能夠聽出來這幾個概念之間的差別嗎？雖然這純粹只是一個概念上的說明，但最大的區別實益就在扣繳義務人，如果沒有完成扣繳義務，請問稅捐債務是否已經完成繳納義務，也就是稅法上的稅捐債務關係是否消滅？

我舉例而言，扣繳義務人，扣繳稅款以後，他跑了。不管是陳敏老師的說法，或者是葛老師的說法，他最後面承擔損失的必然是國家。因為不管是行政助手或是公權力委託私人，那是你們內部的事情，你只要從我納稅義務人那個地方扣了一部分，你只要扣了，你沒有交給國家，那是你們內部之間的公法上委任契約的債務不履行。跟我無關。跟誰無關？跟納稅義務人無關。

相反的，如果你是採我後面說的這個，叫做服公法勞務的私人。所謂的「服公法勞務的私人」，這個私人本身不具有高權地位，他本身是為另外一個人去服這個人本來應自行申報繳納稅款的義務。「服公法勞務的私人」，跟本來應服公法勞務的「本人」之間，存在著一個類似公法上的委任的關係。基本上委任人也沒有辦法，直接指示受任人去做如何如何的扣繳，比如說不要做扣講，比如說以比法律所規定更低的比例去做扣繳。納稅義務人並沒有辦法去指示扣繳義務人，扣繳義務人全然還是要依照法律的規定而去做法定給付時的一個依照比例的扣繳。

從而這個制度本身，確實在概念上來講，是對國家比較有利的。但正因為我們的所得稅法裡面對扣繳義務人如果未履行扣繳義務，法律仍然規定國家可以向納稅義務人去請求繳納他未完成的稅款繳納義務，所以我國的現行法是採取「服公法勞務的私人」的規範，而不是前述兩位學者所講的，授權與私人行使。因為最明顯的差別，就在只有在「服公法勞務的私人」的這個概念以下，沒有扣繳稅款，誰承擔那個損失？國家，原則上他不承擔，他認為，我還是可以跟你納稅義務人，因此他會變成是，可以對納稅義務人要，也可能去對扣繳義務人要，而形成了扣繳義務人跟納稅義務人之間，某種程度上是一個未經法律明文規定的，不真正連帶債務的關係。

不真正連帶，因為真正要負起最扣繳納稅款義務的，應該是納稅義務人。扣繳義務人，他自己扣繳義務沒有履行，他確實要賠繳，他賠繳繳完以後，他是回過頭去，去跟納稅義務人，要求追償。這個概念正是各位在的學民法裡面的不真正連帶。不真正連帶，也沒有法律明文規定。

在德國，他確實是把扣繳義務人跟納稅義務人規定成連帶債務人，有法律的明文規定，國家更有依法課稅，依法去對扣繳義務人去追償的正當性的基礎，因為法律有明定。扣繳義務是一個加諸在第三人的行為上的義務。先是行為義務，之後在你沒有履行扣繳義務的時候，而產生對你的財產權利的剝奪。賠繳本身就是財產權的干預。從而，是工作權在前，財產權在後。

扣繳制度，原則上是要求，你給東西的時候要先做扣繳，那由於我們是一個非常廣泛的就源扣繳義務，不直接連結特定的工作領域，從而他是一般行為義務的干預，然後之後才是財產權的干預。也就是說，因為扣繳義務，並沒有限定在特定的所得類型。我們的扣繳義務是牽涉到所有的所得類型都有，從而他是從一般行為義務這個角度，在你沒有依法去做扣繳的時候，國家一樣可以對扣繳義務人去請求，作賠繳的主張，這個就是責任債務的請求。這個責任債務請求，當然涉及到財產權的干預。

也因此，我們在第一個層次裡面，我們要討論的就是，就源扣繳義務，對境外所得者做就源扣繳，我個人認為是合憲的，因為也沒有更好的方法，你不太能夠期待一個境外所得者，他離境或者在每一年結算申報的時候，他就立刻來做所得的結算申報程序。因此，對境外的有所得稅捐義務的人，我們要求付錢的人，給付所得者，直接在源頭之處，做就源扣繳所得。

這個也是在世界各國範圍內大致上承認的一種稅捐稽徵的手段，特別是對境外所得者，也就是取得所得者，是非境內居住人或是非稅籍居民的事業。這一種類型，只要這個是我們課稅權所及的話，會要求給付所得者去直接做PAYE這個制度。

但相反的，如果本身取得所得者，他本身就是一個稅籍居民，在分類所得稅制的國家，確實還是會用扣繳制度。可是一個綜合所得稅制的國家，繼續採用如此廣泛的就源扣繳制度，特別是在有結算申報制度的前提底下，畢竟還是納稅義務人，自己取得所得自己來做結算申報，那何以要對第三人，課予這麼高的行為義務的內容？至少立法者要在比例原則底下，要好好地告訴我們，說明為什要做這件事情。

相對於就源扣繳，比較輕的干預手段，毋寧是通報，就是你給錢，那你告訴國家，給他多少？就好像我在臺大授課，我賺錢，國家怎麼知道我賺多少錢？請國立臺灣大學通報給國家就可以。而不需要做進一步的就源扣繳的相關義務。你只要比過干預手段，所謂最低限度，你就可以了解，哪一種是比較嚴重的干預。這一種比較嚴重的干預，至少國家在立法上要說出一個正當性。


因此釋字116號，是對境外所得，這個我個人沒有意見。但對境內所得所涉及的釋字673號解釋，我就有很多意見，理由在於，就源扣繳制度本身的合違憲性。特別是，我們是一個綜合所得稅制的國家。理論上，綜合所得者，你自己就去做結算申報，應該要自己的稅捐自己申報，自己負擔繳納行為義務。這個我沒有意見，釋字537號說，這個是對課稅的金錢給付義務，你自己來報，必然必要的一種最小干預手段。

但在此同時，為什麼我們國家有存在著第二軌的制度？這個第二軌制度一樣讓國家因此取得所得，而且是提前取得所得。提前取得所得，因為本來是結算申報啊，你應該是隔一年的5月份的時候，你才取得。然後這也是比通報義務是比較高程度的干預，基本上因為他要做扣取、申報、繳納、填發，這四種義務的內容，因此這是一個一般行為自由的干預。

我剛剛提到，這並不是針對特定的工作權的內容，對特定職業的干預，這是對所有的，只要符合88條法律構成要件規定的所得類型，符合89條所規定的扣繳行為義務人。

臺灣的所得稅法89條又針對特定的職業類別，所謂的職業類別，包括負責人，包括責應扣繳單位主管，包括從事會計的主辦人員，這個就會是對工作權的干預。這個是一個很典型的對工作權的干預。也就是釋字673號當時釋憲的程序標的，是以民國88年以前的主辦會計人員，會計。就源扣繳，當然涉及到對會計從業人員的，不是職業工作規則，而是稅法加諸給會計人員在職業上面，他們在工作上面而負擔的一個行為上的義務。

如果以目前的法律來看，大致上可以說這是一個對工作權的干預，毋寧大概是在事業負責人這個部分，雖然其實看不太出來一個具體特定的工作權的內容。越是看不出來，會越往一般行為自由的干預上面去評價，但越能夠被特定，針對特定的工作領域範圍，就會往我們憲法第15條的工作權這個部分去做行為自由的干預的審查。因為工作權是特定領域裡面的行為自由。


這個是我們在談到的第一個程度的問題，也就是就源扣繳制度本身的合憲性，以及，第二個問題，就源扣繳義務人之設定。

## 【義務內容】

那第三個就是就源扣繳的義務。就源扣繳的義務，其實我自己早期我一直都不太能夠明白為什麼要做四個階段的區隔，扣取、申報、繳納、填發。我後來到財政部訴願會才知道，哦，原來填發是這樣，因為他們在扣取申報繳納的時候，基本上扣繳義務人並沒有指明，這個錢是誰的錢，是要到隔一年1月份的時候填發扣繳憑單的時候，他才具體去告知稅捐稽徵機關跟納稅義務人，哦，我把你的錢給國家了，國家才知道說哦，原來我收了錢是柯格鐘的不是柯小鐘的，不是陳衍任老師的。


填發，是對帳用的。

每個月你拿到錢的時候，扣繳義務人就是逐次給、逐次扣，扣取、申報、繳納，他一次就要把那個單位或是機關內部的所有申報扣取的稅款，他就要一次繳給國家。給國家的時候，其實國家不知道他收到錢，國家也不那麼care，反正我收到錢。

所以我們釋字673號講說，這是國庫調度，我想說，以我自己對673號解釋的想法，就國庫調度，請問國庫調度干納稅有什麼事情？干扣繳義務人什麼事？這個怎麼能夠經過目的正當性的審查？説是增加國庫調度的可能性，國庫調度你可以去跟銀行借錢呢，可以發行公債啊。

納稅義務人的申報義務，在綜合所得稅就是隔一年的5月份的結算申報義務啊，你今天你為了國庫調度，你切割成在前一年的每一個月份的時候就要給錢，讓國家比較好收支。請問這個國庫調度，是加重第三人扣繳義務人行為負擔義務的正當理由嗎？你要做比例原則的第一個階段檢驗就是，這個規範的目的正當性。我個人認為一點正當性都沒有。所以對673號我當然有很多意見。到目前為止，除了境外所得者就有扣繳制度以外，我們境內所得的取得的所得，最重要關鍵的673號解釋說他合憲。


在673號裡面，大致上就把所有的就源扣繳制度的相關問題，全面的，不管你設定誰，都符合，為了要讓國家掌握稅收，這個是正當目的，為了讓國家掌握稅收，其實是為了實踐量能課稅原則。但為了國庫調度，則沒有正當性。因為國庫調度這一件事情，在你的立法理由裡面，不管你立法者有沒有寫這個東西，你寫這個東西就代表著你是基於不當的考量而引進了就源扣繳制度。


對於扣繳義務的內容，我最初的看法比較認為，就源扣繳裡面的「填發」是沒有必要的，因為如果你在申報的時候，你就已經告知，我扣繳義務人扣繳的稅款，納義務稅人是誰，那其實不需要後面那個「填發」。但我們現在實務的作法確實是沒有直接告知國家，所以就變成他後面還是要有一個對帳的動作，不然繳那個錢，到底最後面要算誰的可扣抵的所得稅額，這個就會不清楚，從而會有後面那一個扣繳憑單的「填發」。

一方面要給國稅局，一方面要給納稅義務人，讓納稅義務人也知道哦，原來我你幫我扣取了多少的稅款。這個是我們制度上因此導出來的一個，讓他變成要做這一種兩道的行為義務。

## 【責任債務】

賠繳這個部分，我個人認為，由於行為義務的違反，讓他承擔這個不利益，我認為是合於比例的。扣繳義務人應扣未扣，讓他負擔賠繳義務，主要是為了讓扣繳義務制度，在前面第一個合憲的前提底下，因為我去對納稅義務人，我基本上要不到，特別是境外所得者，我要不到那個錢，所以要扣繳義務人賠繳這筆稅款。我個人認為，扣繳義務制度本身的合憲性，也會證立了扣繳義務人作為第二順位的責任債務人的賠繳的義務。

## 【裁罰】

最後一個叫做，責罰非難，也就是裁罰。正因為在這個整個程序裡面，我們的扣繳義務可能涉及到你是境內所得者跟非境內所得者，只要國家沒有稅款因此短收的風險，原則上不能對扣繳義務人做過度的責罰非難。如果這個扣繳義務人所要扣繳的這個稅款，依照我國法律規定，根本不需要做就源扣繳，比如說我國沒有課稅管轄權，那這個時候你去責罰非難扣繳義務人，是沒有意義的。這一種扣繳的申報填發的義務建立在，我們國家對這筆所得有課稅權限，這一筆所得是屬於中華民國來源所得，納稅義務人本來應該要報繳我們的所得稅，但他沒有這個行為申報的義務，從而必須要仰賴透過就源扣繳制度。那麼也因此最後這一個裁罰的層次，要看現實上是不是會產生國家的稅捐短收的風險存在。

如果一路過來，扣繳義務人其實都有扣取申報繳納，那最後面只是沒有填發扣繳憑單，是對帳的問題，那理論上來講，這個就應該是行爲罰，從而不得責予與過度的非難。行爲罰往往會在接下來的責難裡面會被認為，如果你沒有設一個上限的限制的規定，就會有過度責罰非難的問題。

那我們除了673號解釋第三段有這個文字以外，各位還可以去看們一路以來對扣繳義務有涉及到責罰跟非難的是釋字317、釋字327、釋字673、釋字713號解釋，在這四號解釋裡面，統合背後的意旨是，只要國家沒有因為扣繳稅款而產生應收未收稅款的這一種風險存在，原則上不得過度責難非難扣繳義務人。

唯一留下的問題就是扣繳義務人在我國法制上幾乎是跟納稅義務人是同樣的對待。也就是我們的稅稽法第42條的規定，也給扣繳義務人一個等同於納稅義務人的逃漏稅捐的制裁。這麼高度的責任目前為止沒有任何釋憲。這是不是過度的苛責？原則上他確實有行為義務的違反，補繳責任，在很大程度上已經把國家短收的這個危險透過賠繳，讓國家取得他該取得的稅款，那是不是還要用這樣的一個方式去過度的責難跟非難，本質上是無償為國家完成這個公法上任務的第三人，我個人比較抱持著高度懷疑他的合憲性的看法啊。

這個地方，通過對各個層次的討論，講到所涉及的大法官解釋，跟各位說明扣繳制度。

到這裡我們先休息一下。接下來我們要談關於所得稅的結算申報的最終章，也就是稅捐稽徵程序。