# 20230911_01

---
課程：1121所得稅法一
日期：2023/09/11
周次：2
節次：1
---


我上個禮拜，是希望各位同學把所得稅法的法條找出來，我要你去做歸類。哪一些是屬於稅捐債務法，哪一些是稅捐稽徵法？或者是第幾條到第幾條是稅捐債務法的規定，第幾條到第幾條是稅捐制裁法的規定？

各位同學務必在接下來的課程裡面都必須要去做這個工作，因為我考試會考這個。請你按照順序重新排列一下，我們的綜所稅究竟在我們整個法條規範的順序，法條的内容，就是——稅捐債務法，稅捐稽徵法，稅捐制裁法。我們的每一部稅法的法典，基本上都是這3塊組成。那你必須要把他分辨出來，哪一個部分是哪一個區塊的。


## 【稅法規範體系】

在稅捐債務法裡面，我們可以依照依法課稅原則。
我先給各位一個實然，就是現在的狀態，現在就長這個樣。所謂的法律規範的實然狀態，我們在法學方法上，把他稱之為叫外在體系，就是法條跟法條之間的規範結構。

體系做最好的立法，就是民法。因爲歐陸法系就從民法開始，所以歐陸法系的民法，本身體系分明。整個民法建構在，包括所謂的身份，所謂的契約，那麼這兩個都共同適用的法條規定，我們把他放在民法總則。接下來，在契約裡面，或者是在我們財產法裡面把他再進一步分成了債法跟物權法。原則上我想各位都很清楚這樣一個規範的結構。

其次做最好的規範體系安排的，像刑法，刑法有總則編，有個別的犯罪規定的，個編的，也就是刑法分則。我們會按照國家、跟社會或個人之間的法律的侵害，或者是超個人法益的侵害，就是包括國家跟社會。
不管怎麼分類，他基本上的思考邏輯，反映在立法者的規範體系結構上面。刑法總則是分則的適用上的諸多抽象化的原理原則，具體化成為法條規範內容。

這個就叫做體系，立法者表現出來的立法上的體系，我們這個把他稱之為叫外在體系。根據立法者所表現出來的外在體系，往往他未必能夠表現出我們在思考上面來講，從抽象到具體，從一般到個別，這樣的一個規範上的結構。理論上來講，從抽象到具體，所以在個別法律適用的時候，原則上是具體優先於抽象，特別優先於一般，這個是我們各位，幾乎你在其他法領域裡面學過的基本的常識，基本的這種規範結構。

稅法本來也應該是如此，理論上也應該要有一個總論的東西。

但實際上，臺灣由於一開始本身就做分散式的立法，所以臺灣的稅法，結構上沒有很完整的外在體系，他是分散式的。
如果我們有一個稅法總則的法條規定的話，那麼關於稅捐稽徵程序跟稅捐制裁的相關規範，其實他就收攏過去，讓稅法總論去做規範就好。

以德國為例，大致上就是這樣一個規範結構，也就是說，各稅裡面，原則上他只有稅捐債務法，進一步去區別。各稅，原則上只有規範了稅捐構成要件跟法律效果。如果有必要，做個別稽徵程序的個別規定，那他就在那個稅法裡面，再做一個特別的規定，因為你要有別於原先在稅捐總則法裡面的稅捐稽徵程序。那樣的法條規範結構會讓法律的學習本身變得體系上比較完整。

很可惜的是，我們從稅法一誕生開始，我們一直就不是這樣立法，我們基本上分散式立法，也就是講好聽一點，叫做我們看到哪裡有問題，哪裡有需要，因此我們就立法。講難聽一點，就是我想要什麽稅，想要什麼東西的時候，我就才個別去做立法。因此，這種立法體系結構很紊亂，也很容易產生重複規範，甚至是相互矛盾而不自覺。也就是，一般法跟特別法之間的規定，他可能互相在這裡面兜不起來。而且也常常會有這樣一個重複規範的結構。那么我們現在就已經長這個樣子，沒辦法。再怎麼醜，也還是自己的法律。我們不是要學德國法，我只是告訴各位一個實然狀態，跟相對的叫應然。所謂的應然，就是我們透過一個一套基本的價值來去重整出來的法條規範的結構。

我們的法條現在的狀態，我們把他稱之為叫外在體系。

我上個禮拜跟各位講過，透過量能課稅原則，我們可以把所有的稅法規範，稅法的各稅全部都把他排列成一個經濟活動的不同端點，去做課稅。這個在某種程度上是透過所謂的量能這樣一個價值。内在體系就是透過價值而去做的規範排列安排。體系如果一致，就代表著這個法領域的發展相對是比較成熟的。人們，即使是沒有看法條規定，他大概可以猜想法條應該長什麼樣。這個部分，尤其各位在學民法，比較容易有深刻的感受。因為民法體系是整個歐陸法系發展最早的。越早的東西，他就越成熟，越完整。

拿破崙統一整個法國以後，他首先要證明自己不是只有打仗，不是只是從一個科西嘉島，農村鄉下來的孩子，他認為自己是有這樣一個文治能力的，就是通過1804年拿破崙民法。晚一點的德意志邦聯國家，到19世紀末20世紀初期，施行了德國民法。這兩部法典其實都是歐陸法系繼受了羅馬法的精神以後，把他成文化的一個最典型的代表。法律本身如果反映出內在價值體系，他就會讓你的外在體系規範結構，接近我們剛剛所講的那樣一個價值規範。也就是說，如果今天我想要把一個法條做一個規範結構上的重新排列組織，在我們的體系裡面，稅捐債務法，其實就是透過構成要件、法律效果……什麼叫依法課稅，就是法定債權債務關係。

## 【稅法上構成要件】

那至於哪一些是構成要件裡面的要素？我們在稅法總則的課堂上面我們花了許多時間去跟各位去講，基本的構成要件，叫稅捐主體，稅捐客體，稅基，稅率。這4個，就被稱之為課稅的構成要件\index{構成要件}。
各位如果上所得稅法，沒有這個基本觀念，我會強烈地建議，你一定要回過頭去看稅法總論，總論的東西就是這一堂課的基礎。當然我們上課裡面有許多基礎觀念的部分，如果你上過還是不太清楚，請你務必再回過頭去看。因為我們在這個課堂上沒有辦法，就這些基礎觀念，再一次地去跟你講，那個是什麼東西。要做自己的功課。

### 【主體】

何謂主體\index{構成要件!稅捐主體}？ 權利義務的歸屬對象。只有人，不管是自然人或法人都沒關係，但只有人，才可以是一個權利義務之歸屬主體。就跟民法第6條一樣，人才享有權利才能負擔義務，這一種享有權利負擔義務的能力，資格，身份，地位，ability，這個就叫做權利能力。訴訟法亦如是，相對應於實體法裡面的權利能力概念，叫當事人能力，死人是不能享受權利，也沒有辦法負擔義務的。歐陸法系的整體結構，就是建構在一個體系井然分明的：人，才能享受權利負擔義務。

以所得稅為例，稅捐主體（基本權主體）是人，所以，取得所得的人，那個人就叫稅捐主體。

課稅主體（課稅權限行使之高權主體）在現行稅法裡面不規定。課稅主體，我們是放到財政收支劃分法裡面，簡單來講就是如果你比照民法上的債權債務關係，債務人，我們在稅法規定；債權人，我們則放在財政收支劃分法。這個也是在稅法總論裡面會談的問題。稅捐債權人，在各稅法原則上是不規定。我們規定稅捐債務人。

至於你的權利歸屬的，有收稅權限的，在我們國家放在財政收支劃分法，在德國放在憲法。所以他們稱之為叫財政憲法。財政憲法不是隨便的，因為他們在基本法的規範上面直接明定這個收稅的人是誰。是國家聯邦，還是是各邦，還是各地方自治團體，他們是直接放在憲法層級，保障地方自治團體的稅捐收入，不會被代表國家的聯邦給侵奪。
每個階段，每個層級的政治團體，他受到了所謂的制度保障，那個概念，他不是空口說白話，因為他是放在憲法裡面，這就作為一個聯邦國家的那個體制，他本身呈現出來。
我們如果放到法律的規定，像我們是財政收支劃分法的話，他的保障層級相對就比較低。因為，既然放在立法，那立法者自己就可以形成，自己就有形成的空間跟可能性。

### 【客體】

至於對象的這個，就稱之為叫客體，也就是在所得稅法裡面，稅法裡面所要課稅的那個對象，是物是行為，那個我們把他稱之為叫客體\index{構成要件!稅捐客體}。


### 【稅基】

什麼叫稅基\index{構成要件!稅基}？稅基是客體的數量化。
舉例，民法上的同樣法定之債，各位想到這裡法定之債是什麽？在學民法債編的時候，有契約之債，有法定之債。法定之債是什麼？最典型的法定之債，侵權行為啊。所以，侵權行為，一定要每個侵權行為的構成要件，民法184條第一項前段因故意或過失不法侵害他人權利者，應負損害賠償責任。因故意，或過失，不法，侵害，他人，權利者。這個叫構成要件的各項要素。我們把構成要件，把他每一個排開來。

### 【稅率】

稅率就是課稅的比例。

## 【稅法上法律效果】

法律效果其實只有一個，就是稅基乘稅率，再得到稅額。所得稅法的規範結構裡面，稍微有一點點的不太一樣，就是我們這個稅額在所得稅裡面，他又分兩個概念，一個叫應納稅額，一個叫結算稅額。因為算出來稅基乘稅率的稅額以後，原則上並不是最終實際要繳納的那個稅額。這是法律上算出來，第一層裡面稅基乘稅率算出來，應該法律上應該要付的稅捐債權債務關係。

但由於我們有許多先前繳納的稅捐，所以你可以去做扣抵。有一些透過稅捐優惠，我們讓你可以去做扣抵，所以他會有第二個層次的，結算稅額。結算意思就是settle，就是最終你要繳給國家，繳給稅捐稽徵機關的那個數額。所以，所得稅法稍微對稅額再分兩個層次。一般的其他稅目不會有這麼細，一般來講都是只有應納稅額，應納稅額通常就是結算。但是所得稅法自己本身分得比較細一點。


## 【再談稅法規範體系】

在我們的規範結構裡面，我上個禮拜，是希望各位同學把所得稅法的法條找出來，我要你去做歸類。

這件工作，因爲我們的立法者，外在體系沒有做很好，所以就變成是各位的工作，是我們在教學上面要跟各位去强調的。因為這個其實本來應該放在稅稽法。你看哦，我們臺灣自己就有自己的稅稽法，可是稅稽法沒有規定稅稽法應該要有的相關規定，所以他又放到所得稅法裡面去規定。

我們幾乎所有的稅都長這個樣子。稅稽法沒有該有的規範結構，所以很抱歉，不好意思，就只好請你個別去看各稅的稽徵程序，因為我們的稅捐稽徵法，講白一點就是該規定都沒規定。

大概就是這樣一個外在體系殘缺不全的狀態，所以他也讓稅法難學，這個也是他的一個背景因素。稅法本身，從內在體系，其實他是會有一個整體規範結構，就像你在學民法跟刑法一樣，他其實並沒有什麼特殊性。

只是由於立法者自始從我們這一整套的法律……其實我們的各稅往往歷史都還比稅捐稽徵法還要更早。許多稅，以所得稅而言，我們上一次跟各位講過，他民國4年開始誕生的時候就出來了。所以當時沒有稅稽法的規定，因此當時的立法者沒有實際徵稅。民國4年誕生所得稅條例的時候，其實講白一點，那時候只是法律，根本不是實際執行的法律規範，為什麼？因為他掛在中央政府。中央政府在哪裡？在北京那又怎樣？北京，他的課稅權限，除了在北京城附近可以行使以外，到了南方誰理你啊？課稅權限，很大程度上是跟這個國家的統一跟分治的狀態有很大的實際的關聯性。
所有的稅的出現都是當時候多數都是國家需要錢，以稅為名跟人民要錢。法律制訂出來了，就看國家的能力能不能徹底去挖到人民的口袋，把錢掏出來。基本上都是這樣一個規範結構。當然我們，在法律裡面，想要把這樣一套的國家對人民徵收財產金錢為內容的，給付義務，希望把他做體系化，希望依靠原理原則，一方面，固然許可了，國家根據這樣一個原理原則，跟人民徵收稅捐金錢的可能，但回過頭來，其實他也是保障國家不得對人民進行違法徵收跟過度的徵收、過度干預。他一體兩面。他許可了國家對人民的徵稅行為，在同一個時間，他其實也在保障，國家不可以做法律之外，對人民財產權跟工作權的過度干預。

相關的課程也是回到稅法總則，因為我們在各論裡面，我們只就個別的法條規定，個別的規範結構之間的體系性的關係去做進一步的深化，不然我們會永遠一直都還在稅法總論裡面去打轉。好像各位學完民法總則，你總是要進一步推進到債編總論，要推進到債各，你的那個民法，才會具體化，才會活起來。

法律運用的時候，一定是抽象具體，一般個別之間的交互地去做提示。其實稅法亦如是，只是我們規範的外在體系跟內在體系，這個鴻溝不是只有一條，我這樣畫的白線而已，他是差距很大。我們今天就是要跟各位去講，從內在體系的價值去看，我們現在目前的法條規範結構，外在體系，內在跟外在。內在就是講價值，外在就是講立法者客觀的呈現。當然哲學上有一句話講，存在有他當為的基礎，為什麼長這個樣子，為什麼長這麼醜？他當然有他現在為什麼長這麼醜的原因，但沒有辦法，我們還是必須跟各位講，他其實本來應該可以長得漂亮一點，意思就是說，讓各位比較容易像民法像刑法一樣學習。不過很可惜，現在不是長這個樣。因此，請各位如果你沒做，沒關係，我現在帶著各位一起做。但是你要有法條，你要看著那個法條，你才有辦法把他一個一個把他給扶（？）起來。

## 【開始看法條】

我們來看一下所得稅法的條文，我們從第1條開始。第1條：所得稅，分為綜合所得稅及營利事業所得稅。這個條文告訴你說，我們所得稅法包含了幾個稅目。但這個條文很快你就可以知道，從民國105年以後不合時宜，爲什麽，有房地合一稅啊，他也不是綜所也不是營所。法條自己都立刻打臉，我們的立法者就是這種分散式立法，他後面改，前面不會改。他只會改他看到的那個地方，這個叫頭痛醫頭脚痛醫脚。第一個條文就先打臉自己。以前，105年以前我們的所得稅確實分成了綜所跟營所這兩個，這一部法典主要是規定這兩個稅目，但實際上，105就多出來一個無以為名的稅目。其實你如果待會去看那些法條規定的時候，其實房地合一稅，還只是財政部在他的行政規則裡面去，稱他叫房地合一稅，法條本身的名字還不一定真的這麼清楚地，給他一個稅目的正式名稱，因為我們在那個地方連那個稅目名稱都沒有在我們法條的規範結構裡面出現。

### 【1~3-3】

我們來看一下，第1條，所得稅分綜所跟營所，我都用簡稱就好了。

第2條是綜所的規定，第2條就是典型的綜所稅規定，就是課稅構成要件的規定。當然也包含法律效果。就像民法184條前段，因故意或過失不法侵害他人權利者，應負損害賠償責任。故意跟過失，什麼叫不法侵害，什麼叫應負損害賠償責任？其實他還是要由後面一大串的法條規範來把他補滿。

第2條本身就大概是這樣一個規範結構。有中華民國來源所得之個人，稅捐主體就是個人。取得中華民國來源所得，這個就是你的客體，他這裡面包含你的客體的實現地點。
這個就是我們之後每一堂課會講一個課稅構成要件。個人就是主體。客體則是所得，在中華民國的來源所得，我們會有所得的實現地點。

然後，應就中華民國來源之所得，這個地方沒有稅基的規定，他沒有講很清楚，真正要講，是說，應依本法規定計算所得額。所得額才是稅基。

客體是所得，把他數量化，所得額或者比較好的說法叫應稅所得額。剛剛提到的侵權行為，因故意或過失不法侵害他人權利應負損害賠償責任。損害賠償責任，就是在講，損害賠償額怎麼算。重點不在客體，要負損害賠償的重點，其實輸贏上下就是那個數額怎麼算？ 

比如說我不小心把你撞傷了，我願意賠你，但對不起，因為我月薪收入只有3萬，我一個月1%賠給你3000塊，可不可以？ 一個月只賠3000塊，要賠多久？如果各位將來進入律師這個職務的工作場合，侵權行為損害賠償。那個人說我很有誠意，我願意賠你。很抱歉，對不起，我不小心撞傷你了。哦，但是談賠償的時候，他說我願意賠你100萬，可不可以幫我簽個和解？那請問你怎麽支付那100萬？他説，對不起，我工作收入很少，一個月只有3萬塊，那我一個月賠你3000。你想想看，一個月賠你3000，一年才三萬六。100萬要賠多少年？你認為，那樣的一個侵權行爲人，有沒有賠償的誠意呀？他説我願意一輩子賠你。對啦，先給我看看你的錢在哪裡，你的誠意在哪裡？一個月賠3000塊，對100萬來講，這根本不叫做有誠意的損害賠償。

回過頭來，損害賠償是整個損害賠償法裡面，最根本關鍵的。各位都學過在民法裡面究竟如何計算損害賠償？有民法196有民法213，第一項或第三項的規定。不管是回復原狀或者是，對於減少物之市場上的價格計算，他都是一種approach，如何算出你損害賠償額度的辦法。

那麼，同樣的，在我們的稅法裡面也是一樣，稅基最重要。老師以前早期在講稅法的時候，尤其是早期在民國104年的時候，臺灣曾經想過要課證所稅。稅基最重要，看你所得怎麼算，這個才是根本關鍵。學財稅的、學會計的人不會有這個觀念，他們認為稅率最重要。稅率最重要？不對。任何正確的稅捐負擔能力的掌握是看你的稅基。稅基怎麼算？你今天跟我講要課所得稅，但是所得額亂算。這個不叫做量能課稅，不叫做稅捐負擔的公平正義。

我就舉臺灣最常見的，為什麼一堆人去炒土地？在房地合一稅沒出來之前。 因為臺灣長期以來，土地就沒有被實價課稅過。我要課土地增值稅，土地增值稅啊，結果你的增值怎麼個算法？ 從來不是按照實際轉售價值，從來就是按一個所謂的政府公告現值差。政府公告現值差就是一年調一次。所以你只要年初買年底賣，請問你怎麼會有公告現值差？ 就算房地產你買進來是100萬，年底賣出去是200萬，白花花，我就是賺了100萬。結果在政府或是在法律的眼中裡面說這個沒有公告現值差。所以我們土地增值稅，說要課稅，結果呢？他並沒有真的課，所以有土斯有財不是原因，他是結果。

簡單來講，就是臺灣長期以來對土地，根本沒有正式去面對他，然後我們一天到晚在那邊講說，土地增值稅有憲法上的基礎，我都還不知道你憲法基礎是怎麽來的。胡説八道，真是太誇張。臺灣長期以來沒有真正的土地增值稅。不需要做太多事情，就是你真正買多少？ 賣出去多少？這個不是很簡單的基本價值嗎？對臺灣就是做不到，很抱歉，我們真的到105年為止，我們就從來沒做。從105年，我們才終於開始。但，有日出條款。

所以現在，臺灣絕大多數的房屋，原則上你只要在那個時間以前取得的，原則上都沒有房地合一稅，都是按照舊制。所謂的舊制，就是他不是實際的轉售價差，他是一個根據想象出來的稅捐負擔能力。所以回過頭來還是跟各位講，想像的，不是真正的量能課稅。量能課稅是實際上你的應稅所得的額怎麼算。

稅率就是課稅的比例。在直接稅裡面，基於19世紀進來社會國的思想，所以通常會有累進稅率的設計。

我們的所得稅算是在那個時代裡面的產物，做不做得到是其次，確實在我們的直接稅裡面，最典型的所得稅，是有累進稅率。遺產贈與稅也是一種直接稅的類型，他是一種特種所得的類型，所以我們現在表彰出來的，也是一種累計稅率的設計。不過遺產贈與稅也曾經在我們的某一個時期，是只有固定比例的課稅。

這個就是我現在要透過法條規範的結構來慢慢地在實然跟應然之間去做比較。這也是我們今天課程的主要內容。

第2條第一項是課稅的基礎構成要件，跟他的法律效果的一個籠統性規定，因為實際上他並沒有把各項構成要件的要素都完整描述。從規範結構上看起來，基本上只有主體和客體，但怎麼算稅基，應該是用哪一條的稅率，他是沒有講得很清楚，只是在「應依本法的規定」裡面，做籠統性的規定，就這樣而已。所以你說他是完全性法條？ 不太是。真正很典型的完全性法條是像，剛剛我念到的那個民法184條第一項前段。所謂的完全性法條就是，這個條款裡面，構成要件跟法律效果，他都已經把他寫完了。

刑法很多，刑分裡面大部分都是完整性的法條規定。比如說，因故意致人於死者，他的法律上效果，他就直接在這裡面構成要件，法律效果全部在一個法條完成，這個叫完全性。但大多數的法條都是還是要透過其他的法律規範去補充他，所以我們稱這一些補充性的叫不完全性的法條，因為他本身不是獨立存在，他是要去補一個完全性法條，讓那個構成要件跟法律效果能夠完整。

那也因此，完全性法條其實是第2條的規定。第2條第一項跟第2條第二項。因為第2條第一項是境內居住者的課稅構成要件的規定跟法律效果規定；第2條第二項叫非境內居住者的課稅構成要件，跟法律效果的規定。

第3條，就不是綜所稅的規定，就是營所。回到上個禮拜跟各位講，我們的法條規範結構是混亂的，因為你每一個法條你都要去辨識一下，他到底是綜所還是營所？他適用的主體對象，稅捐主體是誰？因為這個地方稅目是有別的，稅目有差。

所以接下來我們來看一下，3-1條被刪掉的。

3-2條，看得出來規範的稅捐主體是誰嗎？
3-2條第一項規定，委託人為營利事業之信託契約，信託成立時，明定信託利益之全部或一部之受益人為非委託人者，該受益人應將享有信託利益之權利價值，併入成立年度之所得額，依本法規定課徵所得稅。

我們的法條的立法者，透過這個條款規定，你看得出來，他想要針對他的那個稅捐主體是自然人的個人還是在講的是營利事業？一定看不太出來對吧。
大多數的情況是適用在自然人，不過概念上不排除，不排斥，也有可能是適用在營利事業，如果他信託契約裡面的受益人是營利事業的話，確實是有可能，因為這個樣子，讓營利事業變成是信託這個收益的受益人，併入營利事業所得稅。
但這個條款，其實在實務上大多數就是營利事業，透過信託的方式讓自然人受益。大多數的情形是適用在自然人的情況。

但關於信託的課稅制度，我們會到所得稅法三才講。關於信託的所得，或者是透過信託去做遺產贈與稅規劃的，我們到所得稅法三，一併去講。因此，這個條文，我們跳過。


接下來3-3條。配合第3條的規定，信託財產的設定原則上不課徵任何稅捐，所以3-2條、3-3條，我們全部跳過。


### 【所得稅法第4條】

接下來第4條，第一項的規定：下列各種所得，免納所得稅。接下來，請各位一一分辨，他主體適用的對象是自然人還是法人？比如說第三款規定，傷害或死亡之損害賠償。誰能夠被傷害死亡？當然是自然人，法人不會有傷害死亡。所以4條第一項第三款前段基本上是在講綜所稅裡面的，損害賠償金免納所得稅。

第4條就是很典型的雞兔同籠，就是綜所營所都適用，那你要個別分辨。我們在這個地方我們確實會有一堂課來跟各位去討論這裡面的免稅所得的規定，因為他的法條雖然寫免納所得稅，可是就像我們公司法上的決議，他的決議瑕疵狀態包括了不成立，無效，跟得撤銷。是哪一種類型？你在學公司法的時候，要去辨識。那我們在這裡，都叫做免納所得稅，但實際上他可能是非所得。非所得，本身概念上就不是所得。所以規定免納所得稅其實不是，稅捐優惠，他其實只是去反映出，本質上不是所得，譬如傷害的損害賠償。去年，不小心在路上，被後面一個冒失鬼撞傷了，有人開車，不小心把你撞傷，撞斷了一條腿，賠你100萬，要不要去報所得稅？請問這個算不算所得？學過法律的各位，毫不猶豫，你不用什麼特殊會計學或是財務學的觀念。什麼叫損害賠償？ 填補固有利益的損害，沒有財產上的增加。所以我們剛剛看到那個法條第4條第一項第三款傷害或死亡之損害賠償，請問放在這是稅捐優惠嗎？當然不是稅捐優惠。他是一個非所得，本來就不是所得，我今天放在這裡，只是告訴你，宣示一個既明的道理。就是，只要是填補固有利益之損害的損害賠償，原則上不課所得稅。
我們再請各位來看另外一個條第4條。這裡面一堆雞兔同籠的條文規定，包括了，比如，第十六款的規定。第4條第十六款，個人及營利事業出售土地。第十七款的規定，因繼承、遺贈或贈與而取得之財產。第4條的第二十三款的規定，個人稿費、版稅、樂譜、作曲、編劇、漫畫及講演之鐘點費之收入。這些全部都鷄兔同籠，叫做免納所得稅。

我們把第三款的因死亡或傷害的損害賠償，跟十六、十七款的個人出售土地跟個人取得遺產遺贈，跟個人取得稿費、版稅等收入。各位辨識一下來看看，哪些是真優惠？ 哪些其實不是真優惠？他並不是優惠，他只是一個在闡明所得跟非所得概念的區別。
剛剛我們講過第三款的，因死亡或傷害的損害賠償，那個就是一個典型的他是非所得，所以他不是稅捐優惠。我想各位學過民法，應該很清楚。
我們來看一下，二十三款的規定個人稿費、版稅、樂譜、作曲、編劇、漫畫及講演之鐘點費之收入。這些活動，爲什麽可以18萬免稅？因為立法者鼓勵你做文化活動。稿費、版稅是錢嗎？是。是你透過你的文化的創作，透過你的智慧的產出，所產生出來的收入。所以他是典型的所得。只是立法者鼓勵文化，這一種智慧財產的創新，或者是創設智慧財產權的文化活動，而給予的一個基於文化政策的稅捐優惠。也因此，這個條文規定，他本身就存在著立法者給予優惠的意思。但他跟第三款的規定，他都同樣放在這個地方裡面去做一致性的規範，看起來好像是同等對待，實際上是鷄兔同籠，因為他們性質完全不同。


回到十六、十七款，這是一個很典型，在臺灣實務上一直被誤認的規定，因為看起來叫免納所得稅，所以以為是稅捐優惠，實際上不是。十六、十七款，實際上是因為我們有另課土地增值稅、另課遺產贈與稅。所以他是一個分離課稅，避免重複課稅的規定。分離課稅，分離在綜所稅的稅基之外，併課別的稅目。為了避免重複課稅，所以規定免納所得稅。請問這個叫優惠嗎？其實不是稅捐優惠，其實是一個避免重複課稅，讓別的稅目去擔負起量能課稅的功能任務的一個條款規定。

光只有所得稅法第4條規定，你就可以看得到，同樣都叫免納所得稅，結果這裡面，是有所得跟非所得，有分離課稅的所得，跟真的是受到優惠獎勵的所得。你就知道我們的實然跟應然差多大。不是各位的問題，是我們立法者，在法律規範上，很大程度上沒有去區別出他該有的樣子。如果在這樣的規範底下，要能夠去理解整個規範的價值，說實在，沒有經過一個體系的呈現，有時候確實是不容易清楚地理解。

---

我們先休息一下，我只是用這個例子，但接下來我可能要很快的，把我們這一次上課要跟各位去做說明的，一些基本的原理原則跟各位介紹。

因為透過量能課稅的原理原則，我們大致上會把一些比較重要的，綜所稅的稅捐構成要件，立法上本來應該長什麼樣子，但我們現在實然的狀態並不是長這個樣子，我們要把情況把他做一個比較完整的呈現，我們先休息一下。