# 20231016_02

---
課程：1121所得稅法一
日期：2023/10/16
周次：07
節次：2
---

## 【繼續談獨立勞務】

### 【繼續談執行業務】

執行業務所得，其實他是一種特種業務的態樣，也就是說他是一種特種職業的態樣。只是說透過11條第一項的規定所提出來的一個以技藝自力營生者，這樣一個類型特徵，能不能足夠的去前面去做涵蓋而已。由於差別對待，各位看到14條第一項，第一類營利所得，我們根據各式各樣不同的營利所得的類型，有成本費用的這個認列的問題。特別是獨資跟合夥，因為在獨資跟合夥這一類型裡面，在我們傳統上面，過去的所得稅法都把他當作是營利事業的一種形態。因此各位看到，我們所得稅法第11條的第二項，他也把獨資跟合夥列為一種職業的類別。

第11條的第二項：
本法稱營利事業，係指公營、私營或公私合營，以營利為目的，具備營業牌號或場所之獨資、合夥、公司及其他組織方式之工、商、農、林、漁、牧、礦冶等營利事業。

組織型態，包括了獨資合夥公司跟其他組織方式都在內。營業的內容包括了工商農林漁牧礦冶等。因此11條第二項跟11條第一項執行業務者，他們的共同特徵都在透過自力提供一定的勞務內容，也就是獨立性地，提供服務的內容或是勞務的內容，或是商品的內容，那差別只是差在於執行業務者他的勞務的特殊性。

勞務其實是11條第二項裡面的經營事業的其中一種類型而已，因為經營事業包括了「工、商、農、林、漁、牧、礦冶」。其中「農林漁牧礦冶」的部分，作爲所得稅法裡面的一種類型，也是我們待會會跟各位進一步去探討的。

所得稅法第14條第一項第六類：自力耕作、漁、牧、林、礦。

這個地方，很有趣的，不是有趣，很無聊的，把「農」變成是「自力耕作」，然後「礦冶」後面那個「冶」就不見啊。就這樣啊，這個我們的立法者的外在體系就不太容易對應的起來。你在前面11條第二項，你講到所謂的「工、商、農、林、漁、牧、礦冶」。好，然後再第14條的第一項第六類，裡面所謂的「農」，變成「自力耕作」。當然這個解釋上應該是同一個啊，就是說自力耕作，這個是指農業上的所得。

「漁牧林礦」之所得，待會我們再來進一步去講「冶」，因為也這個部分，特別是跟工匠有關，只要你是以勞務為內容的話，那他基本上就會是屬於執行業務所得。因爲工匠的技藝在11條第一項裡面，是列為執行業務。


所以，我們先從現行法律規範裡面，跟各位去解讀，所得稅法第14條第一項第二類的執行業務所得，跟第一類裡面的營業所得，去做一個區別。待會去跟第六類自力耕作漁牧林礦之所得做一個分別。但這三類所得，他們的共同特徵，都是獨立的去營生，獨立透過他的勞務服務或者是商品的提供，而去賺取經濟成果，也就是取得所得。取得經濟上的成果，這個就是他的所得，只是我們對於他的勞務內容做分類。

第一種抽出來的執行業務所得，根據11條第一項的規定，以四大師為首的，透過特定的養成教育，加上國家考試。

第二種，以人的精神創作所產生出來的經濟成果，作家、作曲家、音樂家、演唱家，這一些都是。專欄的作家、自由的記者，這個都是。運動員也是，高收入的那些運動員，雖然他看起來，如果照我們的看法好像看起來是受僱於球團，但這個在德國都是屬於執行業務者。因為他怎麼去踢球，基本上他有很高的自由度。這個地方確實會存在著不同國家對這個部分的定義上的差別。

然後第三類型就是獨立的自力營生。像工匠跟經紀人。所以你看，保險經紀人，就是屬於執行業務。不動產經紀人，也是屬於執行業務者，而不認為是一個營利事業。

那我們在這裡面，特別是第三類獨立技藝自力營生，這個部分，其實已經跟11條第二項裡面的「工、商」，尤其是那個「商」相關，因為「商」，本質上就是各種各式各樣的勞務跟服務之提供。

從而從法律解釋上來講，執行業務是特種的商業服務，就這樣而已，他是被特別拉出來而已。那這個特別拉出來，當然他有區別對待的實義，因為我們現行法裡面把他列入不同類型的所得：一個是第二類的執行業務所得，一個是回到第一類的營利所得，就是應該被稱之為叫營業所得，因為他是一個獨資或合夥經營事業的這種形態。

所以，原則上，法律適用上是，如果有執行業務的類別的話，優先適用。他是特別的一種業務類別，現行法律上是一個特別的業務類別，立法論上則可以廢止執行業務者，回到一般業別就可以。他只是一種業別上面透過成本費用去做個別的計算而已。

當然執行業務者確實有特殊的業務上要求，比如說不得正義做誇張不實的廣告，以及要負無限的責任這件事情。當然，其實隨著律師會計師醫師，本身在執行業務上面，我們現在已經開放所謂的社團法人。律師會計師，尤其是醫師，可以用社團法人的方式去執行業務，不像早期只有獨資，自己經營職業。各位，我們在律師業裡面，你看到最多的就是自己打天下闖江湖的這一種自己執業的。數個人一起合夥執業，像現在我們的大所，大部分都是合夥型態的，但法律上他其實也可以用社團法人的形態。現在的法律是這樣，我查過。醫生最多。醫生為了要阻擋那個無限責任。因為如果你是今天是一個合夥一起執業，死一個個人，大概你們那個那間醫院就會倒了。

這樣你知道嗎？所以像安隆案，會計師，你今天做一個那個簽證，在美國就倒了。類似的案子，其實在臺灣也應該要倒才對。因為那種都是是無限的責任啦，你把他想像成是一個無限責任的公司的話，哇，那只要一出事，大家就全倒。所以其實理論上來講，如果他成立社團法人，他就可以透過有限責任的方式去把責任擋住。當你可以這樣做的時候，你其實跟一般工商服務有什麼差別？有什麼區別對待的道理？

所以，也許我們的法制的變遷，就是所謂的四大師執業的法律環境變遷，其實也會影響到稅法上面。稅法上我個人的看法是認為沒有區別對待的理由，沒有區別對待的正當性。但現行法制上是有區別對待。因為一個是職業所得，一個是營利所得，也就是營利所得裡面的獨資跟合夥的營業類型。


### 【農漁牧林礦】

好，接下來我們先跳過去，講第六類。「自力耕作、漁、牧、林、礦」，簡單來講叫「農漁牧林礦」所得，我自己就直接就簡稱叫「農林所得」。當然了，在臺灣，林業不會比漁業更多啊，當然你要講農漁所得也可以，只是順不順而已。什麼叫自力耕作漁牧林礦（簡稱農林所得）呢？就是從大自然界的第一次產出，尤其是從土地第一次產出的，透過你的勞動力投入在大自然界，特別是從土地。那裡面漁業養殖漁業算不算土地啊？你可以跟我吵。尤其是如果說去捕魚的，去海洋，這個算不算土地？好啦，我就跟你講，就是大自然嘛，好不好，土地跟海洋裡面產生出來的。你從那裡面第一次產出的，這個就叫農林所得。你去播種，土地長出來稻穀的，去種果樹的，這個都叫農林所得。

農林漁牧，一樣喔，你養羊，就是「牧」。從大自然界第一次產出的，這個就叫做農林所得。如果不是從大自然做第一次產出，而是做一定程度上加工處理的，這個就不再是農林所得，這個就是營業所得。
你只要是獨立的話，你就會是營業所得。所以營業所得，在概念上，是執業、農林所得的補充性類型。農林跟執業所得，則是營業所得的特別類型，是一種特殊的勞務付出類型，跟特殊的商品服務類型。

農林所得，是對於大自然界第一次產出，剛剛所講的從土地海洋，從這個大自然界裡面，你去養殖耕作，因此產生出來的第一次產出，這個部分叫農林所得，之後的加工，這個就已經不再是大自然界第一次產出哦。所以你今天去捕魚，做成魚丸打包賣出去，這個不是農林所得，那個叫工商農林漁牧礦裡面的商業的一種類型，營利所得。

那當然，你今天的組織型態也會影響到你是屬於公司合作社或是獨資合夥商號而做這個區別。


因此，透過你的勞務的付出，特種勞務的被稱之為叫農林，或者是執行業務者，其他一律就是所謂的營業所得。


我待會，我們把他重組以後，各位就可以很清楚的知道這一個類型的類型特徵，主要的經濟成果是來自於一種獨立性的參與市場經濟活動，透過他的勞務再加上資本，而勞務在這裡面是以獨立性，是不是用技藝為主（決定他是執行業務或者是一般營業的標準），是不是從大自然界而產生出來的商品、貨物（決定他是農民或者是一般營業），而做這個差別對待。

這個是我們在談到的所得稅法第14條第一項，第六類跟第二類跟第一類裡面的營業所得之間的差別。


## 【非獨立勞務】

接下來我們來談，非獨立勞務，第一個類型就是薪資所得。

那我們接下來跳過去，講第九類退休所得。

第九類：退職所得：凡個人領取之退休金、資遣費、退職金、離職金、終身俸、非屬保險給付之養老金及依勞工退休金條例規定辦理年金保險之保險給付等所得。

退休所得跟薪資所得，類型特徵都是來自於一段期間的非獨立性的勞務的付出。在非獨立性勞務的前提下，從現在的僱傭關係，從現在的非獨立勞務的付出裡面，直接從僱傭關係的雇主所取得的，依照我國的現行法規定，這個是薪資所得的範圍。等到你的僱傭關係結束之後，這個時候所產生出來的不管是來自於雇主，或者是保險單位——我們保險單位包括了保險的機關（構）——依照法律規定所做的，或者依照契約所做的保險金給付。這一個部分就會變成是第九類的退休所得。特別是照顧退休後的這一段期間裡面的，因為退休關係而產生出來的保險金給付或退休金的給予，這個是屬於退休所得。

當然，我們法條的規定是夯不隆冬把很多東西稱之為叫退職所得。退職所得跟薪資所得的差別在，對於僱傭關係的現在的給付，或者是對將來的給付，也就是你領到的這一個所得，如果是來自於先前的僱傭關係的延續，產生出來的不管是雇主給付還是保險單位所做的給付，依法依契約所做的給付，理論上就會進入退休退職所得的範圍。

所以，我們的法條規定是退職所得，在德國，是薪資所得的一環。因為德國的薪資所得，包括了現在的非獨立勞務所提供的對價給付，以及為了將來，以及為了過去的僱傭關係。

將來，譬如說，假設各位在日本，大四的學生通常就已經被大企業預訂，喔，你畢業就直接進我們Sony工作。你現在領到的Sony提供給你的，就叫做為了未來的僱傭契約所做的給付，所以你領到薪資所得。薪資所得包括為了將來，為了現在以及為了過去的僱傭關係，因此所取得的給付，不管你是來自於雇主，第三人，包括保險單位所做的給付，都是薪資所得的範圍。所以在德國，退休金給付是薪資所得的範圍，包括你的遺孀遺屬，繼續從雇主或者是保險單位所取得的報酬，仍然是薪資所得的範圍。因為德國認為這是同類型所得，都是來自於一個僱傭關係產生出來的，對現在過去和將來的給付，不管取得所得者是不是勞動付出之本人，都是薪資所得，從而是同一種類型。

但在臺灣，我們把他分兩種不同類型，而且這兩種不同類型的分類，對退職所得是比較優惠的分類，各位可以去看第14條的第九類的退職所得。第14條的第九類的退職所得有各式各樣不同的計算方式。因為我們的退職領取的方式有不同的領取方式。這裡面一次領取者，可以去後除掉一定的數額啊，一次領取的話可以扣一個15萬啊，在15萬以下的話，所得額為零，如果超過15萬，那么則乘以他退職的年資，未達30萬，則以半數為所得額，超過30萬部分則以他的乘以退職服務年資之金額部分，全數為所得額。

也就是在我們退職所得的計算方式裡面，根據你一次領還是是分期領，而做不同的區別對待。立法者並沒有很清楚的交代，但我們可以去這樣理解，當你是一次領取，會有累積多年所得一次大量實現，在綜合所得稅是累進稅率的前提底下，會被大量一次急劇增加稅負的問題，從而在我們的第九類第一款，一次領取的計算方式上面給予特殊對待。

我個人不認為他是一種稅捐優惠。因為這是為了避免一次領取退職所得產生的所得急劇集中在一年實現，產生大量稅捐負擔的問題。雖然確實你可以去講，那都是同樣是累積多年所得一次大量實現，實現立法者為什麼在14條第二項的變動所得，跟14條第一項第九類的退職所得裡面做不同的區別對待？

沒錯，很好，這就是各位學過平等原則，上過課以後，你就自然會產生出來的思考，立法者做了一個可能說不出來正當理由的區別對待。同樣是累積多年所得，但我們的立法者做了一個不同方式的區別對待。有沒有違反平等原則，確實存在著疑慮。但回過頭來，如果光以這個條款來看，他並不應該直接就被認為這是一種稅捐優惠規範，理由在於累積多年所得一次大量實現會有稅負級距而增加的這種稅負提高的不利，這是為了避免這種不利益，只是他採取的手段，對同樣的累積多年所得一次大量實現，做了不同對待。在這個地方一碼歸一碼。

我還是要跟各位強調，我不認為那個是稅收優惠，而是避免稅負級距增加，產生出來的不利益負擔，從而用這一種看起來不太連貫的方式。有一個算數的計算方法，這種計算方法半數所得半數課稅，然後有一些是所得免稅，那是認為說哦，如果是這種情況底下，我們就不計入所得的課稅的計算的範圍，那當然超過一定數額的話，我們就用半數啊，如果超過一定數額，則用全數。

這裡面確實存在著立法者的形成空間，立法者也在這裡面對同樣性質的累積多年所得，做了一個不同對待。但這個地方一碼歸一碼，個別去處理。

我現在要講的是分期給付。退職所得，當他用分期給付，用按月給付的時候。今天用按月給付，全年領取總額可以減除65萬後的餘額來做為所得。所以假設薪資所得者退休後所得替代率是100%，我又選擇按月給付，我根據所得稅法14條第一項第九類的第二款規定，我可以減除65萬的餘額來做為所得額。這就是很明顯而赤裸裸的對現在的薪資所得者不利差別對待。講清楚明白一點，就是退休的比在職工作的，稅負上更好，因為他可以扣60萬，你不行。

這個如果沒有違反平等原則，那還有什麼違反平等原則？我如果是一次領，當然你會說，為了避免稅負級距產生不利的對待啊，這種情況啊，我當然我可以選擇，用一個比較有利的計算方式。可是當我今天是分期給付，說實在話，為了過去的僱傭關係跟為了現在的僱傭關係的區分，假設你今天的所得替代率100%。當然因此我們要檢驗，目前的職業年金保險的制度有沒有所得的100%替代？ 假如啦，我只是假設一個狀況，假如所得替代率，退休後，像在希臘可以110%，又有我們這個65萬的減項，那請問你，你今天50歲可以退休，你會不會退休？ 傻瓜才不退。太愛國了，想不清楚才會不退。

因為我現在如果在職的時候領100塊，退休可以領110%，然後我又可以有65萬的免稅額，為什麼不退休？

這個就是稅制做出區別對待。像分期給付這件事情，尤其讓類型特徵就更接近他跟薪資所得者的同樣的待遇的情況，為了現在跟過去的僱傭關係而受領的給付，做不同的區別對待，在我國法制裡面特別看得出來他作對現職的勞務付出者，他有不利的稅捐待遇的問題。

當然我們這個地方是以退職所得，跟其他的這個薪資所得去做一個對比。本質上面退職所得，其實包括了獨資跟合夥事業，為了獨資資本主跟合夥事業的事業組，也就是執行業務合夥人跟合夥人本身他們所提列的退休金給付。因此，退職所得，在我們的法律規定裡面，也包括了營利事業，以獨資跟合夥作為前提，未來，他為自己所提供的退休後的給付。雖然這個地方在我們的實務上，這一類型操作，獨資跟合夥為自己提列退休金的情形並不是那麼普遍。但理論上來講，退職所得也可以在前面，你是一個勞務付出，你只要是一個營利事業的形態的獨資跟合夥，其實還是有可能，還是會存在著這樣的一個退職所得的形態。

我們把勞務付出的類型就說到這裡。接下來進入資本的投入。

## 【資本投入】

資本投入所取得的第一種類型的所得，最大宗的叫做孳息。因為所有的資本投入，只要持續一段期間，一般而言就會產生孳息的所得，這類孳息的所得有以下的不同的名稱，包括了第一類，透過投入股本，進入公司合作社或有限合夥成為股東，因此而產生出來的第一類，我們稱之為叫股利盈餘的營利所得。這是第一種孳息的類型。

第二種孳息的類型是第四類，利息。也就是資本的型態，如果是金錢或債券，包括公債、公司債、金融債券跟各種短期票券在內，所有的這一類都叫做利息所得。

資本的本體如果是股本就會產生股利盈餘，是第一類所得，法律名稱叫營利所得。如果你的資本類型是金錢或債券，包括公債、公司債、金融債券跟短期票券，各種存款跟其他貸出款項之利息。在這裡面，公債不分是中央國債或是地方政府發行公債。公司債，我們也不分。原則上公司在跟金融債券是發行機構的差別而已，也就是債務人主體不同而已，短期票券這個分類，基本上他也是一個短期的資金融通手段，只是6個月以內而已。所以這裡面，原則上6個月以上是債券，6個月以內的短期資金融通工具，這個就稱之為叫票券，資本本體其實都是來自於金錢，跟金錢轉換成有價證券的標的，只是差在6個月以上稱債券，債務人主體是國家或公法人稱之為公債，或者是私法人裡面的公司或金融機構，差別差在這裡面而已。但基本上都是資本的本體是通貨，或者是以通貨為標的物的所謂的融通資金的工具，也就是借錢，就是資金的借貸。

通貨是一個國家發行的法定貨幣，你可以把他理解成他是持有者對國家的一個債權的主張，這樣各位可以理解嗎？美金等於是我對美國政府的一個債權主張，美國政府要擔保我在市場上對市場上實體物的購買力。所謂的通貨膨脹，就是這個國家發行出來的通貨，本來是作為支付工具，但無法有效地購買他先前所承諾的那些物品，這個時候就叫通貨膨脹，相反的就叫緊縮。新臺幣亦如是，新臺幣是對中華民國的一個請求，確保他在市場上實體物購買的實質的購買力的一個憑證。所以基本上債權是通貨的衍生性商品。今天如果我借給你錢，我把他拿去做有價證券化，變成是債之衍生性金融產品，這個就是衍生性金融商品的類型態樣。我可以再繼續，我可以做swap，做交換，我對你的債跟你對他的債，我們做交換，然後我再把他去做有價證券化，就再發行出去，這個就是衍生性金融商品的概念。

回到我們這裡面，股利盈餘這個地方，如果你的資本類型是通貨獲得，是通貨衍生性出去的債權的話，原則上你取得的都叫利息。

資本的本體如果是第五類，接下來進入到有體物。不管是不動產或者是動產，就會產生租賃所得。第五類裡面還有一個資本的本體是無體財產。無體財產的權利金所得，也就是他是一個使用權的讓與，而不是所有權讓與。資本本體是無形資產，無體財產。無形資產是會計用語，那在我們法律上面就是無體財產。無體財產使用權的讓與，這個是權利金。有體財產裡面，我們再來去看，不動產跟動產則是租賃所得；以金錢為對象的，我們再分成是股本的股利盈餘營利所得或者是利息。

這幾個都是產自於一段期間裡面的孳息所得，因此只是差在資本的本體類型有差別而已。他們都是一種孳息所得的類型，包括：
第一類的股利盈餘，排除掉獨資跟合夥這種營業所得，也就是你透過你的股本，你去投資公司合作社或有限合夥組織，因此所產生出來的這個孳息，這個叫股利盈餘，也就是第一類的營利所得。
第二種所得，資本的形態是通貨，或者是以通貨為標的債券，6個月以內的叫票券，這一類的所得孳息就稱之為第四類的利息所得。
如果你的資本類型是有體物，不管是動產或不動產，因此產生出來的孳息，這個叫租賃所得。
如果你的資本是無體財產，包括專利、商標或者是著作權，你授權給他人行使而取得的，這個就叫權利金所得。

這些是因為財產本體和資本的差異，而產生不同的所得的類型，在這裡面，包括在孳息所得這個概念底下。


最後面我們再來談一個財產本體可以做交易，因此財產類型的所得會產生第二種類型所得，叫做財產交易所得，又稱為轉售價差，又稱為資本利得。財產本身可以產生一種轉售上的價差。我們的法條規定稱之為叫財產交易所得，在第七類。外國立法例上有可能稱之為叫capital gain，叫資本利得稅，那一般通用的說法叫轉售價差。

## 【小結】


財產會產生兩種所得，一種叫孳息，一種叫資本利得。所以臺灣俗話講「錢四脚」，就是錢又可以賺孳息，又可以賺利得。為什麼「人兩脚」，因為你的勞務投入只能夠一天24小時。所以臺灣俗話講「人兩脚，錢四脚」，就是這樣來的。

我透過這個圖形，我就告訴各位一件簡單的事情，找好工作不一定是好事。有本事跟銀行撈錢出來，你賺價差的這個叫資本利得，賺孳息差的就是你的利息所得。所以人永遠跟不上錢的速度，所以資本家們是用錢去賺錢。我們傳統的教育告訴你應該要找好工作，好好努力學習法律。說穿了，也就是這樣，法律上，同樣是所得，但做不同對待，所以要賺錢絕對不是找好工作。要賺錢，就是想辦法用錢賺錢。這是這一堂課給各位最大的禮物。

那為什麼會有這樣的一個差別？因為稅制上面就是根據這個類型做不同的區別。勞動力投入，獨立跟非獨立這兩種類型。非獨立裡面，現在的勞務投入，取得薪資所得。因過去的非獨立勞動力投入取得的，這個叫退職所得。

獨立勞務，分三種類型：普遍性的，作為補充性的叫營業所得；特殊勞務的執業所得；特種貨品，大自然界第一次產出的，農林所得。

財產的所得，這個部分。第一，孳息。資本的形態是股本的，叫股利盈餘。資本的形態是通過通貨、債券或者票券的，這個叫利息。資本的形態是有體物的，是租賃所得。資本的形態是無體財產，叫權利金所得。

財產，還有另外一個，是資本利得。

各位，腦袋裡面有沒有這個圖像？你有這個圖像，不用看所得稅法第14條，大致上就可以全部掌握。這樣可以嗎？這樣你才會知道什麼叫等者等之，什麼叫稅捐中立性？同樣一個類型的東西，理論上要同等對待。你如果沒有這個類型，對你而言，所得稅法就是一堆枝枝節節的法律條文的拼湊，你才會一天到晚那邊字字句句斟酌。這真的是沒辦法的事情，因為我們的立法的外在體系極其糟糕，沒有辦法看出來那個同類。真正好的立法體系，就是可以透過立法的結構就讓你分出來。德國原則上大概就會有這樣一個立法結構。所以學德國的所得稅法，確實有幫助於人們從法條規範，就很快可以掌握他們該有的類型。但臺灣不能，還真的是，沒辦法，不太容易。此前有同學問我說，老師，有沒有課本？我就跟你們講沒有課本。我們現在目前的稅法教科書有這樣去分類所得嗎？有這樣的類型，就可以看得出來這個不同類型的手段不同對待，真的是有區別的。

那我們今天先談到這裡。所得的類型，除了繼續性，我還有一個一時性的，還沒講。所以我們下個禮拜再從所得的類型再發展下去，包括一時貿易，包括第八類的機會中獎，包括第十類的其他所得。下個禮拜我們都會去談。各位，這個禮拜務必要把這幾種類型在腦海裡面把他串起來，把他連起來，那這樣你才會比較有一個整體性的概念。

我們今天先說到這裡。