# 20230904_01

---
課程：1121所得稅法一
日期：2023/09/04
周次：1
節次：1
---

## 【導言】

沒有指定課本。

陳清秀稅法總論、稅法各論。

當然還有其他的，稅法的其他的稅務的法律的規定，包括營業稅，包括遺產稅與稅，那麼也有另外一本是黃茂榮老師葛克昌老師跟陳清秀老師3位老師主編，然後由這個我們國內的一些學者去共同寫作的一本稅法各論。那除了這兩本稅法各論以外啊，很可惜，到目前為止。並沒有一本專門針對所得稅法的一個教科書出現。老師有確實有想要把這個部分把他做講義來，至於比較比較特殊的寫作，但，時間上很有限的緣故，老師到目前為止還並沒有辦法把他形諸於文字，當然希望未來能夠透過我們這個課程上的寫作，能夠把他進一步的有文字化的給同學做參考。這個是未來的目標，但目前為止，確實是沒有這樣的一個一個講意識的課程。你可以講所有的課程的內容大概都只能在老師現在的腦袋裡面喔。那，也因此我會希望我在課堂上可以盡可能簡單清楚明瞭的告訴各位所得稅法的意義跟內容，也歡迎各位同學修這一堂課，歡迎各位。如果你的這個課課程之外，或者在課堂上有不清楚的地方，希望你能夠踴躍的提問。因為老師看著各位的臉龐，不一定能夠分辨是不是聽懂了內容，你必須告訴我，我才能夠反應給你，你擔心別的同學的課程會因為上課發問而延遲，那沒有關係，你可以在課後問。老師也有另外的Office hour給各位，如果你有問題，歡迎你提問，歡迎你用寫的也可以，或者請我們助教轉達也可以。歡迎各位提問，因為你不提問，我是無法每一位同學都去詢問你是否了解。

那我會按照每一次上課的進度給各位我們這個所得稅法所想要介紹的內容。
至於每一次的進度內容，我已經寫在ntu cool上面，請各位能夠自行參考，我們每一次上課就是講這些內容的具體化。那也因此，各位可以比照在ntu cool上你想要去了解老師上課的大概進度，那就請各位再來做參考，那當然我會隨時稍微做一些調整，假設如果沒有講完的話，因為這個很難說。老師自己以往的經驗也常常會顯示，我有一些地方講太多呢，導致於沒有辦法講得很完整。那我可能會利用下一次上課前面一段時間稍微做一下補充。如果還有不足的地方，那可能也希望各位同學能夠告訴我，因為我們課堂時間基本上只有100分鐘，我不一定會聽得到那個鈴聲，所以我可能不一定能夠照每一個他課堂中間下課休息時間，各位同學自己有需要，請自行離開，我們要上廁所或是喝茶，或者是覺得有點悶，有一點不太舒服，你自己去行動就可以了不用特別跟老師報告。

然後另外第二件事情有同學問說要不要請假，老師不點名，所以今天可能會是各位最多的一次。啊，大家都當過學生，我也當過啊，我們第一次上課通常會看老師不是好不好欺負，就是他講的內容會不會一樣，那我可以跟各位說不太會一樣，那當然歡迎各位，每一次即使，你沒有點名你自己覺得有這樣的一個需要你來上課跟老師做討論。


那麼老師因為不點名的緣故，所以我沒有辦法以出席率、還有討論來做為評分的標準，老師的評分標準只有兩次，考試的機會一次是期末考，所以我現在要跟各位講我們的期末考的時間。那一次期末考請各位務必要來，因為你不來的話，我會產生一個不太容易在一個平等的基礎上去做評分的，這樣的一個可能，當然如果同學們真的到時候萬一發生了不可預測之天災，像颱風，或者是事故啊，真的是發生了意外，沒有辦法來參加，沒關係，你就照 程序請假，老師一定會給各位補考。我們的臺大期末考週就是在12月18號，務必請各位同學把那個時間空下來。另外一次期中考的時間……

我們有一次是在10月9號，那一次是調整彈性上課，跟這個放假的時間，也就是10月9號，那一天會放假。那麼根據政府表定的時間是把他放到9月23。但我認為9月23對我來講，稍微有點趕了一點點，因為9月23的話大概是在上課，剛開始下下個禮拜就已經開始了，那老師希望把這一個課的時間，我把他改成到11月4號做期中考試。11月4號早上的時間，因為我要跟我另外一堂稅法總論的課配合，所以他應該會是在，早上10點半到12點半之間去做考試期中考，我們有兩次考試，11月4號跟12月18號兩次考試請各位務必到來做考試，至於考試的方式，原則上12月18號我會用，實務案例改編的實例題來考各位，因為那個才是真正的實務。我會用綜所稅的實務案例把他做一下改編變化。這個判決太多了，所以各位大概很難猜測我會從哪裡取出一個題目的方向，那我可以跟各位說，他一定是實務發生的案例，改編了，我會把他稍微簡化，把一些事實做一些篩選。那如果是，期中考的11月4號，這一次，由於我們是在期中，我根據以往的經驗，有些實例題考的比較早了一點點，那這個時候可能對各位同學在解釋上面會有一點小小的困難，那沒關係，我們在期中考的時候，老師會稍微變換一下，我們不要用那麼嚴格的實例題，也就是在實例當中，我們埋一些問答，讓各位能夠有一些基礎觀念的理解來做題目上的回答，也就是說，比如說基本的問題，就是說在這個地方涉及到什麼樣的問題，然後這個問題底下有哪一些，譬如說基本原則或者是稅捐構成要件的爭議，那麼會有一些跟問答有關的題目來給各位做一個測驗，那這個對老師來講也是一個嘗試。因為以往我在所得稅法的科目裡面，我盡可能都是出實例，但有時候實例出太難了。同學們考試起來會不太打擊各位的信心，我自己，我如果是學生，我也會被打擊到啊。如果考試出來，成績不太好的話。但回過頭來來講，這才是真正的現實。因為實務上的到法院去的稅捐的救濟的案件，絕對不會是問答題，他一定都是從個案衍生出來的爭議，歡迎各位同學來所得稅法的課堂上去理解跟了解，認識我們的稅捐爭訟實務的樣子。

老師依序之後會做一些稅各，因為有一些客觀因素的添加，表示以後再稅法的教學上面會盡量往稅課去推動推進，也就是未來我們這個課程除了今年的這個上個學期的綜所稅以外，而是因為下個學期要休假，所以我下個學期沒有開課，但這個之後我會依序的把營所，遺產稅跟贈與稅，一個一個科目來進行。
我會把信託放在跟遺產贈與稅那個地方一起。

所得稅法四是要談房地合一稅跟所得基本稅額條例。我們的所得稅法總共就是4個學期，他是一個比較完整的一個總和性地認識所得稅法，因為這個科目在法律體系上面不是太完整，稍微有點小複雜，但也希望各位不會因為他復雜而退卻，當然以各位要考國家考試，假如各位今年或者明年要考國家考試的話，以這樣的教學的密度來講是蠻長的，但各位不用特別擔心，因為國家考試裡面的稅法，基本上都是法條，演變而已。他不會太複雜。那個都不會真的像訴訟實務上的稅法爭議問題那麼大。國家考試的稅法大部分都是法條演變，當然不能直接考你法條超被這樣，那沒有意義，他都是法條的演變，所以各位你在考試的時候，你不用特別擔心，你就只需要把我們上課裡面所提到的這些基本法條概念弄清楚就好。考試是基本觀念的延伸，好就是他是一個基本觀念，再去做一些實務上的延伸訴訟實務也是訴訟實務。當然有一些東西我們沒有辦法在課堂上去考。我舉個例子來講，像證據評價，這個我們就真的沒有辦法在課堂上考要考，是我恐怕需要去法官學院，請他們給我們卷，大量的一個遺產贈與稅案件全部丟給你，然後你去看這個到底是遺產、還是贈與、還是所得？ 讓你去就所有的證據資料去做評價。在學校的考試我只能簡化事實，然後告訴你說這個地方有一筆財產，進了誰的口袋裡面去，我大概都已經直接跟你講那個答案。通常在實務上面，這個答案是不存在，因為你要必須要去像拼圖一樣的。有些人說刑事訴訟是拼圖，他把被告究竟有沒有從事該項行為，慢慢的慢慢的一塊一塊地透過證據去把他拼圖補滿，檢察官要補被告的犯罪的拼圖，納辯護人不需要，只需要讓這個檢察官的拼圖裡面缺少了重要的一塊，就可以了。那其實行政訴訟何嘗又不是如此呢？國稅局也要去拼你的圖，拼上當事人在這個地方究竟有沒有拿到錢，有沒有所得，有沒有遺產，有沒有贈與，有沒有營業的行為，那相對的訴訟人之納稅人這一方他的主要的說明上面，他可能是去破壞那樣子的一個拼圖，說另外一套故事，讓稅捐稽徵機關原先的拼圖拼不起來。


無論如何，我們的稅課的教學會往前去推進，不光只是直接稅而已，老師也希望未來，心有餘力的可能性，我們還有一個非常重要的拼圖，是間接稅就是營業稅。營業稅是非常重要一塊拼圖。另外還有一部分叫關稅，他是國境稅，裡面因為所有的這些直接稅，我們在稅制裡面把他稱之為叫做内地稅。一國之內課徵的稅捐主要分直接稅跟間接稅這兩大類，那麼國跟國之間的貨物的往來的課稅，這個主要就是關稅。我們還有這一塊拼圖，這個算是在國內幾乎各大學，沒有在教授，包括財政系會計系法律系，更不用講，都沒有在教授，當然老師自己個人對關稅關務有一定程度上的興趣，不過他在我的研究的拼圖上面是比較後面的，我需要把内地稅先把他照顧起來。
那麼還有一塊是未來也是各位非常重要，也需要擅長去就這個部分的領域去研究的就是國際租稅。國際租稅未來會在我們，臺大法律學院，陳衍任老師應該會給各位上關於國際租稅的這個部分。我雖然有興趣，但一個人一輩子也只能做好有限的幾件事情。也就是說，如果老師順利，沒有什麼身體健康問題，退休之前還有時間當然可以做，但如果做來不及的話，我們需要分工，需要一同去推進稅捐法在法律人的領域裡面的各方面的研究，沒有研究，不會有更多的我們的從事於這個工作的法律人。

你現在在外面看不到，那是因為，我們以前法律人不研究稅法。那是果，不是因。當然，因果相互循環，也希望未來下個世代由各位所領導主導的法律人的世代能夠有更多的從事於稅捐這一塊領域，不光只是救濟，如同訴訟法一樣，他其實很前端的非訟法，也就是稅捐規劃，能夠有更多的法律人，切入這個領域。這個是作為法律背景的老師終生終生的期盼，希望在下個世代……老師這個世代來不及了，因為在這樣一個有限的時間裡面，能做的很有限，希望未來在各位的是在裡面有比較多的可能性，我們能夠有更多的從事稅捐規劃，對稅捐這件事情，去預測當事人的稅捐負擔，從而在他的私法契約裡面去做一些對應。這個稅捐負擔往往有時候會影響到，當事人契約價格的決定。不要小看這件事情，沒有考慮到稅捐，往往你在稅捐重要的價格因素決定上面不會注意到哦，原來這個地方還多出來一個稅負，你本來想要淨賺的數額會因為稅負而有所減少。一個思慮周密的法律人應該在契約裡面將相關的稅負把他考慮進去。

一個思慮周密的法律人，也應該在各式的組織行為乃至於身份上面去考慮。各位可能沒有辦法想像，遺產到跟贈與跟我們現在目前離婚的契約，很多人從事於這一類的工作，但從來沒有去想過離婚之後，小孩子的扶養費誰出誰報稅的問題。這個是幾乎在實務上面，包括法院到實務從事於這一類工作的法律人比較容易忽略的，往往之後就產生諸多諸多的爭議，希望未來下一代的各位不至於有這麼多的困擾或問題存在。這個是我想未來在規劃上面，希望提供給各位同學上這個課。

除了剛剛我所提到的要注意到，考試時間以外，另外一件事情是可能希望各位，我會希望各位至少要有一個工具書，就是你要把所得稅法下載下來，你不買稅務小六法沒關係，你要拿那個簡明小六法。不過因為簡明小六法，一般而言不一定會有稅。你如果沒有法條老師上課很難推得動，而且在考試上面你會對法律本身就不熟悉。我再講一次，國考的稅法其實不難啊，大部分都是法條延伸而已。因此不是要求各位買，而是要求各位，你至少要有那個工具，你沒有工具的話，你一天聽老師在課堂上面講說，哦，這個第幾條第幾項規定，你可能做一個筆記，也許你回去還會看。但不看的話，其實說實在話，很可惜你就不知道到底老師上課裡面講的那些觀念，或是那些問題到底在哪裡。

另外一件事情是因為所得稅法的法條本身。所得稅法算是稅法裡面規範密度高一點的。但很多重要的構成要件規定稅捐構成要件規定其實連法律本身都沒規定，所以我們必要的時候會有一些參考解釋函令，因為實務的操作就是這些解釋案例去建構的稅捐稽徵實務。在法律學院之外臺大的會計系會計系的課堂上面他一樣會上稅務法規。稅務法規在會計系的教學裡面，他們非常著重在這些解釋函令。以法律系的觀點解釋函令，幾乎是整個規範的末端，根本不能牴觸依法課稅原則，或者是根據法律規定沒有明確規定的。原則上你總不能透過行政機關的解釋函令去做這個樣子的延伸或者是補充。但機身實務上完全不考慮這件事情，他就是沒規定。沒規定，但要每天要操作要怎麼辦？我們在實務上有大量的解釋函令，也因此有一部分重要的解釋函令，我會在這一個所有小六法裡面把他補上去。他本來應該是法律規定，但沒有那也沒有辦法，我也只能跟各位說，那你要把那個解釋函令找出來，就這樣而已，那其實，所以我想說法只是方便各位去找出比較重要的法規，命令行政規則就這樣而已，各位也可以自行上網去下載考試的時候，各位可以帶六法，包括你認為重要的解釋函令你自己帶。因為我沒有辦法應給你，你就自己帶。當然國家考試的做法是，他會把比較重要的法規範附在後面，附在後面寫，那我一直覺得這是在暗示：這個是重要，這個是會用到的。這個不太不太符合真實的狀況。原則上面來講，你如果法律適用上需要用的法條跟解釋函令，那麼原則上應該在法律適用的過程當中，裡面不管是納稅人方的律師或會計師，或者是國稅局，他們都會去找非常對個案來講重要的解釋函令，那也因此。如果我在出實例題的時候，需要用解釋函令，我會補給各位啊，為了要稍微增加一點難度，會稍微魚目混珠一下啊，不一定真的用得到，不一定真的用得到，只是拿來魚目混珠而已，看起來有點關聯，就這樣而已，也因此請各位在考試的時候做一些斟酌。

還有一件事情，原則上，如果各位，初選沒選到加選的話，我們這邊已經寫給各位，原則上老師會盡可能的給各位在課堂這個容量許可的範圍內給各位做加選，所以各位不用擔心。那要不要每一次請假，你自己決定啊，因為其實不用跟我講，我也不會點名，然後你就兩次考試到而已。有問題請各位來提問，沒問題的話，你覺得你很清楚，那我也沒意見，不過我只是跟各位講，因為上課老師都是在課堂上面去講重點的部分，請各位再斟酌。

我們這一堂課，所得稅法，老師並不要求特別一定要以稅法總論作為前提。也因此，今天我們講的一些內容，如果你是同時修稅總跟所得稅法的話，因為這個理論上可以該當構成，因為老師之前也有碰過同學們，他直接跟老師表示說，老師，我很認真，我願意自己去上課，或是我自己去買教科書來看好，那你就自己承擔風險好，如果老師上課講的一些基本的東西不清楚沒關係，請各位你在。是你再去找那個稅法總論裡面的教科書或是稅法總論裡面的一些基礎觀念，待會我會講內容的時候也一樣會有一些基礎的部分，各位如果是初次聽到沒有太多概念的話，建議各位，你先把關鍵字寫下來，然後你再自己去找那個稅法總論的教科書或是稅法總論的這個課程去把他補上去。老師在學校的臺大開放性課程也有錄一整個學年的稅法總論的課程。各位，你可以自己上去看。各位，你也可以去買稅法總論的教科書來補起來。
你自己要修這個課程，我歡迎各位好，我歡迎各位。因為跟稅法總論有關聯性的當然會有，但也有一些是所得稅法中所稅自己要處理的一些問題，如果你剛好同時兼修總論跟所得稅法，那可能各位稍微要多花一點點時間，同時間把那個基礎觀念把他補起來就可以。我們的整個行政規則，我就跟各位介紹到這裡。

關於考試、關於加選、關於修課，關於我們課程進行的順序跟這個內容，請問各位同學有沒有問題？ 假設各位沒問題，那我們接下來就開始要上課囉。好，我會盡可能照下課的時間，不過因為有時候我沒有聽到，各位如果有事情的話，或者是你需要先行離開的話，就請自便。


## 【稅目】

我在今天的課堂上，我就必須要先跟各位先說一下，所得稅法裡面不是只有一個稅目。我們出現第一個專有名詞：稅目。稅法，所得稅法當然是一個由立法者制定的法律，可是在我們的所得稅法的規範機構裡面，我們的所得稅法並不是一稅目而已。我們的立法的背景比較特殊，所得稅法是從民國4年，1915年開始。當時我們的所得稅法，他就兩個稅目，就有兩個，也就是後來演進成，我們現在的個人綜所稅，以及現在的營利事業所得稅。

所謂的稅目是一個簡單的名詞的簡稱，叫稅捐名目，課稅名目的意思。他的名稱，他的名目。我們的所得稅法，包含了個人綜所稅這個稅稅目，跟營利事業所得稅，我們這種立法體系其實是蠻罕見的。一般而言，一般而言通常是一稅目一稅法。分散式立法的結構特色就是一稅目一立法。但臺灣的稅法從來都不是這樣，他比較沒有規則，就是有時候立法者會一稅目一稅法，比如說印花稅，他就一稅目一稅法，契稅有一稅目一稅法，可是我們也有一些說，他本身一開始就兩個以上的稅目。像遺產贈與稅，他是從民國42年開始制定，當時只有一個稅目，叫遺產稅。後來就發現，大家不會把遺產留到最後面，在生前給，就不要被課到遺產稅，所以後來到民國62年的時候，我們立法者趕快把他補進去，就變成是現在的遺產贈與稅法。所以就變成兩個稅目，因為課一個稅目很容易被規避掉。

那我們的所得稅法又是另外一個故事。他是一開始我們就跟別人不太一樣，我們就一開始就兩個稅目一個稅法。那也因為這樣一個立法結構，其實大多數國家通常是這個稅目，都是一個個別的稅法，這個叫做個人綜所稅，如果用英文翻譯叫individual，或者是personal income tax就是individual，就是自然人，個人的意思。但如果是講營利事業所得稅，各國大部分都會以公司組織作為他的課稅的名目，可能稱之為叫公司稅，也可能稱之為繳法人稅，名稱不一而足，但原則上一定是以一個營利作為指向目標課徵的一個主體稅，這一點倒是沒有什麼不同。大多數國家通常是individual or personal income tax或是Corporation tax，或者是作為叫做所謂的法人稅，因為德國就稱之為叫法人稅，當然法人不是指公法人，一定是指私法人。不管是哪一種稱呼，大部分都是兩個稅法兩個稅目，臺灣自始就是用兩個稅目一個稅法，然後我們到105年的時候。要加進來另外一個稅目叫房地合一稅。因此我們現在在這一部所得稅法裡面，我們其實總共有三個稅目。國家考試在講說，我要考所得稅法，其實他就跟你講，我要考試這些。所得稅法包含了三個稅目。每一個稅目都有每一個稅本身的課稅構成要件。他的稽徵程序的規定。所以我們在一部所得稅法，他一開始本身就是有兩個，後來變三個，他原則上會是三個兩個以上的課稅構成要件、法律效果、稅捐稽徵程序跟制裁法的規範。其實是別人兩部稅法或三部稅法的加總而已，但我們的法條規範結構基本上是比較簡略的而已。

所以我們今天第一節課，我們除了跟各位大概介紹所得稅法這一部法典，但我們的上課，其實這個學期我們大概只會把重心放在其中的這個稅目，個人綜所稅。這個是這個學期之後，老師休完假以後。接下來是營利事業所得稅。接下來當然就是遺產稅及贈與稅。這個在實務上面最多稅捐訴訟案例的稅目。他也是由兩個稅目所構成。這兩個稅目基本上是一種特種所得，是一種特種類型的所得。簡單來講是從市場上賺來的，這一種財產上的增加，我們課所得稅的所得，再按照自然人或是營利事業去做分類。自然人，或者是，法人組織的營利事業去做這個分類而已。當然，我們民國105年又加進來房地合一稅，納房地合一稅是把這兩類所得裡面，把房地，拉出去做分離課稅。也就是，他的，稅捐的規範結構是把他從本來綜所跟營所，本來是要把他全部包含起來，他把他拉出去，做一個獨立的稅目，做一個個別分離在原先稅基之外的課稅。

遺產跟贈與原則上不來自於市場經濟活動。而是來自於主要是兩種關係，第一種是來自於血緣。你有好爸爸。有好爸爸，他死的時候給你。這個就叫遺產。你的好爸爸死之前就已經把財產給你，這個就叫贈與。基於血緣關係的遺產取得，或者是基於任意性的給予，無償增益他人財產，不一定來自於血緣，而是來自於任意性，喜歡OK。像小三小王贈與，不一定有血緣關係。只是為了某一種特定的關係，而任意性給予的，這個就是所謂的遺產跟贈與稅裡面的特種所得。除了這幾個稅目以外，我們還可以看到本質上，應該跟所得是一樣的類型，但在我們的法律規範裡面，我們另外把他拉出去做分離課稅。那個就是土地增值稅，土地稅法裡面的，一個稅目。土地稅法又是另外一套。同樣我們這個稅法裡面總共有三個稅目，土地稅法總共有：地價稅、田賦、土地增值稅。以土地，為集合，規定在土地稅法。但土地增值在本質上面是一種被稱之為叫資本利得。在英文裡面很好玩的，我們中文其實看不出來這個意思，你看。這個概念在英文裡面並不包含capital gain。Capital gain這個的英文字眼，照中英文的字面來翻，叫做資本利得。因為英文裡面的爲income那個概念，他稱這個不是指那個capital本身，而是透過capital去轉嫁去轉售的價差，這個才叫做Capital gain。你把他想像成一件事情是樹會長果實，只有果實才叫income，只有果實，而且果實還要掉下來哦，這是他長出來的，多出來的。
德文稱之爲孳息，各位在民法裡面學到的孳息。
但如果是本體的這個部分的話，在英文，income的概念是不包含所謂的資產本體的價值增加。這個是英文的字彙，在中文字彙裡面我們不太能夠去感受到這個差別，因為我們從語言裡面看不到這個差別。那這個差別主要是來自於income這個概念，一般他是指所謂的，長出來的孳息。那長出來的孳息，這個才叫income。如果是還連接在財產本體裡面，透過財產的本體的轉售而取得的轉售價差，這個在英文裡面就被稱之為叫capital gain。他是一個獨立稅目。比如說在印度income就不包含capital gain這個概念，他是另外獨立分開來的。香港也是一樣，凡是受到英國影響的，大部分，對income的概念基本上跟capital gain是不同的概念的想法。

但回到中文的世界裡面，其實我們不太有這個差別。總而言之，你今天賣果樹，只要上面長果實價值增加，這也是一種所得的概念。你本來是用100塊，結果你把他透過勞動力的施作，讓他變成長出果實，他上面可以賣到120塊，這個轉售價差，這個在中文的概念裡面來講，其實我們也認為那是所得。那也因此capital gain這個概念在我們的法制裡面，把土地增值這個部分另外拉出去，另外去做分離課稅。除了土地以外，其他基本上都是回到所謂的所得稅裡面有一種類型叫做財產交易的損益。我們後面的課程會去講到財產交易損益：我們的所得類型裡面有一種類型叫財產交易損益。所以除了不動產的土地拉出去以土地增值稅課稅以外，其他的財產交易的轉售價差，原則上我們的綜所稅是放在財產交易損益裡面去做課稅，做相關的課稅的規定。也因此除了綜所營所遺產稅贈與稅土地增值稅，還有後來加進來的房地合一稅。

當然你現在看到這個地方的圖形的說明的時候，很快地就會注意到，都是針對不動產，土地跟房地，有重疊。所以我們105年。引進的房地合一稅，他特別把土地增值稅的稅基扣掉，避免重複課稅，所以土地增值稅，目前為止還在。從105年以後，我們加進來房地合一稅。為了避免這兩個稅目打架——重複課稅的意思。我們在稅基計算上，我們特別把土地增值稅的稅基把他扣掉，以避免重複課稅。那麼相關條文，我們到所得稅法四的時候，再跟各位去說明。關於所得基本稅額跟土地增值，還有房地合一稅，我們到所得稅法四，也就是第四個學期，再跟各位去做說明。那其實也是法條而已，你去看法條大概就可以去了解，在那個地方，把稅基扣除掉。

最後一個我們就跟各位講，所得基本稅額條例的所得基本稅額。個人跟營利事業還有一個所得基本稅額。好，怎麼會有這種東西？這個是臺灣法制上一個奇蹟，一個很奇怪的結構。因為臺灣的所得稅，例如綜所稅，我們原則上只課中華民國來源所得的所得稅，我們不對境外來源所得去課所得稅。因此在民國95年的時候，2006年林全當財政部長任內的時候，我們就做了一個立法，叫所得基本稅額條例的最低稅負制的立法。把個人在境外取得的，個人在境外取得本來在綜所稅裡面不課的所得稅的所得——他其實是所得，但是不課所得稅，由於不課所得稅，所以我們在民國95年的時候立法把他改課所得基本稅額。這個名稱有點拗口，有點怪異。他其實是所謂的我們一般稱呼叫做最低稅負制，就是你如果都賺到海外所得，至少讓你負一個最低的稅捐負擔，他的概念是這樣。
所以，我們臺灣的稅法裡面把一部分本來在綜所稅裡面不課的所得；在營利事業所得稅，因為臺灣有很多營利事業所得稅的稅捐優惠規定，所以我們現在把在原先所得稅裡面可能是被免稅的，可能是被稅捐優惠的，我們透過2006年的所得基本稅額條例，再把他拉回來，課一個最低稅負，這個叫做個人所得基本稅額，或叫營利事業所得基本稅額。有一點拗口的一個稅目名稱，那這個部分我們到所得稅法四這個時候才去跟各位做進一步說明。但我要跟各位說，其實所得基本稅額條例，因為太仰賴太吃稅法法條規定，在考試上面幾乎很難考，因為給法條，大概就給答案了。但是實務操作上他卻很重要。
因為實務操作上大部分都是看著法條，然後去跟國稅局去吵說欸，我有稅捐優惠適用，然後國稅局說哦，沒有你的租稅優惠是我們再用所得基本稅額條例又再把你拉進來，課稅。大概在實務上面吃法條很重的，考試上面不太容易去考，但操作實務上他真的還蠻重要的，我們到時候的稅法四，我們把後面這幾個撿回來，一併去做一個說明。一個是資本利得稅的土地增值稅，房地合一稅，然後另外一個就是所得基本稅額的這個最低稅負制，這是我們所得稅法四。

所以你看到我們大致上所得稅法，個人綜所稅，針對個人原則上是綜合所得的課稅。如果你是一個營利事業就改課營利事業所得稅。如果你是從爸爸那裡拿來的錢，就課遺產稅，課贈與稅。如果你是炒地皮賺的，就是土地增值稅，105年以後再加徵房地合一稅。在海外賺來的錢就課徵個人所得基本稅額條例裡面的最低稅負制。

這個就是我們現在的所得稅，以一個個人作為中心。透過這一個不同稅目的拼湊，你大致上就會瞭解……先不批判，先不批判，你要先認識客觀現況的立法。你在臺北賺到了錢，課綜所稅所得。你在美國賺到的錢，課所得基本稅額條例的最低稅負制。你炒地皮賺的錢，課土地增值稅房地合一稅。你叫爸爸，爸爸很開心給你的錢，課遺產稅。爸爸生前給的這個就叫贈與稅。每一種不同的財產上的增益，課徵不同的稅目。

這個就是我們立法者所做的，我們把他稱之為叫價值決定。立法者在不同的稅法裡面，埋不同的稅目，用不同的稅目去切割，本質上都是財產上增益的所得。這一種叫價值決定。立法者，由於他是一個可以在民主國家裡面負起政治上抉擇的一個團體，在權力分立底下，享有這樣一個，我們在公法上憲法學上稱之為叫立法形成空間。在這個地方具體做出來的決定就叫價值決定。各位聯繫上憲法，立法形成空間，權力分立原則，對於這一件事情，司法跟行政只能看立法者，因為只有立法者能做這樣一個決定。

先請各位不要批判他，因為你要先認識現況長什麼樣子，有沒有道理，當然這個是我們法律人最特殊，也是最厲害的本事，這也是各位在市場上你會跟會計師背景可能會有所差別，因為會計師比較知道現況長這個樣子，但他不會採取批判的角度。只有法律人，在教育訓練上，因為我們對現況的這一種價值決定。固然認為立法者有他的立法形成空間，但這個形成空間是否違反憲法上的原則？特別是平等原則。在這個地方，法律人就會發揮他去對立法者這樣一個價值決定的批判，乃至於認為他有違憲的疑慮。這個也正是各位未來在實務現場裡面，可能跟會計師不管是合作或競爭的關係，原則上我們的背景思考，大致上就是給各位這樣一個能力。但我要請求各位。你一定要先了解現況大概長什麼樣？ 不要不了解現況，就一味地去做批判。這個地方立法者的價值決定就是做了不同的稅基切割。同一筆財產上增益，顧客賺來，老闆賺來的，跟爸爸拿來的錢，做不同的稅目的課徵做不同的稅基的計算，這一種叫價值決定。我們之後有機會，當然在稅法總論的課程裡面，會去進一步去討論，平等原則應該是怎麼樣一個情況。

那我們先休息一下，我大致上用第一個小時的後半段的時間跟各位介紹，我們接下來一個學期要上的綜所稅。跟其他稅目同樣是屬於財產上增益的課稅，跟這些各稅目之間的關係，
我們休息之後，我們第二個小時還要跟各位繼續介紹一下，跟其他稅目還有稅法所得稅法的規範結構，讓各位能夠清楚。先休息。
